--Zone: West Ronfaure
--Zone ID: 100
return {
    Names = {
        ['Amanita']             = { Name='Amanita', Ecosystem='plantoids', Family='funguars' },
        ['Bomb']                = { Name='Bomb', Ecosystem='arcana', Family='bombs' },
        ['Carrion Worm']        = { Name='Carrion Worm', Ecosystem='amorphs', Family='worms' },
        ['Ding Bats']           = { Name='Ding Bats', Ecosystem='birds', Family='bat trios' },
        ['Enchanted Bones']     = { Name='Enchanted Bones', Ecosystem='undead', Family='skeletons' },
        ['Forest Funguar']      = { Name='Forest Funguar', Ecosystem='plantoids', Family='funguars' },
        ['Forest Hare']         = { Name='Forest Hare', Ecosystem='beasts', Family='rabbits' },
        ['Fungus Beetle']       = { Name='Fungus Beetle', Ecosystem='vermin', Family='beetles' },
        ['Goblin Digger']       = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Fisher']       = { Name='Goblin Fisher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Thug']         = { Name='Goblin Thug', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Weaver']       = { Name='Goblin Weaver', Ecosystem='beastmen', Family='goblins' },
        ['Gougetooth Ganzaga']  = { Name='Gougetooth Ganzaga', Ecosystem='beasts', Family='rabbits' },
        ['Jaggedy-Eared Jack']  = { Name='Jaggedy-Eared Jack', Ecosystem='beasts', Family='rabbits' },
        ['Lancing Lamorak']     = { Name='Lancing Lamorak', Ecosystem='vermin', Family='beetles' },
        ['Land Crab']           = { Name='Land Crab', Ecosystem='aquans', Family='crabs' },
        ['Limicoline Crab']     = { Name='Limicoline Crab', Ecosystem='aquans', Family='crabs' },
        ['Marauder Dvogzog']    = { Name='Marauder Dvogzog', Ecosystem='beastmen', Family='orcs' },
        ['Mouse Bat']           = { Name='Mouse Bat', Ecosystem='birds', Family='bats' },
        ['Orcish Chasseur']     = { Name='Orcish Chasseur', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Cursemaker']   = { Name='Orcish Cursemaker', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Fighter']      = { Name='Orcish Fighter', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Fighterchief'] = { Name='Orcish Fighterchief', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Fodder']       = { Name='Orcish Fodder', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Grappler']     = { Name='Orcish Grappler', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Mesmerizer']   = { Name='Orcish Mesmerizer', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Serjeant']     = { Name='Orcish Serjeant', Ecosystem='beastmen', Family='orcs' },
        ['Passage Crab']        = { Name='Passage Crab', Ecosystem='aquans', Family='crabs' },
        ['Pixie']               = { Name='Pixie', Ecosystem='elementals', Family='pixies' },
        ['Pyracmon']            = { Name='Pyracmon', Ecosystem='demons', Family='ahriman' },
        ['River Crab']          = { Name='River Crab', Ecosystem='aquans', Family='crabs' },
        ['Scarab Beetle']       = { Name='Scarab Beetle', Ecosystem='vermin', Family='beetles' },
        ['Tainted Hound']       = { Name='Tainted Hound', Ecosystem='undead', Family='hounds' },
        ['Tree Crab']           = { Name='Tree Crab', Ecosystem='aquans', Family='crabs' },
        ['Tunnel Worm']         = { Name='Tunnel Worm', Ecosystem='amorphs', Family='worms' },
        ['Vermivorous Crab']    = { Name='Vermivorous Crab', Ecosystem='aquans', Family='crabs' },
        ['Wild Rabbit']         = { Name='Wild Rabbit', Ecosystem='beasts', Family='rabbits' },
        ['Wild Sheep']          = { Name='Wild Sheep', Ecosystem='beasts', Family='sheep' },
        ['Wraith Bat']          = { Name='Wraith Bat', Ecosystem='birds', Family='bats' },
    },
};
