--Zone: East Ronfaure
--Zone ID: 101
return {
    Names = {
        ['Bigmouth Billy']      = { Name='Bigmouth Billy', Ecosystem='aquans', Family='pugils' },
        ['Bomb']                = { Name='Bomb', Ecosystem='arcana', Family='bombs' },
        ['Capricornus']         = { Name='Capricornus', Ecosystem='aquans', Family='pugils' },
        ['Carrion Worm']        = { Name='Carrion Worm', Ecosystem='amorphs', Family='worms' },
        ['Cheval Pugil']        = { Name='Cheval Pugil', Ecosystem='aquans', Family='pugils' },
        ['Ding Bats']           = { Name='Ding Bats', Ecosystem='birds', Family='bat trios' },
        ['Enchanted Bones']     = { Name='Enchanted Bones', Ecosystem='undead', Family='skeletons' },
        ['Fighting Pugil']      = { Name='Fighting Pugil', Ecosystem='aquans', Family='pugils' },
        ['Forest Funguar']      = { Name='Forest Funguar', Ecosystem='plantoids', Family='funguars' },
        ['Forest Hare']         = { Name='Forest Hare', Ecosystem='beasts', Family='rabbits' },
        ['Gawky Gawain']        = { Name='Gawky Gawain', Ecosystem='vermin', Family='beetles' },
        ['Goblin Digger']       = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Fisher']       = { Name='Goblin Fisher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Thug']         = { Name='Goblin Thug', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Weaver']       = { Name='Goblin Weaver', Ecosystem='beastmen', Family='goblins' },
        ['Hugemaw Harold']      = { Name='Hugemaw Harold', Ecosystem='amorphs', Family='worms' },
        ['Krabkatoa']           = { Name='Krabkatoa', Ecosystem='aquans', Family='crabs' },
        ['Mouse Bat']           = { Name='Mouse Bat', Ecosystem='birds', Family='bats' },
        ['Mud Pugil']           = { Name='Mud Pugil', Ecosystem='aquans', Family='pugils' },
        ['Orcish Fodder']       = { Name='Orcish Fodder', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Grappler']     = { Name='Orcish Grappler', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Mesmerizer']   = { Name='Orcish Mesmerizer', Ecosystem='beastmen', Family='orcs' },
        ['Pixie']               = { Name='Pixie', Ecosystem='elementals', Family='pixies' },
        ['Pug Pugil']           = { Name='Pug Pugil', Ecosystem='aquans', Family='pugils' },
        ['Pugil']               = { Name='Pugil', Ecosystem='aquans', Family='pugils' },
        ['Pyracmon']            = { Name='Pyracmon', Ecosystem='demons', Family='ahriman' },
        ['Quagmire Pugil']      = { Name='Quagmire Pugil', Ecosystem='aquans', Family='pugils' },
        ['Rambukk']             = { Name='Rambukk', Ecosystem='beasts', Family='sheep' },
        ['Sarimanok']           = { Name='Sarimanok', Ecosystem='dragons', Family='puks' },
        ['Scarab Beetle']       = { Name='Scarab Beetle', Ecosystem='vermin', Family='beetles' },
        ['Sunderclaw']          = { Name='Sunderclaw', Ecosystem='aquans', Family='crabs' },
        ['Swamfisk']            = { Name='Swamfisk', Ecosystem='aquans', Family='pugils' },
        ['Tainted Hound']       = { Name='Tainted Hound', Ecosystem='undead', Family='hounds' },
        ['Tunnel Worm']         = { Name='Tunnel Worm', Ecosystem='amorphs', Family='worms' },
        ['Wild Rabbit']         = { Name='Wild Rabbit', Ecosystem='beasts', Family='rabbits' },
        ['Wild Sheep']          = { Name='Wild Sheep', Ecosystem='beasts', Family='sheep' },
        ['Wraith Bat']          = { Name='Wraith Bat', Ecosystem='birds', Family='bats' },
        ['Yacumama']            = { Name='Yacumama', Ecosystem='aquans', Family='sea monks' },
        ['Yilbegan']            = { Name='Yilbegan', Ecosystem='dragons', Family='zilant' },
    },
};
