--Zone: La Theine Plateau
--Zone ID: 102
return {
    Names = {
        ['Acro Bat']                = { Name='Acro Bat', Ecosystem='birds', Family='bats' },
        ['Air Elemental']           = { Name='Air Elemental', Ecosystem='elementals', Family='elementals' },
        ['Akbaba']                  = { Name='Akbaba', Ecosystem='birds', Family='birds' },
        ['Battering Ram']           = { Name='Battering Ram', Ecosystem='beasts', Family='rams' },
        ['Bloodtear Baldurf']       = { Name='Bloodtear Baldurf', Ecosystem='beasts', Family='rams' },
        ['Chesma']                  = { Name='Chesma', Ecosystem='beasts', Family='coeurls' },
        ['Coral Crab']              = { Name='Coral Crab', Ecosystem='aquans', Family='crabs' },
        ['Dawon']                   = { Name='Dawon', Ecosystem='beasts', Family='tigers' },
        ['Gale Bats']               = { Name='Gale Bats', Ecosystem='birds', Family='bat trios' },
        ['Ghost']                   = { Name='Ghost', Ecosystem='undead', Family='ghosts' },
        ['Giant Pugil']             = { Name='Giant Pugil', Ecosystem='aquans', Family='pugils' },
        ['Goblin Ambusher']         = { Name='Goblin Ambusher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Archaeologist']    = { Name='Goblin Archaeologist', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Butcher']          = { Name='Goblin Butcher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Digger']           = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Fisher']           = { Name='Goblin Fisher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Thug']             = { Name='Goblin Thug', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Tinkerer']         = { Name='Goblin Tinkerer', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Weaver']           = { Name='Goblin Weaver', Ecosystem='beastmen', Family='goblins' },
        ['Grass Funguar']           = { Name='Grass Funguar', Ecosystem='beastmen', Family='funguars' },
        ['Grenade']                 = { Name='Grenade', Ecosystem='arcana', Family='bombs' },
        ['Huge Wasp']               = { Name='Huge Wasp', Ecosystem='birds', Family='bees' },
        ['Ironhorn Baldurno']       = { Name='Ironhorn Baldurno', Ecosystem='beasts', Family='rams' },
        ['Lumbering Lambert']       = { Name='Lumbering Lambert', Ecosystem='beasts', Family='rams' },
        ['Mad Sheep']               = { Name='Mad Sheep', Ecosystem='beasts', Family='sheep' },
        ['Nihniknoovi']             = { Name='Nihniknoovi', Ecosystem='birds', Family='birds' },
        ['Orcish Fodder']           = { Name='Orcish Fodder', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Grappler']         = { Name='Orcish Grappler', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Grunt']            = { Name='Orcish Grunt', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Mesmerizer']       = { Name='Orcish Mesmerizer', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Neckchopper']      = { Name='Orcish Neckchopper', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Stonechucker']     = { Name='Orcish Stonechucker', Ecosystem='beastmen', Family='orcs' },
        ['Otherworldly Rimester']   = { Name='Otherworldly Rimester', Ecosystem='beastmen', Family='ghosts' },
        ['Pixie']                   = { Name='Pixie', Ecosystem='elementals', Family='elementals' },
        ['Plague Bats']             = { Name='Plague Bats', Ecosystem='birds', Family='bat trios' },
        ['Poison Bat']              = { Name='Poison Bat', Ecosystem='birds', Family='bats' },
        ['Poison Funguar']          = { Name='Poison Funguar', Ecosystem='plantoids', Family='funguars' },
        ['Poltergeist']             = { Name='Poltergeist', Ecosystem='undead', Family='ghosts' },
        ['Prickly Sheep']           = { Name='Prickly Sheep', Ecosystem='beasts', Family='sheep' },
        ['Puffer Pugil']            = { Name='Puffer Pugil', Ecosystem='aquans', Family='pugils' },
        ['Pug Pugil']               = { Name='Pug Pugil', Ecosystem='aquans', Family='pugils' },
        ['Rock Eater']              = { Name='Rock Eater', Ecosystem='amorphs', Family='worms' },
        ['Skeleton Sorcerer']       = { Name='Skeleton Sorcerer', Ecosystem='undead', Family='skeletons' },
        ['Skeleton Warrior']        = { Name='Skeleton Warrior', Ecosystem='undead', Family='skeletons' },
        ['Slumbering Samwell']      = { Name='Slumbering Samwell', Ecosystem='beasts', Family='sheep' },
        ['Stachysaurus']            = { Name='Stachysaurus', Ecosystem='lizards', Family='wivres' },
        ['Steppe Hare']             = { Name='Steppe Hare', Ecosystem='beasts', Family='rabbits' },
        ['Strolling Sapling']       = { Name='Strolling Sapling', Ecosystem='plantoids', Family='saplings' },
        ['Tammuz']                  = { Name='Tammuz', Ecosystem='beasts', Family='rams' },
        ['Thickshell']              = { Name='Thickshell', Ecosystem='aquans', Family='crabs' },
        ['Tumbling Truffle']        = { Name='Tumbling Truffle', Ecosystem='plantoids', Family='funguars' },
        ['Void Hare']               = { Name='Void Hare', Ecosystem='beasts', Family='rabbits' },
        ['Water Elemental']         = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
        ['Wolf Zombie']             = { Name='Wolf Zombie', Ecosystem='undead', Family='hounds' },
        ['Yilbegan']                = { Name='Yilbegan', Ecosystem='dragons', Family='zilant' },
        ['Zagh']                    = { Name='Zagh', Ecosystem='birds', Family='birds' },
    },
};
