--Zone: Valkurm Dunes
--Zone ID: 103
return {
    Names = {
        ['Beach Monk']              = { Name='Beach Monk', Ecosystem='aquans', Family='sea monks' },
        ['Beach Pugil']             = { Name='Beach Pugil', Ecosystem='aquans', Family='pugils' },
        ['Blue Bascinet']           = { Name='Blue Bascinet', Ecosystem='aquans', Family='crabs' },
        ['Bogy']                    = { Name='Bogy', Ecosystem='undead', Family='ghosts' },
        ['Brutal Sheep']            = { Name='Brutal Sheep', Ecosystem='beasts', Family='sheep' },
        ['Cutter']                  = { Name='Cutter', Ecosystem='aquans', Family='crabs' },
        ['Damselfly']               = { Name='Damselfly', Ecosystem='vermin', Family='flies' },
        ['Doman']                   = { Name='Doman', Ecosystem='undead', Family='fomors' },
        ['Earth Elemental']         = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Fire Elemental']          = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals' },
        ['Ghoul']                   = { Name='Ghoul', Ecosystem='undead', Family='skeletons' },
        ['Giant Bat']               = { Name='Giant Bat', Ecosystem='birds', Family='bats' },
        ['Goblin Ambusher']         = { Name='Goblin Ambusher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Bounty Hunter']    = { Name='Goblin Bounty Hunter', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Butcher']          = { Name='Goblin Butcher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Digger']           = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Gambler']          = { Name='Goblin Gambler', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Gaoler']           = { Name='Goblin Gaoler', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Leecher']          = { Name='Goblin Leecher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Mugger']           = { Name='Goblin Mugger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Swindler']         = { Name='Goblin Swindler', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Swordmaker']       = { Name='Goblin Swordmaker', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Tinkerer']         = { Name='Goblin Tinkerer', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Dragonfly']     = { Name='Goblin\'s Dragonfly', Ecosystem='birds', Family='flies' },
        ['Golden Bat']              = { Name='Golden Bat', Ecosystem='birds', Family='bats' },
        ['Halforc Black Mage']      = { Name='Halforc Black Mage', Ecosystem='beastmen', Family='orcs' },
        ['Halforc Dark Knight']     = { Name='Halforc Dark Knight', Ecosystem='beastmen', Family='orcs' },
        ['Halforc Dragoon']         = { Name='Halforc Dragoon', Ecosystem='beastmen', Family='orcs' },
        ['Halforc Monk']            = { Name='Halforc Monk', Ecosystem='beastmen', Family='orcs' },
        ['Halforc Paladin']         = { Name='Halforc Paladin', Ecosystem='beastmen', Family='orcs' },
        ['Halforc Ranger']          = { Name='Halforc Ranger', Ecosystem='beastmen', Family='orcs' },
        ['Halforc Warrior']         = { Name='Halforc Warrior', Ecosystem='beastmen', Family='orcs' },
        ['Heike Crab']              = { Name='Heike Crab', Ecosystem='aquans', Family='crabs' },
        ['Hill Lizard']             = { Name='Hill Lizard', Ecosystem='lizards', Family='lizards' },
        ['Hippomaritimus']          = { Name='Hippomaritimus', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Beastmaster']   = { Name='Hobgoblin Beastmaster', Ecosystem='beastmen', Family='pugils' },
        ['Hobgoblin Black Mage']    = { Name='Hobgoblin Black Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Dark Knight']   = { Name='Hobgoblin Dark Knight', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Ranger']        = { Name='Hobgoblin Ranger', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Red Mage']      = { Name='Hobgoblin Red Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Thief']         = { Name='Hobgoblin Thief', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Warrior']       = { Name='Hobgoblin Warrior', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin White Mage']    = { Name='Hobgoblin White Mage', Ecosystem='beastmen', Family='goblins' },
        ['Houu the Shoalwader']     = { Name='Houu the Shoalwader', Ecosystem='beastmen', Family='sahagin' },
        ['Ig-Alima']                = { Name='Ig-Alima', Ecosystem='demons', Family='gallu' },
        ['Marchelute']              = { Name='Marchelute', Ecosystem='undead', Family='fomors' },
        ['Metal Shears']            = { Name='Metal Shears', Ecosystem='aquans', Family='crabs' },
        ['Metaquadav Black Mage']   = { Name='Metaquadav Black Mage', Ecosystem='beastmen', Family='quadav' },
        ['Metaquadav Dark Knight']  = { Name='Metaquadav Dark Knight', Ecosystem='beastmen', Family='quadav' },
        ['Metaquadav Paladin']      = { Name='Metaquadav Paladin', Ecosystem='beastmen', Family='quadav' },
        ['Metaquadav Red Mage']     = { Name='Metaquadav Red Mage', Ecosystem='beastmen', Family='quadav' },
        ['Metaquadav Thief']        = { Name='Metaquadav Thief', Ecosystem='beastmen', Family='quadav' },
        ['Metaquadav Warrior']      = { Name='Metaquadav Warrior', Ecosystem='beastmen', Family='quadav' },
        ['Metaquadav White Mage']   = { Name='Metaquadav White Mage', Ecosystem='beastmen', Family='quadav' },
        ['Night Bats']              = { Name='Night Bats', Ecosystem='birds', Family='bat trios' },
        ['Onryo']                   = { Name='Onryo', Ecosystem='undead', Family='ghosts' },
        ['Orc\'s Wyvern']           = { Name='Orc\'s Wyvern', Ecosystem='Dragons', Family='pet wyverns' },
        ['Pixie']                   = { Name='Pixie', Ecosystem='elementals', Family='pixies' },
        ['Puffer Pugil']            = { Name='Puffer Pugil', Ecosystem='aquans', Family='pugils' },
        ['Sand Bats']               = { Name='Sand Bats', Ecosystem='birds', Family='bat trios' },
        ['Sand Hare']               = { Name='Sand Hare', Ecosystem='beasts', Family='rabbits' },
        ['Snipper']                 = { Name='Snipper,' Ecosystem='aquans', Family='crabs' },
        ['Stag Crab']               = { Name='Stag Crab', Ecosystem='aquans', Family='crabs' },
        ['Star Bat']                = { Name='Star Bat', Ecosystem='birds', Family='bats' },
        ['Thread Leech']            = { Name='Thread Leech', Ecosystem='amorphs', Family='leeches' },
        ['Valkurm Emperor']         = { Name='Valkurm Emperor', Ecosystem='vermin', Family='flies' },
        ['Will-o\'-the-Wisp']       = { Name='Will-o\'-the-Wisp', Ecosystem='arcana', Family='bombs' },
    },
};
