--Zone: Jugner Forest
--Zone ID: 104
return {
    Names = {
        ['Belphoebe']               = { Name='Belphoebe', Ecosystem='elementals', Family='pixies' },
        ['Boggart']                 = { Name='Boggart', Ecosystem='arcana', Family='evil weapons' },
        ['Bogy']                    = { Name='Bogy', Ecosystem='undead', Family='ghosts' },
        ['Brutal Sheep']            = { Name='Brutal Sheep', Ecosystem='beasts', Family='sheep' },
        ['Capricornus']             = { Name='Capricornus', Ecosystem='aquans', Family='pugils' },
        ['Cernunnos']               = { Name='Cernunnos', Ecosystem='plantoids', Family='treants' },
        ['Duessa']                  = { Name='Duessa', Ecosystem='plantoids', Family='saplings' },
        ['Emperor Arthro']          = { Name='Emperor Arthro', Ecosystem='aquans', Family='crabs' },
        ['Ferocious Pugil']         = { Name='Ferocious Pugil', Ecosystem='aquans', Family='pugils' },
        ['Forest Leech']            = { Name='Forest Leech', Ecosystem='amorphs', Family='leeches' },
        ['Forest Tiger']            = { Name='Forest Tiger', Ecosystem='beasts', Family='tigers' },
        ['Fradubio']                = { Name='Fradubio', Ecosystem='plantoids', Family='treants' },
        ['Fraelissa']               = { Name='Fraelissa', Ecosystem='plantoids', Family='treants' },
        ['Ghoul']                   = { Name='Ghoul', Ecosystem='undead', Family='skeletons' },
        ['Giollemitte B Feroun']    = { Name='Giollemitte B Feroun', Ecosystem='undead', Family='fomors' },
        ['Goblin Ambusher']         = { Name='Goblin Ambusher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Butcher']          = { Name='Goblin Butcher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Digger']           = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Gambler']          = { Name='Goblin Gambler', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Leecher']          = { Name='Goblin Leecher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Mugger']           = { Name='Goblin Mugger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Tinkerer']         = { Name='Goblin Tinkerer', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Beetle']        = { Name='Goblin\'s Beetle', Ecosystem='vermin', Family='beetles' },
        ['Halforc Black Mage']      = { Name='Halforc Black Mage', Ecosystem='beastmen', Family='orcs' },
        ['Halforc Dark Knight']     = { Name='Halforc Dark Knight', Ecosystem='beastmen', Family='orcs' },
        ['Halforc Dragoon']         = { Name='Halforc Dragoon', Ecosystem='beastmen', Family='orcs' },
        ['Halforc Monk']            = { Name='Halforc Monk', Ecosystem='beastmen', Family='orcs' },
        ['Halforc Paladin']         = { Name='Halforc Paladin', Ecosystem='beastmen', Family='orcs' },
        ['Halforc Ranger']          = { Name='Halforc Ranger', Ecosystem='beastmen', Family='orcs' },
        ['Halforc Warrior']         = { Name='Halforc Warrior', Ecosystem='beastmen', Family='orcs' },
        ['Hobgoblin Beastmaster']   = { Name='Hobgoblin Beastmaster', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Black Mage']    = { Name='Hobgoblin Black Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Dark Knight']   = { Name='Hobgoblin Dark Knight', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Ranger']        = { Name='Hobgoblin Ranger', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Red Mage']      = { Name='Hobgoblin Red Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Thief']         = { Name='Hobgoblin Thief', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Warrior']       = { Name='Hobgoblin Warrior', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin White Mage']    = { Name='Hobgoblin White Mage', Ecosystem='beastmen', Family='goblins' },
        ['Huge Leech']              = { Name='Huge Leech', Ecosystem='amorphs', Family='leeches' },
        ['Jugner Funguar']          = { Name='Jugner Funguar', Ecosystem='plantoids', Family='funguars' },
        ['King Arthro']             = { Name='King Arthro', Ecosystem='aquans', Family='crabs' },
        ['Knight Crab']             = { Name='Knight Crab', Ecosystem='aquans', Family='crabs' },
        ['Krabkatoa']               = { Name='Krabkatoa', Ecosystem='aquans', Family='crabs' },
        ['Kumbaba']                 = { Name='Kumbaba', Ecosystem='beastmen', Family='gigas' },
        ['Land Pugil']              = { Name='Land Pugil', Ecosystem='aquans', Family='pugils' },
        ['Meteormauler Zhagtegg']   = { Name='Meteormauler Zhagtegg', Ecosystem='beastmen', Family='orcs' },
        ['Orc\'s Wyvern']           = { Name='Orc\'s Wyvern', Ecosystem='dragons', Family='wyvern' },
        ['Orcish Chasseur']         = { Name='Orcish Chasseur', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Colonel']          = { Name='Orcish Colonel', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Cursemaker']       = { Name='Orcish Cursemaker', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Fighter']          = { Name='Orcish Fighter', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Grunt']            = { Name='Orcish Grunt', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Neckchopper']      = { Name='Orcish Neckchopper', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Serjeant']         = { Name='Orcish Serjeant', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Stonechucker']     = { Name='Orcish Stonechucker', Ecosystem='beastmen', Family='orcs' },
        ['Panzer Percival']         = { Name='Panzer Percival', Ecosystem='vermin', Family='beetles' },
        ['Quagmire Pugil']          = { Name='Quagmire Pugil', Ecosystem='aquans', Family='pugils' },
        ['Sappy Sycamore']          = { Name='Sappy Sycamore', Ecosystem='plantoids', Family='saplings' },
        ['Scavenging Hound']        = { Name='Scavenging Hound', Ecosystem='undead', Family='hounds' },
        ['Screamer']                = { Name='Screamer', Ecosystem='birds', Family='birds' },
        ['Skeleton Esquire']        = { Name='Skeleton Esquire', Ecosystem='undead', Family='skeletons' },
        ['Snipper']                 = { Name='Snipper', Ecosystem='aquans', Family='crabs' },
        ['Spring Pugil']            = { Name='Spring Pugil', Ecosystem='aquans', Family='pugils' },
        ['Sprite']                  = { Name='Sprite', Ecosystem='elementals', Family='pixies' },
        ['Stag Beetle']             = { Name='Stag Beetle', Ecosystem='vermin', Family='beetles' },
        ['Stag Crab']               = { Name='Stag Crab', Ecosystem='aquans', Family='crabs' },
        ['Sunderclaw']              = { Name='Sunderclaw', Ecosystem='aquans', Family='crabs' },
        ['Supplespine Mujwuj']      = { Name='Supplespine Mujwuj', Ecosystem='beastmen', Family='orcs' },
        ['Thread Leech']            = { Name='Thread Leech', Ecosystem='amorphs', Family='leeches' },
        ['Thunder Elemental']       = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
        ['Walking Tree']            = { Name='Walking Tree', Ecosystem='plantoids', Family='treants' },
        ['Wandering Sapling']       = { Name='Wandering Sapling', Ecosystem='plantoids', Family='saplings' },
        ['Water Elemental']         = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
        ['Will-o\'-the-Wisp']       = { Name='Will-o\'-the-Wisp', Ecosystem='arcana', Family='bombs' },
        ['Yacumama']                = { Name='Yacumama', Ecosystem='aquans', Family='sea monks' },
        ['Yilbegan']                = { Name='Yilbegan', Ecosystem='dragons', Family='zilant' },
        -- Custom content for HorizonXI
        ['Despotic Decapod']        = { Name='Despotic Decapod', Ecosystem='aquans', Family='crabs' },
    },
};
