--Zone: Batallia Downs
--Zone ID: 105
return {
    Names = {
        ['Ahtu']                    = { Name='Ahtu', Ecosystem='plantoids', Family='treants' },
        ['Aither']                  = { Name='Aither', Ecosystem='elementals', Family='elementals' },
        ['Ba']                      = { Name='Ba', Ecosystem='birds', Family='birds' },
        ['Badshah']                 = { Name='Badshah', Ecosystem='beast', Family='tiger' },
        ['Beorht']                  = { Name='Beorht', Ecosystem='elementals', Family='elementals' },
        ['Cherufe']                 = { Name='Cherufe', Ecosystem='lizards', Family='wivres' },
        ['Clipper']                 = { Name='Clipper', Ecosystem='aquans', Family='crabs' },
        ['Cutter']                  = { Name='Cutter', Ecosystem='aquans', Family='crabs' },
        ['Deorc']                   = { Name='Deorc', Ecosystem='elementals', Family='elementals' },
        ['Earth Elemental']         = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Eorthe']                  = { Name='Eorthe', Ecosystem='elementals', Family='elementals' },
        ['Evil Spirit']             = { Name='Evil Spirit', Ecosystem='undead', Family='ghosts' },
        ['Evil Weapon']             = { Name='Evil Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Eyegouger']               = { Name='Eyegouger', Ecosystem='birds', Family='birds' },
        ['Goblin Bounty Hunter']    = { Name='Goblin Bounty Hunter', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Digger']           = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Furrier']          = { Name='Goblin Furrier', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Gambler']          = { Name='Goblin Gambler', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Leecher']          = { Name='Goblin Leecher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Mugger']           = { Name='Goblin Mugger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Pathfinder']       = { Name='Goblin Pathfinder', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Shaman']           = { Name='Goblin Shaman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Smithy']           = { Name='Goblin Smithy', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Dragonfly']     = { Name='Goblin\'s Dragonfly', Ecosystem='vermin', Family='flies' },
        ['Greater Pugil']           = { Name='Greater Pugil', Ecosystem='aquans', Family='pugils' },
        ['Ice Elemental']           = { Name='Ice Elemental', Ecosystem='elementals', Family='elementals' },
        ['Ignis Fatuus']            = { Name='Ignis Fatuus', Ecosystem='arcana', Family='bombs' },
        ['Kraken']                  = { Name='Kraken', Ecosystem='aquans', Family='sea monks' },
        ['Lacus']                   = { Name='Lacus', Ecosystem='elementals', Family='elementals' },
        ['Land Pugil']              = { Name='Land Pugil', Ecosystem='aquans', Family='pugils' },
        ['Lanky Lenglen']           = { Name='Lanky Lenglen', Ecosystem='vermin', Family='flies' },
        ['Lumber Jack']             = { Name='Lumber Jack', Ecosystem='vermin', Family='beetles' },
        ['Mauthe Doog']             = { Name='Mauthe Doog', Ecosystem='undead', Family='hounds' },
        ['May Fly']                 = { Name='May Fly', Ecosystem='vermin', Family='flies' },
        ['Orcish Beastrider']       = { Name='Orcish Beastrider', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Brawler']          = { Name='Orcish Brawler', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Cursemaker']       = { Name='Orcish Cursemaker', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Fighter']          = { Name='Orcish Fighter', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Impaler']          = { Name='Orcish Impaler', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Nightraider']      = { Name='Orcish Nightraider', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Serjeant']         = { Name='Orcish Serjeant', Ecosystem='beastmen', Family='orcs' },
        ['Prankster Maverix']       = { Name='Prankster Maverix', Ecosystem='arcana', Family='evil weapons' },
        ['Pruina']                  = { Name='Pruina', Ecosystem='elementals', Family='elementals' },
        ['Puretos']                 = { Name='Puretos', Ecosystem='elementals', Family='elementals' },
        ['Sabertooth Tiger']        = { Name='Sabertooth Tiger', Ecosystem='beasts', Family='tigers' },
        ['Skirling Liger']          = { Name='Skirling Liger', Ecosystem='beasts', Family='tigers' },
        ['Skuld']                   = { Name='Skuld', Ecosystem='elementals', Family='pixies' },
        ['Snipper']                 = { Name='Snipper', Ecosystem='aquans', Family='crabs' },
        ['Sobbing Sapling']         = { Name='Sobbing Sapling', Ecosystem='plantoids', Family='saplings' },
        ['Sprite']                  = { Name='Sprite', Ecosystem='elementals', Family='pixies' },
        ['Stalking Sapling']        = { Name='Stalking Sapling', Ecosystem='plantoids', Family='saplings' },
        ['Sturmtiger']              = { Name='Sturmtiger', Ecosystem='beasts', Family='tigers' },
        ['Suparna']                 = { Name='Suparna', Ecosystem='birds', Family='birds' },
        ['Suparna Fledgling']       = { Name='Suparna Fledgling', Ecosystem='birds', Family='birds' },
        ['Thunor']                  = { Name='Thunor', Ecosystem='elementals', Family='elementals' },
        ['Tottering Toby']          = { Name='Tottering Toby', Ecosystem='plantoids', Family='saplings' },
        ['Treant']                  = { Name='Treant', Ecosystem='plantoids', Family='treants' },
        ['Urd']                     = { Name='Urd', Ecosystem='elementals', Family='pixies' },
        ['Vegnix Greenthumb']       = { Name='Vegnix Greenthumb', Ecosystem='beastmen', Family='goblins' },
        ['Verthandi']               = { Name='Verthandi', Ecosystem='elementals', Family='pixies' },
        ['Weeping Willow']          = { Name='Weeping Willow', Ecosystem='plantoids', Family='treants' },
        ['Wight']                   = { Name='Wight', Ecosystem='undead', Family='skeletons' },
        ['Yilbegan']                = { Name='Yilbegan', Ecosystem='dragons', Family='zilant' },
    },
};
