--Zone: North Gustaberg
--Zone ID: 106
return {
    Names = {
        ['Amber Quadav']            = { Name='Amber Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Amethyst Quadav']         = { Name='Amethyst Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Bedrock Barry']           = { Name='Bedrock Barry', Ecosystem='amorphs', Family='worms' },
        ['Black Wolf']              = { Name='Black Wolf', Ecosystem='undead', Family='hound' },
        ['Blobdingnag']             = { Name='Blobdingnag', Ecosystem='beastmen', Family='quadav' },
        ['Brass Quadav']            = { Name='Brass Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Deathly Stinger']         = { Name='Deathly Stinger', Ecosystem='vermin', Family='bees' },
        ['Ding Bats']               = { Name='Ding Bats', Ecosystem='birds', Family='bat trios' },
        ['Enchanted Bones']         = { Name='Enchanted Bones', Ecosystem='undead', Family='skeletons' },
        ['Fighting Pugil']          = { Name='Fighting Pugil', Ecosystem='aquans', Family='pugils' },
        ['Fledermaus']              = { Name='Fledermaus', Ecosystem='birds', Family='bats' },
        ['Gambilox Wanderling']     = { Name='Gambilox Wanderling', Ecosystem='beastmen', Family='goblins' },
        ['Globster']                = { Name='Globster', Ecosystem='amorphs', Family='slimes' },
        ['Goblin Digger']           = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Fisher']           = { Name='Goblin Fisher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Gambler']          = { Name='Goblin Gambler', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Leecher']          = { Name='Goblin Leecher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Mugger']           = { Name='Goblin Mugger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Thug']             = { Name='Goblin Thug', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Weaver']           = { Name='Goblin Weaver', Ecosystem='beastmen', Family='goblins' },
        ['Ground Guzzler']          = { Name='Ground Guzzler', Ecosystem='amorphs', Family='worms' },
        ['Heliodor Quadav']         = { Name='Heliodor Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Huge Hornet']             = { Name='Huge Hornet', Ecosystem='vermin', Family='bees' },
        ['Lamprey Lord']            = { Name='Lamprey Lord', Ecosystem='amorphs', Family='leeches' },
        ['Land Crab']               = { Name='Land Crab', Ecosystem='aquans', Family='crabs' },
        ['Lead Quadav']             = { Name='Lead Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Maighdean Uaine']         = { Name='Maighdean Uaine', Ecosystem='plantoids', Family='saplings' },
        ['Maneating Hornet']        = { Name='Maneating Hornet', Ecosystem='vermin', Family='bees' },
        ['Old Quadav']              = { Name='Old Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Ornery Sheep']            = { Name='Ornery Sheep', Ecosystem='beasts', Family='sheep' },
        ['Pixie']                   = { Name='Pixie', Ecosystem='elementals', Family='pixies' },
        ['Pug Pugil']               = { Name='Pug Pugil', Ecosystem='aquans', Family='pugils' },
        ['Pyracmon']                = { Name='Pyracmon', Ecosystem='demons', Family='ahriman' },
        ['River Crab']              = { Name='River Crab', Ecosystem='aquans', Family='crabs' },
        ['Rock Lizard']             = { Name='Rock Lizard', Ecosystem='lizards', Family='lizards' },
        ['Sallow Seymour']          = { Name='Sallow Seymour', Ecosystem='amorphs', Family='worms' },
        ['Sand Crab']               = { Name='Sand Crab', Ecosystem='aquans', Family='crabs' },
        ['Sand Pugil']              = { Name='Sand Pugil', Ecosystem='aquans', Family='pugils' },
        ['Sapphirine Quadav']       = { Name='Sapphirine Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Septic Boil']             = { Name='Septic Boil', Ecosystem='amorphs', Family='slimes' },
        ['Shoggoth']                = { Name='Shoggoth', Ecosystem='amorphs', Family='hecteyes' },
        ['Shrapnel']                = { Name='Shrapnel', Ecosystem='arcana', Family='bombs' },
        ['Stinging Sophie']         = { Name='Stinging Sophie', Ecosystem='birds', Family='bees' },
        ['Stone Crab']              = { Name='Stone Crab', Ecosystem='aquans', Family='crabs' },
        ['Stone Eater']             = { Name='Stone Eater', Ecosystem='amorphs', Family='worms' },
        ['Tunnel Worm']             = { Name='Tunnel Worm', Ecosystem='amorphs', Family='worms' },
        ['Vulture']                 = { Name='Vulture', Ecosystem='birds', Family='birds' },
        ['Walking Sapling']         = { Name='Walking Sapling', Ecosystem='plantoids', Family='saplings' },
        ['Wraith Bat']              = { Name='Wraith Bat', Ecosystem='birds', Family='bats' },
        ['Yilbegan']                = { Name='Yilbegan', Ecosystem='dragons', Family='zilant' },
        ['Young Quadav']            = { Name='Young Quadav', Ecosystem='beastmen', Family='quadav' },
    },
};
