--Zone: South Gustaberg
--Zone ID: 107
return {
    Names = {
        ['Amber Quadav']        = { Name='Amber Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Amethyst Quadav']     = { Name='Amethyst Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Bhishani']            = { Name='Bhishani', Ecosystem='elementals', Family='pixies' },
        ['Black Wolf']          = { Name='Black Wolf', Ecosystem='undead', Family='hounds' },
        ['Bounding Belinda']    = { Name='Bounding Belinda', Ecosystem='lizards', Family ='lizards' },
        ['Bubbly Bernie']       = { Name='Bubbly Bernie', Ecosystem='aquans', Family='crabs' },
        ['Carnero']             = { Name='Carnero', Ecosystem='beasts', Family='sheep' },
        ['Ding Bats']           = { Name='Ding Bats', Ecosystem='birds', Family='bat trios' },
        ['Enchanted Bones']     = { Name='Enchanted Bones', Ecosystem='undead', Family='skeletons' },
        ['Fledermaus']          = { Name='Fledermaus', Ecosystem='birds', Family='bats' },
        ['Goblin Digger']       = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Fisher']       = { Name='Goblin Fisher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Thug']         = { Name='Goblin Thug', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Weaver']       = { Name='Goblin Weaver', Ecosystem='beastmen', Family='goblins' },
        ['Grylio']              = { Name='Grylio', Ecosystem='lizards', Family='lizards' },
        ['Huge Hornet']         = { Name='Huge Hornet', Ecosystem='vermin', Family='bees' },
        ['Land Crab']           = { Name='Land Crab', Ecosystem='aquans', Family='crabs' },
        ['Leaping Lizzy']       = { Name='Leaping Lizzy', Ecosystem='lizards', Family='lizards' },
        ['Maneating Hornet']    = { Name='Maneating Hornet', Ecosystem='vermin', Family='bees' },
        ['Mole Crab']           = { Name='Mole Crab', Ecosystem='aquans', Family='crabs' },
        ['Ornery Sheep']        = { Name='Ornery Sheep', Ecosystem='beasts', Family='sheep' },
        ['Passage Crab']        = { Name='Passage Crab', Ecosystem='aquans', Family='crabs' },
        ['Pixie']               = { Name='Pixie', Ecosystem='elementals', Family='pixies' },
        ['Pyracmon']            = { Name='Pyracmon', Ecosystem='demons', Family='ahriman' },
        ['Rock Lizard']         = { Name='Rock Lizard', Ecosystem='lizards', Family='lizards' },
        ['Sand Crab']           = { Name='Sand Crab', Ecosystem='aquans', Family='crabs' },
        ['Shrapnel']            = { Name='Shrapnel', Ecosystem='arcana', Family='bombs' },
        ['Stone Crab']          = { Name='Stone Crab', Ecosystem='aquans', Family='crabs' },
        ['Stone Eater']         = { Name='Stone Eater', Ecosystem='amorphs', Family='worms' },
        ['Tococo']              = { Name='Tococo', Ecosystem='birds', Family='birds' },
        ['Tunnel Worm']         = { Name='Tunnel Worm', Ecosystem='amorphs', Family='worms' },
        ['Vulture']             = { Name='Vulture', Ecosystem='birds', Family='birds' },
        ['Walking Sapling']     = { Name='Walking Sapling', Ecosystem='plantoids', Family='saplings' },
        ['Wraith Bat']          = { Name='Wraith Bat', Ecosystem='birds', Family='bats' },
        ['Young Quadav']        = { Name='Young Quadav', Ecosystem='beastmen', Family='quadav' },
    },
};
