--Zone: Konschtat Highlands
--Zone ID: 108
return {
    Names = {
        ['Amber Quadav']            = { Name='Amber Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Amethyst Quadav']         = { Name='Amethyst Quadav', Ecosystem='beastmen' Family='quadav' },
        ['Bendigeit Vran']          = { Name='Bendigeit Vran', Ecosystem='undead' Family='fomors' },
        ['Chesma']                  = { Name='Chesma', Ecosystem='beasts' Family='coeurls' },
        ['Dawon']                   = { Name='Dawon', Ecosystem='beasts' Family='tigers' },
        ['Earth Elemental']         = { Name='Earth Elemental', Ecosystem='elementals' Family='elementals' },
        ['Forger']                  = { Name='Forger', Ecosystem='arcana' Family='bombs' },
        ['Ghillie Dhu']             = { Name='Ghillie Dhu', Ecosystem='plantoids' Family='saplings' },
        ['Ghost']                   = { Name='Ghost', Ecosystem='undead' Family='ghosts' },
        ['Goblin Ambusher']         = { Name='Goblin Ambusher', Ecosystem='beastmen' Family='goblins' },
        ['Goblin Archaeologist']    = { Name='Goblin Archaeologist', Ecosystem='beastmen' Family='goblins' },
        ['Goblin Butcher']          = { Name='Goblin Butcher', Ecosystem='beastmen' Family='goblins' },
        ['Goblin Digger']           = { Name='Goblin Digger', Ecosystem='beastmen' Family='goblins' },
        ['Goblin Thug']             = { Name='Goblin Thug', Ecosystem='beastmen' Family='goblins' },
        ['Goblin Tinkerer']         = { Name='Goblin Tinkerer', Ecosystem='beastmen' Family='goblins' },
        ['Goblin Weaver']           = { Name='Goblin Weaver', Ecosystem='beastmen' Family='goblins' },
        ['Greater Quadav']          = { Name='Greater Quadav', Ecosystem='beastmen' Family='quadav' },
        ['Grenade']                 = { Name='Grenade', Ecosystem='arcana' Family='bombs' },
        ['Gwynn ap Nudd']           = { Name='Gwynn ap Nudd', Ecosystem='undead' Family='corpselights' },
        ['Haty']                    = { Name='Haty', Ecosystem='undead' Family='hounds' },
        ['Highlander Lizard']       = { Name='Highlander Lizard', Ecosystem='lizards' Family='lizards' },
        ['Huge Wasp']               = { Name='Huge Wasp', Ecosystem='vermin' Family='bees' },
        ['Mad Sheep']               = { Name='Mad Sheep', Ecosystem='beasts' Family='sheep' },
        ['Mist Lizard']             = { Name='Mist Lizard', Ecosystem='lizards' Family='lizards' },
        ['Onyx Quadav']             = { Name='Onyx Quadav', Ecosystem='beastmen' Family='quadav' },
        ['Otherworldly Rimester']   = { Name='Otherworldly Rimester', Ecosystem='undead' Family='ghosts' },
        ['Pixie']                   = { Name='Pixie', Ecosystem='elementals' Family='pixies' },
        ['Poltergeist']             = { Name='Poltergeist', Ecosystem='undead' Family='ghosts' },
        ['Prickly Sheep']           = { Name='Prickly Sheep', Ecosystem='beasts' Family='sheep' },
        ['Rampaging Ram']           = { Name='Rampaging Ram', Ecosystem='beasts' Family='rams' },
        ['Rock Eater']              = { Name='Rock Eater', Ecosystem='amorphs' Family='worms' },
        ['Skeleton Sorcerer']       = { Name='Skeleton Sorcerer', Ecosystem='undead' Family='skeletons' },
        ['Skeleton Warrior']        = { Name='Skeleton Warrior', Ecosystem='undead' Family='skeletons' },
        ['Steelfleece Baldarich']   = { Name='Steelfleece Baldarich', Ecosystem='beasts' Family='rams' },
        ['Stray Mary']              = { Name='Stray Mary', Ecosystem='beasts' Family='sheep' },
        ['Strolling Sapling']       = { Name='Strolling Sapling', Ecosystem='plantoids' Family='saplings' },
        ['Tammuz']                  = { Name='Tammuz', Ecosystem='beasts' Family='rams' },
        ['Thunder Elemental']       = { Name='Thunder Elemental', Ecosystem='elementals' Family='elementals' },
        ['Thunderhead']             = { Name='Thunderhead', Ecosystem='beasts' Family='sheep' },
        ['Tremor Ram']              = { Name='Tremor Ram', Ecosystem='beasts' Family='rams' },
        ['Veteran Quadav']          = { Name='Veteran Quadav', Ecosystem='beastmen' Family='quadav' },
        ['Void Hare']               = { Name='Void Hare', Ecosystem='beasts' Family='rabbits' },
        ['Wolf Zombie']             = { Name='Wolf Zombie', Ecosystem='undead' Family='hounds' },
        ['Yilbegan']                = { Name='Yilbegan', Ecosystem='dragons' Family='zilant' },
        ['Young Quadav']            = { Name='Young Quadav', Ecosystem='beastmen' Family='quadav' },
        -- Custom content for HorizonXI
        ['Mineral Eater']           = { Name='Mineral Eater', Ecosystem='amorphs', Family='worms' },
        ['Yellow Jacket']           = { Name='Yellow Jacket', Ecosystem='vermin', Family='bees' },
    },
};
