--Zone: Pashhow Marshlands
--Zone ID: 109
return {
    Names = {
        ['Ballistosporer']              = { Name='Ballistosporer', Ecosystem='plantoids', Family='funguars' },
        ['Black Bat']                   = { Name='Black Bat', Ecosystem='birds', Family='bats' },
        ['Blobdingnag']                 = { Name='Blobdingnag', Ecosystem='amorphs', Family='slimes' },
        ['Bloodpool Vorax']             = { Name='Bloodpool Vorax', Ecosystem='amorphs', Family='leeches' },
        ['Bo\'Who Warmonger']           = { Name='Bo\'Who Warmonger',Ecosystem='arcana', Family='evil weapons' },
        ['Bog Bunny']                   = { Name='Bog Bunny', Ecosystem='undead', Family='ghosts' },
        ['Bog Dog']                     = { Name='Bog Dog', Ecosystem='undead', Family='ghosts' },
        ['Bogy']                        = { Name='Bogy', Ecosystem='undead', Family='ghosts' },
        ['Brass Quadav']                = { Name='Brass Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Carnivorous Crawler']         = { Name='Carnivorous Crawler', Ecosystem='vermin', Family='crawlers' },
        ['Cobalt Quadav']               = { Name='Cobalt Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Copper Quadav']               = { Name='Copper Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Fox Fire']                    = { Name='Fox Fire', Ecosystem='arcana', Family='bombs' },
        ['Gadfly']                      = { Name='Gadfly', Ecosystem='vermin', Family='flies' },
        ['Ghoul']                       = { Name='Ghoul', Ecosystem='undead', Family='skeletons' },
        ['Globster']                    = { Name='Globster', Ecosystem='amorphs', Family='slimes' },
        ['Goblin Ambusher']             = { Name='Goblin Ambusher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Butcher']              = { Name='Goblin Butcher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Digger']               = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Gambler']              = { Name='Goblin Gambler', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Leecher']              = { Name='Goblin Leecher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Mugger']               = { Name='Goblin Mugger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Tinkerer']             = { Name='Goblin Tinkerer', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Bee']               = { Name='Goblin\'s Bee', Ecosystem='vermin', Family='bees' },
        ['Goobbue']                     = { Name='Goobbue', Ecosystem='plantoids', Family='goobbues' },
        ['Greater Quadav']              = { Name='Greater Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Ground Guzzler']              = { Name='Ground Guzzler', Ecosystem='amorphs', Family='worms' },
        ['Heliodor Quadav']             = { Name='Heliodor Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Hobgoblin Beastmaster']       = { Name='Hobgoblin Beastmaster', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Black Mage']        = { Name='Hobgoblin Black Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Dark Knight']       = { Name='Hobgoblin Dark Knight', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Ranger']            = { Name='Hobgoblin Ranger', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Red Mage']          = { Name='Hobgoblin Red Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Thief']             = { Name='Hobgoblin Thief', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Warrior']           = { Name='Hobgoblin Warrior', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin White Mage']        = { Name='Hobgoblin White Mage', Ecosystem='beastmen', Family='goblins' },
        ['Jolly Green']                 = { Name='Jolly Green', Ecosystem='plantoids', Family='goobbues' },
        ['Joyous Green']                = { Name='Joyous Green', Ecosystem='plantoids', Family='goobbues' },
        ['Lamprey Lord']                = { Name='Lamprey Lord', Ecosystem='plantoids', Family='leeches' },
        ['Land Pugil']                  = { Name='Land Pugil', Ecosystem='aquans', Family='pugils' },
        ['Malboro']                     = { Name='Malboro', Ecosystem='plantoids', Family='morbols' },
        ['Marsh Funguar']               = { Name='Marsh Funguar', Ecosystem='plantoids', Family='funguars' },
        ['Metaquadav Black Mage']       = { Name='Metaquadav Black Mage', Ecosystem='beastmen', Family='quadav' },
        ['Metaquadav Dark Knight']      = { Name='Metaquadav Dark Knight', Ecosystem='beastmen', Family='quadav' },
        ['Metaquadav Paladin']          = { Name='Metaquadav Paladin', Ecosystem='beastmen', Family='quadav' },
        ['Metaquadav Red Mage']         = { Name='Metaquadav Red Mage', Ecosystem='beastmen', Family='quadav' },
        ['Metaquadav Thief']            = { Name='Metaquadav Thief', Ecosystem='beastmen', Family='quadav' },
        ['Metaquadav Warrior']          = { Name='Metaquadav Warrior', Ecosystem='beastmen', Family='quadav' },
        ['Metaquadav White Mage']       = { Name='Metaquadav White Mage', Ecosystem='beastmen', Family='quadav' },
        ['Murk-veined Baneberry']       = { Name='Murk-veined Baneberry', Ecosystem='beastmen', Family='tonberries' },
        ['Ni\'Zho Bladebender']         = { Name='Ni\'Zho Bladebender', Ecosystem='beastmen', Family='quadav' },
        ['Night Bats']                  = { Name='Night Bats', Ecosystem='birds', Family='bat trios' },
        ['Old Quadav']                  = { Name='Old Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Onyx Quadav']                 = { Name='Onyx Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Sapphirine Quadav']           = { Name='Sapphirine Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Septic Boil']                 = { Name='Septic Boil', Ecosystem='amorphs', Family='slimes' },
        ['Shoggoth']                    = { Name='Shoggoth', Ecosystem='amorphs', Family='hecteyes' },
        ['Snipper']                     = { Name='Snipper', Ecosystem='aquans', Family='crabs' },
        ['Sprite']                      = { Name='Sprite', Ecosystem='elementals', Family='pixies' },
        ['Stag Crab']                   = { Name='Stag Crab', Ecosystem='aquans', Family='crabs' },
        ['Swamp Leech']                 = { Name='Swamp Leech', Ecosystem='amorphs', Family='leeches' },
        ['Swamp Pugil']                 = { Name='Swamp Pugil', Ecosystem='aquans', Family='pugils' },
        ['Thread Leech']                = { Name='Thread Leech', Ecosystem='smorphs', Family='leeches' },
        ['Thunder Elemental']           = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
        ['Toxic Tamlyn']                = { Name='Toxic Tamlyn', Ecosystem='plantoids', Family='morbols' },
        ['Veteran Quadav']              = { Name='Veteran Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Water Elemental']             = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
        ['Water Wasp']                  = { Name='Water Wasp', Ecosystem='vermin', Family='bees' },
        ['Yilbegan']                    = { Name='Yilbegan', Ecosystem='dragons', Family='zilant' },
        ['Zombie']                      = { Name='Zombie', Ecosystem='undead', Family='skeletons' },
    },
};
