--Zone: Rolanberry Fields
--Zone ID: 110
return {
    Names = {
        ['Aither']                  = { Name='Aither', Ecosystem='elementals', Family='elementals' },
        ['Beorht']                  = { Name='Beorht', Ecosystem='elementals', Family='elementals' },
        ['Berry Grub']              = { Name='Berry Grub', Ecosystem='vermin', Family='crawlers' },
        ['Big Jaw']                 = { Name='Big Jaw', Ecosystem='aquans', Family='pugils' },
        ['Big Leech']               = { Name='Big Leech', Ecosystem='amorphs', Family='leeches' },
        ['Black Triple Stars']      = { Name='Black Triple Stars', Ecosystem='birds', Family='bat trios' },
        ['Brass Quadav']            = { Name='Brass Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Bronze Quadav']           = { Name='Bronze Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Chuglix Berrypaws']       = { Name='Chuglix Berrypaws', Ecosystem='beastmen', Family='goblins' },
        ['Clipper']                 = { Name='Clipper', Ecosystem='aquans', Family='crabs' },
        ['Copper Quadav']           = { Name='Copper Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Death Wasp']              = { Name='Death Wasp', Ecosystem='vermin', Family='bees' },
        ['Deorc']                   = { Name='Deorc', Ecosystem='elementals', Family='elementals' },
        ['Drooling Daisy']          = { Name='Drooling Daisy', Ecosystem='plantoids', Family='morbols' },
        ['Eldritch Edge']           = { Name='Eldritch Edge', Ecosystem='arcana', Family='evil weapons' },
        ['Eorthe']                  = { Name='Eorthe', Ecosystem='elementals', Family='elementals' },
        ['Evil Spirit']             = { Name='Evil Spirit', Ecosystem='undead', Family='ghosts' },
        ['Evil Weapon']             = { Name='Evil Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Fire Elemental']          = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals' },
        ['Garnet Quadav']           = { Name='Garnet Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Goblin Digger']           = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Furrier']          = { Name='Goblin Furrier', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Gambler']          = { Name='Goblin Gambler', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Leecher']          = { Name='Goblin Leecher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Mugger']           = { Name='Goblin Mugger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Pathfinder']       = { Name='Goblin Pathfinder', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Shaman']           = { Name='Goblin Shaman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Smithy']           = { Name='Goblin Smithy', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Bee']           = { Name='Goblin\'s Bee', Ecosystem='vermin', Family='bees' },
        ['Goobbue Farmer']          = { Name='Goobbue Farmer', Ecosystem='plantoids', Family='goobbues' },
        ['Greater Pugil']           = { Name='Greater Pugil', Ecosystem='aquans', Family='pugils' },
        ['Horrid Fluke']            = { Name='Horrid Fluke', Ecosystem='amorphs', Family='leeches' },
        ['Ignis Fatuus']            = { Name='Ignis Fatuus', Ecosystem='arcana', Family='bombs' },
        ['Lacus']                   = { Name='Lacus', Ecosystem='elementals', Family='elementals' },
        ['Midnight Wings']          = { Name='Midnight Wings', Ecosystem='birds', Family='bat trios' },
        ['Moon Bat']                = { Name='Moon Bat', Ecosystem='birds', Family='bats' },
        ['Ochu']                    = { Name='Ochu', Ecosystem='plantoids', Family='morbols' },
        ['Old Quadav']              = { Name='Old Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Poison Leech']            = { Name='Poison Leech', Ecosystem='amorphs', Family='leeches' },
        ['Pruina']                  = { Name='Pruina', Ecosystem='elementals', Family='elementals' },
        ['Puretos']                 = { Name='Puretos', Ecosystem='elementals', Family='elementals' },
        ['Ravenous Crawler']        = { Name='Ravenous Crawler', Ecosystem='vermin', Family='crawlers' },
        ['Silk Caterpillar']        = { Name='Silk Caterpillar', Ecosystem='vermin', Family='crawlers' },
        ['Silver Quadav']           = { Name='Silver Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Simurgh']                 = { Name='Simurgh', Ecosystem='birds', Family='rocs' },
        ['Skuld']                   = { Name='Skuld', Ecosystem='elementals', Family='pixies' },
        ['Snipper']                 = { Name='Snipper', Ecosystem='aquans', Family='crabs' },
        ['Sprite']                  = { Name='Sprite', Ecosystem='elementals', Family='pixies' },
        ['Strix']                   = { Name='Strix', Ecosystem='birds', Family='rocs' },
        ['Thunor']                  = { Name='Thunor', Ecosystem='elementals', Family='elementals' },
        ['Urayuli']                 = { Name='Urayuli', Ecosystem='plantoids', Family='goobbues' },
        ['Urd']                     = { Name='Urd', Ecosystem='elementals', Family='pixies' },
        ['Verthandi']               = { Name='Verthandi', Ecosystem='elementals', Family='pixies' },
        ['Water Elemental']         = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
        ['Wight']                   = { Name='Wight', Ecosystem='undead', Family='skeletons' },
        ['Yatagarasu']              = { Name='Yatagarasu', Ecosystem='birds', Family='rocs' },
        ['Yilbegan']                = { Name='Yilbegan', Ecosystem='dragons', Family='zilant' },
        ['Zircon Quadav']           = { Name='Zircon Quadav', Ecosystem='beastmen', Family='quadav' },
        -- Custom content for HorizonXI
        ['Ruinous Rocs']            = { Name='Ruinous Rocs', Ecosystem='birds', Family='rocs' },
        ['Shell Grub']              = { Name='Shell Grub', Ecosystem='vermin', Family='crawlers' },
    },
};
