--Zone: Beaucedine Glacier
--Zone ID: 111
return {
    Names = {
        ['Apsaras']                 = { Name='Apsaras', Ecosystem='aquans', Family='pugils' },
        ['Bat Eye']                 = { Name='Bat Eye', Ecosystem='demons', Family='ahriman' },
        ['Calcabrina']              = { Name='Calcabrina', Ecosystem='arcana', Family='doll' },
        ['Cold Gigas']              = { Name='Cold Gigas', Ecosystem='beastmen', Family='gigas' },
        ['Dark Elemental']          = { Name='Dark Elemental', Ecosystem='elementals', Family='elementals' },
        ['Erebus']                  = { Name='Erebus', Ecosystem='undead', Family='skeletons' },
        ['Feuerunke']               = { Name='Feuerunke', Ecosystem='undead', Family='doomed' },
        ['Gargantua']               = { Name='Gargantua', Ecosystem='arcana', Family='golem' },
        ['Ghast']                   = { Name='Ghast', Ecosystem='undead', Family='skeletons' },
        ['Gigas Beastmaster']       = { Name='Gigas Beastmaster', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Clearcutter']       = { Name='Gigas Clearcutter', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Hillrazer']         = { Name='Gigas Hillrazer', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Monk']              = { Name='Gigas Monk', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Overseer']          = { Name='Gigas Overseer', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Ranger']            = { Name='Gigas Ranger', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Warrior']           = { Name='Gigas Warrior', Ecosystem='beastmen', Family='gigas' },
        ['Gigas\'s Tiger']          = { Name='Gigas\'s Tiger', Ecosystem='beast', Family='tigers' },
        ['Gjenganger']              = { Name='Gjenganger', Ecosystem='undead', Family='ghosts' },
        ['Goblin Furrier']          = { Name='Goblin Furrier', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Pathfinder']       = { Name='Goblin Pathfinder', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Poacher']          = { Name='Goblin Poacher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Reaper']           = { Name='Goblin Reaper', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Robber']           = { Name='Goblin Robber', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Shaman']           = { Name='Goblin Shaman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Smithy']           = { Name='Goblin Smithy', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Trader']           = { Name='Goblin Trader', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Tiger']         = { Name='Goblin\'s Tiger', Ecosystem='beast', Family='tigers' },
        ['Gorehound']               = { Name='Gorehound', Ecosystem='undead', Family='hounds' },
        ['Greater Pugil']           = { Name='Greater Pugil', Ecosystem='aquans', Family='pugils' },
        ['Hobgoblin Beastmaster']   = { Name='Hobgoblin Beastmaster', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Black Mage']    = { Name='Hobgoblin Black Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Dark Knight']   = { Name='Hobgoblin Dark Knight', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Ranger']        = { Name='Hobgoblin Ranger', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Red Mage']      = { Name='Hobgoblin Red Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Thief']         = { Name='Hobgoblin Thief', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Warrior']       = { Name='Hobgoblin Warrior', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin White Mage']    = { Name='Hobgoblin White Mage', Ecosystem='beastmen', Family='goblins' },
        ['Humbaba']                 = { Name='Humbaba', Ecosystem='beastmen', Family='gigas' },
        ['Ice Elemental']           = { Name='Ice Elemental', Ecosystem='elementals', Family='elementals' },
        ['Kalasutrax']              = { Name='Kalasutrax', Ecosystem='undead', Family='naraka' },
        ['Kirata']                  = { Name='Kirata', Ecosystem='beast', Family='tigers' },
        ['Kraken']                  = { Name='Kraken', Ecosystem='aquans', Family='sea monks' },
        ['Largantua']               = { Name='Largantua', Ecosystem='arcana', Family='golems' },
        ['Living Statue']           = { Name='Living Statue', Ecosystem='acana', Family='dolls' },
        ['Lord Ruthven']            = { Name='Lord Ruthven', Ecosystem='undead', Family='vampyr' },
        ['Lugat']                   = { Name='Lugat', Ecosystem='undead', Family='ghosts' },
        ['Morgawr']                 = { Name='Morgawr', Ecosystem='aquans', Family='sea monks' },
        ['Nue']                     = { Name='Nue', Ecosystem='beast', Family='tigers' },
        ['Plumbago']                = { Name='Plumbago', Ecosystem='beast', Family='tigers' },
        ['Rime Gigas']              = { Name='Rime Gigas', Ecosystem='beastmen', Family='gigas' },
        ['Sleet Gigas']             = { Name='Sleet Gigas', Ecosystem='beastmen', Family='gigas' },
        ['Snow Gigas']              = { Name='Snow Gigas', Ecosystem='beastmen', Family='gigas' },
        ['Stone Golem']             = { Name='Stone Golem', Ecosystem='arcana', Family='golems' },
        ['Tundra Tiger']            = { Name='Tundra Tiger', Ecosystem='beast', Family='tigers' },
        ['Vepar']                   = { Name='Vepar', Ecosystem='aquans', Family='pugils' },
        ['Yilbegan']                = { Name='Yilbegan', Ecosystem='dragons', Family='zilant' },
    },
};
