--Zone: Xarcabard
--Zone ID: 112
return {
    Names = {
        ['Barbaric Weapon']         = { Name='Barbaric Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Beist']                   = { Name='Beist', Ecosystem='dragons', Family='dragons' },
        ['Biast']                   = { Name='Biast', Ecosystem='dragons', Family='dragons' },
        ['Blizzard Gigas']          = { Name='Blizzard Gigas', Ecosystem='beastmen', Family='gigas' },
        ['Boreal Coeurl']           = { Name='Boreal Coeurl', Ecosystem='beasts', Family='coeurls' },
        ['Boreal Hound']            = { Name='Boreal Hound', Ecosystem='undead', Family='hounds' },
        ['Boreal Tiger']            = { Name='Boreal Tiger', Ecosystem='beasts', Family='tigers' },
        ['Chaos Elemental']         = { Name='Chaos Elemental', Ecosystem='elementals', Family='elementals' },
        ['Cursed Weapon']           = { Name='Cursed Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Dark Elemental']          = { Name='Dark Elemental', Ecosystem='elementals', Family='elementals' },
        ['Demon Aristocrat']        = { Name='Demon Aristocrat', Ecosystem='demons', Family='demons' },
        ['Demon Knight']            = { Name='Demon Knight', Ecosystem='demons', Family='demons' },
        ['Demon Pawn']              = { Name='Demon Pawn', Ecosystem='demons', Family='demons' },
        ['Demon Warlock']           = { Name='Demon Warlock', Ecosystem='demons', Family='demons' },
        ['Demon Wizard']            = { Name='Demon Wizard', Ecosystem='demons', Family='demons' },
        ['Demon\'s Elemental']      = { Name='Demon\'s Elemental', Ecosystem='elementals', Family='elementals' },
        ['Duke Focalor']            = { Name='Duke Focalor', Ecosystem='demons', Family='demons' },
        ['Erebus']                  = { Name='Erebus', Ecosystem='undead', Family='skeletons' },
        ['Ereshkigal']              = { Name='Ereshkigal', Ecosystem='undead', Family='ghosts' },
        ['Etemmu']                  = { Name='Etemmu', Ecosystem='undead', Family='ghosts' },
        ['Evil Eye']                = { Name='Evil Eye', Ecosystem='demons', Family='ahriman' },
        ['Feuerunke']               = { Name='Feuerunke', Ecosystem='undead', Family='doomed' },
        ['Frost Gigas']             = { Name='Frost Gigas', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Beastmaster']       = { Name='Gigas Beastmaster', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Monk']              = { Name='Gigas Monk', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Ranger']            = { Name='Gigas Ranger', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Warrior']           = { Name='Gigas Warrior', Ecosystem='beastmen', Family='gigas' },
        ['Gigas\'s Tiger']          = { Name='Gigas\'s Tiger', Ecosystem='beast', Family='tigers' },
        ['Gjenganger']              = { Name='Gjenganger', Ecosystem='undead', Family='ghosts' },
        ['Goblin\'s Tiger']         = { Name='Goblin\'s Tiger', Ecosystem='beasts', Family='tigers' },
        ['Gorehound']               = { Name='Gorehound', Ecosystem='undead', Family='hounds' },
        ['Graupel Gigas']           = { Name='Graupel Gigas', Ecosystem='beastmen', Family='gigas' },
        ['Hail Gigas']              = { Name='Hail Gigas', Ecosystem='beastmen', Family='gigas' },
        ['Hobgoblin Beastmaster']   = { Name='Hobgoblin Beastmaster', Ecosystem='beastmen', Family='quadav' },
        ['Hobgoblin Black Mage']    = { Name='Hobgoblin Black Mage', Ecosystem='beastmen', Family='quadav' },
        ['Hobgoblin Dark Knight']   = { Name='Hobgoblin Dark Knight', Ecosystem='beastmen', Family='quadav' },
        ['Hobgoblin Ranger']        = { Name='Hobgoblin Ranger', Ecosystem='beastmen', Family='quadav' },
        ['Hobgoblin Red Mage']      = { Name='Hobgoblin Red Mage', Ecosystem='beastmen', Family='quadav' },
        ['Hobgoblin Thief']         = { Name='Hobgoblin Thief', Ecosystem='beastmen', Family='quadav' },
        ['Hobgoblin Warrior']       = { Name='Hobgoblin Warrior', Ecosystem='beastmen', Family='quadav' },
        ['Hobgoblin White Mage']    = { Name='Hobgoblin White Mage', Ecosystem='beastmen', Family='quadav' },
        ['Ice Elemental']           = { Name='Ice Elemental', Ecosystem='elementals', Family='elementals' },
        ['Koenigstiger']            = { Name='Koenigstiger', Ecosystem='beasts', Family='tigers' },
        ['Kulili']                  = { Name='Kulili', Ecosystem='dragons', Family='dragons' },
        ['Lord Ruthven']            = { Name='Lord Ruthven', Ecosystem='undead', Family='vampyrs' },
        ['Lost Soul']               = { Name='Lost Soul', Ecosystem='undead', Family='skeletons' },
        ['Shadow Dragon']           = { Name='Shadow Dragon', Ecosystem='dragons', Family='dragons' },
        ['Shadow Eye']              = { Name='Shadow Eye', Ecosystem='demons', Family='ahriman' },
        ['Timeworn Warrior']        = { Name='Timeworn Warrior', Ecosystem='undead', Family='skeletons' },
        ['Yilbegan']                = { Name='Yilbegan', Ecosystem='dragons', Family='zilant' },
        -- Custom content for HorizonXI
        ['Ice Crab']                = { Name='Ice Crab', Ecosystem='aquans', Family='crabs' },
        ['Icefallo']                = { Name='Icefallo', Ecosystem='beasts', Family='buffaloes'}
    },
};
