--Zone: Cape Teriggan
--Zone ID: 113
return {
    Names = {
        ['Air Elemental']           = { Name='Air Elemental', Ecosystem='elementals', Family='elementals' },
        ['Axesarion the Wanderer']  = { Name='Axesarion the Wanderer', Ecosystem='undead', Family='fomors' },
        ['Beach Bunny']             = { Name='Beach Bunny', Ecosystem='beasts', Family='rabbits' },
        ['Devil Manta']             = { Name='Devil Manta', Ecosystem='aquans', Family='sea monks' },
        ['Doom Mage']               = { Name='Doom Mage', Ecosystem='undead', Family='skeletons' },
        ['Doom Soldier']            = { Name='Doom Soldier', Ecosystem='undead', Family='skeletons' },
        ['Enna-enna']               = { Name='Enna-enna', Ecosystem='arcana', Family='bombs' },
        ['Fantasma']                = { Name='Fantasma', Ecosystem='undead', Family='ghosts' },
        ['Fire Elemental']          = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals' },
        ['Frostmane']               = { Name='Frostmane', Ecosystem='beasts', Family='manticores' },
        ['Glazemane']               = { Name='Glazemane', Ecosystem='beasts', Family='manticores' },
        ['Goblin Alchemist']        = { Name='Goblin Alchemist', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Bandit']           = { Name='Goblin Bandit', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Boss']             = { Name='Goblin Boss', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Doctor']           = { Name='Goblin Doctor', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Duelist']          = { Name='Goblin Duelist', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Mercenary']        = { Name='Goblin Mercenary', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Pirate']           = { Name='Goblin Pirate', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Professor']        = { Name='Goblin Professor', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Shepherd']         = { Name='Goblin Shepherd', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Rabbit']        = { Name='Goblin\'s Rabbit', Ecosystem='beasts', Family='rabbits' },
        ['Greater Manticore']       = { Name='Greater Manticore', Ecosystem='beasts', Family='manticores' },
        ['Hobgoblin Beastmaster']   = { Name='Hobgoblin Beastmaster', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Black Mage']    = { Name='Hobgoblin Black Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Dark Knight']   = { Name='Hobgoblin Dark Knight', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Ranger']        = { Name='Hobgoblin Ranger', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Red Mage']      = { Name='Hobgoblin Red Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Thief']         = { Name='Hobgoblin Thief', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Warrior']       = { Name='Hobgoblin Warrior', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin White Mage']    = { Name='Hobgoblin White Mage', Ecosystem='beastmen', Family='goblins' },
        ['Kaneakeluh']              = { Name='Kaneakeluh', Ecosystem='birds', Family='cockatrices' },
        ['Killer Jonny']            = { Name='Killer Jonny', Ecosystem='birds', Family='cockatrices' },
        ['Kreutzet']                = { Name='Kreutzet', Ecosystem='birds', Family='rocs' },
        ['Razorjaw Pugil']          = { Name='Razorjaw Pugil', Ecosystem='aquans', Family='pugils' },
        ['Robber Crab']             = { Name='Robber Crab', Ecosystem='aquans', Family='crabs' },
        ['Rock Crab']               = { Name='Rock Crab', Ecosystem='aquans', Family='crabs' },
        ['Sand Cockatrice']         = { Name='Sand Cockatrice', Ecosystem='birds', Family='cockatrices' },
        ['Sand Lizard']             = { Name='Sand Lizard', Ecosystem='lizards', Family='lizards' },
        ['Stolas']                  = { Name='Stolas', Ecosystem='birds', Family='birds' },
        ['Stygian Pugil']           = { Name='Stygian Pugil', Ecosystem='aquans', Family='pugils' },
        ['Tegmine']                 = { Name='Tegmine', Ecosystem='aquans', Family='crabs' },
        ['Terror Pugil']            = { Name='Terror Pugil', Ecosystem='aquans', Family='pugils' },
        ['Vedrfolnir']              = { Name='Vedrfolnir', Ecosystem='birds', Family='rocs' },
        ['Velociraptor']            = { Name='Velociraptor', Ecosystem='lizards', Family='raptors' },
        ['Zmey Gorynych']           = { Name='Zmey Gorynych', Ecosystem='lizards', Family='raptors' },
        -- Custom content for HorizonXI
        ['Arid Lizard']             = { Name='Arid Lizard', Ecosystem='lizards', Family='lizards' },
        ['Dust Bat']                = { Name='Dust Bat', Ecosystem='birds', Family='bats' },
    },
};
