--Zone: Eastern Altepa Desert
--Zone ID: 114
return {
    Names = {
        ['Antican Auxiliarius']     = { Name='Antican Auxiliarius', Ecosystem='beastmen', Family='antica' },
        ['Antican Centurio']        = { Name='Antican Centurio', Ecosystem='beastmen', Family='antica' },
        ['Antican Decurio']         = { Name='Antican Decurio', Ecosystem='beastmen', Family='antica' },
        ['Antican Faber']           = { Name='Antican Faber', Ecosystem='beastmen', Family='antica' },
        ['Antican Funditor']        = { Name='Antican Funditor', Ecosystem='beastmen', Family='antica' },
        ['Antican Sagittarius']     = { Name='Antican Sagittarius', Ecosystem='beastmen', Family='antica' },
        ['Antican Speculator']      = { Name='Antican Speculator', Ecosystem='beastmen', Family='antica' },
        ['Antican Veles']           = { Name='Antican Veles', Ecosystem='beastmen', Family='antica' },
        ['Bigclaw']                 = { Name='Bigclaw', Ecosystem='aquans', Family='pugils' },
        ['Cactrot Rapido']          = { Name='Cactrot Rapido', Ecosystem='plantoids', Family='sabotenders' },
        ['Cactrot Veloz']           = { Name='Cactrot Veloz', Ecosystem='plantoids', Family='sabotenders' },
        ['Centurio XII-I']          = { Name='Centurio XII-I', Ecosystem='beastmen', Family='antica' },
        ['Centurio XIII-V']         = { Name='Centurio XIII-V', Ecosystem='beastmen', Family='antica' },
        ['Contantican Black Mage']  = { Name='Contantican Black Mage', Ecosystem='beastmen', Family='antica' },
        ['Contantican Paladin']     = { Name='Contantican Paladin', Ecosystem='beastmen', Family='antica' },
        ['Contantican Ranger']      = { Name='Contantican Ranger', Ecosystem='beastmen', Family='antica' },
        ['Contantican Warrior']     = { Name='Contantican Warrior', Ecosystem='beastmen', Family='antica' },
        ['Cutter']                  = { Name='Cutter', Ecosystem='aquans', Family='crabs' },
        ['Decurio I-III']           = { Name='Decurio I-III', Ecosystem='beastmen', Family='antica' },
        ['Decurio XIII-LV']         = { Name='Decurio XIII-LV', Ecosystem='beastmen', Family='antica' },
        ['Desert Dhalmel']          = { Name='Desert Dhalmel', Ecosystem='beasts', Family='dhalmels' },
        ['Diatryma']                = { Name='Diatryma', Ecosystem='birds', Family='greater birds' },
        ['Donnergugi']              = { Name='Donnergugi', Ecosystem='vermin', Family='beetles' },
        ['Doom Scorpion']           = { Name='Doom Scorpion', Ecosystem='vermin', Family='scorpions' },
        ['Dune Widow']              = { Name='Dune Widow', Ecosystem='vermin', Family='spiders' },
        ['Earth Elemental']         = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Fire Elemental']          = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals' },
        ['Flesh Eater']             = { Name='Flesh Eater', Ecosystem='amorphs', Family='worms' },
        ['Giant Spider']            = { Name='Giant Spider', Ecosystem='vermin', Family='spiders' },
        ['Goblin Digger']           = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Poacher']          = { Name='Goblin Poacher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Reaper']           = { Name='Goblin Reaper', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Robber']           = { Name='Goblin Robber', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Trader']           = { Name='Goblin Trader', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Spider']        = { Name='Goblin\'s Spider', Ecosystem='vermin', Family='spiders' },
        ['Greater Pugil']           = { Name='Greater Pugil', Ecosystem='aquans', Family='pugils' },
        ['Hastatus XIII-CXXVIII']   = { Name='Hastatus XIII-CXXVIII', Ecosystem='beastmen', Family='antica' },
        ['Hastatus XIII-LXXV']      = { Name='Hastatus XIII-LXXV', Ecosystem='beastmen', Family='antica' },
        ['Hastatus XIII-XCVI']      = { Name='Hastatus XIII-XCVI', Ecosystem='beastmen', Family='antica' },
        ['Hastatus XIII-XXV']       = { Name='Hastatus XIII-XXV', Ecosystem='beastmen', Family='antica' },
        ['Hobgoblin Beastmaster']   = { Name='Hobgoblin Beastmaster', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Black Mage']    = { Name='Hobgoblin Black Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Dark Knight']   = { Name='Hobgoblin Dark Knight', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Ranger']        = { Name='Hobgoblin Ranger', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Red Mage']      = { Name='Hobgoblin Red Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Thief']         = { Name='Hobgoblin Thief', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Warrior']       = { Name='Hobgoblin Warrior', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin White Mage']    = { Name='Hobgoblin White Mage', Ecosystem='beastmen', Family='goblins' },
        ['Ironshell']               = { Name='Ironshell', Ecosystem='aquans', Family='crabs' },
        ['Lesser Manticore']        = { Name='Lesser Manticore', Ecosystem='beasts', Family='manticores' },
        ['Lost Soul']               = { Name='Lost Soul', Ecosystem='undead', Family='skeletons' },
        ['Makara']                  = { Name='Makara', Ecosystem='aquans', Family='pugils' },
        ['Nandi']                   = { Name='Nandi', Ecosystem='beasts', Family='dhalmels' },
        ['Princeps XIII-LXXXIX']    = { Name='Princeps XIII-LXXXIX', Ecosystem='beastmen', Family='antica' },
        ['Sabotender']              = { Name='Sabotender', Ecosystem='plantoids', Family='sabotenders' },
        ['Sabotender Corrido']      = { Name='Sabotender Corrido', Ecosystem='plantoids', Family='sabotenders' },
        ['Sagittarius XIII-XXVI']   = { Name='Sagittarius XIII-XXVI', Ecosystem='beastmen', Family='antica' },
        ['Sand Beetle']             = { Name='Sand Beetle', Ecosystem='vermin', Family='beetles' },
        ['Satyral']                 = { Name='Satyral', Ecosystem='beasts', Family='manticores' },
        ['Triarius XIII-LIX']       = { Name='Triarius XIII-LIX', Ecosystem='beastmen', Family='antica' },
        ['Tsuchigumo']              = { Name='Tsuchigumo', Ecosystem='vermin', Family='spiders' },
        -- Custom content for HorizonXI
        ['Scorch Dhalmel']          = { Name='Scorch Dhalmel', Ecosystem='beasts', Family='dhalmels' },
        ['Muddy Slime']             = { Name='Muddy Slime', Ecosystem='amorphs', Family='slimes'},
        ['Sand Worm']               = { Name='Sand Worm', Ecosystem='amorphs', Family='worms' },
        ['Mud Crab']                = { Name='Mud Crab', Ecosystem='aquans', Family='crabs' },
        ['Muddyeyes']               = { Name='Muddyeyes', Ecosystem='amorphs', Family='hecteyes' },
    },
};
