--Zone: West Sarutabaruta
--Zone ID: 115
return {
    Names = {
        ['Bakru']               = { Name='Bakru', Ecosystem='plantoids', Family='mandragoras' },
        ['Balloon']             = { Name='Balloon', Ecosystem='arcana', Family='bombs' },
        ['Bumblebee']           = { Name='Bumblebee', Ecosystem='vermin', Family='bees' },
        ['Carrion Crow']        = { Name='Carrion Crow', Ecosystem='birds', Family='birds' },
        ['Crawler']             = { Name='Crawler', Ecosystem='vermin', Family='crawlers' },
        ['Farruca Fly']         = { Name='Farruca Fly', Ecosystem='vermin', Family='flies' },
        ['Giant Bee']           = { Name='Giant Bee', Ecosystem='vermin', Family='bees' },
        ['Goblin Digger']       = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Fisher']       = { Name='Goblin Fisher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Thug']         = { Name='Goblin Thug', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Weaver']       = { Name='Goblin Weaver', Ecosystem='beastmen', Family='goblins' },
        ['Jyeshtha']            = { Name='Jyeshtha', Ecosystem='vermin', Family='scorpions' },
        ['Land Crab']           = { Name='Land Crab', Ecosystem='aquans', Family='crabs' },
        ['Mad Fox']             = { Name='Mad Fox', Ecosystem='undead', Family='hounds' },
        ['Magicked Bones']      = { Name='Magicked Bones', Ecosystem='undead', Family='skeletons' },
        ['Mandragora']          = { Name='Mandragora', Ecosystem='plantoids', Family='mandragoras' },
        ['Mugger Crab']         = { Name='Mugger Crab', Ecosystem='aquans', Family='crabs' },
        ['Numbing Norman']      = { Name='Numbing Norman', Ecosystem='vermin', Family='bees' },
        ['Nunyenunc']           = { Name='Nunyenunc', Ecosystem='birds', Family='birds' },
        ['Orcus']               = { Name='Orcus', Ecosystem='vermin', Family='antlions' },
        ['Palm Crab']           = { Name='Palm Crab', Ecosystem='aquans', Family='crabs' },
        ['Passage Crab']        = { Name='Passage Crab', Ecosystem='aquans', Family='crabs' },
        ['Pixie']               = { Name='Pixie', Ecosystem='elementals', Family='pixies' },
        ['Pyracmon']            = { Name='Pyracmon', Ecosystem='demons', Family='ahriman' },
        ['Raker Bee']           = { Name='Raker Bee', Ecosystem='vermin', Family='bees' },
        ['River Crab']          = { Name='River Crab', Ecosystem='aquans', Family='crabs' },
        ['Rummager Beetle']     = { Name='Rummager Beetle', Ecosystem='vermin', Family='beetles' },
        ['Savanna Crab']        = { Name='Savanna Crab', Ecosystem='aquans', Family='crabs' },
        ['Savanna Rarab']       = { Name='Savanna Rarab', Ecosystem='beasts', Family='rabbits' },
        ['Tiny Mandragora']     = { Name='Tiny Mandragora', Ecosystem='plantoids', Family='mandragoras' },
        ['Tom Tit Tat']         = { Name='Tom Tit Tat', Ecosystem='plantoids', Family='mandragoras' },
        ['Virvatuli']           = { Name='Virvatuli', Ecosystem='undead', Family='corpselights' },
        ['Wraith Bat']          = { Name='Wraith Bat', Ecosystem='birds', Family='bats' },
        ['Yagudo Acolyte']      = { Name='Yagudo Acolyte', Ecosystem='beastmen', Family='yagudos' },
        ['Yagudo Condottiere']  = { Name='Yagudo Condottiere', Ecosystem='beastmen', Family='yagudos' },
        ['Yagudo Follower']     = { Name='Yagudo Follower', Ecosystem='beastmen', Family='yagudos' },
        ['Yagudo Initiate']     = { Name='Yagudo Initiate', Ecosystem='beastmen', Family='yagudos' },
        ['Yagudo Priest']       = { Name='Yagudo Priest', Ecosystem='beastmen', Family='yagudos' },
        ['Yagudo Scribe']       = { Name='Yagudo Scribe', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Theologist']   = { Name='Yagudo Theologist', Ecosystem='beastmen', Family='yagudos' },
        ['Yagudo Votary']       = { Name='Yagudo Votary', Ecosystem='beastmen', Family='yagudos' },
        ['Yilbegan']            = { Name='Yilbegan', Ecosystem='dragons', Family='zilant' },
    },
};
