--Zone: East Sarutabaruta
--Zone ID: 116
return {
    Names = {
        ['Balloon']             = { Name='Balloon', Ecosystem='arcana', Family='bombs' },
        ['Bolster']             = { Name='Bolster', Ecosystem='vermin', Family='crawlers' },
        ['Bumblebee']           = { Name='Bumblebee', Ecosystem='vermin', Family='bees' },
        ['Carrion Crow']        = { Name='Carrion Crow', Ecosystem='birds', Family='birds' },
        ['Crawler']             = { Name='Crawler', Ecosystem='vermin', Family='crawlers' },
        ['Duke Decapod']        = { Name='Duke Decapod', Ecosystem='aquans', Family='crabs' },
        ['Fighting Pugil']      = { Name='Fighting Pugil', Ecosystem='aquans', Family='pugils' },
        ['Giant Bee']           = { Name='Giant Bee', Ecosystem='vermin', Family='bees' },
        ['Goblin Digger']       = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Fisher']       = { Name='Goblin Fisher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Thug']         = { Name='Goblin Thug', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Weaver']       = { Name='Goblin Weaver', Ecosystem='beastmen', Family='goblins' },
        ['Mad Fox']             = { Name='Mad Fox', Ecosystem='undead', Family='hounds' },
        ['Magicked Bones']      = { Name='Magicked Bones', Ecosystem='undead', Family='skeletons' },
        ['Mandragora']          = { Name='Mandragora', Ecosystem='plantoids', Family='mandragoras' },
        ['Mud Pugil']           = { Name='Mud Pugil', Ecosystem='aquans', Family='pugils' },
        ['Palm Crab']           = { Name='Palm Crab', Ecosystem='aquans', Family='crabs' },
        ['Pixie']               = { Name='Pixie', Ecosystem='elementals', Family='pixies' },
        ['Prickly Pitriv']      = { Name='Prickly Pitriv', Ecosystem='vermin', Family='crawlers' },
        ['Pug Pugil']           = { Name='Pug Pugil', Ecosystem='aquans', Family='pugils' },
        ['Pyracmon']            = { Name='Pyracmon', Ecosystem='demons', Family='ahriman' },
        ['River Crab']          = { Name='River Crab', Ecosystem='aquans', Family='crabs' },
        ['Rw Nw Prt M Hrw']     = { Name='Rw Nw Prt M Hrw', Ecosystem='arcana', Family='grimoires' },
        ['Savanna Crab']        = { Name='Savanna Crab', Ecosystem='aquans', Family='crabs' },
        ['Savanna Rarab']       = { Name='Savanna Rarab', Ecosystem='beasts', Family='rabbits' },
        ['Sharp-Eared Ropipi']  = { Name='Sharp-Eared Ropipi', Ecosystem='beasts', Family='rabbits' },
        ['Spiny Spipi']         = { Name='Spiny Spipi', Ecosystem='vermin', Family='crawlers' },
        ['Tiny Mandragora']     = { Name='Tiny Mandragora', Ecosystem='plantoids', Family='mandragoras' },
        ['Wraith Bat']          = { Name='Wraith Bat', Ecosystem='birds', Family='bats' },
        ['Yagudo Acolyte']      = { Name='Yagudo Acolyte', Ecosystem='beastmen', Family='yagudos' },
        ['Yagudo Initiate']     = { Name='Yagudo Initiate', Ecosystem='beastmen', Family='yagudos' },
        ['Yagudo Scribe']       = { Name='Yagudo Scribe', Ecosystem='beastmen', Family='yagudos' },
    },
};
