--Zone: Tahrongi Canyon
--Zone ID: 117
return {
    Names = {
        ['Air Elemental']           = { Name='Air Elemental', Ecosystem='elementals', Family='elementals' },
        ['Akbaba']                  = { Name='Akbaba', Ecosystem='birds', Family='birds' },
        ['Allocamelus']             = { Name='Allocamelus', Ecosystem='beast', Family='dhalmels' },
        ['Barghest']                = { Name='Barghest', Ecosystem='undead', Family='hounds' },
        ['Canyon Crawler']          = { Name='Canyon Crawler', Ecosystem='vermin', Family='crawlers' },
        ['Canyon Rarab']            = { Name='Canyon Rarab', Ecosystem='vermin', Family='rabbits' },
        ['Chesma']                  = { Name='Chesma', Ecosystem='beast', Family='coeurls' },
        ['Dawon']                   = { Name='Dawon', Ecosystem='beast', Family='tigers' },
        ['Earth Elemental']         = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Ghost']                   = { Name='Ghost', Ecosystem='undead', Family='ghosts' },
        ['Goblin Ambusher']         = { Name='Goblin Ambusher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Archaeologist']    = { Name='Goblin Archaeologist', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Butcher']          = { Name='Goblin Butcher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Digger']           = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Thug']             = { Name='Goblin Thug', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Tinkerer']         = { Name='Goblin Tinkerer', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Weaver']           = { Name='Goblin Weaver', Ecosystem='beastmen', Family='goblins' },
        ['Grenade']                 = { Name='Grenade', Ecosystem='arcana', Family='bombs' },
        ['Habrok']                  = { Name='Habrok', Ecosystem='birds', Family='birds' },
        ['Herbage Hunter']          = { Name='Herbage Hunter', Ecosystem='vermin', Family='crawlers' },
        ['Killer Bee']              = { Name='Killer Bee', Ecosystem='vermin', Family='bees' },
        ['Otherworldly Rimester']   = { Name='Otherworldly Rimester', Ecosystem='undead', Family='ghosts' },
        ['Pixie']                   = { Name='Pixie', Ecosystem='elementals', Family='pixies' },
        ['Poltergeist']             = { Name='Poltergeist', Ecosystem='undead', Family='ghosts' },
        ['Prickly Sheep']           = { Name='Prickly Sheep', Ecosystem='beast', Family='sheep' },
        ['Pygmaioi']                = { Name='Pygmaioi', Ecosystem='plantoids', Family='mandragora' },
        ['Serpopard Ishtar']        = { Name='Serpopard Ishtar', Ecosystem='beast', Family='dhalmels' },
        ['Serpopard Ninlil']        = { Name='Serpopard Ninlil', Ecosystem='beast', Family='dhalmels' },
        ['Skeleton Sorcerer']       = { Name='Skeleton Sorcerer', Ecosystem='undead', Family='skeletons' },
        ['Skeleton Warrior']        = { Name='Skeleton Warrior', Ecosystem='undead', Family='skeletons' },
        ['Smierc']                  = { Name='Smierc', Ecosystem='undead', Family='skeletons' },
        ['Strolling Sapling']       = { Name='Strolling Sapling', Ecosystem='plantoids', Family='saplings' },
        ['Tammuz']                  = { Name='Tammuz', Ecosystem='beast', Family='rams' },
        ['Void Hare']               = { Name='Void Hare', Ecosystem='vermin', Family='rabbits' },
        ['Wild Dhalmel']            = { Name='Wild Dhalmel', Ecosystem='beast', Family='dhalmels' },
        ['Yagudo Acolyte']          = { Name='Yagudo Acolyte', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Initiate']         = { Name='Yagudo Initiate', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Mendicant']        = { Name='Yagudo Mendicant', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Persecutor']       = { Name='Yagudo Persecutor', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Piper']            = { Name='Yagudo Piper', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Scribe']           = { Name='Yagudo Scribe', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo\'s Elemental']     = { Name='Yagudo\'s Elemental', Ecosystem='elementals', Family='elementals' },
        ['Yara Ma Yha Who']         = { Name='Yara Ma Yha Who', Ecosystem='plantoids', Family='saplings' },
        ['Yilbegan']                = { Name='Yilbegan', Ecosystem='dragons', Family='zilant' },
    },
};
