--Zone: Buburimu Peninsula
--Zone ID: 118
return {
    Names = {
        ['Abyssdiver']              = { Name='Abyssdiver', Ecosystem='birds', Family='birds' },
        ['Air Elemental']           = { Name='Air Elemental', Ecosystem='elementals', Family='elementals' },
        ['Backoo']                  = { Name='Backoo', Ecosystem='plantoids', Family='mandragoras' },
        ['Bogy']                    = { Name='Bogy', Ecosystem='undead', Family='ghosts' },
        ['Botulus Rex']             = { Name='Botulus Rex', Ecosystem='amorphs', Family='botuli' },
        ['Buburimboo']              = { Name='Buburimboo', Ecosystem='aquans', Family='pugils' },
        ['Bull Dhalmel']            = { Name='Bull Dhalmel', Ecosystem='beasts', Family='dhalmels' },
        ['Carnivorous Crawler']     = { Name='Carnivorous Crawler', Ecosystem='vermin', Family='crawlers' },
        ['Clipper']                 = { Name='Clipper', Ecosystem='aquans', Family='crabs' },
        ['Ghoul']                   = { Name='Ghoul', Ecosystem='undead', Family='ghosts' },
        ['Goblin Ambusher']         = { Name='Goblin Ambusher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Bounty Hunter']    = { Name='Goblin Bounty Hunter', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Butcher']          = { Name='Goblin Butcher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Digger']           = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Furrier']          = { Name='Goblin Furrier', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Gambler']          = { Name='Goblin Gambler', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Guide']            = { Name='Goblin Guide', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Leecher']          = { Name='Goblin Leecher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Mugger']           = { Name='Goblin Mugger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Shaman']           = { Name='Goblin Shaman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Swordmaker']       = { Name='Goblin Swordmaker', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Thespian']         = { Name='Goblin Thespian', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Tinkerer']         = { Name='Goblin Tinkerer', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Rabbit']        = { Name='Goblin\'s Rabbit', Ecosystem='beasts', Family='rabbits' },
        ['Helldiver']               = { Name='Helldiver', Ecosystem='birds', Family='birds' },
        ['Hobgoblin Beastmaster']   = { Name='Hobgoblin Beastmaster', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Black Mage']    = { Name='Hobgoblin Black Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Dark Knight']   = { Name='Hobgoblin Dark Knight', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Ranger']        = { Name='Hobgoblin Ranger', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Red Mage']      = { Name='Hobgoblin Red Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Thief']         = { Name='Hobgoblin Thief', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Warrior']       = { Name='Hobgoblin Warrior', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin White Mage']    = { Name='Hobgoblin White Mage', Ecosystem='beastmen', Family='goblins' },
        ['Ketos']                   = { Name='Ketos', Ecosystem='aquans', Family='pugis' },
        ['Mighty Rarab']            = { Name='Mighty Rarab', Ecosystem='beasts', Family='rabbits' },
        ['Pixie']                   = { Name='Pixie', Ecosystem='elementals', Family='pixies' },
        ['Poison Leech']            = { Name='Poison Leech', Ecosystem='amorphs', Family='leeches' },
        ['Puffer Pugil']            = { Name='Puffer Pugil', Ecosystem='aquans', Family='pugils' },
        ['Shoal Pugil']             = { Name='Shoal Pugil', Ecosystem='aquans', Family='pugils' },
        ['Snipper']                 = { Name='Snipper', Ecosystem='aquans', Family='crabs' },
        ['Stag Crab']               = { Name='Stag Crab', Ecosystem='aquans', Family='crabs' },
        ['Sylvestre']               = { Name='Sylvestre', Ecosystem='plantoids', Family='mandragoras' },
        ['Theoyagudo Bard']         = { Name='Theoyagudo Bard', Ecosystem='beastmen', Family='yagados' },
        ['Theoyagudo Black Mage']   = { Name='Theoyagudo Black Mage', Ecosystem='beastmen', Family='yagados' },
        ['Theoyagudo Monk']         = { Name='Theoyagudo Monk', Ecosystem='beastmen', Family='yagados' },
        ['Theoyagudo Ninja']        = { Name='Theoyagudo Ninja', Ecosystem='beastmen', Family='yagados' },
        ['Theoyagudo Samurai']      = { Name='Theoyagudo Samurai', Ecosystem='beastmen', Family='yagados' },
        ['Theoyagudo Summoner']     = { Name='Theoyagudo Summoner', Ecosystem='beastmen', Family='yagados' },
        ['Theoyagudo White Mage']   = { Name='Theoyagudo White Mage', Ecosystem='beastmen', Family='yagados' },
        ['Wake Warder Wanda']       = { Name='Wake Warder Wanda', Ecosystem='aquans', Family='crabs' },
        ['Water Elemental']         = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
        ['Will-o\'-the-Wisp']       = { Name='Will-o\'-the-Wisp', Ecosystem='arcana', Family='bombs' },
        ['Yagudo\'s Avatar']        = { Name='Yagudo\'s Avatar', Ecosystem='unclassified', Family='monsters' },
        ['Yagudo\'s Elemental']     = { Name='Yagudo\'s Elemental', Ecosystem='elementals', Family='elementals' },
        ['Zombie']                  = { Name='Zombie', Ecosystem='undead', Family='skeletons' },
        ['Zu']                      = { Name='Zu', Ecosystem='birds', Family='birds' },
        -- Custom content for HorizonXI
        ['Cape Coney']              = { Name='Cape Coney', Ecosystem='beasts', Family='rabbits' },
        ['Cape Dhalmels']           = { Name='Cape Dhalmels', Ecosystem='beasts', Family='dhalmels' },
    },
};
