--Zone: Meriphataud Mountains
--Zone ID: 119
return {
    Names = {
        ['Axe Beak']                = { Name='Axe Beak', Ecosystem='birds', Family='cockatrices' },
        ['Black Bat']               = { Name='Black Bat', Ecosystem='birds', Family='bats' },
        ['Boggart']                 = { Name='Boggart', Ecosystem='arcana', Family='evil weapons' },
        ['Bogy']                    = { Name='Bogy', Ecosystem='undead', Family='ghosts' },
        ['Chonchon']                = { Name='Chonchon', Ecosystem='birds', Family='cockatrices' },
        ['Coeurl']                  = { Name='Coeurl', Ecosystem='beasts', Family='coeurls' },
        ['Coo Keja the Unseen']     = { Name='Coo Keja the Unseen', Ecosystem='beastmen', Family='yugado' },
        ['Crane Fly']               = { Name='Crane Fly', Ecosystem='vermin', Family='flies' },
        ['Daggerclaw Dracos']       = { Name='Daggerclaw Dracos', Ecosystem='lizards', Family='raptors' },
        ['Earth Elemental']         = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Farruca Fly']             = { Name='Farruca Fly', Ecosystem='vermin', Family='flies' },
        ['Fire Elemental']          = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals' },
        ['Goblin Ambusher']         = { Name='Goblin Ambusher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Butcher']          = { Name='Goblin Butcher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Digger']           = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Gambler']          = { Name='Goblin Gambler', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Leecher']          = { Name='Goblin Leecher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Mugger']           = { Name='Goblin Mugger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Tinkerer']         = { Name='Goblin Tinkerer', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Dragonfly']     = { Name='Goblin\'s Dragonfly', Ecosystem='vermin', Family='flies' },
        ['Hill Lizard']             = { Name='Hill Lizard', Ecosystem='lizards', Family='lizards' },
        ['Hobgoblin Beastmaster']   = { Name='Hobgoblin Beastmaster', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Black Mage']    = { Name='Hobgoblin Black Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Dark Knight']   = { Name='Hobgoblin Dark Knight', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Ranger']        = { Name='Hobgoblin Ranger', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Red Mage']      = { Name='Hobgoblin Red Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Thief']         = { Name='Hobgoblin Thief', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Warrior']       = { Name='Hobgoblin Warrior', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin White Mage']    = { Name='Hobgoblin White Mage', Ecosystem='beastmen', Family='goblins' },
        ['Jubjub']                  = { Name='Jubjub', Ecosystem='birds', Family='birds' },
        ['Jyeshtha']                = { Name='Jyeshtha', Ecosystem='vermin', Family='scorpions' },
        ['Lord Asag']               = { Name='Lord Asag', Ecosystem='undead', Family='vampyrs' },
        ['Naa Zeku the Unwaiting']  = { Name='Naa Zeku the Unwaiting', Ecosystem='beastmen', Family='yugado' },
        ['Night Bats']              = { Name='Night Bats', Ecosystem='birds', Family='bat trios' },
        ['Orcus']                   = { Name='Orcus', Ecosystem='beasts', Family='coeurls' },
        ['Patripatan']              = { Name='Patripatan', Ecosystem='beastmen', Family='yugado' },
        ['Raker Bee']               = { Name='Raker Bee', Ecosystem='vermin', Family='bees' },
        ['Raptor']                  = { Name='Raptor', Ecosystem='lizards', Family='raptors' },
        ['Rummager Beetle']         = { Name='Rummager Beetle', Ecosystem='vermin', Family='beetles' },
        ['Scavenging Hound']        = { Name='Scavenging Hound', Ecosystem='undead', Family='hounds' },
        ['Sprite']                  = { Name='Sprite', Ecosystem='elementals', Family='pixies' },
        ['Stag Beetle']             = { Name='Stag Beetle', Ecosystem='vermin', Family='beetles' },
        ['Theoyagudo Bard']         = { Name='Theoyagudo Bard', Ecosystem='beastmen', Family='yugado' },
        ['Theoyagudo Black Mage']   = { Name='Theoyagudo Black Mage', Ecosystem='beastmen', Family='yugado' },
        ['Theoyagudo Monk']         = { Name='Theoyagudo Monk', Ecosystem='beastmen', Family='yugado' },
        ['Theoyagudo Ninja']        = { Name='Theoyagudo Ninja', Ecosystem='beastmen', Family='yugado' },
        ['Theoyagudo Samurai']      = { Name='Theoyagudo Samurai', Ecosystem='beastmen', Family='yugado' },
        ['Theoyagudo Summoner']     = { Name='Theoyagudo Summoner', Ecosystem='beastmen', Family='yugado' },
        ['Theoyagudo White Mage']   = { Name='Theoyagudo White Mage', Ecosystem='beastmen', Family='yugado' },
        ['Tsaagan']                 = { Name='Tsaagan', Ecosystem='lizards', Family='raptors' },
        ['Wandering Sapling']       = { Name='Wandering Sapling', Ecosystem='plantoids', Family='saplings' },
        ['Waraxe Beak']             = { Name='Waraxe Beak', Ecosystem='birds', Family='cockatrices' },
        ['Warblade Beak']           = { Name='Warblade Beak', Ecosystem='birds', Family='cockatrices' },
        ['Will-o\'-the-Wisp']       = { Name='Will-o\'-the-Wisp', Ecosystem='arcana', Family='bombs' },
        ['Yagudo Follower']         = { Name='Yagudo Follower', Ecosystem='beastmen', Family='yugado' },
        ['Yagudo Mendicant']        = { Name='Yagudo Mendicant', Ecosystem='beastmen', Family='yugado' },
        ['Yagudo Missionary']       = { Name='Yagudo Missionary', Ecosystem='beastmen', Family='yugado' },
        ['Yagudo Persecutor']       = { Name='Yagudo Persecutor', Ecosystem='beastmen', Family='yugado' },
        ['Yagudo Piper']            = { Name='Yagudo Piper', Ecosystem='beastmen', Family='yugado' },
        ['Yagudo Priest']           = { Name='Yagudo Priest', Ecosystem='beastmen', Family='yugado' },
        ['Yagudo Theologist']       = { Name='Yagudo Theologist', Ecosystem='beastmen', Family='yugado' },
        ['Yagudo Votary']           = { Name='Yagudo Votary', Ecosystem='beastmen', Family='yugado' },
        ['Yagudo\'s Avatar']        = { Name='Yagudo\'s Avatar', Ecosystem='unclassified', Family='monsters' },
        ['Yagudo\'s Elemental']     = { Name='Yagudo\'s Elemental', Ecosystem='elementals', Family='elementals' },
        ['Yilbegan']                = { Name='Yilbegan', Ecosystem='dragons', Family='zilant' },
        ['Zombie']                  = { Name='Zombie', Ecosystem='undead', Family='skeletons' },
        -- Custom content for HorizonXI
        ['Migrant Hawker']          = { Name='Migrant Hawker', Ecosystem='vermin', Family='flies' },
        ['Dust Lizard']             = { Name='Dust Lizard', Ecosystem='lizards', Family='lizards' },
        ['Ridge Lizard']            = { Name='Ridge Lizard', Ecosystem='lizards', Family='lizards' },
        ['Puma']                    = { Name='Puma', Ecosystem='beasts', Family='coeurls' },
        ['Drooling Hound']          = { Name='Drooling Hound', Ecosystem='undead', Family='hounds' },
        ['Dromaeosaurus']           = { Name='Dromaeosaurus', Ecosystem='lizards', Family='raptors'},
        ['Cliff Glider']            = { Name='Cliff Glider', Ecosystem='vermin', Family='flies'},
    },
};
