--Zone: Oldton Movalpolos
--Zone ID: 11
return {
    Names = {
        ['Amoebic Nodule']          = { Name='Amoebic Nodule', Ecosystem='amorphs', Family='slimes' },
        ['Ancient Bomb']            = { Name='Ancient Bomb', Ecosystem='arcana', Family='bombs' },
        ['Blind Crab']              = { Name='Blind Crab', Ecosystem='aquans', Family='crabs' },
        ['Bugallug']                = { Name='Bugallug', Ecosystem='beastmen', Family='bugbears' },
        ['Bugbear Bondman']         = { Name='Bugbear Bondman', Ecosystem='beastmen', Family='bugbears' },
        ['Bugbear Muscleman']       = { Name='Bugbear Muscleman', Ecosystem='beastmen', Family='bugbears' },
        ['Bugbear Porterman']       = { Name='Bugbear Porterman', Ecosystem='beastmen', Family='bugbears' },
        ['Bugbear Servingman']      = { Name='Bugbear Servingman', Ecosystem='beastmen', Family='bugbears' },
        ['Bugbear Strongman']       = { Name='Bugbear Strongman', Ecosystem='beastmen', Family='bugbears' },
        ['Cutter']                  = { Name='Cutter', Ecosystem='aquans', Family='crabs' },
        ['Dark Bats']               = { Name='Dark Bats', Ecosystem='birds', Family='bat trios' },
        ['Dread Dealing Dredodak']  = { Name='Dread Dealing Dredodak', Ecosystem='beastmen', Family='goblins' },
        ['Earth Elemental']         = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Ghost Crab']              = { Name='Ghost Crab', Ecosystem='aquans', Family='crabs' },
        ['Goblin Craftsman']        = { Name='Goblin Craftsman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Doorman']          = { Name='Goblin Doorman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Freelance']        = { Name='Goblin Freelance', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Gutterman']        = { Name='Goblin Gutterman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Hammerman']        = { Name='Goblin Hammerman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Leadman']          = { Name='Goblin Leadman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Oilman']           = { Name='Goblin Oilman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Preceptor']        = { Name='Goblin Preceptor', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Shovelman']        = { Name='Goblin Shovelman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Tollman']          = { Name='Goblin Tollman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Wolfman']          = { Name='Goblin Wolfman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Bat']           = { Name='Goblin\'s Bat', Ecosystem='birds', Family='bats' },
        ['Grimoire Guru Grimogek']  = { Name='Grimoire Guru Grimogek', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Ashman']           = { Name='Moblin Ashman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Chapman']          = { Name='Moblin Chapman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Coalman']          = { Name='Moblin Coalman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Gasman']           = { Name='Moblin Gasman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Gurneyman']        = {Name='Moblin Gurneyman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Pickman']          = { Name='Moblin Pickman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Pikeman']          = { Name='Moblin Pikeman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Ragman']           = { Name='Moblin Ragman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Repairman']        = { Name='Moblin Repairman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Rodman']           = { Name='Moblin Rodman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Witchman']         = { Name='Moblin Witchman', Ecosystem='beastmen', Family='moblins' },
        ['Snipper']                 = { Name='Snipper', Ecosystem='aquans', Family='crabs' },
        ['Stirge']                  = { Name='Stirge', Ecosystem='birds', Family='bats' },
        ['Thunder Elemental']       = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
    },
};
