--Zone: Sauromugue Champaign
--Zone ID: 120
return {
    Names = {
        ['Aither']                  = { Name='Aither', Ecosystem='elementals', Family='elementals' },
        ['Arke']                    = { Name='Arke', Ecosystem='birds', Family='rocs' },
        ['Balam-Agab']              = { Name='Balam-Agab', Ecosystem='beasts', Family='coeurls' },
        ['Bashe']                   = { Name='Bashe', Ecosystem='lizards', Family='lizards' },
        ['Beorht']                  = { Name='Beorht', Ecosystem='elementals', Family='elementals' },
        ['Big Jaw']                 = { Name='Big Jaw', Ecosystem='aquans', Family='pugils' },
        ['Blighting Brand']         = { Name='Blighting Brand', Ecosystem='beasts', Family='coeurls' },
        ['Champaign Coeurl']        = { Name='Champaign Coeurl', Ecosystem='arcana', Family='evil weapons' },
        ['Climbpix Highrise']       = { Name='Climbpix Highrise', Ecosystem='beastmen', Family='goblins' },
        ['Cutter']                  = { Name='Cutter', Ecosystem='aquans', Family='crabs' },
        ['Deadly Dodo']             = { Name='Deadly Dodo', Ecosystem='beasts', Family='cockatrices' },
        ['Deorc']                   = { Name='Deorc', Ecosystem='elementals', Family='elementals' },
        ['Diving Beetle']           = { Name='Diving Beetle', Ecosystem='vermin', Family='beetles' },
        ['Dribblix Greasemaw']      = { Name='Dribblix Greasemaw', Ecosystem='beastmen', Family='goblins' },
        ['Earth Elemental']         = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Eorthe']                  = { Name='Eorthe', Ecosystem='elementals', Family='elementals' },
        ['Evil Spirit']             = { Name='Evil Spirit', Ecosystem='undead', Family='ghosts' },
        ['Evil Weapon']             = { Name='Evil Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Goblin Bounty Hunter']    = { Name='Goblin Bounty Hunter',Ecosystem='beastmen', Family='goblins' },
        ['Goblin Digger']           = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Furrier']          = { Name='Goblin Furrier', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Gambler']          = { Name='Goblin Gambler', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Leecher']          = { Name='Goblin Leecher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Mugger']           = { Name='Goblin Mugger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Pathfinder']       = { Name='Goblin Pathfinder', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Shaman']           = { Name='Goblin Shaman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Smithy']           = { Name='Goblin Smithy', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Beetle']        = { Name='Goblin\'s Beetle', Ecosystem='vermin', Family='beetles' },
        ['Goji']                    = { Name='Goji', Ecosystem='demons', Family='gargouille' },
        ['Greater Pugil']           = { Name='Greater Pugil', Ecosystem='aquans', Family='pugils' },
        ['Hill Lizard']             = { Name='Hill Lizard', Ecosystem='lizards', Family='lizards' },
        ['Ignis Fatuus']            = { Name='Ignis Fatuus', Ecosystem='arcana', Family='bombs' },
        ['Kraken']                  = { Name='Kraken', Ecosystem='aquans', Family='sea monks' },
        ['Lacus']                   = { Name='Lacus', Ecosystem='elementals', Family='elementals' },
        ['Midnight Wings']          = { Name='Midnight Wings', Ecosystem='birds', Family='bat trios' },
        ['Moon Bat']                = { Name='Moon Bat', Ecosystem='birds', Family='bats' },
        ['Old Sabertooth']          = { Name='Old Sabertooth', Ecosystem='beasts', Family='tigers' },
        ['Pruina']                  = { Name='Pruina', Ecosystem='elementals', Family='elementals' },
        ['Puretos']                 = { Name='Puretos', Ecosystem='elementals', Family='elementals' },
        ['Roc']                     = { Name='Roc', Ecosystem='birds', Family='rocs' },
        ['Sabertooth Tiger']        = { Name='Sabertooth Tiger', Ecosystem='beasts', Family='tigers' },
        ['Sauromugue Skink']        = { Name='Sauromugue Skink', Ecosystem='lizards', Family='raptors' },
        ['Skuld']                   = { Name='Skuld', Ecosystem='arcana', Family='pixies' },
        ['Snipper']                 = { Name='Snipper', Ecosystem='aquans', Family='crabs' },
        ['Sprite']                  = { Name='Sprite', Ecosystem='arcana', Family='pixies' },
        ['Tabar Beak']              = { Name='Tabar Beak', Ecosystem='birds', Family='cockatrices' },
        ['Thunder Elemental']       = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
        ['Thunderclaw Thuban']      = { Name='Thunderclaw Thuban', Ecosystem='lizards', Family='raptors' },
        ['Thunor']                  = { Name='Thunor', Ecosystem='elementals', Family='elementals' },
        ['Urd']                     = { Name='Urd', Ecosystem='arcana', Family='pixies' },
        ['Verthandi']               = { Name='Verthandi', Ecosystem='arcana', Family='pixies' },
        ['Wight']                   = { Name='Wight', Ecosystem='undead', Family='skeletons' },
        ['Yagudo Drummer']          = { Name='Yagudo Drummer', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Herald']           = { Name='Yagudo Herald', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Interrogator']     = { Name='Yagudo Interrogator', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Oracle']           = { Name='Yagudo Oracle', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Priest']           = { Name='Yagudo Priest', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Theologist']       = { Name='Yagudo Theologist', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Votary']           = { Name='Yagudo Votary', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo\'s Elemental']     = { Name='Yagudo\'s Elemental', Ecosystem='elementals', Family='elementals' },
        ['Yilbegan']                = { Name='Yilbegan', Ecosystem='dragons', Family='zilant' },
        -- Custom content for HorizonXI
        ['Sacred Scorpions']        = { Name='Sacred Scorpions', Ecosystem='vermin', Family='scorpions' },
        ['Flying Beetle']           = { Name='Flying Beetle', Ecosystem='vermin', Family='beetles' },
        ['Young Uragnite']          = { Name='Young Uragnite', Ecosystem='aquans', Family='uragnites' },
    },
};
