--Zone: Sauromugue Champaign
--Zone ID: 120
return {
    Names = {
        ['Aither'] = { Name='Aither', 
        ['Arke'] = { Name='Arke', 
        ['Balam-Agab'] = { Name='Balam-Agab', 
        ['Bashe'] = { Name='Bashe', 
        ['Beorht'] = { Name='Beorht', 
        ['Big Jaw'] = { Name='Big Jaw', 
        ['Blighting Brand'] = { Name='Blighting Brand', 
        ['Champaign Coeurl'] = { Name='Champaign Coeurl', 
        ['Climbpix Highrise'] = { Name='Climbpix Highrise', 
        ['Cutter'] = { Name='Cutter', 
        ['Deadly Dodo'] = { Name='Deadly Dodo', 
        ['Deorc'] = { Name='Deorc', 
        ['Diving Beetle'] = { Name='Diving Beetle', 
        ['Dribblix Greasemaw'] = { Name='Dribblix Greasemaw', 
        ['Earth Elemental'] = { Name='Earth Elemental', 
        ['Eorthe'] = { Name='Eorthe', 
        ['Evil Spirit'] = { Name='Evil Spirit', 
        ['Evil Weapon'] = { Name='Evil Weapon', 
        ['Goblin Bounty Hunter'] = { Name='Goblin Bounty Hunter', 
        ['Goblin Digger'] = { Name='Goblin Digger', 
        ['Goblin Furrier'] = { Name='Goblin Furrier', 
        ['Goblin Gambler'] = { Name='Goblin Gambler', 
        ['Goblin Leecher'] = { Name='Goblin Leecher', 
        ['Goblin Mugger'] = { Name='Goblin Mugger', 
        ['Goblin Pathfinder'] = { Name='Goblin Pathfinder', 
        ['Goblin Shaman'] = { Name='Goblin Shaman', 
        ['Goblin Smithy'] = { Name='Goblin Smithy', 
        ['Goblin\'s Beetle'] = { Name='Goblin\'s Beetle', 
        ['Goji'] = { Name='Goji', 
        ['Greater Pugil'] = { Name='Greater Pugil', 
        ['Hill Lizard'] = { Name='Hill Lizard', 
        ['Ignis Fatuus'] = { Name='Ignis Fatuus', 
        ['Kraken'] = { Name='Kraken', 
        ['Lacus'] = { Name='Lacus', 
        ['Midnight Wings'] = { Name='Midnight Wings', 
        ['Moon Bat'] = { Name='Moon Bat', 
        ['Old Sabertooth'] = { Name='Old Sabertooth', 
        ['Pruina'] = { Name='Pruina', 
        ['Puretos'] = { Name='Puretos', 
        ['Roc'] = { Name='Roc', 
        ['Sabertooth Tiger'] = { Name='Sabertooth Tiger', 
        ['Sauromugue Skink'] = { Name='Sauromugue Skink', 
        ['Skuld'] = { Name='Skuld', 
        ['Snipper'] = { Name='Snipper', 
        ['Sprite'] = { Name='Sprite', 
        ['Tabar Beak'] = { Name='Tabar Beak', 
        ['Thunder Elemental'] = { Name='Thunder Elemental', 
        ['Thunderclaw Thuban'] = { Name='Thunderclaw Thuban', 
        ['Thunor'] = { Name='Thunor', 
        ['Urd'] = { Name='Urd', 
        ['Verthandi'] = { Name='Verthandi', 
        ['Wight'] = { Name='Wight', 
        ['Yagudo Drummer'] = { Name='Yagudo Drummer', 
        ['Yagudo Herald'] = { Name='Yagudo Herald', 
        ['Yagudo Interrogator'] = { Name='Yagudo Interrogator', 
        ['Yagudo Oracle'] = { Name='Yagudo Oracle', 
        ['Yagudo Priest'] = { Name='Yagudo Priest', 
        ['Yagudo Theologist'] = { Name='Yagudo Theologist', 
        ['Yagudo Votary'] = { Name='Yagudo Votary', 
        ['Yagudo\'s Elemental'] = { Name='Yagudo\'s Elemental', 
        ['Yilbegan'] = { Name='Yilbegan', 
    },
};
