--Zone: The Sanctuary of Zi'Tah
--Zone ID: 121
return {
    Names = {
        ['Ancient Bat']             = { Name='Ancient Bat', Ecosystem='birds', Family='bats' },
        ['Apsaras']                 = { Name='Apsaras', Ecosystem='aquans', Family='pugils' },
        ['Bastet']                  = { Name='Bastet', Ecosystem='beast', Family='coeurls' },
        ['Bigclaw']                 = { Name='Bigclaw', Ecosystem='aquans', Family='crabs' },
        ['Blest Bones']             = { Name='Blest Bones', Ecosystem='undead', Family='skeletons' },
        ['Cath Palug']              = { Name='Cath Palug', Ecosystem='beast', Family='coeurls' },
        ['Clipper']                 = { Name='Clipper', Ecosystem='aquans', Family='crabs' },
        ['Doomed Pilgrims']         = { Name='Doomed Pilgrims', Ecosystem='undead', Family='doomed' },
        ['Elusive Edwin']           = { Name='Elusive Edwin', Ecosystem='vermin', Family='flies' },
        ['Goblin Bouncer']          = { Name='Goblin Bouncer', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Doyen']            = { Name='Goblin Doyen', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Enchanter']        = { Name='Goblin Enchanter', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Furrier']          = { Name='Goblin Furrier', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Gambler']          = { Name='Goblin Gambler', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Leecher']          = { Name='Goblin Leecher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Mugger']           = { Name='Goblin Mugger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Poacher']          = { Name='Goblin Poacher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Reaper']           = { Name='Goblin Reaper', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Robber']           = { Name='Goblin Robber', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Smithy']           = { Name='Goblin Smithy', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Trader']           = { Name='Goblin Trader', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Leech']         = { Name='Goblin\'s Leech', Ecosystem='amorphs', Family='leeches' },
        ['Goobbue Gardener']        = { Name='Goobbue Gardener', Ecosystem='plantoids', Family='goobues' },
        ['Goobbue Parasite']        = { Name='Goobbue Parasite', Ecosystem='amorphs', Family='leeches' },
        ['Greater Pugil']           = { Name='Greater Pugil', Ecosystem='aquans', Family='pugils' },
        ['Greenman']                = { Name='Greenman', Ecosystem='plantoids', Family='treants' },
        ['Grwnan']                  = { Name='Grwnan', Ecosystem='beast', Family='coeurls' },
        ['Guardian Treant']         = { Name='Guardian Treant', Ecosystem='plantoids', Family='treants' },
        ['Hell Hound']              = { Name='Hell Hound', Ecosystem='undead', Family='hounds' },
        ['Hobgoblin Beastmaster']   = { Name='Hobgoblin Beastmaster', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Black Mage']    = { Name='Hobgoblin Black Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Dark Knight']   = { Name='Hobgoblin Dark Knight', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Ranger']        = { Name='Hobgoblin Ranger', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Red Mage']      = { Name='Hobgoblin Red Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Thief']         = { Name='Hobgoblin Thief', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Warrior']       = { Name='Hobgoblin Warrior', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin White Mage']    = { Name='Hobgoblin White Mage', Ecosystem='beastmen', Family='goblins' },
        ['Holey Horror']            = { Name='Holey Horror', Ecosystem='undead', Family='ghosts' },
        ['Huwasi']                  = { Name='Huwasi', Ecosystem='arcana', Family='golems' },
        ['Isonade']                 = { Name='Isonade', Ecosystem='aquans', Family='pugils' },
        ['Keeper of Halidom']       = { Name='Keeper of Halidom', Ecosystem='plantoids', Family='goobues' },
        ['Keeper of Heiligtum']     = { Name='Keeper of Heiligtum', Ecosystem='plantoids', Family='goobues' },
        ['Lesser Gaylas']           = { Name='Lesser Gaylas', Ecosystem='birds', Family='bat trios' },
        ['Lost Soul']               = { Name='Lost Soul', Ecosystem='undead', Family='skeletons' },
        ['Master Coeurl']           = { Name='Master Coeurl', Ecosystem='beast', Family='coeurls' },
        ['Myxomycete']              = { Name='Myxomycete', Ecosystem='plantoids', Family='funguars' },
        ['Noble Mold']              = { Name='Noble Mold', Ecosystem='plantoids', Family='funguars' },
        ['Ogrefly']                 = { Name='Ogrefly', Ecosystem='vermin', Family='flies' },
        ['Puroboros']               = { Name='Puroboros', Ecosystem='arcana', Family='bombs' },
        ['Revenant']                = { Name='Revenant', Ecosystem='undead', Family='ghosts' },
        ['Rock Golem']              = { Name='Rock Golem', Ecosystem='arcana', Family='golems' },
        ['Rot Prowler']             = { Name='Rot Prowler', Ecosystem='undead', Family='skeletons' },
        ['Ruebezahl']               = { Name='Ruebezahl', Ecosystem='arcana', Family='golems' },
        ['Skeleton Scuffler']       = { Name='Skeleton Scuffler', Ecosystem='undead', Family='skeletons' },
        ['Thunder Elemental']       = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
        ['Water Elemental']         = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
    },
};
