--Zone: Yuhtunga Jungle
--Zone ID: 123
return {
    Names = {
        ['Bayawak']                 = { Name='Bayawak', Ecosystem='lizards', Family='lizards' },
        ['Bigclaw']                 = { Name='Bigclaw', Ecosystem='aquans', Family='crabs' },
        ['Bloodsucker']             = { Name='Bloodsucker', Ecosystem='amorphs', Family='leeches' },
        ['Brook Sahagin']           = { Name='Brook Sahagin', Ecosystem='beastmen', Family='sahagans' },
        ['Carthi']                  = { Name='Carthi', Ecosystem='beast', Family='opo-opos' },
        ['Creek Sahagin']           = { Name='Creek Sahagin', Ecosystem='beastmen', Family='sahagans' },
        ['Death Jacket']            = { Name='Death Jacket', Ecosystem='vermin', Family='bees' },
        ['Demisahagin Bard']        = { Name='Demisahagin Bard', Ecosystem='beastmen', Family='sahagans' },
        ['Demisahagin Dragoon']     = { Name='Demisahagin Dragoon', Ecosystem='beastmen', Family='sahagans' },
        ['Demisahagin Monk']        = { Name='Demisahagin Monk', Ecosystem='beastmen', Family='sahagans' },
        ['Demishagin White Mage']   = { Name='Demishagin White Mage', Ecosystem='beastmen', Family='sahagans' },
        ['Fire Elemental']          = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals' },
        ['Goblin Digger']           = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Furrier']          = { Name='Goblin Furrier', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Poacher']          = { Name='Goblin Poacher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Reaper']           = { Name='Goblin Reaper', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Robber']           = { Name='Goblin Robber', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Smithy']           = { Name='Goblin Smithy', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Bee']           = { Name='Goblin\'s Bee', Ecosystem='vermin', Family='bees' },
        ['Hobgoblin Beastmaster']   = { Name='Hobgoblin Beastmaster', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Black Mage']    = { Name='Hobgoblin Black Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Dark Knight']   = { Name='Hobgoblin Dark Knight', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Ranger']        = { Name='Hobgoblin Ranger', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Red Mage']      = { Name='Hobgoblin Red Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Thief']         = { Name='Hobgoblin Thief', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Warrior']       = { Name='Hobgoblin Warrior', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin White Mage']    = { Name='Hobgoblin White Mage', Ecosystem='beastmen', Family='goblins' },
        ['Holy Moly']               = { Name='Holy Moly', Ecosystem='plantoids', Family='rafflesias' },
        ['Ironshell']               = { Name='Ironshell', Ecosystem='aquans', Family='crabs' },
        ['Ivory Lizard']            = { Name='Ivory Lizard', Ecosystem='lizards', Family='lizards' },
        ['Jungle Coeurl']           = { Name='Jungle Coeurl', Ecosystem='beast', Family='coeurls' },
        ['Koropokkur']              = { Name='Koropokkur', Ecosystem='plantoids', Family='mandragoras' },
        ['Lake Sahagin']            = { Name='Lake Sahagin', Ecosystem='beastmen', Family='sahagans' },
        ['Lava Bomb']               = { Name='Lava Bomb', Ecosystem='arcana', Family='bombs' },
        ['Makara']                  = { Name='Makara', Ecosystem='aquans', Family='pugils' },
        ['Meww the Turtlerider']    = { Name='Meww the Turtlerider', Ecosystem='beastmen', Family='sahagans' },
        ['Mischievous Micholas']    = { Name='Mischievous Micholas', Ecosystem='beast', Family='opo-opos' },
        ['Moly']                    = { Name='Moly', Ecosystem='plantoids', Family='rafflesias' },
        ['Nasus']                   = { Name='Nasus', Ecosystem='vermin', Family='bees' },
        ['Nutcracker']              = { Name='Nutcracker', Ecosystem='beast', Family='opo-opos' },
        ['Overgrown Rose']          = { Name='Overgrown Rose', Ecosystem='plantoids', Family='morbols' },
        ['Pyuu the Spatemaker']     = { Name='Pyuu the Spatemaker', Ecosystem='beastmen', Family='sahagans' },
        ['River Sahagin']           = { Name='River Sahagin', Ecosystem='beastmen', Family='sahagans' },
        ['Rivulet Sahagin']         = { Name='Rivulet Sahagin', Ecosystem='beastmen', Family='sahagans' },
        ['Rose Garden']             = { Name='Rose Garden', Ecosystem='plantoids', Family='morbols' },
        ['Sahagin Patriarch']       = { Name='Sahagin Patriarch', Ecosystem='beastmen', Family='sahagans' },
        ['Sahagin\'s Wyvern']       = { Name='Sahagin\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Siren']                   = { Name='Siren', Ecosystem='birds', Family='birds' },
        ['Soldier Crawler']         = { Name='Soldier Crawler', Ecosystem='vermin', Family='crawlers' },
        ['Stream Sahagin']          = { Name='Stream Sahagin', Ecosystem='beastmen', Family='sahagans' },
        ['Tipha']                   = { Name='Tipha', Ecosystem='beast', Family='opo-opos' },
        ['Voluptuous Vilma']        = { Name='Voluptuous Vilma', Ecosystem='plantoids', Family='morbols' },
        ['Water Elemental']         = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
        ['Young Opo-opo']           = { Name='Young Opo-opo', Ecosystem='beast', Family='opo-opos' },
        ['Yuhtunga Mandragora']     = { Name='Yuhtunga Mandragora', Ecosystem='plantoids', Family='mandragoras' },
    },
};
