--Zone: Yhoator Jungle
--Zone ID: 124
return {
    Names = {
        ['Acolnahuacatl'] = { Name='Acolnahuacatl', Ecosystem='beasts', Family='coeurls'},
        ['Anemone'] = { Name='Anemone', Ecosystem='plantoids', Family='morbols'},
        ['Big Jaw'] = { Name='Big Jaw', Ecosystem='aquans', Family='pugils'},
        ['Bisque-heeled Sunberry'] = { Name='Bisque-heeled Sunberry', Ecosystem='beastmen', Family='tonberries'},
        ['Bright-handed Kunberry'] = { Name='Bright-handed Kunberry', Ecosystem='beastmen', Family='tonberries'},
        ['Clipper'] = { Name='Clipper', Ecosystem='aquans', Family='crabs'},
        ['Edacious Opo-opo'] = { Name='Edacious Opo-opo', Ecosystem='beasts', Family='opo-opos'},
        ['Fire Elemental'] = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals'},
        ['Goblin Bouncer'] = { Name='Goblin Bouncer', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Digger'] = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Hunter'] = { Name='Goblin Hunter', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Pathfinder'] = { Name='Goblin Pathfinder', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Poacher'] = { Name='Goblin Poacher', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Reaper'] = { Name='Goblin Reaper', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Robber'] = { Name='Goblin Robber', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Shaman'] = { Name='Goblin Shaman', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Smithy'] = { Name='Goblin Smithy', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Trader'] = { Name='Goblin Trader', Ecosystem='beastmen', Family='goblins'},
        ['Goblin\'s Bee'] = { Name='Goblin\'s Bee', Ecosystem='vermin', Family='bees'},
        ['Greater Pugil'] = { Name='Greater Pugil', Ecosystem='aquans', Family='pugils'},
        ['Hoar-knuckled Rimberry'] = { Name='Hoar-knuckled Rimberry', Ecosystem='beastmen', Family='tonberries'},
        ['Hobgoblin Beastmaster'] = { Name='Hobgoblin Beastmaster', Ecosystem='beastmen', Family='goblins'},
        ['Hobgoblin Black Mage'] = { Name='Hobgoblin Black Mage', Ecosystem='beastmen', Family='goblins'},
        ['Hobgoblin Dark Knight'] = { Name='Hobgoblin Dark Knight', Ecosystem='beastmen', Family='goblins'},
        ['Hobgoblin Ranger'] = { Name='Hobgoblin Ranger', Ecosystem='beastmen', Family='goblins'},
        ['Hobgoblin Red Mage'] = { Name='Hobgoblin Red Mage', Ecosystem='beastmen', Family='goblins'},
        ['Hobgoblin Thief'] = { Name='Hobgoblin Thief', Ecosystem='beastmen', Family='goblins'},
        ['Hobgoblin Warrior'] = { Name='Hobgoblin Warrior', Ecosystem='beastmen', Family='goblins'},
        ['Hobgoblin White Mage'] = { Name='Hobgoblin White Mage', Ecosystem='beastmen', Family='goblins'},
        ['Kappa Akuso'] = { Name='Kappa Akuso', Ecosystem='beastmen', Family='sahagins'},
        ['Kappa Biwa'] = { Name='Kappa Biwa', Ecosystem='beastmen', Family='sahagins'},
        ['Kappa Bonze'] = { Name='Kappa Bonze', Ecosystem='beastmen', Family='sahagins'},
        ['Kedgebelly Kate'] = { Name='Kedgebelly Kate', Ecosystem='plantoids', Family='morbols'},
        ['Makara'] = { Name='Makara', Ecosystem='aquans', Family='pugils'},
        ['Master Coeurl'] = { Name='Master Coeurl', Ecosystem='beasts', Family='coeurls'},
        ['Noctonberry Black Mage'] = { Name='Noctonberry Black Mage', Ecosystem='beastmen', Family='tonberries'},
        ['Noctonberry Ninja'] = { Name='Noctonberry Ninja', Ecosystem='beastmen', Family='tonberries'},
        ['Noctonberry Summoner'] = { Name='Noctonberry Summoner', Ecosystem='beastmen', Family='tonberries'},
        ['Noctonberry Thief'] = { Name='Noctonberry Thief', Ecosystem='beastmen', Family='tonberries'},
        ['Powderer Penny'] = { Name='Powderer Penny', Ecosystem='vermin', Family='bees'},
        ['Puroboros'] = { Name='Puroboros', Ecosystem='arcana', Family='bombs'},
        ['Tonberry Chopper'] = { Name='Tonberry Chopper', Ecosystem='beastmen', Family='tonberries'},
        ['Tonberry Creeper'] = { Name='Tonberry Creeper', Ecosystem='beastmen', Family='tonberries'},
        ['Tonberry Decimator'] = { Name='Tonberry Decimator', Ecosystem='beastmen', Family='tonberries'},
        ['Tonberry Harasser'] = { Name='Tonberry Harasser', Ecosystem='beastmen', Family='tonberries'},
        ['Tonberry Hexer'] = { Name='Tonberry Hexer', Ecosystem='beastmen', Family='tonberries'},
        ['Tonberry Jinxer'] = { Name='Tonberry Jinxer', Ecosystem='beastmen', Family='tonberries'},
        ['Tonberry Shadower'] = { Name='Tonberry Shadower', Ecosystem='beastmen', Family='tonberries'},
        ['Tonberry\'s Avatar'] = { Name='Tonberry\'s Avatar', Ecosystem='unclassified', Family='avatars'},
        ['Tonberry\'s Elemental'] = { Name='Tonberry\'s Elemental', Ecosystem='elementals', Family='elementals'},
        ['Vepar'] = { Name='Vepar', Ecosystem='aquans', Family='pugils'},
        ['Water Elemental'] = { Name='Water Elemental', Ecosystem='elementals', Family='elementals'},
        ['White Lizard'] = { Name='White Lizard', Ecosystem='lizards', Family='lizards'},
        ['Woodland Sage'] = { Name='Woodland Sage', Ecosystem='plantoids', Family='triants'},
        ['Worker Crawler'] = { Name='Worker Crawler', Ecosystem='vermin', Family='crawlers'},
        ['Yhoator Mandragora'] = { Name='Yhoator Mandragora', Ecosystem='plantoids', Family='mandragoras'},
        ['Yhoator Wasp'] = { Name='Yhoator Wasp', Ecosystem='vermin', Family='bees'},
        ['Young Opo-opo'] = { Name='Young Opo-opo', Ecosystem='beasts', Family='opo-opos'},
            -- Custom content for HorizonXI
        ['Tonberry Sovereign'] = { Name='Tonberry Sovereign', Ecosystem='beastmen', Family='tonberries' },
    },
};
