--Zone: Western Altepa Desert
--Zone ID: 125
return {
    Names = {
        ['Antican Eques']           = { Name='Antican Eques', Ecosystem='beastmen', Family='antica' },
        ['Antican Essedarius']      = { Name='Antican Essedarius', Ecosystem='beastmen', Family='antica' },
        ['Antican Hoplomachus']     = { Name='Antican Hoplomachus', Ecosystem='beastmen', Family='antica' },
        ['Antican Lanista']         = { Name='Antican Lanista', Ecosystem='beastmen', Family='antica' },
        ['Antican Retiarius']       = { Name='Antican Retiarius', Ecosystem='beastmen', Family='antica' },
        ['Antican Secutor']         = { Name='Antican Secutor', Ecosystem='beastmen', Family='antica' },
        ['Apsaras']                 = { Name='Apsaras', Ecosystem='aquans', Family='pugils' },
        ['Bigclaw']                 = { Name='Bigclaw', Ecosystem='aquans', Family='crabs' },
        ['Cactuar']                 = { Name='Cactuar', Ecosystem='plantoids', Family='sabotenders' },
        ['Cactuar Cantautor']       = { Name='Cactuar Cantautor', Ecosystem='plantoids', Family='sabotenders' },
        ['Calchas']                 = { Name='Calchas', Ecosystem='vermin', Family='scorpions' },
        ['Celphie']                 = { Name='Celphie', Ecosystem='beasts', Family='dhalmels' },
        ['Dahu']                    = { Name='Dahu', Ecosystem='beasts', Family='manticores' },
        ['Desert Beetle']           = { Name='Desert Beetle', Ecosystem='vermin', Family='beetles' },
        ['Desert Dhalmel']          = { Name='Desert Dhalmel', Ecosystem='beasts', Family='dhalmels' },
        ['Desert Manticore']        = { Name='Desert Manticore', Ecosystem='beasts', Family='manticores' },
        ['Desert Spider']           = { Name='Desert Spider', Ecosystem='vermin', Family='spiders' },
        ['Desert Worm']             = { Name='Desert Worm', Ecosystem='amorphs', Family='worms' },
        ['Earth Elemental']         = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Eastern Sphinx']          = { Name='Eastern Sphinx', Ecosystem='beasts', Family='manticores' },
        ['Fallen Knight']           = { Name='Fallen Knight', Ecosystem='undead', Family='skeletons' },
        ['Fire Elemental']          = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals' },
        ['Goblin Bouncer']          = { Name='Goblin Bouncer', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Digger']           = { Name='Goblin Digger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Enchanter']        = { Name='Goblin Enchanter', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Hunter']           = { Name='Goblin Hunter', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Welldigger']       = { Name='Goblin Welldigger', Ecosystem='beastmen', Family='goblins' },
        ['Ironshell']               = { Name='Ironshell', Ecosystem='aquans', Family='crabs' },
        ['King Uropygid']           = { Name='King Uropygid', Ecosystem='vermin', Family='scorpions' },
        ['King Vinegarroon']        = { Name='King Vinegarroon', Ecosystem='vermin', Family='scorpions' },
        ['Lich']                    = { Name='Lich', Ecosystem='undead', Family='skeletons' },
        ['Maharaja']                = { Name='Maharaja', Ecosystem='beasts', Family='tigers' },
        ['Monarca de Altepa']       = { Name='Monarca de Altepa', Ecosystem='plantoids', Family='sabotenders' },
        ['Phorusrhacos']            = { Name='Phorusrhacos', Ecosystem='birds', Family='rocs' },
        ['Picolaton']               = { Name='Picolaton', Ecosystem='birds', Family='rocs' },
        ['Razorjaw Pugil']          = { Name='Razorjaw Pugil', Ecosystem='aquans', Family='pugils' },
        ['Sabotender Campeador']    = { Name='Sabotender Campeador', Ecosystem='plantoids', Family='sabotenders' },
        ['Sabotender Enamorado']    = { Name='Sabotender Enamorado', Ecosystem='plantoids', Family='sabotenders' },
        ['Sabotender Mercenario']   = { Name='Sabotender Mercenario', Ecosystem='plantoids', Family='sabotenders' },
        ['Tulwar Scorpion']         = { Name='Tulwar Scorpion', Ecosystem='vermin', Family='scorpions' },
        ['Western Sphinx']          = { Name='Western Sphinx', Ecosystem='beasts', Family='manticores' },
        -- Custom content for HorizonXI
        ['Scorch Dhalmel']          = { Name='Scorch Dhalmel', Ecosystem='beasts', Family='dhalmels' },
        ['Bloody Beetle']           = { Name='Bloody Beetle', Ecosystem='vermin', Family='beetles' },
        ['Desert Gazer']            = { Name='Desert Gazer', Ecosystem='amorphs', Family='hecteyes' },
        ['Desert Slime']            = { Name='Desert Slime', Ecosystem='amorphs', Family='slimes' },
    },
};
