--Zone: Qufim Island
--Zone ID: 126
return {
    Names = {
        ['Acrophies']               = { Name='Acrophies', Ecosystem='amorphs', Family='leeches' },
        ['Ancient Bat']             = { Name='Ancient Bat', Ecosystem='birds', Family='bats' },
        ['Atkorkamuy']              = { Name='Atkorkamuy', Ecosystem='aquans', Family='sea monks' },
        ['Banshee']                 = { Name='Banshee', Ecosystem='undead', Family='ghosts' },
        ['Clipper']                 = { Name='Clipper', Ecosystem='aquans', Family='crabs' },
        ['Dancing Weapon']          = { Name='Dancing Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Dark Bats']               = { Name='Dark Bats', Ecosystem='birds', Family='bat trios' },
        ['Dosetsu Tree']            = { Name='Dosetsu Tree', Ecosystem='plantoids', Family='treants' },
        ['Giant Ascetic']           = { Name='Giant Ascetic', Ecosystem='beastmen', Family='gigas' },
        ['Giant Beastmaster']       = { Name='Giant Beastmaster', Ecosystem='beastmen', Family='gigas' },
        ['Giant High Ranger']       = { Name='Giant High Ranger', Ecosystem='beastmen', Family='gigas' },
        ['Giant Hunter']            = { Name='Giant Hunter', Ecosystem='beastmen', Family='gigas' },
        ['Giant Monk']              = { Name='Giant Monk', Ecosystem='beastmen', Family='gigas' },
        ['Giant Ranger']            = { Name='Giant Ranger', Ecosystem='beastmen', Family='gigas' },
        ['Giant Trapper']           = { Name='Giant Trapper', Ecosystem='beastmen', Family='gigas' },
        ['Giant Warrior']           = { Name='Giant Warrior', Ecosystem='beastmen', Family='gigas' },
        ['Gigas\'s Leech']          = { Name='Gigas\'s Leech', Ecosystem='amorphs', Family='leeches' },
        ['Glow Bat']                = { Name='Glow Bat', Ecosystem='birds', Family='bats' },
        ['Goblin Bounty Hunter']    = { Name='Goblin Bounty Hunter', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Leech']         = { Name='Goblin\'s Leech', Ecosystem='amorphs', Family='leeches' },
        ['Greater Pugil']           = { Name='Greater Pugil', Ecosystem='aquans', Family='pugils' },
        ['Hobgoblin Beastmaster']   = { Name='Hobgoblin Beastmaster', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Black Mage']    = { Name='Hobgoblin Black Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Dark Knight']   = { Name='Hobgoblin Dark Knight', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Ranger']        = { Name='Hobgoblin Ranger', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Red Mage']      = { Name='Hobgoblin Red Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Thief']         = { Name='Hobgoblin Thief', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Warrior']       = { Name='Hobgoblin Warrior', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin White Mage']    = { Name='Hobgoblin White Mage', Ecosystem='beastmen', Family='goblins' },
        ['Hunting Chief']           = { Name='Hunting Chief', Ecosystem='beastmen', Family='gigas' },
        ['Ingaevon']                = { Name='Ingaevon', Ecosystem='beastmen', Family='gigas' },
        ['Jester Malatrix']         = { Name='Jester Malatrix', Ecosystem='arcana', Family='evil weapons' },
        ['Kaggen']                  = { Name='Kaggen', Ecosystem='vermin', Family='mantids' },
        ['Kraken']                  = { Name='Kraken', Ecosystem='aquans', Family='sea monks' },
        ['Land Worm']               = { Name='Land Worm', Ecosystem='amorphs', Family='worms' },
        ['Light Elemental']         = { Name='Light Elemental', Ecosystem='elementals', Family='elementals' },
        ['Malefic Fencer']          = { Name='Malefic Fencer', Ecosystem='arcana', Family='evil weapons' },
        ['Ophiotaurus']             = { Name='Ophiotaurus', Ecosystem='beasts', Family='yztargs' },
        ['Qoofim']                  = { Name='Qoofim', Ecosystem='aquans', Family='pugils' },
        ['Qufim Pugil']             = { Name='Qufim Pugil', Ecosystem='aquans', Family='pugils' },
        ['Sea Bishop']              = { Name='Sea Bishop', Ecosystem='aquans', Family='sea monks' },
        ['Seed Mandragora']         = { Name='Seed Mandragora', Ecosystem='plantoids', Family='mandragoras' },
        ['Seeker Bats']             = { Name='Seeker Bats', Ecosystem='birds', Family='bat trios' },
        ['Slippery Sucker']         = { Name='Slippery Sucker', Ecosystem='amorphs', Family='leeches' },
        ['Thunder Elemental']       = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
        ['Trickster Kinetix']       = { Name='Trickster Kinetix', Ecosystem='arcana', Family='evil weapons' },
        ['Vepar']                   = { Name='Vepar', Ecosystem='aquans', Family='pugils' },
        ['Wight']                   = { Name='Wight', Ecosystem='undead', Family='skeletons' },
        -- Custom content for HorizonXI
        ['Island Gloop']            = { Name='Island Gloop', Ecosystem='amorphs', Family='slimes' },
        ['Hexed Weapon']            = { Name='Hexed Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Cliff Worm']              = { Name='Cliff Worm', Ecosystem='amorphs', Family='worms' },
    },
};
