--Zone: Newton Movalpolos
--Zone ID: 12
return {
    Names = {
        ['Bugbear Deathsman']       = { Name='Bugbear Deathsman', Ecosystem='beastmen', Family='bugbears' },
        ['Bugbear Matman']          = { Name='Bugbear Matman', Ecosystem='beastmen', Family='bugbears' },
        ['Bugbear Trashman']        = { Name='Bugbear Trashman', Ecosystem='beastmen', Family='bugbears' },
        ['Bugbear Watchman']        = { Name='Bugbear Watchman', Ecosystem='beastmen', Family='bugbears' },
        ['Dire Bat']                = { Name='Dire Bat', Ecosystem='birds', Family='bats' },
        ['Earth Elemental']         = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Goblin Collector']        = { Name='Goblin Collector', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Fireman']          = { Name='Goblin Fireman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Foreman']          = { Name='Goblin Foreman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Hangman']          = { Name='Goblin Hangman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Headman']          = { Name='Goblin Headman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Junkman']          = { Name='Goblin Junkman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Lengthman']        = { Name='Goblin Lengthman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Marksman']         = { Name='Goblin Marksman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Packman']          = { Name='Goblin Packman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Swordsman']        = { Name='Goblin Swordsman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Bat']           = { Name='Goblin\'s Bat', Ecosystem='birds', Family='bats' },
        ['Mimic']                   = { Name='Mimic', Ecosystem='arcana', Family='mimics' },
        ['Moblin Aidman']           = { Name='Moblin Aidman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Draftsman']        = { Name='Moblin Draftsman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Engineman']        = { Name='Moblin Engineman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Groundman']        = { Name='Moblin Groundman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Roadman']          = { Name='Moblin Roadman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Scalpelman']       = { Name='Moblin Scalpelman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Tankman']          = { Name='Moblin Tankman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Topsman']          = { Name='Moblin Topsman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Workman']          = { Name='Moblin Workman', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Yardman']          = { Name='Moblin Yardman', Ecosystem='beastmen', Family='moblins' },
        ['Nightmare Bats']          = { Name='Nightmare Bats', Ecosystem='birds', Family='bat trios' },
        ['Purgatory Bat']           = { Name='Purgatory Bat', Ecosystem='birds', Family='bats' },
        ['Succubus Bats']           = { Name='Succubus Bats', Ecosystem='birds', Family='bat trios' },
        ['Swashstox Beadblinker']   = { Name='Swashstox Beadblinker', Ecosystem='beastmen', Family='goblins' },
        ['Sword Sorcerer Solisoq']  = { Name='Sword Sorcerer Solisoq', Ecosystem='beastmen', Family='goblins' },
        ['Thunder Elemental']       = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
    },
};
