--Zone: Dynamis - Beaucedine
--Zone ID: 134
return {
    Names = {
        ['Adamantking Effigy']          = { Name='Adamantking Effigy', Ecosystem='unclassified', Family='replicas'},
        ['Adamantking Image']           = { Name='Adamantking Image', Ecosystem='unclassified', Family='replicas'},
        ['Angra Mainyu']                = { Name='Angra Mainyu', Ecosystem='demons', Family='ahriman'},
        ['Arch Angra Mainyu']           = { Name='Arch Angra Mainyu', Ecosystem='demons', Family='ahriman'},
        ['Ascetox Ratgums']             = { Name='Ascetox Ratgums', Ecosystem='beastmen', Family='goblins'},
        ['Avatar Icon']                 = { Name='Avatar Icon', Ecosystem='unclassified', Family='replica'},
        ['Avatar Idol']                 = { Name='Avatar Idol', Ecosystem='unclassified', Family='replica'},
        ['Be\'Zhe Keeprazer']           = { Name='Be\'Zhe Keeprazer', Ecosystem='beastmen', Family='quadav'},
        ['Bhuu Wjato the Firepool']     = { Name='Bhuu Wjato the Firepool', Ecosystem='beastmen', Family='yagudo'},
        ['Bordox Kittyback']            = { Name='Bordox Kittyback', Ecosystem='beastmen', Family='goblins'},
        ['Brewnix Bittypupils']         = { Name='Brewnix Bittypupils', Ecosystem='beastmen', Family='goblins'},
        ['Caa Xaza the Madpiercer']     = { Name='Caa Xaza the Madpiercer', Ecosystem='beastmen', Family='yagudo'},
        ['Cavanneche']                  = { Name='Cavanneche', Ecosystem='undead', Family='fomors'},
        ['Cobraclaw Buchzvotch']        = { Name='Cobraclaw Buchzvotch', Ecosystem='beastmen', Family='orcs'},
        ['Dagourmarche']                = { Name='Dagourmarche', Ecosystem='undead', Family='fomors'},
        ['Dagourmarche\'s Avatar']      = { Name='Dagourmarche\'s Avatar', Ecosystem='unclassified', Family='avatars'},
        ['Dagourmarche\'s Wyvern']      = { Name='Dagourmarche\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['De\'Bho Pyrohand']            = { Name='De\'Bho Pyrohand', Ecosystem='beastmen', Family='quadav'},
        ['Deathcaller Bidfbid']         = { Name='Deathcaller Bidfbid', Ecosystem='beastmen', Family='orcs'},
        ['Drakefeast Wubmfub']          = { Name='Drakefeast Wubmfub', Ecosystem='beastmen', Family='orcs'},
        ['Draklix Scalecrust']          = { Name='Draklix Scalecrust', Ecosystem='beastmen', Family='goblins'},
        ['Droprix Granitepalms']        = { Name='Droprix Granitepalms', Ecosystem='beastmen', Family='goblins'},
        ['Elvaanlopper Grokdok']        = { Name='Elvaanlopper Grokdok', Ecosystem='beastmen', Family='orcs'},
        ['Fire Pukis']                  = { Name='Fire Pukis', Ecosystem='dragons', Family='dragons'},
        ['Foo Peku the Bloodcloak']     = { Name='Foo Peku the Bloodcloak', Ecosystem='beastmen', Family='yagudo'},
        ['Ga\'Fho Venomtouch']          = { Name='Ga\'Fho Venomtouch', Ecosystem='beastmen', Family='quadav'},
        ['Galkarider Retzpratz']        = { Name='Galkarider Retzpratz', Ecosystem='beastmen', Family='orcs'},
        ['Gibberox Pimplebeak']         = { Name='Gibberox Pimplebeak', Ecosystem='beastmen', Family='goblins'},
        ['Go\'Tyo Magenapper']          = { Name='Go\'Tyo Magenapper', Ecosystem='beastmen', Family='quadav'},
        ['Goblin Replica']              = { Name='Goblin Replica', Ecosystem='unclassified', Family='replica'},
        ['Goblin Statue']               = { Name='Goblin Statue', Ecosystem='unclassified', Family='replica'},
        ['Goublefaupe']                 = { Name='Goublefaupe', Ecosystem='undead', Family='fomors'},
        ['Gu\'Khu Dukesniper']          = { Name='Gu\'Khu Dukesniper', Ecosystem='beastmen', Family='quadav'},
        ['Gu\'Nha Wallstormer']         = { Name='Gu\'Nha Wallstormer', Ecosystem='beastmen', Family='quadav'},
        ['Guu Waji the Preacher']       = { Name='Guu Waji the Preacher', Ecosystem='beastmen', Family='yagudo'},
        ['Heavymail Djidzbad']          = { Name='Heavymail Djidzbad', Ecosystem='beastmen', Family='orcs'},
        ['Hee Mida the Meticulous']     = { Name='Hee Mida the Meticulous', Ecosystem='beastmen', Family='yagudo'},
        ['Hitaume']                     = { Name='Hitaume', Ecosystem='undead', Family='fomors'},
        ['Humegutter Adzjbadj']         = { Name='Humegutter Adzjbadj', Ecosystem='beastmen', Family='orcs'},
        ['Hydra Bard']                  = { Name='Hydra Bard', Ecosystem='undead', Family='fomors'},
        ['Hydra Beastmaster']           = { Name='Hydra Beastmaster', Ecosystem='undead', Family='fomors'},
        ['Hydra Black Mage']            = { Name='Hydra Black Mage', Ecosystem='undead', Family='fomors'},
        ['Hydra Dark Knight']           = { Name='Hydra Dark Knight', Ecosystem='undead', Family='fomors'},
        ['Hydra Dragoon']               = { Name='Hydra Dragoon', Ecosystem='undead', Family='fomors'},
        ['Hydra Monk']                  = { Name='Hydra Monk', Ecosystem='undead', Family='fomors'},
        ['Hydra Ninja']                 = { Name='Hydra Ninja', Ecosystem='undead', Family='fomors'},
        ['Hydra Paladin']               = { Name='Hydra Paladin', Ecosystem='undead', Family='fomors'},
        ['Hydra Ranger']                = { Name='Hydra Ranger', Ecosystem='undead', Family='fomors'},
        ['Hydra Red Mage']              = { Name='Hydra Red Mage', Ecosystem='undead', Family='fomors'},
        ['Hydra Samurai']               = { Name='Hydra Samurai', Ecosystem='undead', Family='fomors'},
        ['Hydra Summoner']              = { Name='Hydra Summoner', Ecosystem='undead', Family='fomors'},
        ['Hydra Thief']                 = { Name='Hydra Thief', Ecosystem='undead', Family='fomors'},
        ['Hydra Warrior']               = { Name='Hydra Warrior', Ecosystem='undead', Family='fomors'},
        ['Hydra White Mage']            = { Name='Hydra White Mage', Ecosystem='undead', Family='fomors'},
        ['Hydra\'s Avatar']             = { Name='Hydra\'s Avatar', Ecosystem='unclassified', Family='avatars'},
        ['Hydra\'s Hound']              = { Name='Hydra\'s Hound', Ecosystem='undead', Family='hounds'},
        ['Hydra\'s Wyvern']             = { Name='Hydra\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Jeunoraider Gepkzip']         = { Name='Jeunoraider Gepkzip', Ecosystem='undead', Family='fomors'},
        ['Ji\'Fhu Infiltrator']         = { Name='Ji\'Fhu Infiltrator', Ecosystem='beastmen', Family='quadav'},
        ['Ji\'Khu Towercleaver']        = { Name='Ji\'Khu Towercleaver', Ecosystem='beastmen', Family='quadav'},
        ['Knii Hoqo the Bisector']      = { Name='Knii Hoqo the Bisector', Ecosystem='beastmen', Family='yagudo'},
        ['Koo Saxu the Everfast']       = { Name='Koo Saxu the Everfast', Ecosystem='beastmen', Family='yagudo'},
        ['Kuu Xuka the Nimble']         = { Name='Kuu Xuka the Nimble', Ecosystem='beastmen', Family='yagudo'},
        ['Lockbuster Zapdjipp']         = { Name='Lockbuster Zapdjipp', Ecosystem='beastmen', Family='orcs'},
        ['Maa Zaua the Wyrmkeeper']     = { Name='Maa Zaua the Wyrmkeeper', Ecosystem='beastmen', Family='yagudo'},
        ['Mi\'Rhe Whisperblade']        = { Name='Mi\'Rhe Whisperblade', Ecosystem='beastmen', Family='quadav'},
        ['Mildaunegeux']                = { Name='Mildaunegeux', Ecosystem='undead', Family='fomors'},
        ['Mithraslaver Debhabob']       = { Name='Mithraslaver Debhabob', Ecosystem='beastmen', Family='orcs'},
        ['Moltenox Stubthumbs']         = { Name='Moltenox Stubthumbs', Ecosystem='beastmen', Family='goblins'},
        ['Morblox Chubbychin']          = { Name='Morblox Chubbychin', Ecosystem='beastmen', Family='goblins'},
        ['Mu\'Gha Legionkiller']        = { Name='Mu\'Gha Legionkiller', Ecosystem='beastmen', Family='quadav'},
        ['Na\'Hya Floodmaker']          = { Name='Na\'Hya Floodmaker', Ecosystem='beastmen', Family='quadav'},
        ['Nee Huxa the Judgmental']     = { Name='Nee Huxa the Judgmental', Ecosystem='beastmen', Family='yagudo'},
        ['Nu\'Bhi Spiraleye']           = { Name='Nu\'Bhi Spiraleye', Ecosystem='beastmen', Family='quadav'},
        ['Petro Pukis']                 = { Name='Petro Pukis', Ecosystem='dragons', Family='dragons'},
        ['Pignonpausard']               = { Name='Pignonpausard', Ecosystem='undead', Family='fomors'},
        ['Poison Pukis']                = { Name='Poison Pukis', Ecosystem='dragons', Family='dragons'},
        ['Puu Timu the Phantasmal']     = { Name='Puu Timu the Phantasmal', Ecosystem='beastmen', Family='yagudo'},
        ['Quiebitiel']                  = { Name='Quiebitiel', Ecosystem='undead', Family='fomor'},
        ['Rearguard Eye']               = { Name='Rearguard Eye', Ecosystem='demons', Family='ahriman'},
        ['Routsix Rubbertendon']        = { Name='Routsix Rubbertendon', Ecosystem='beastmen', Family='goblins'},
        ['Ruffbix Jumbolobes']          = { Name='Ruffbix Jumbolobes', Ecosystem='beastmen', Family='goblins'},
        ['Ryy Qihi the Idolrobber']     = { Name='Ryy Qihi the Idolrobber', Ecosystem='beastmen', Family='yagudo'},
        ['Serjeant Tombstone']          = { Name='Serjeant Tombstone', Ecosystem='unclassified', Family='replica'},
        ['Shisox Widebrow']             = { Name='Shisox Widebrow', Ecosystem='beastmen', Family='goblins'},
        ['Skinmask Ugghfogg']           = { Name='Skinmask Ugghfogg', Ecosystem='beastmen', Family='orcs'},
        ['Slinkix Trufflesniff']        = { Name='Slinkix Trufflesniff', Ecosystem='beastmen', Family='goblins'},
        ['So\'Gho Adderhandler']        = { Name='So\'Gho Adderhandler', Ecosystem='beastmen', Family='quadav'},
        ['So\'Zho Metalbender']         = { Name='So\'Zho Metalbender', Ecosystem='beastmen', Family='quadav'},
        ['Soo Jopo the Fiendking']      = { Name='Soo Jopo the Fiendking', Ecosystem='beastmen', Family='yagudo'},
        ['Spinalsucker Galflmall']      = { Name='Spinalsucker Galflmall', Ecosystem='beastmen', Family='orcs'},
        ['Swypestix Tigershins']        = { Name='Swypestix Tigershins', Ecosystem='beastmen', Family='goblins'},
        ['Ta\'Hyu Gallanthunter']       = { Name='Ta\'Hyu Gallanthunter', Ecosystem='beastmen', Family='quadav'},
        ['Taquede']                     = { Name='Taquede', Ecosystem='undead', Family='fomors'},
        ['Taquede\'s Wyvern']           = { Name='Taquede\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Taruroaster Biggsjig']        = { Name='Taruroaster Biggsjig', Ecosystem='beastmen', Family='orcs'},
        ['Tocktix Thinlids']            = { Name='Tocktix Thinlids', Ecosystem='beastmen', Family='goblins'},
        ['Ultrasonic Zeknajak']         = { Name='Ultrasonic Zeknajak', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Alchemist']          = { Name='Vanguard Alchemist', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Ambusher']           = { Name='Vanguard Ambusher', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Amputator']          = { Name='Vanguard Amputator', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Armorer']            = { Name='Vanguard Armorer', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Assassin']           = { Name='Vanguard Assassin', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Backstabber']        = { Name='Vanguard Backstabber', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Beasttender']        = { Name='Vanguard Beasttender', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Bugler']             = { Name='Vanguard Bugler', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Chanter']            = { Name='Vanguard Chanter', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Constable']          = { Name='Vanguard Constable', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Defender']           = { Name='Vanguard Defender', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Dollmaster']         = { Name='Vanguard Dollmaster', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Dragontamer']        = { Name='Vanguard Dragontamer', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Drakekeeper']        = { Name='Vanguard Drakekeeper', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Enchanter']          = { Name='Vanguard Enchanter', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Exemplar']           = { Name='Vanguard Exemplar', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Eye']                = { Name='Vanguard Eye', Ecosystem='demons', Family='ahriman' },
        ['Vanguard Footsoldier']        = { Name='Vanguard Footsoldier', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Grappler']           = { Name='Vanguard Grappler', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Gutslasher']         = { Name='Vanguard Gutslasher', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Hatamoto']           = { Name='Vanguard Hatamoto', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Hawker']             = { Name='Vanguard Hawker', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Hitman']             = { Name='Vanguard Hitman', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Impaler']            = { Name='Vanguard Impaler', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Inciter']            = { Name='Vanguard Inciter', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Kusa']               = { Name='Vanguard Kusa', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Liberator']          = { Name='Vanguard Liberator', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Maestro']            = { Name='Vanguard Maestro', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Mason']              = { Name='Vanguard Mason', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Mesmerizer']         = { Name='Vanguard Mesmerizer', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Militant']           = { Name='Vanguard Militant', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Minstrel']           = { Name='Vanguard Minstrel', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Neckchopper']        = { Name='Vanguard Neckchopper', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Necromancer']        = { Name='Vanguard Necromancer', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Ogresoother']        = { Name='Vanguard Ogresoother', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Oracle']             = { Name='Vanguard Oracle', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Partisan']           = { Name='Vanguard Partisan', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Pathfinder']         = { Name='Vanguard Pathfinder', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Persecutor']         = { Name='Vanguard Persecutor', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Pillager']           = { Name='Vanguard Pillager', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Pitfighter']         = { Name='Vanguard Pitfighter', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Predator']           = { Name='Vanguard Predator', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Prelate']            = { Name='Vanguard Prelate', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Priest']             = { Name='Vanguard Priest', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Protector']          = { Name='Vanguard Protector', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Purloiner']          = { Name='Vanguard Purloiner', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Ronin']              = { Name='Vanguard Ronin', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Salvager']           = { Name='Vanguard Salvager', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Sentinel']           = { Name='Vanguard Sentinel', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Shaman']             = { Name='Vanguard Shaman', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Skirmisher']         = { Name='Vanguard Skirmisher', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Smithy']             = { Name='Vanguard Smithy', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Thaumaturge']        = { Name='Vanguard Thaumaturge', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Tinkerer']           = { Name='Vanguard Tinkerer', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Trooper']            = { Name='Vanguard Trooper', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Undertaker']         = { Name='Vanguard Undertaker', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Vexer']              = { Name='Vanguard Vexer', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Vigilante']          = { Name='Vanguard Vigilante', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Vindicator']         = { Name='Vanguard Vindicator', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Visionary']          = { Name='Vanguard Visionary', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Welldigger']         = { Name='Vanguard Welldigger', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard\'s Avatar']          = { Name='Vanguard\'s Avatar', Ecosystem='unclassified', Family='monster'},
        ['Vanguard\'s Crow']            = { Name='Vanguard\'s Crow', Ecosystem='birds', Family='birds'},
        ['Vanguard\'s Hecteyes']        = { Name='Vanguard\'s Hecteyes', Ecosystem='amorphs', Family='hecteyes'},
        ['Vanguard\'s Scorpion']        = { Name='Vanguard\'s Scorpion', Ecosystem='vermin', Family='scorpions'},
        ['Vanguard\'s Slime']           = { Name='Vanguard\'s Slime', Ecosystem='amorphs', Family='slimes'},
        ['Vanguard\'s Wyvern']          = { Name='Vanguard\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Velosareon']                  = { Name='Velosareon', Ecosystem='undead', Family='fomors'},
        ['Warchief Tombstone']          = { Name='Warchief Tombstone', Ecosystem='unclassified', Family='replica'},
        ['Whistrix Toadthroat']         = { Name='Whistrix Toadthroat', Ecosystem='beastmen', Family='goblins'},
        ['Wind Pukis']                  = { Name='Wind Pukis', Ecosystem='dragons', Family='dragons'},
        ['Wraithdancer Gidbnod']        = { Name='Wraithdancer Gidbnod', Ecosystem='beastmen', Family='orcs'},
        ['Xaa Chau the Roctalon']       = { Name='Xaa Chau the Roctalon', Ecosystem='beastmen', Family='yagudo'},
        ['Xhoo Fuza the Sublime']       = { Name='Xhoo Fuza the Sublime', Ecosystem='beastmen', Family='yagudo'},
    },
};
