--Zone: Dynamis - Xarcabard
--Zone ID: 135
return {
    Names = {
        ['Adamantking Effigy'] = { Name='Adamantking Effigy', Ecosystem='unclassified', Family='replicas' },
        ['Andras\'s Vouivre'] = { Name='Andras\'s Vouivre', Ecosystem='dragons', Family='wyverns' },
        ['Animated Claymore'] = { Name='Animated Claymore', Ecosystem='unclassified', Family='animated weapons' },
        ['Animated Dagger'] = { Name='Animated Dagger', Ecosystem='unclassified', Family='animated weapons' },
        ['Animated Great Axe'] = { Name='Animated Great Axe', Ecosystem='unclassified', Family='animated weapons' },
        ['Animated Gun'] = { Name='Animated Gun', Ecosystem='unclassified', Family='animated weapons' },
        ['Animated Hammer'] = { Name='Animated Hammer', Ecosystem='unclassified', Family='animated weapons' },
        ['Animated Horn'] = { Name='Animated Horn', Ecosystem='unclassified', Family='animated weapons' },
        ['Animated Knuckles'] = { Name='Animated Knuckles', Ecosystem='unclassified', Family='animated weapons' },
        ['Animated Kunai'] = { Name='Animated Kunai', Ecosystem='unclassified', Family='animated weapons' },
        ['Animated Longbow'] = { Name='Animated Longbow', Ecosystem='unclassified', Family='animated weapons' },
        ['Animated Longsword'] = { Name='Animated Longsword', Ecosystem='unclassified', Family='animated weapons' },
        ['Animated Scythe'] = { Name='Animated Scythe', Ecosystem='unclassified', Family='animated weapons' },
        ['Animated Shield'] = { Name='Animated Shield', Ecosystem='unclassified', Family='animated weapons' },
        ['Animated Spear'] = { Name='Animated Spear', Ecosystem='unclassified', Family='animated weapons' },
        ['Animated Staff'] = { Name='Animated Staff', Ecosystem='unclassified', Family='animated weapons' },
        ['Animated Tabar'] = { Name='Animated Tabar', Ecosystem='unclassified', Family='animated weapons' },
        ['Animated Tachi'] = { Name='Animated Tachi', Ecosystem='unclassified', Family='animated weapons' },
        ['Arch Dynamis Lord'] = { Name='Arch Dynamis Lord', Ecosystem='beastmen', Family='shadow lords' },
        ['Avatar Icon'] = { Name='Avatar Icon', Ecosystem='unclassified', Family='replicas' },
        ['Baron Avnas'] = { Name='Baron Avnas', Ecosystem='demons', Family='demons' },
        ['Caim\'s Vouivre'] = { Name='Caim\'s Vouivre', Ecosystem='dragons', Family='wyverns' },
        ['Count Haagenti'] = { Name='Count Haagenti', Ecosystem='demons', Family='demons' },
        ['Count Raum'] = { Name='Count Raum', Ecosystem='demons', Family='demons' },
        ['Count Vine'] = { Name='Count Vine', Ecosystem='demons', Family='demons' },
        ['Count Zaebos'] = { Name='Count Zaebos', Ecosystem='demons', Family='demons' },
        ['Duke Berith'] = { Name='Duke Berith', Ecosystem='demons', Family='demons' },
        ['Duke Gomory'] = { Name='Duke Gomory', Ecosystem='demons', Family='demons' },
        ['Duke Haures'] = { Name='Duke Haures', Ecosystem='demons', Family='demons' },
        ['Duke Scox'] = { Name='Duke Scox', Ecosystem='demons', Family='demons' },
        ['Dynamis Lord'] = { Name='Dynamis Lord', Ecosystem='beastmen', Family='shadow lords' },
        ['Effigy Prototype'] = { Name='Effigy Prototype', Ecosystem='unclassified', Family='replicas' },
        ['Goblin Replica'] = { Name='Goblin Replica', Ecosystem='unclassified', Family='replicas' },
        ['Haagenti\'s Avatar'] = { Name='Haagenti\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Icon Prototype'] = { Name='Icon Prototype', Ecosystem='unclassified', Family='replicas' },
        ['Kindred Bard'] = { Name='Kindred Bard', Ecosystem='demons', Family='demons' },
        ['Kindred Beastmaster'] = { Name='Kindred Beastmaster', Ecosystem='demons', Family='demons' },
        ['Kindred Black Mage'] = { Name='Kindred Black Mage', Ecosystem='demons', Family='demons' },
        ['Kindred Dark Knight'] = { Name='Kindred Dark Knight', Ecosystem='demons', Family='demons' },
        ['Kindred Dragoon'] = { Name='Kindred Dragoon', Ecosystem='demons', Family='demons' },
        ['Kindred Monk'] = { Name='Kindred Monk', Ecosystem='demons', Family='demons' },
        ['Kindred Ninja'] = { Name='Kindred Ninja', Ecosystem='demons', Family='demons' },
        ['Kindred Paladin'] = { Name='Kindred Paladin', Ecosystem='demons', Family='demons' },
        ['Kindred Ranger'] = { Name='Kindred Ranger', Ecosystem='demons', Family='demons' },
        ['Kindred Red Mage'] = { Name='Kindred Red Mage', Ecosystem='demons', Family='demons' },
        ['Kindred Samurai'] = { Name='Kindred Samurai', Ecosystem='demons', Family='demons' },
        ['Kindred Summoner'] = { Name='Kindred Summoner', Ecosystem='demons', Family='demons' },
        ['Kindred Thief'] = { Name='Kindred Thief', Ecosystem='demons', Family='demons' },
        ['Kindred Warrior'] = { Name='Kindred Warrior', Ecosystem='demons', Family='demons' },
        ['Kindred White Mage'] = { Name='Kindred White Mage', Ecosystem='demons', Family='demons' },
        ['Kindred\'s Avatar'] = { Name='Kindred\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Kindred\'s Vouivre'] = { Name='Kindred\'s Vouivre', Ecosystem='dragons', Family='wyverns' },
        ['Kindred\'s Wyvern'] = { Name='Kindred\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['King Zagan'] = { Name='King Zagan', Ecosystem='demons', Family='demons' },
        ['Marquis Andras'] = { Name='Marquis Andras', Ecosystem='demons', Family='demons' },
        ['Marquis Caim'] = { Name='Marquis Caim', Ecosystem='demons', Family='demons' },
        ['Marquis Cimeries'] = { Name='Marquis Cimeries', Ecosystem='demons', Family='demons' },
        ['Marquis Decarabia'] = { Name='Marquis Decarabia', Ecosystem='demons', Family='demons' },
        ['Marquis Gamygyn'] = { Name='Marquis Gamygyn', Ecosystem='demons', Family='demons' },
        ['Marquis Nebiros'] = { Name='Marquis Nebiros', Ecosystem='demons', Family='demons' },
        ['Marquis Orias'] = { Name='Marquis Orias', Ecosystem='demons', Family='demons' },
        ['Marquis Sabnak'] = { Name='Marquis Sabnak', Ecosystem='demons', Family='demons' },
        ['Nebiros\'s Avatar'] = { Name='Nebiros\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Prince Seere'] = { Name='Prince Seere', Ecosystem='demons', Family='demons' },
        ['Prototype Eye'] = { Name='Prototype Eye', Ecosystem='demons', Family='ahriman' },
        ['Satellite Claymores'] = { Name='Satellite Claymores', Ecosystem='unclassified', Family='animated weapons' },
        ['Satellite Daggers'] = { Name='Satellite Daggers', Ecosystem='unclassified', Family='animated weapons' },
        ['Satellite Great Axes'] = { Name='Satellite Great Axes', Ecosystem='unclassified', Family='animated weapons' },
        ['Satellite Guns'] = { Name='Satellite Guns', Ecosystem='unclassified', Family='animated weapons' },
        ['Satellite Hammers'] = { Name='Satellite Hammers', Ecosystem='unclassified', Family='animated weapons' },
        ['Satellite Horns'] = { Name='Satellite Horns', Ecosystem='unclassified', Family='animated weapons' },
        ['Satellite Knuckles'] = { Name='Satellite Knuckles', Ecosystem='unclassified', Family='animated weapons' },
        ['Satellite Kunai'] = { Name='Satellite Kunai', Ecosystem='unclassified', Family='animated weapons' },
        ['Satellite Longbows'] = { Name='Satellite Longbows', Ecosystem='unclassified', Family='animated weapons' },
        ['Satellite Longswords'] = { Name='Satellite Longswords', Ecosystem='unclassified', Family='animated weapons' },
        ['Satellite Scythes'] = { Name='Satellite Scythes', Ecosystem='unclassified', Family='animated weapons' },
        ['Satellite Shield'] = { Name='Satellite Shield', Ecosystem='unclassified', Family='animated weapons' },
        ['Satellite Spears'] = { Name='Satellite Spears', Ecosystem='unclassified', Family='animated weapons' },
        ['Satellite Staves'] = { Name='Satellite Staves', Ecosystem='unclassified', Family='animated weapons' },
        ['Satellite Tabars'] = { Name='Satellite Tabars', Ecosystem='unclassified', Family='animated weapons' },
        ['Satellite Tachi'] = { Name='Satellite Tachi', Ecosystem='unclassified', Family='animated weapons' },
        ['Serjeant Tombstone'] = { Name='Serjeant Tombstone', Ecosystem='unclassified', Family='replicas' },
        ['Statue Prototype'] = { Name='Statue Prototype', Ecosystem='unclassified', Family='replicas' },
        ['Tombstone Prototype'] = { Name='Tombstone Prototype', Ecosystem='unclassified', Family='replicas' },
        ['Vanguard Dragon'] = { Name='Vanguard Dragon', Ecosystem='dragons', Family='dragons' },
        ['Vanguard Eye'] = { Name='Vanguard Eye', Ecosystem='demons', Family='ahriman' },
        ['Yang'] = { Name='Yang', Ecosystem='dragons', Family='dragons' },
        ['Ying'] = { Name='Ying', Ecosystem='dragons', Family='dragons' },
        ['Zagan\'s Wyvern'] = { Name='Zagan\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
    },
};
