--Zone: Horlais Peak
--Zone ID: 139
return {
    Names = {
        ['Archer Pugil']                = { Name='Archer Pugil', Ecosystem='aquans', Family='pugils'},
        ['Aries']                       = { Name='Aries', Ecosystem='beasts', Family='rams'},
        ['Armsmaster Dekbuk']           = { Name='Armsmaster Dekbuk', Ecosystem='beastmen', Family='orcs'},
        ['Atori-Tutori ???']            = { Name='Atori-Tutori ???', Ecosystem='humanoids', Family='tarutarus'},
        ['Bisan']                       = { Name='Bisan', Ecosystem='vermin', Family='beetles'},
        ['Bonesetter Medokvok']         = { Name='Bonesetter Medokvok', Ecosystem='beastmen', Family='orcs'},
        ['Bruteborn Krushkosh']         = { Name='Bruteborn Krushkosh', Ecosystem='beastmen', Family='orcs'},
        ['Chest O\'Plenty']             = { Name='Chest O\'Plenty', Ecosystem='arcana', Family='mimics'},
        ['Chlevnik']                    = { Name='Chlevnik', Ecosystem='beasts', Family='behemoths'},
        ['Coffer O\'Plenty']            = { Name='Coffer O\'Plenty', Ecosystem='arcana', Family='mimics'},
        ['Compound Eyes']               = { Name='Compound Eyes', Ecosystem='amorphs', Family='hecteyes'},
        ['Cottontail']                  = { Name='Cottontail', Ecosystem='vermin', Family='rabbits'},
        ['Crackshot Zwogchog']          = { Name='Crackshot Zwogchog', Ecosystem='beastmen', Family='orcs'},
        ['Darokbok of Clan Reaper']     = { Name='Darokbok of Clan Reaper', Ecosystem='beastmen', Family='orcs'},
        ['Derakbak of Clan Wolf']       = { Name='Derakbak of Clan Wolf', Ecosystem='beastmen', Family='orcs'},
        ['Dragonian Berzerker']         = { Name='Dragonian Berzerker', Ecosystem='dragons', Family='dragons'},
        ['Dragonian Minstrel']          = { Name='Dragonian Minstrel', Ecosystem='dragons', Family='dragons'},
        ['Dragzagg\'s Wyvern']          = { Name='Dragzagg\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Dread Dragon']                = { Name='Dread Dragon', Ecosystem='dragons', Family='dragons'},
        ['Evil Oscar']                  = { Name='Evil Oscar', Ecosystem='plantoids', Family='morbols'},
        ['Fighting Sheep']              = { Name='Fighting Sheep', Ecosystem='beast', Family='sheep'},
        ['Gerjis']                      = { Name='Gerjis', Ecosystem='beast', Family='tigers'},
        ['Helltail Harry']              = { Name='Helltail Harry', Ecosystem='vermin', Family='rabbits'},
        ['Houndfly']                    = { Name='Houndfly', Ecosystem='vermin', Family='flies'},
        ['Huntfly']                     = { Name='Huntfly', Ecosystem='vermin', Family='flies'},
        ['Invulnerable Mazzgozz']       = { Name='Invulnerable Mazzgozz', Ecosystem='beastmen', Family='orcs'},
        ['Jagidbod of Clan Reaper']     = { Name='Jagidbod of Clan Reaper', Ecosystem='beastmen', Family='orcs'},
        ['Keeneyed Aufwuf']             = { Name='Keeneyed Aufwuf', Ecosystem='beastmen', Family='orcs'},
        ['Longarmed Gottditt']          = { Name='Longarmed Gottditt', Ecosystem='beastmen', Family='orcs'},
        ['Maat']                        = { Name='Maat', Ecosystem='humanoids', Family='humes'},
        ['Malodorous Mort']             = { Name='Malodorous Mort', Ecosystem='plantoids', Family='funguars'},
        ['Mind\'s-eyed Klugwug']        = { Name='Mind\'s-eyed Klugwug', Ecosystem='beastmen', Family='orcs'},
        ['Mortobello']                  = { Name='Mortobello', Ecosystem='plantoids', Family='funguars'},
        ['Orc\'s Wyvern']               = { Name='Orc\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Orcish Onager']               = { Name='Orcish Onager', Ecosystem='beastmen', Family='orcish warmachines'},
        ['Pilwiz']                      = { Name='Pilwiz', Ecosystem='vermin', Family='beetles'},
        ['Reaper Clan Warmachine']      = { Name='Reaper Clan Warmachine', Ecosystem='beastmen', Family='orcish warmachines'},
        ['Sniper Pugil']                = { Name='Sniper Pugil', Ecosystem='aquans', Family='pugils'},
        ['Sobbing Eyes']                = { Name='Sobbing Eyes', Ecosystem='amorphs', Family='hecteyes'},
        ['Spotter']                     = { Name='Spotter', Ecosystem='demons', Family='ahriman'},
        ['Undefeatable Sappdapp']       = { Name='Undefeatable Sappdapp', Ecosystem='beastmen', Family='orcs'},
        ['Wolf Clan Warmachine']        = { Name='Wolf Clan Warmachine', Ecosystem='beastmen', Family='orcish warmachines'},
        ['Wyvernkin Dragzagg']          = { Name='Wyvernkin Dragzagg', Ecosystem='beastmen', Family='orcs'},
    },
};
