--Zone: Ghelsba Outpost
--Zone ID: 140
return {
    Names = {
        ['Bloody Vrukwuk']          = { Name='Bloody Vrukwuk', Ecosystem='beastmen', Family='orcs'},
        ['Carrion Dragon']          = { Name='Carrion Dragon', Ecosystem='dragons', Family='dragons'},
        ['Cheiroptera']             = { Name='Cheiroptera', Ecosystem='birds', Family='bats'},
        ['Colo-colo']               = { Name='Colo-colo', Ecosystem='birds', Family='bats'},
        ['Cyranuce M Cutauleon']    = { Name='Cyranuce M Cutauleon', Ecosystem='dragons', Family='wyverns'},
        ['Fodderchief Vokdek']      = { Name='Fodderchief Vokdek', Ecosystem='beastmen', Family='orcs'},
        ['Fogweaver Mozzfuzz']      = { Name='Fogweaver Mozzfuzz', Ecosystem='beastmen', Family='orcs'},
        ['Furies']                  = { Name='Furies', Ecosystem='birds', Family='bat trios'},
        ['Ghelsba Pugil']           = { Name='Ghelsba Pugil', Ecosystem='aquans', Family='pugils'},
        ['Giant Pugil']             = { Name='Giant Pugil', Ecosystem='aquans', Family='pugils'},
        ['Kalamainu']               = { Name='Kalamainu', Ecosystem='lizards', Family='lizards'},
        ['Kilioa']                  = { Name='Kilioa', Ecosystem='lizards', Family='lizards'},
        ['Orcish Barricader']       = { Name='Orcish Barricader', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Fodder']           = { Name='Orcish Fodder', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Grappler']         = { Name='Orcish Grappler', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Grunt']            = { Name='Orcish Grunt', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Mesmerizer']       = { Name='Orcish Mesmerizer', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Neckchopper']      = { Name='Orcish Neckchopper', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Stonechucker']     = { Name='Orcish Stonechucker', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Stonelauncher']    = { Name='Orcish Stonelauncher', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Wallbreacher']     = { Name='Orcish Wallbreacher', Ecosystem='beastmen', Family='orcs'},
        ['Puffer Pugil']            = { Name='Puffer Pugil', Ecosystem='aquans', Family='pugils'},
        ['Pug Pugil']               = { Name='Pug Pugil', Ecosystem='aquans', Family='pugils'},
        ['Pugil']                   = { Name='Pugil', Ecosystem='aquans', Family='pugils'},
        ['Spectacled Bats']         = { Name='Spectacled Bats', Ecosystem='birds', Family='bat trios'},
        ['Strongarm Zodvad']        = { Name='Strongarm Zodvad', Ecosystem='beastmen', Family='orcs'},
        ['Sureshot Snatgat']        = { Name='Sureshot Snatgat', Ecosystem='beastmen', Family='orcs'},
        ['Thousandarm Deshglesh']   = { Name='Thousandarm Deshglesh', Ecosystem='beastmen', Family='orcs'},
        ['Toadbolster']             = { Name='Toadbolster', Ecosystem='plantoids', Family='funguars'},
        ['Toadcushion']             = { Name='Toadcushion', Ecosystem='plantoids', Family='funguars'},
        ['Toadpillow']              = { Name='Toadpillow', Ecosystem='plantoids', Family='funguars'},
        ['Toadsquab']               = { Name='Toadsquab', Ecosystem='plantoids', Family='funguars'},
        ['Toadstool']               = { Name='Toadstool', Ecosystem='plantoids', Family='funguars'},
        ['Warchief Vatgit']         = { Name='Warchief Vatgit', Ecosystem='beastmen', Family='orcs'},
        ['Watch Lizard']            = { Name='Watch Lizard', Ecosystem='lizards', Family='lizards'},
    },
};
