--Zone: Waughroon Shrine
--Zone ID: 144
return {
    Names = {
        ['Atori-Tutori ???']        = { Name='Atori-Tutori ???', Ecosystem='humanoids', Family='tarutaru'},
        ['Ayakashi']                = { Name='Ayakashi', Ecosystem='arcana', Family='avatars'},
        ['Bi\'Fho Jestergrin']      = { Name='Bi\'Fho Jestergrin', Ecosystem='beastmen', Family='quadav'},
        ['Chest O\'Plenty']         = { Name='Chest O\'Plenty', Ecosystem='arcana', Family='mimics'},
        ['Coffer O\'Plenty']        = { Name='Coffer O\'Plenty', Ecosystem='arcana', Family='mimics'},
        ['Da\'Shu Knightslayer']    = { Name='Da\'Shu Knightslayer', Ecosystem='beastmen', Family='quadav'},
        ['Dark Dragon']             = { Name='Dark Dragon', Ecosystem='dragons', Family='dragons'},
        ['Ea\'Tho Cruelheart']      = { Name='Ea\'Tho Cruelheart', Ecosystem='beastmen', Family='quadav'},
        ['Fe\'e']                   = { Name='Fe\'e', Ecosystem='aquans', Family='sea monks'},
        ['Flayer Franz']            = { Name='Flayer Franz', Ecosystem='amorphs', Family='worms'},
        ['Flesh Eater']             = { Name='Flesh Eater', Ecosystem='amorphs', Family='worms'},
        ['Gaki']                    = { Name='Gaki', Ecosystem='demons', Family='demons'},
        ['Go\'Bha Slaughterer']     = { Name='Go\'Bha Slaughterer', Ecosystem='beastmen', Family='quadav'},
        ['Heavy Metal Crab']        = { Name='Heavy Metal Crab', Ecosystem='aquans', Family='crabs'},
        ['Ka\'Nha Jabbertongue']    = { Name='Ka\'Nha Jabbertongue', Ecosystem='beastmen', Family='quadav'},
        ['Ku\'Jhu Graniteskin']     = { Name='Ku\'Jhu Graniteskin', Ecosystem='beastmen', Family='quadav'},
        ['Ku\'Tya Hotblood']        = { Name='Ku\'Tya Hotblood', Ecosystem='beastmen', Family='quadav'},
        ['Maat']                    = { Name='Maat', Ecosystem='humanoids', Family='humes'},
        ['Maat\'s Pet']             = { Name='Maat\'s Pet', Ecosystem='unclassified', Family='monsters'},
        ['Macha']                   = { Name='Macha', Ecosystem='birds', Family='birds'},
        ['Metal Crab']              = { Name='Metal Crab', Ecosystem='aquans', Family='crabs'},
        ['Metsanhaltija']           = { Name='Metsanhaltija', Ecosystem='plantoids', Family='saplings'},
        ['Metsanneitsyt']           = { Name='Metsanneitsyt', Ecosystem='plantoids', Family='saplings'},
        ['Neman']                   = { Name='Neman', Ecosystem='birds', Family='birds'},
        ['Onibi']                   = { Name='Onibi', Ecosystem='elementals', Family='elementals'},
        ['Onki']                    = { Name='Onki', Ecosystem='demons', Family='demons'},
        ['Osschaart']               = { Name='Osschaart', Ecosystem='demons', Family='ahriman'},
        ['Osschaart\'s Automaton']  = { Name='Osschaart\'s Automaton', Ecosystem='unclassified', Family='automatons'},
        ['Osschaart\'s Avatar']     = { Name='Osschaart\'s Avatar', Ecosystem='arcana', Family='avatars'},
        ['Osschaart\'s Bat']        = { Name='Osschaart\'s Bat', Ecosystem='birds', Family='bats'},
        ['Osschaart\'s Wyvern']     = { Name='Osschaart\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Platoon Scorpion']        = { Name='Platoon Scorpion', Ecosystem='vermin', Family='scorpions'},
        ['Princess Jelly']          = { Name='Princess Jelly', Ecosystem='amorphs', Family='slimes'},
        ['Queen Jelly']             = { Name='Queen Jelly', Ecosystem='amorphs', Family='slimes'},
        ['Rasetsu']                 = { Name='Rasetsu', Ecosystem='demons', Family='demons'},
        ['Sa\'Nha Soulsaver']       = { Name='Sa\'Nha Soulsaver', Ecosystem='beastmen', Family='quadav'},
        ['Seeker']                  = { Name='Seeker', Ecosystem='semons', Family='ahriman'},
        ['Tartaruga Gigante']       = { Name='Tartaruga Gigante', Ecosystem='lizards', Family='adamantoises'},
        ['The Waughroon Kid']       = { Name='The Waughroon Kid', Ecosystem='plantoids', Family='goobues'},
        ['Time Bomb']               = { Name='Time Bomb', Ecosystem='arcana', Family='bombs'},
        ['Titanis Dax']             = { Name='Titanis Dax', Ecosystem='birds', Family='rocs'},
        ['Titanis Jax']             = { Name='Titanis Jax', Ecosystem='birds', Family='rocs'},
        ['Titanis Max']             = { Name='Titanis Max', Ecosystem='birds', Family='rocs'},
        ['Titanis Xax']             = { Name='Titanis Xax', Ecosystem='birds', Family='rocs'},
        ['Yo\'Bhu Hideousmask']     = { Name='Yo\'Bhu Hideousmask', Ecosystem='beastmen', Family='quadav'},
        ['Zo\'Dhu Legslicer']       = { Name='Zo\'Dhu Legslicer', Ecosystem='beastmen', Family='quadav'},
    },
};
