--Zone: Balga's Dais
--Zone ID: 146
return {
    Names = {
        ['Aa Nawu the Thunderblade']    = { Name='Aa Nawu the Thunderblade', Ecosystem='beastmen', Family='yagudo'},
        ['Atori-Tutori ???']            = { Name='Atori-Tutori ???', Ecosystem='humanoids', Family='tarutarus'},
        ['Bitoso']                      = { Name='Bitoso', Ecosystem='vermin', Family='crawlers'},
        ['Black Dragon']                = { Name='Black Dragon', Ecosystem='dragons', Family='dragons'},
        ['Buu Xolo the Bloodfaced']     = { Name='Buu Xolo the Bloodfaced', Ecosystem='beastmen', Family='yagudo'},
        ['Chaa Paqa the Profound']      = { Name='Chaa Paqa the Profound', Ecosystem='beastmen', Family='yagudo'},
        ['Chest O\'Plenty']             = { Name='Chest O\'Plenty', Ecosystem='arcana', Family='mimics'},
        ['Coffer O\'Plenty']            = { Name='Coffer O\'Plenty', Ecosystem='arcana', Family='mimics'},
        ['Cuu Doko the Blizzard']       = { Name='Cuu Doko the Blizzard', Ecosystem='beastmen', Family='yagudo'},
        ['Domovoi']                     = { Name='Domovoi', Ecosystem='plantoids', Family='mandragoras'},
        ['Dromiceiomimus']              = { Name='Dromiceiomimus', Ecosystem='lizards', Family='raptors'},
        ['Dvorovoi']                    = { Name='Dvorovoi', Ecosystem='plantoids', Family='mandragoras'},
        ['Giant Moa']                   = { Name='Giant Moa', Ecosystem='birds', Family='cockatrices'},
        ['Gii Jaha the Raucous']        = { Name='Gii Jaha the Raucous', Ecosystem='beastmen', Family='yagudo'},
        ['Gilagoge Tlugvi']             = { Name='Gilagoge Tlugvi', Ecosystem='plantoids', Family='treants'},
        ['Goga Tlugvi']                 = { Name='Goga Tlugvi', Ecosystem='plantoids', Family='treants'},
        ['Gola Tlugvi']                 = { Name='Gola Tlugvi', Ecosystem='plantoids', Family='treants'},
        ['Juu Zeni the Poisonmist']     = { Name='Juu Zeni the Poisonmist', Ecosystem='beastmen', Family='yagudo'},
        ['Kaa Xehi the Doomsayer']      = { Name='Kaa Xehi the Doomsayer', Ecosystem='beastmen', Family='yagudo'},
        ['King of Batons']              = { Name='King of Batons', Ecosystem='arcana', Family='cardians'},
        ['King of Coins']               = { Name='King of Coins', Ecosystem='arcana', Family='cardians'},
        ['King of Cups']                = { Name='King of Cups', Ecosystem='arcana', Family='cardians'},
        ['King of Swords']              = { Name='King of Swords', Ecosystem='arcana', Family='cardians'},
        ['Kutkha']                      = { Name='Kutkha', Ecosystem='birds', Family='birds'},
        ['Kutkha\'s Get']               = { Name='Kutkha\'s Get', Ecosystem='birds', Family='birds'},
        ['Large Box']                   = { Name='Large Box', Ecosystem='arcana', Family='mimics'},
        ['Maat']                        = { Name='Maat', Ecosystem='humanoids', Family='humes'},
        ['Maat\'s Avatar']              = { Name='Maat\'s Avatar', Ecosystem='undefined', Family='monsters'},
        ['Macan Gadangan']              = { Name='Macan Gadangan', Ecosystem='beasts', Family='coeurls'},
        ['Medium Box']                  = { Name='Medium Box', Ecosystem='arcana', Family='mimics'},
        ['Myrmidon Apu-apu']            = { Name='Myrmidon Apu-apu', Ecosystem='beasts', Family='opo-opos'},
        ['Myrmidon Epa-epa']            = { Name='Myrmidon Epa-epa', Ecosystem='beasts', Family='opo-opos'},
        ['Myrmidon Spo-spo']            = { Name='Myrmidon Spo-spo', Ecosystem='beasts', Family='opo-opos'},
        ['Nenaunir']                    = { Name='Nenaunir', Ecosystem='beats', Family='dhahmels'},
        ['Nenaunir\'s Wife']            = { Name='Nenaunir\'s Wife', Ecosystem='beasts', Family='dhahmels'},
        ['Nuu Kofu the Gentle']         = { Name='Nuu Kofu the Gentle', Ecosystem='beastmen', Family='yagudo'},
        ['Opo-opo Heir']                = { Name='Opo-opo Heir', Ecosystem='beasts', Family='opo-opos'},
        ['Opo-opo Monarch']             = { Name='Opo-opo Monarch', Ecosystem='beasts', Family='opo-opos'},
        ['Pepper']                      = { Name='Pepper', Ecosystem='amorphs', Family='leeches'},
        ['Pha Groxo the Aloof']         = { Name='Pha Groxo the Aloof', Ecosystem='beastmen', Family='yagudo'},
        ['Phoedme']                     = { Name='Phoedme', Ecosystem='amorphs', Family='leeches'},
        ['Prune']                       = { Name='Prune', Ecosystem='amorphs', Family='leeches'},
        ['Queen of Batons']             = { Name='Queen of Batons', Ecosystem='arcana', Family='cardians'},
        ['Queen of Cups']               = { Name='Queen of Cups', Ecosystem='arcana', Family='cardians'},
        ['Searcher']                    = { Name='Searcher', Ecosystem='demons', Family='ahriman'},
        ['Small Box']                   = { Name='Small Box', Ecosystem='arcana', Family='mimics'},
        ['Ulagohvsdi Tlugvi']           = { Name='Ulagohvsdi Tlugvi', Ecosystem='plantoids', Family='treants'},
        ['Voo Tolu the Ghostfist']      = { Name='Voo Tolu the Ghostfist', Ecosystem='beastmen', Family='yagudo'},
        ['Wyrm']                        = { Name='Wyrm', Ecosystem='dragons', Family='wyrms'},
        ['Xee Khoyi the Shrouded']      = { Name='Xee Khoyi the Shrouded', Ecosystem='beastmen', Family='yagudo'},
        ['Yagudo\'s Avatar']            = { Name='Yagudo\'s Avatar', Ecosystem='undefined', Family='monsters'},
        ['Yagudo\'s Elemental']         = { Name='Yagudo\'s Elemental', Ecosystem='elementals', Family='elementals'},
        ['Yoo Mihi the Haze']           = { Name='Yoo Mihi the Haze', Ecosystem='beastmen', Family='yagudo'},
        ['Zuu Feya the Impassive']      = { Name='Zuu Feya the Impassive', Ecosystem='beastmen', Family='yagudo'},
        ['Zuu Xowu the Darksmoke']      = { Name='Zuu Xowu the Darksmoke', Ecosystem='beastmen', Family='yagudo'},
    },
};
