--Zone: Beadeaux
--Zone ID: 147
return {
    Names = {
        ['Ancient Quadav']          = { Name='Ancient Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Bi\'Gho Headtaker']       = { Name='Bi\'Gho Headtaker', Ecosystem='beastmen', Family='quadav'},
        ['Big Jaw']                 = { Name='Big Jaw', Ecosystem='aquans', Family='pugils'},
        ['Brass Quadav']            = { Name='Brass Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Bronze Quadav']           = { Name='Bronze Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Broo']                    = { Name='Broo', Ecosystem='beasts', Family='sheep'},
        ['Caterpillar']             = { Name='Caterpillar', Ecosystem='vermin', Family='crawlers'},
        ['Charging Sheep']          = { Name='Charging Sheep', Ecosystem='beast', Family='sheep'},
        ['Copper Quadav']           = { Name='Copper Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Da\'Dha Hundredmask']     = { Name='Da\'Dha Hundredmask', Ecosystem='beastmen', Family='quadav'},
        ['Darksteel Quadav']        = { Name='Darksteel Quadav', Ecosystem='beastmen', Family='quadav'},
        ['De\'Vyu Headhunter']      = { Name='De\'Vyu Headhunter', Ecosystem='beastmen', Family='quadav'},
        ['Elder Quadav']            = { Name='Elder Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Emerald Quadav']          = { Name='Emerald Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Ga\'Bhu Unvanquished']    = { Name='Ga\'Bhu Unvanquished', Ecosystem='beastmen', Family='quadav'},
        ['Garnet Quadav']           = { Name='Garnet Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Ge\'Dha Evileye']         = { Name='Ge\'Dha Evileye', Ecosystem='beastmen', Family='quadav'},
        ['Gloop']                   = { Name='Gloop', Ecosystem='amorphs', Family='slimes'},
        ['Go\'Bhu Gascon']          = { Name='Go\'Bhu Gascon', Ecosystem='beastmen', Family='quadav'},
        ['Gold Quadav']             = { Name='Gold Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Iron Quadav']             = { Name='Iron Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Land Pugil']              = { Name='Land Pugil', Ecosystem='aquans', Family='pugils'},
        ['Larva']                   = { Name='Larva', Ecosystem='vermin', Family='crawlers'},
        ['Magnes Quadav']           = { Name='Magnes Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Mimic']                   = { Name='Mimic', Ecosystem='arcana', Family='mimics'},
        ['Mythril Quadav']          = { Name='Mythril Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Nickel Quadav']           = { Name='Nickel Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Old Quadav']              = { Name='Old Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Ooze']                    = { Name='Ooze', Ecosystem='amorphs', Family='slimes'},
        ['Platinum Quadav']         = { Name='Platinum Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Sapphire Quadav']         = { Name='Sapphire Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Silver Quadav']           = { Name='Silver Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Spinel Quadav']           = { Name='Spinel Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Steel Quadav']            = { Name='Steel Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Thunder Elemental']       = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals'},
        ['Topaz Quadav']            = { Name='Topaz Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Water Elemental']         = { Name='Water Elemental', Ecosystem='elementals', Family='elementals'},
        ['Zircon Quadav']           = { Name='Zircon Quadav', Ecosystem='beastmen', Family='quadav'},
        ['Zo\'Khu Blackcloud']      = { Name='Zo\'Khu Blackcloud', Ecosystem='beastmen', Family='quadav'},
    },
};
