--Zone: Davoi
--Zone ID: 149
return {
    Names = {
        ['Barakbok']                = { Name='Barakbok', Ecosystem='beastmen', Family='orcs' },
        ['Bilopdop']                = { Name='Bilopdop', Ecosystem='beastmen', Family='orcs' },
        ['Blubbery Bulge']          = { Name='Blubbery Bulge', Ecosystem='amorphs', Family='slimes' },
        ['Davoi Hornet']            = { Name='Davoi Hornet', Ecosystem='vermin', Family='bees' },
        ['Davoi Mush']              = { Name='Davoi Mush', Ecosystem='amorphs', Family='slimes' },
        ['Davoi Pugil']             = { Name='Davoi Pugil', Ecosystem='aquans', Family='pugils' },
        ['Davoi Wasp']              = { Name='Davoi Wasp', Ecosystem='vermin', Family='bees' },
        ['Deloknok']                = { Name='Deloknok', Ecosystem='beastmen', Family='orcs' },
        ['Dirtyhanded Gochakzuk']   = { Name='Dirtyhanded Gochakzuk', Ecosystem='beastmen', Family='orcs' },
        ['Ferocious Pugil']         = { Name='Ferocious Pugil', Ecosystem='aquans', Family='pugils' },
        ['Gavotvut']                = { Name='Gavotvut', Ecosystem='beastmen', Family='orcs' },
        ['Geezard']                 = { Name='Geezard', Ecosystem='lizards', Family='lizards' },
        ['Gloop']                   = { Name='Gloop', Ecosystem='amorphs', Family='slimes' },
        ['Greater Pugil']           = { Name='Greater Pugil', Ecosystem='aquans', Family='pugils' },
        ['Hawkeyed Dnatbat']        = { Name='Hawkeyed Dnatbat', Ecosystem='beastmen', Family='orcs' },
        ['Hematic Cyst']            = { Name='Hematic Cyst', Ecosystem='amorphs', Family='slimes' },
        ['Morbol']                  = { Name='Morbol', Ecosystem='plantoids', Family='morbols' },
        ['Oil Spill']               = { Name='Oil Spill', Ecosystem='amorphs', Family='slimes' },
        ['One-eyed Gwajboj']        = { Name='One-eyed Gwajboj', Ecosystem='beastmen', Family='orcs' },
        ['Orc\'s Wyvern']           = { Name='Orc\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Orcish Beastrider']       = { Name='Orcish Beastrider', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Bowshooter']       = { Name='Orcish Bowshooter', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Brawler']          = { Name='Orcish Brawler', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Champion']         = { Name='Orcish Champion', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Cursemaker']       = { Name='Orcish Cursemaker', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Dragoon']          = { Name='Orcish Dragoon', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Dreadnought']      = { Name='Orcish Dreadnought', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Farkiller']        = { Name='Orcish Farkiller', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Fighter']          = { Name='Orcish Fighter', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Firebelcher']      = { Name='Orcish Firebelcher', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Footsoldier']      = { Name='Orcish Footsoldier', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Gladiator']        = { Name='Orcish Gladiator', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Impaler']          = { Name='Orcish Impaler', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Nightraider']      = { Name='Orcish Nightraider', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Predator']         = { Name='Orcish Predator', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Serjeant']         = { Name='Orcish Serjeant', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Trooper']          = { Name='Orcish Trooper', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Veteran']          = { Name='Orcish Veteran', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Warchief']         = { Name='Orcish Warchief', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Zerker']           = { Name='Orcish Zerker', Ecosystem='beastmen', Family='orcs' },
        ['Poisonhand Gnadgad']      = { Name='Poisonhand Gnadgad', Ecosystem='beastmen', Family='orcs' },
        ['Purpleflash Brukdok']     = { Name='Purpleflash Brukdok', Ecosystem='beastmen', Family='orcs' },
        ['Steelbiter Gudrud']       = { Name='Steelbiter Gudrud', Ecosystem='beastmen', Family='orcs' },
        ['Three-eyed Prozpuz']      = { Name='Three-eyed Prozpuz', Ecosystem='beastmen', Family='orcs' },
        ['Thunder Elemental']       = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
        ['Tigerbane Bakdak']        = { Name='Tigerbane Bakdak', Ecosystem='beastmen', Family='orcs' },
        ['War Lizard']              = { Name='War Lizard', Ecosystem='lizards', Family='lizards' },
        ['Water Elemental']         = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
        ['Wolf Bat']                = { Name='Wolf Bat', Ecosystem='birds', Family='bats' },
        ['Wood Bats']               = { Name='Wood Bats', Ecosystem='birds', Family='bat trios' },
    },
};
