--Zone: Castle Oztroja
--Zone ID: 151
return {
    Names = {
        ['Bastion Bats']            = { Name='Bastion Bats', Ecosystem='birds', Family='bat trios' },
        ['Bulwark Bat']             = { Name='Bulwark Bat', Ecosystem='birds', Family='bats' },
        ['Cutter']                  = { Name='Cutter', Ecosystem='aquans', Family='crabs' },
        ['Earth Elemental']         = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Fire Elemental']          = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals' },
        ['Huu Xalmo the Savage']    = { Name='Huu Xalmo the Savage', Ecosystem='beastmen', Family='yagudo' },
        ['Lii Jixa the Somnolist']  = { Name='Lii Jixa the Somnolist', Ecosystem='beastmen', Family='yagudo' },
        ['Meat Maggot']             = { Name='Meat Maggot', Ecosystem='amorphs', Family='leeches' },
        ['Mee Deggi the Punisher']  = { Name='Mee Deggi the Punisher', Ecosystem='beastmen', Family='yagudo' },
        ['Mimic']                   = { Name='Mimic', Ecosystem='arcana', Family='mimics' },
        ['Moo Ouzi the Swiftblade'] = { Name='Moo Ouzi the Swiftblade', Ecosystem='beastmen', Family='yagudo' },
        ['Odontotyrannus']          = { Name='Odontotyrannus', Ecosystem='aquans', Family='pugils' },
        ['Ooze']                    = { Name='Ooze', Ecosystem='amorphs', Family='slimes' },
        ['Quu Domi the Gallant']    = { Name='Quu Domi the Gallant', Ecosystem='beastmen', Family='yagudo' },
        ['Saa Doyi the Fervid']     = { Name='Saa Doyi the Fervid', Ecosystem='beastmen', Family='yagudo' },
        ['Tzee Xicu the Manifest']  = { Name='Tzee Xicu the Manifest', Ecosystem='beastmen', Family='yagudo' },
        ['Yaa Haqa the Profane']    = { Name='Yaa Haqa the Profane', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Abbot']            = { Name='Yagudo Abbot', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Assassin']         = { Name='Yagudo Assassin', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Avatar']           = { Name='Yagudo Avatar', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Chanter']          = { Name='Yagudo Chanter', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Conductor']        = { Name='Yagudo Conductor', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Conquistador']     = { Name='Yagudo Conquistador', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Drummer']          = { Name='Yagudo Drummer', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Flagellant']       = { Name='Yagudo Flagellant', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Herald']           = { Name='Yagudo Herald', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo High Priest']      = { Name='Yagudo High Priest', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Inquisitor']       = { Name='Yagudo Inquisitor', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Interrogator']     = { Name='Yagudo Interrogator', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Lutenist']         = { Name='Yagudo Lutenist', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Muralist']         = { Name='Yagudo Muralist', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Oracle']           = { Name='Yagudo Oracle', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Parasite']         = { Name='Yagudo Parasite', Ecosystem='amorphs', Family='leeches' },
        ['Yagudo Prelate']          = { Name='Yagudo Prelate', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Priest']           = { Name='Yagudo Priest', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Prior']            = { Name='Yagudo Prior', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Sentinel']         = { Name='Yagudo Sentinel', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Templar']          = { Name='Yagudo Templar', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Theologist']       = { Name='Yagudo Theologist', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Votary']           = { Name='Yagudo Votary', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Zealot']           = { Name='Yagudo Zealot', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo\'s Avatar']        = { Name='Yagudo\'s Avatar', Ecosystem='undefined', Family='monsters' },
        ['Yagudo\'s Elemental']     = { Name='Yagudo\'s Elemental', Ecosystem='elementals', Family='elementals' },
    },
};
