--Zone: The Boyahda Tree
--Zone ID: 153
return {
    Names = {
        ['Agas']                    = { Name='Agas', Ecosystem='birds', Family='bats' },
        ['Ancient Goobbue']         = { Name='Ancient Goobbue', Ecosystem='plantoids', Family='goobues' },
        ['Aquarius']                = { Name='Aquarius', Ecosystem='aquans', Family='crabs' },
        ['Ayapec']                  = { Name='Ayapec', Ecosystem='aquans', Family='crabs' },
        ['Bark Spider']             = { Name='Bark Spider', Ecosystem='vermin', Family='spiders' },
        ['Bark Tarantula']          = { Name='Bark Tarantula', Ecosystem='vermin', Family='spiders' },
        ['Beet Leafhopper']         = { Name='Beet Leafhopper', Ecosystem='vermin', Family='flies' },
        ['Blood Ball']              = { Name='Blood Ball', Ecosystem='amorphs', Family='leeches' },
        ['Bouncing Ball']           = { Name='Bouncing Ball', Ecosystem='amorphs', Family='leeches' },
        ['Boyahda Sapling']         = { Name='Boyahda Sapling', Ecosystem='plantoids', Family='saplings' },
        ['Darter']                  = { Name='Darter', Ecosystem='vermin', Family='flies' },
        ['Death Cap']               = { Name='Death Cap', Ecosystem='plantoids', Family='funguars' },
        ['Demonic Pugil']           = { Name='Demonic Pugil', Ecosystem='aquans', Family='pugils' },
        ['Demonic Rose']            = { Name='Demonic Rose', Ecosystem='plantoids', Family='morbols' },
        ['Elder Goobbue']           = { Name='Elder Goobbue', Ecosystem='plantoids', Family='goobues' },
        ['Ellyllon']                = { Name='Ellyllon', Ecosystem='plantoids', Family='funguars' },
        ['Hidhaegg']                = { Name='Hidhaegg', Ecosystem='dragons', Family='wyrms' },
        ['Knight Crawler']          = { Name='Knight Crawler', Ecosystem='vermin', Family='crawlers' },
        ['Korrigan']                = { Name='Korrigan', Ecosystem='plantoids', Family='mandragoras' },
        ['Leshonki']                = { Name='Leshonki', Ecosystem='plantoids', Family='saplings' },
        ['Mimic']                   = { Name='Mimic', Ecosystem='arcana', Family='mimics' },
        ['Modron']                  = { Name='Modron', Ecosystem='plantoids', Family='treants' },
        ['Modron\'s Druid']         = { Name='Modron\'s Druid', Ecosystem='plantoids', Family='treants' },
        ['Morbol Menace']           = { Name='Morbol Menace', Ecosystem='plantoids', Family='morbols' },
        ['Moss Eater']              = { Name='Moss Eater', Ecosystem='vermin', Family='rabbits' },
        ['Mourioche']               = { Name='Mourioche', Ecosystem='plantoids', Family='mandragoras' },
        ['Mourning Crawler']        = { Name='Mourning Crawler', Ecosystem='vermin', Family='crawlers' },
        ['Old Goobbue']             = { Name='Old Goobbue', Ecosystem='plantoids', Family='goobues' },
        ['Processionaire']          = { Name='Processionaire', Ecosystem='vermin', Family='crawlers' },
        ['Robber Crab']             = { Name='Robber Crab', Ecosystem='aquans', Family='crabs' },
        ['Scavenger Crab']          = { Name='Scavenger Crab', Ecosystem='aquans', Family='crabs' },
        ['Skimmer']                 = { Name='Skimmer', Ecosystem='vermin', Family='flies' },
        ['Snaggletooth Peapuk']     = { Name='Snaggletooth Peapuk', Ecosystem='dragons', Family='puks' },
        ['Steelshell']              = { Name='Steelshell', Ecosystem='aquans', Family='crabs' },
        ['Stygian Pugil']           = { Name='Stygian Pugil', Ecosystem='aquans', Family='pugils' },
        ['Thunder Elemental']       = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
        ['Unut']                    = { Name='Unut', Ecosystem='vermin', Family='rabbits' },
        ['Viseclaw']                = { Name='Viseclaw', Ecosystem='aquans', Family='crabs' },
        ['Voluptuous Vivian']       = { Name='Voluptuous Vivian', Ecosystem='plantoids', Family='morbols' },
        ['Water Elemental']         = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
    },
};
