--Zone: Middle Delkfutt's Tower
--Zone ID: 157
return {
    Names = {
        ['Banshee'] = { Name='Banshee', Ecosystem='undead', Family='ghosts' },
        ['Big Bat'] = { Name='Big Bat', Ecosystem='birds', Family='bats' },
        ['Eurytos'] = { Name='Eurytos', Ecosystem='beastmen', Family='gigas' },
        ['Evil Spirit'] = { Name='Evil Spirit', Ecosystem='undead', Family='ghosts' },
        ['Gerwitz\'s Scythe'] = { Name='Gerwitz\'s Scythe', Ecosystem='arcana', Family='evil weapons' },
        ['Giant Gatekeeper'] = { Name='Giant Gatekeeper', Ecosystem='beastmen', Family='gigas' },
        ['Giant Guard'] = { Name='Giant Guard', Ecosystem='beastmen', Family='gigas' },
        ['Giant Lobber'] = { Name='Giant Lobber', Ecosystem='beastmen', Family='gigas' },
        ['Giant Sentry'] = { Name='Giant Sentry', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Jailer'] = { Name='Gigas Jailer', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Kettlemaster'] = { Name='Gigas Kettlemaster', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Quarrier'] = { Name='Gigas Quarrier', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Wallwatcher'] = { Name='Gigas Wallwatcher', Ecosystem='beastmen', Family='gigas' },
        ['Gigas\'s Bat'] = { Name='Gigas\'s Bat', Ecosystem='birds', Family='bat trios' },
        ['Gigas\'s Bats'] = { Name='Gigas\'s Bats', Ecosystem='birds', Family='bat trios' },
        ['Goblin Furrier'] = { Name='Goblin Furrier', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Pathfinder'] = { Name='Goblin Pathfinder', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Shaman'] = { Name='Goblin Shaman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Smithy'] = { Name='Goblin Smithy', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Bat'] = { Name='Goblin\'s Bat', Ecosystem='birds', Family='bats' },
        ['Jagd Doll'] = { Name='Jagd Doll', Ecosystem='arcana', Family='dolls' },
        ['Light Elemental'] = { Name='Light Elemental', Ecosystem='elementals', Family='elementals' },
        ['Magic Jar'] = { Name='Magic Jar', Ecosystem='arcana', Family='magic pots' },
        ['Magic Pot'] = { Name='Magic Pot', Ecosystem='arcana', Family='magic pots' },
        ['Mold Bats'] = { Name='Mold Bats', Ecosystem='birds', Family='bat trios' },
        ['Ogygos'] = { Name='Ogygos', Ecosystem='beastmen', Family='gigas' },
        ['Ophion'] = { Name='Ophion', Ecosystem='beastmen', Family='gigas' },
        ['Panzer Doll'] = { Name='Panzer Doll', Ecosystem='arcana', Family='dolls' },
        ['Polybotes'] = { Name='Polybotes', Ecosystem='beastmen', Family='gigas' },
        ['Rhoikos'] = { Name='Rhoikos', Ecosystem='beastmen', Family='gigas' },
        ['Rhoitos'] = { Name='Rhoitos', Ecosystem='beastmen', Family='gigas' },
        ['Scythe Victim'] = { Name='Scythe Victim', Ecosystem='undead', Family='skeletons' },
        ['Stirge'] = { Name='Stirge', Ecosystem='birds', Family='bats' },
        ['Thunder Elemental'] = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
        ['Tower Bats'] = { Name='Tower Bats', Ecosystem='birds', Family='bat trios' },
    },
};
