--Zone: Temple of Uggalepih
--Zone ID: 159
return {
    Names = {
        ['Azure-toothed Clawberry'] = { Name='Azure-toothed Clawberry', Ecosystem='beastmen', Family='tonberries' },
        ['Beryl-footed Molberry'] = { Name='Beryl-footed Molberry', Ecosystem='beastmen', Family='tonberries' },
        ['Bloodsucker'] = { Name='Bloodsucker', Ecosystem='amorphs', Family='leeches' },
        ['Bonze Marberry'] = { Name='Bonze Marberry', Ecosystem='beastmen', Family='tonberries' },
        ['Bouncing Ball'] = { Name='Bouncing Ball', Ecosystem='amorphs', Family='leeches' },
        ['Branding Iron'] = { Name='Branding Iron', Ecosystem='arcana', Family='dolls' },
        ['Clawberry\'s Avatar'] = { Name='Clawberry\'s Avatar', Ecosystem='unclassified', Family='monsters' },
        ['Clawberry\'s Elemental'] = { Name='Clawberry\'s Elemental', Ecosystem='elementals', Family='elementals' },
        ['Cleuvarion M Resoaix'] = { Name='Cleuvarion M Resoaix', Ecosystem='undead', Family='shadows' },
        ['Cook Fulberry'] = { Name='Cook Fulberry', Ecosystem='beastmen', Family='tonberries' },
        ['Cook Minberry'] = { Name='Cook Minberry', Ecosystem='beastmen', Family='tonberries' },
        ['Cook Nalberry'] = { Name='Cook Nalberry', Ecosystem='beastmen', Family='tonberries' },
        ['Cook Solberry'] = { Name='Cook Solberry', Ecosystem='beastmen', Family='tonberries' },
        ['Crimson-toothed Pawberry'] = { Name='Crimson-toothed Pawberry', Ecosystem='beastmen', Family='tonberries' },
        ['Death from Above'] = { Name='Death from Above', Ecosystem='vermin', Family='bees' },
        ['Fire Elemental'] = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals' },
        ['Flauros'] = { Name='Flauros', Ecosystem='beasts', Family='coeurls' },
        ['Habetrot'] = { Name='Habetrot', Ecosystem='vermin', Family='crawler' },
        ['Hover Tank'] = { Name='Hover Tank', Ecosystem='arcana', Family='magic pots' },
        ['Iron Maiden'] = { Name='Iron Maiden', Ecosystem='arcana', Family='dolls' },
        ['Manipulator'] = { Name='Manipulator', Ecosystem='arcana', Family='dolls' },
        ['Mimic'] = { Name='Mimic', Ecosystem='arcana', Family='mimics' },
        ['Neith'] = { Name='Neith', Ecosystem='vermin', Family='diremites' },
        ['Neith\'s Bobbin'] = { Name='Neith\'s Bobbin', Ecosystem='vermin', Family='spiders' },
        ['Nio-A'] = { Name='Nio-A', Ecosystem='arcana', Family='dolls' },
        ['Nio-Hum'] = { Name='Nio-Hum', Ecosystem='arcana', Family='dolls' },
        ['Rompaulion S Citalle'] = { Name='Rompaulion S Citalle', Ecosystem='undead', Family='shadows' },
        ['Rumble Crawler'] = { Name='Rumble Crawler', Ecosystem='vermin', Family='crawler' },
        ['Sacrificial Goblet'] = { Name='Sacrificial Goblet', Ecosystem='arcana', Family='magic pots' },
        ['Sozu Rogberry'] = { Name='Sozu Rogberry', Ecosystem='beastmen', Family='tonberries' },
        ['Sozu Sarberry'] = { Name='Sozu Sarberry', Ecosystem='beastmen', Family='tonberries' },
        ['Sozu Terberry'] = { Name='Sozu Terberry', Ecosystem='beastmen', Family='tonberries' },
        ['Temple Bee'] = { Name='Temple Bee', Ecosystem='vermin', Family='bees' },
        ['Temple Guardian'] = { Name='Temple Guardian', Ecosystem='arcana', Family='dolls' },
        ['Temple Opo-opo'] = { Name='Temple Opo-opo', Ecosystem='beasts', Family='opo-opos' },
        ['Tonberry Cutter'] = { Name='Tonberry Cutter', Ecosystem='beastmen', Family='tonberries' },
        ['Tonberry Dismayer'] = { Name='Tonberry Dismayer', Ecosystem='beastmen', Family='tonberries' },
        ['Tonberry Harrier'] = { Name='Tonberry Harrier', Ecosystem='beastmen', Family='tonberries' },
        ['Tonberry Kinq'] = { Name='Tonberry Kinq', Ecosystem='beastmen', Family='tonberries' },
        ['Tonberry Maledictor'] = { Name='Tonberry Maledictor', Ecosystem='beastmen', Family='tonberries' },
        ['Tonberry Pursuer'] = { Name='Tonberry Pursuer', Ecosystem='beastmen', Family='tonberries' },
        ['Tonberry Stabber'] = { Name='Tonberry Stabber', Ecosystem='beastmen', Family='tonberries' },
        ['Tonberry Stalker'] = { Name='Tonberry Stalker', Ecosystem='beastmen', Family='tonberries' },
        ['Tonberry\'s Avatar'] = { Name='Tonberry\'s Avatar', Ecosystem='arcana', Family='avatars' },
        ['Tonberry\'s Elemental'] = { Name='Tonberry\'s Elemental', Ecosystem='elementals', Family='elementals' },
        ['Torama'] = { Name='Torama', Ecosystem='beasts', Family='coeurls' },
        ['Trompe L\'Oeil'] = { Name='Trompe L\'Oeil', Ecosystem='arcana', Family='golems' },
        ['Uggalepih Leech'] = { Name='Uggalepih Leech', Ecosystem='amorphs', Family='leeches' },
        ['Water Elemental'] = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
        ['Wespe'] = { Name='Wespe', Ecosystem='vermin', Family='bees' },
        ['Yallery Brown'] = { Name='Yallery Brown', Ecosystem='plantoids', Family='saplings' },
    },
};
