--Zone: Den of Rancor
--Zone ID: 160
return {
    Names = {
        ['Azrael'] = { Name='Azrael', Ecosystem='amorphs', Family='hecteyes' },
        ['Bifrons'] = { Name='Bifrons', Ecosystem='arcana', Family='bombs' },
        ['Bistre-hearted Malberry'] = { Name='Bistre-hearted Malberry', Ecosystem='beastmen', Family='tonberries' },
        ['Bloodsucker'] = { Name='Bloodsucker', Ecosystem='amorphs', Family='leeches' },
        ['Bullbeggar'] = { Name='Bullbeggar', Ecosystem='beasts', Family='opo-opos' },
        ['Carmine-tailed Janberry'] = { Name='Carmine-tailed Janberry', Ecosystem='beastmen', Family='tonberries' },
        ['Cave Worm'] = { Name='Cave Worm', Ecosystem='amorphs', Family='worms' },
        ['Celeste-eyed Tozberry'] = { Name='Celeste-eyed Tozberry', Ecosystem='beastmen', Family='tonberries' },
        ['Cutlass Scorpion'] = { Name='Cutlass Scorpion', Ecosystem='vermin', Family='scorpions' },
        ['Demonic Pugil'] = { Name='Demonic Pugil', Ecosystem='aquans', Family='pugils' },
        ['Den Scorpion'] = { Name='Den Scorpion', Ecosystem='vermin', Family='scorpions' },
        ['Dire Bat'] = { Name='Dire Bat', Ecosystem='birds', Family='bats' },
        ['Doom Toad'] = { Name='Doom Toad', Ecosystem='undead', Family='doomed' },
        ['Fire Elemental'] = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals' },
        ['Friar Rush'] = { Name='Friar Rush', Ecosystem='arcana', Family='bombs' },
        ['Hakutaku'] = { Name='Hakutaku', Ecosystem='amorphs', Family='hecteyes' },
        ['Million Eyes'] = { Name='Million Eyes', Ecosystem='amorphs', Family='hecteyes' },
        ['Mimic'] = { Name='Mimic', Ecosystem='arcana', Family='mimics' },
        ['Mokumokuren'] = { Name='Mokumokuren', Ecosystem='amorphs', Family='hecteyes' },
        ['Mousse'] = { Name='Mousse', Ecosystem='amorphs', Family='slimes' },
        ['Ogama'] = { Name='Ogama', Ecosystem='undead', Family='doomed' },
        ['Puck'] = { Name='Puck', Ecosystem='plantoids', Family='mandragoras' },
        ['Rancor Torch'] = { Name='Rancor Torch', Ecosystem='arcana', Family='bombs' },
        ['Razorjaw Pugil'] = { Name='Razorjaw Pugil', Ecosystem='aquans', Family='pugils' },
        ['Rock Crab'] = { Name='Rock Crab', Ecosystem='aquans', Family='crabs' },
        ['Sozu Bliberry'] = { Name='Sozu Bliberry', Ecosystem='beastmen', Family='tonberries' },
        ['Succubus Bats'] = { Name='Succubus Bats', Ecosystem='birds', Family='bat trios' },
        ['Tawny-fingered Mugberry'] = { Name='Tawny-fingered Mugberry', Ecosystem='beastmen', Family='tonberries' },
        ['Tonberry Beleaguerer'] = { Name='Tonberry Beleaguerer', Ecosystem='beastmen', Family='tonberries' },
        ['Tonberry Decapitator'] = { Name='Tonberry Decapitator', Ecosystem='beastmen', Family='tonberries' },
        ['Tonberry Imprecator'] = { Name='Tonberry Imprecator', Ecosystem='beastmen', Family='tonberries' },
        ['Tonberry Pontifex'] = { Name='Tonberry Pontifex', Ecosystem='beastmen', Family='tonberries' },
        ['Tonberry Slasher'] = { Name='Tonberry Slasher', Ecosystem='beastmen', Family='tonberries' },
        ['Tonberry Tracker'] = { Name='Tonberry Tracker', Ecosystem='beastmen', Family='tonberries' },
        ['Tonberry Trailer'] = { Name='Tonberry Trailer', Ecosystem='beastmen', Family='tonberries' },
        ['Tonberry\'s Elemental'] = { Name='Tonberry\'s Elemental', Ecosystem='elementals', Family='elementals' },
        ['Tormentor'] = { Name='Tormentor', Ecosystem='lizards', Family='lizards' },
        ['Water Elemental'] = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
    },
};
