--Zone: Castle Zvahl Baileys
--Zone ID: 161
return {
    Names = {
        ['Abyssal Demon'] = { Name='Abyssal Demon', Ecosystem='demons', Family='demons' },
        ['Ahriman'] = { Name='Ahriman', Ecosystem='demons', Family='ahriman' },
        ['Arch Demon'] = { Name='Arch Demon', Ecosystem='demons', Family='demons' },
        ['Blood Demon'] = { Name='Blood Demon', Ecosystem='demons', Family='demons' },
        ['Dark Elemental'] = { Name='Dark Elemental', Ecosystem='elementals', Family='elementals' },
        ['Dark Spark'] = { Name='Dark Spark', Ecosystem='elementals', Family='elementals' },
        ['Demon Banneret'] = { Name='Demon Banneret', Ecosystem='demons', Family='demons' },
        ['Demon Chancellor'] = { Name='Demon Chancellor', Ecosystem='demons', Family='demons' },
        ['Demon Commander'] = { Name='Demon Commander', Ecosystem='demons', Family='demons' },
        ['Demon General'] = { Name='Demon General', Ecosystem='demons', Family='demons' },
        ['Demon Knight'] = { Name='Demon Knight', Ecosystem='demons', Family='demons' },
        ['Demon Magistrate'] = { Name='Demon Magistrate', Ecosystem='demons', Family='demons' },
        ['Demon Pawn'] = { Name='Demon Pawn', Ecosystem='demons', Family='demons' },
        ['Demon Secretary'] = { Name='Demon Secretary', Ecosystem='demons', Family='demons' },
        ['Demon Warlock'] = { Name='Demon Warlock', Ecosystem='demons', Family='demons' },
        ['Demon Wizard'] = { Name='Demon Wizard', Ecosystem='demons', Family='demons' },
        ['Demon\'s Avatar'] = { Name='Demon\'s Avatar', Ecosystem='elementals', Family='elementals' },
        ['Demon\'s Elemental'] = { Name='Demon\'s Elemental', Ecosystem='elementals', Family='elementals' },
        ['Doom Demon'] = { Name='Doom Demon', Ecosystem='demons', Family='demons' },
        ['Dread Demon'] = { Name='Dread Demon', Ecosystem='demons', Family='demons' },
        ['Duke Haborym'] = { Name='Duke Haborym', Ecosystem='demons', Family='demons' },
        ['Elder Quadav'] = { Name='Elder Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Emerald Quadav'] = { Name='Emerald Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Evil Eye'] = { Name='Evil Eye', Ecosystem='demons', Family='ahriman' },
        ['Goblin Poacher'] = { Name='Goblin Poacher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Reaper'] = { Name='Goblin Reaper', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Robber'] = { Name='Goblin Robber', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Trader'] = { Name='Goblin Trader', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Bats'] = { Name='Goblin\'s Bats', Ecosystem='birds', Family='bat trios' },
        ['Gore Demon'] = { Name='Gore Demon', Ecosystem='demons', Family='demons' },
        ['Grand Duke Batym'] = { Name='Grand Duke Batym', Ecosystem='demons', Family='demons' },
        ['Ice Elemental'] = { Name='Ice Elemental', Ecosystem='elementals', Family='elementals' },
        ['Iron Quadav'] = { Name='Iron Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Judicator Demon'] = { Name='Judicator Demon', Ecosystem='demons', Family='demons' },
        ['Likho'] = { Name='Likho', Ecosystem='demons', Family='ahriman' },
        ['Marquis Allocen'] = { Name='Marquis Allocen', Ecosystem='demons', Family='demons' },
        ['Marquis Amon'] = { Name='Marquis Amon', Ecosystem='demons', Family='demons' },
        ['Marquis Andrealphus'] = { Name='Marquis Andrealphus', Ecosystem='demons', Family='demons' },
        ['Marquis Naberius'] = { Name='Marquis Naberius', Ecosystem='demons', Family='demons' },
        ['Marquis Sabnock'] = { Name='Marquis Sabnock', Ecosystem='demons', Family='demons' },
        ['Mimic'] = { Name='Mimic', Ecosystem='amorphs', Family='mimics' },
        ['Morbid Eye'] = { Name='Morbid Eye', Ecosystem='demons', Family='ahriman' },
        ['Orcish Bowshooter'] = { Name='Orcish Bowshooter', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Footsoldier'] = { Name='Orcish Footsoldier', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Gladiator'] = { Name='Orcish Gladiator', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Trooper'] = { Name='Orcish Trooper', Ecosystem='beastmen', Family='orcs' },
        ['Spinel Quadav'] = { Name='Spinel Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Stygian Demon'] = { Name='Stygian Demon', Ecosystem='demons', Family='demons' },
        ['Yagudo Conquistador'] = { Name='Yagudo Conquistador', Ecosystem='beastmen', Family='yugado' },
        ['Yagudo Lutenist'] = { Name='Yagudo Lutenist', Ecosystem='beastmen', Family='yugado' },
        ['Yagudo Prior'] = { Name='Yagudo Prior', Ecosystem='beastmen', Family='yugado' },
        ['Yagudo Zealot'] = { Name='Yagudo Zealot', Ecosystem='beastmen', Family='yugado' },
    },
};
