--Zone: Castle Zvahl Keep
--Zone ID: 162
return {
    Names = {
        ['Baron Vapula'] = { Name='Baron Vapula', Ecosystem='demons', Family='demons' },
        ['Baronet Romwe'] = { Name='Baronet Romwe', Ecosystem='demons', Family='demons' },
        ['Count Bifrons'] = { Name='Count Bifrons', Ecosystem='demons', Family='demons' },
        ['Deadly Iris'] = { Name='Deadly Iris', Ecosystem='demons', Family='ahriman' },
        ['Demon Knight'] = { Name='Demon Knight', Ecosystem='demons', Family='demons' },
        ['Demon Pawn'] = { Name='Demon Pawn', Ecosystem='demons', Family='demons' },
        ['Demon Warlock'] = { Name='Demon Warlock', Ecosystem='demons', Family='demons' },
        ['Demon Wizard'] = { Name='Demon Wizard', Ecosystem='demons', Family='demons' },
        ['Demon\'s Avatar'] = { Name='Demon\'s Avatar', Ecosystem='elementals', Family='elementals' },
        ['Demon\'s Elemental'] = { Name='Demon\'s Elemental', Ecosystem='elementals', Family='elementals' },
        ['Elder Quadav'] = { Name='Elder Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Emerald Quadav'] = { Name='Emerald Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Evil Eye'] = { Name='Evil Eye', Ecosystem='demons', Family='ahriman' },
        ['Goblin Bouncer'] = { Name='Goblin Bouncer', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Enchanter'] = { Name='Goblin Enchanter', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Hunter'] = { Name='Goblin Hunter', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Poacher'] = { Name='Goblin Poacher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Reaper'] = { Name='Goblin Reaper', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Robber'] = { Name='Goblin Robber', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Trader'] = { Name='Goblin Trader', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Bat'] = { Name='Goblin\'s Bat', Ecosystem='birds', Family='bats' },
        ['Gold Quadav'] = { Name='Gold Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Iron Quadav'] = { Name='Iron Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Morbid Eye'] = { Name='Morbid Eye', Ecosystem='demons', Family='ahriman' },
        ['Mythril Quadav'] = { Name='Mythril Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Orcish Bowshooter'] = { Name='Orcish Bowshooter', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Footsoldier'] = { Name='Orcish Footsoldier', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Gladiator'] = { Name='Orcish Gladiator', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Predator'] = { Name='Orcish Predator', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Trooper'] = { Name='Orcish Trooper', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Veteran'] = { Name='Orcish Veteran', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Warchief'] = { Name='Orcish Warchief', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Zerker'] = { Name='Orcish Zerker', Ecosystem='beastmen', Family='orcs' },
        ['Spinel Quadav'] = { Name='Spinel Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Steel Quadav'] = { Name='Steel Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Topaz Quadav'] = { Name='Topaz Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Viscount Morax'] = { Name='Viscount Morax', Ecosystem='demons', Family='demons' },
        ['Yagudo Abbot'] = { Name='Yagudo Abbot', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Chanter'] = { Name='Yagudo Chanter', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Conquistador'] = { Name='Yagudo Conquistador', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Inquisitor'] = { Name='Yagudo Inquisitor', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Lutenist'] = { Name='Yagudo Lutenist', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Prior'] = { Name='Yagudo Prior', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Sentinel'] = { Name='Yagudo Sentinel', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Zealot'] = { Name='Yagudo Zealot', Ecosystem='beastmen', Family='yagudo' },
    },
};
