--Zone: Ranguemont Pass
--Zone ID: 166
return {
    Names = {
        ['Bat Eye'] = { Name='Bat Eye', Ecosystem='demons', Family='ahriman' },
        ['Bilesucker'] = { Name='Bilesucker', Ecosystem='amorphs', Family='leeches' },
        ['Blade Bat'] = { Name='Blade Bat', Ecosystem='birds', Family='bats' },
        ['Cave Scorpion'] = { Name='Cave Scorpion', Ecosystem='vermin', Family='scorpions' },
        ['Evil Weapon'] = { Name='Evil Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Giant Scorpion'] = { Name='Giant Scorpion', Ecosystem='vermin', Family='scorpions' },
        ['Gloom Eye'] = { Name='Gloom Eye', Ecosystem='demons', Family='ahriman' },
        ['Goblin Artificer'] = { Name='Goblin Artificer', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Chaser'] = { Name='Goblin Chaser', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Gambler'] = { Name='Goblin Gambler', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Hoodoo'] = { Name='Goblin Hoodoo', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Leecher'] = { Name='Goblin Leecher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Mugger'] = { Name='Goblin Mugger', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Tanner'] = { Name='Goblin Tanner', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Thug'] = { Name='Goblin Thug', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Weaver'] = { Name='Goblin Weaver', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Bats'] = { Name='Goblin\'s Bats', Ecosystem='birds', Family='bats' },
        ['Hecteyes'] = { Name='Hecteyes', Ecosystem='amorphs', Family='hecteyes' },
        ['Hovering Oculus'] = { Name='Hovering Oculus', Ecosystem='demons', Family='ahriman' },
        ['Hyakume'] = { Name='Hyakume', Ecosystem='amorphs', Family='hecteyes' },
        ['Metallic Slime'] = { Name='Metallic Slime', Ecosystem='amorphs', Family='slimes' },
        ['Mucoid Mass'] = { Name='Mucoid Mass', Ecosystem='amorphs', Family='slimes' },
        ['Oil Slick'] = { Name='Oil Slick', Ecosystem='amorphs', Family='slimes' },
        ['Ooze'] = { Name='Ooze', Ecosystem='amorphs', Family='slimes' },
        ['Seeker Bats'] = { Name='Seeker Bats', Ecosystem='birds', Family='bat trios' },
        ['Stirge'] = { Name='Stirge', Ecosystem='birds', Family='bats' },
        ['Taisai'] = { Name='Taisai', Ecosystem='amorphs', Family='hecteyes' },
        ['Taisaijin'] = { Name='Taisaijin', Ecosystem='amorphs', Family='hecteyes' },
        ['Tros'] = { Name='Tros', Ecosystem='aquans', Family='sea monks' },
        ['Wind Bats'] = { Name='Wind Bats', Ecosystem='birds', Family='bat trios' },
        -- Custom content for HorizonXI
        ['Goblin Smithy'] = { Name='Goblin Smithy', Ecosystem='beastmen', Family='goblins' },
    },
};
