--Zone: Toraimarai Canal
--Zone ID: 169
return {
    Names = {
        ['Bigclaw'] = { Name='Bigclaw', Ecosystem='aquans', Family='pugils' },
        ['Blackwater Pugil'] = { Name='Blackwater Pugil', Ecosystem='aquans', Family='pugils' },
        ['Bloodsucker'] = { Name='Bloodsucker', Ecosystem='amorphs', Family='leeches' },
        ['Bouncing Ball'] = { Name='Bouncing Ball', Ecosystem='amorphs', Family='leeches' },
        ['Brazen Bones'] = { Name='Brazen Bones', Ecosystem='undead', Family='skeletons' },
        ['Canal Bats'] = { Name='Canal Bats', Ecosystem='birds', Family='bat trios' },
        ['Canal Leech'] = { Name='Canal Leech', Ecosystem='amorphs', Family='leeches' },
        ['Canal Moocher'] = { Name='Canal Moocher', Ecosystem='amorphs', Family='leeches' },
        ['Dark Aspic'] = { Name='Dark Aspic', Ecosystem='amorphs', Family='slimes' },
        ['Deviling Bats'] = { Name='Deviling Bats', Ecosystem='birds', Family='bat trios' },
        ['Dire Bat'] = { Name='Dire Bat', Ecosystem='birds', Family='bats' },
        ['Doom Mage'] = { Name='Doom Mage', Ecosystem='undead', Family='skeletons' },
        ['Doom Soldier'] = { Name='Doom Soldier', Ecosystem='undead', Family='skeletons' },
        ['Drowned Bones'] = { Name='Drowned Bones', Ecosystem='undead', Family='skeletons' },
        ['Fallen Knight'] = { Name='Fallen Knight', Ecosystem='undead', Family='skeletons' },
        ['Fleshcraver'] = { Name='Fleshcraver', Ecosystem='undead', Family='skeletons' },
        ['Flume Toad'] = { Name='Flume Toad', Ecosystem='aquans', Family='toads' },
        ['Girtab'] = { Name='Girtab', Ecosystem='vermin', Family='scorpions' },
        ['Hell Bat'] = { Name='Hell Bat', Ecosystem='birds', Family='bats' },
        ['Hinge Oil'] = { Name='Hinge Oil', Ecosystem='amorphs', Family='slimes' },
        ['Impish Bats'] = { Name='Impish Bats', Ecosystem='birds', Family='bat trios' },
        ['Konjac'] = { Name='Konjac', Ecosystem='amorphs', Family='slimes' },
        ['Lich'] = { Name='Lich', Ecosystem='undead', Family='skeletons' },
        ['Magic Sludge'] = { Name='Magic Sludge', Ecosystem='elementals', Family='elementals' },
        ['Makara'] = { Name='Makara', Ecosystem='aquans', Family='pugils' },
        ['Mimic'] = { Name='Mimic', Ecosystem='arcana', Family='mimics' },
        ['Mindcraver'] = { Name='Mindcraver', Ecosystem='undead', Family='skeletons' },
        ['Mousse'] = { Name='Mousse', Ecosystem='amorphs', Family='slimes' },
        ['Oni Carcass'] = { Name='Oni Carcass', Ecosystem='undead', Family='doomed' },
        ['Plunderer Crab'] = { Name='Plunderer Crab', Ecosystem='aquans', Family='crabs' },
        ['Poroggo Excavator'] = { Name='Poroggo Excavator', Ecosystem='beastmen', Family='poroggos' },
        ['Rapier Scorpion'] = { Name='Rapier Scorpion', Ecosystem='vermin', Family='scorpions' },
        ['Rock Crab'] = { Name='Rock Crab', Ecosystem='aquans', Family='crabs' },
        ['Rotten Sod'] = { Name='Rotten Sod', Ecosystem='undead', Family='doomed' },
        ['Scavenger Crab'] = { Name='Scavenger Crab', Ecosystem='aquans', Family='crabs' },
        ['Sodden Bones'] = { Name='Sodden Bones', Ecosystem='undead', Family='skeletons' },
        ['Starborer'] = { Name='Starborer', Ecosystem='vermin', Family='beetles' },
        ['Starmite'] = { Name='Starmite', Ecosystem='vermin', Family='beetles' },
        ['Stygian Pugil'] = { Name='Stygian Pugil', Ecosystem='aquans', Family='pugils' },
        -- Custom content for HorizonXI
        ['Diphylla'] = { Name='Diphylla', Ecosystem='birds', Family='bats' },
        ['Channel Pugil'] = { Name='Channel Pugil', Ecosystem='aquans', Family='pugils' },
    },
};
