--Zone: Korroloka Tunnel
--Zone ID: 173
return {
    Names = {
        ['Bogy'] = { Name='Bogy', Ecosystem='undead', Family='ghosts' },
        ['Cargo Crab Colin'] = { Name='Cargo Crab Colin', Ecosystem='aquans', Family='crabs' },
        ['Clipper'] = { Name='Clipper', Ecosystem='aquans', Family='crabs' },
        ['Combat'] = { Name='Combat', Ecosystem='birds', Family='bats' },
        ['Dame Blanche'] = { Name='Dame Blanche', Ecosystem='undead', Family='ghosts' },
        ['Falcatus Aranei'] = { Name='Falcatus Aranei', Ecosystem='vermin', Family='spiders' },
        ['Gigas Foreman'] = { Name='Gigas Foreman', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Stonecarrier'] = { Name='Gigas Stonecarrier', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Stonegrinder'] = { Name='Gigas Stonegrinder', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Stonemason'] = { Name='Gigas Stonemason', Ecosystem='beastmen', Family='gigas' },
        ['Gigas\'s Spider'] = { Name='Gigas\'s Spider', Ecosystem='vermin', Family='spiders' },
        ['Goblin Bounty Hunter'] = { Name='Goblin Bounty Hunter', Ecosystem='beastmen', Family='goblins' },
        ['Greater Pugil'] = { Name='Greater Pugil', Ecosystem='aquans', Family='pugils' },
        ['Huge Spider'] = { Name='Huge Spider', Ecosystem='vermin', Family='spiders' },
        ['Jammer Leech'] = { Name='Jammer Leech', Ecosystem='amorphs', Family='leeches' },
        ['Jelly'] = { Name='Jelly', Ecosystem='amorphs', Family='slimes' },
        ['Korroloka Leech'] = { Name='Korroloka Leech', Ecosystem='amorphs', Family='leeches' },
        ['Kraken'] = { Name='Kraken', Ecosystem='aquans', Family='sea monks' },
        ['Lacerator'] = { Name='Lacerator', Ecosystem='aquans', Family='crabs' },
        ['Land Worm'] = { Name='Land Worm', Ecosystem='amorphs', Family='worms' },
        ['Metallic Slime'] = { Name='Metallic Slime', Ecosystem='amorphs', Family='slimes' },
        ['Morion Worm'] = { Name='Morion Worm', Ecosystem='amorphs', Family='worms' },
        ['Sea Monk'] = { Name='Sea Monk', Ecosystem='aquans', Family='sea monks' },
        ['Seeker Bats'] = { Name='Seeker Bats', Ecosystem='birds', Family='bat trios' },
        ['Snipper'] = { Name='Snipper', Ecosystem='aquans', Family='crabs' },
        ['Spool Leech'] = { Name='Spool Leech', Ecosystem='amorphs', Family='leeches' },
        ['Thoon'] = { Name='Thoon', Ecosystem='beastmen', Family='gigas' },
        ['Thread Leech'] = { Name='Thread Leech', Ecosystem='amorphs', Family='leeches' },
        ['Thunder Elemental'] = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
        ['Water Elemental'] = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
    },
};
