--Zone: Kuftal Tunnel
--Zone ID: 174
return {
    Names = {
        ['Air Elemental'] = { Name='Air Elemental', Ecosystem='elementals', Family='elementals' },
        ['Amemet'] = { Name='Amemet', Ecosystem='lizards', Family='lizards' },
        ['Arachne'] = { Name='Arachne', Ecosystem='vermin', Family='spiders' },
        ['Bloodthirster Madkix'] = { Name='Bloodthirster Madkix', Ecosystem='beastmen', Family='goblins' },
        ['Cancer'] = { Name='Cancer', Ecosystem='aquans', Family='crabs' },
        ['Cave Worm'] = { Name='Cave Worm', Ecosystem='amorphs', Family='worms' },
        ['Deinonychus'] = { Name='Deinonychus', Ecosystem='lizards', Family='raptors' },
        ['Dervo\'s Ghost'] = { Name='Dervo\'s Ghost', Ecosystem='undead', Family='ghosts' },
        ['Devil Manta'] = { Name='Devil Manta', Ecosystem='aquans', Family='Sea Monks' },
        ['Diplopod'] = { Name='Diplopod', Ecosystem='vermin', Family='scorpions' },
        ['Fire Elemental'] = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals' },
        ['Gizerl\'s Ghost'] = { Name='Gizerl\'s Ghost', Ecosystem='undead', Family='ghosts' },
        ['Goblin Alchemist'] = { Name='Goblin Alchemist', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Bandit'] = { Name='Goblin Bandit', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Mercenary'] = { Name='Goblin Mercenary', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Tamer'] = { Name='Goblin Tamer', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Spider'] = { Name='Goblin\'s Spider', Ecosystem='vermin', Family='spiders' },
        ['Gordov\'s Ghost'] = { Name='Gordov\'s Ghost', Ecosystem='undead', Family='ghosts' },
        ['Greater Cockatrice'] = { Name='Greater Cockatrice', Ecosystem='birds', Family='cockatrices' },
        ['Guivre'] = { Name='Guivre', Ecosystem='dragons', Family='wyverns' },
        ['Haunt'] = { Name='Haunt', Ecosystem='undead', Family='ghosts' },
        ['Kettenkaefer'] = { Name='Kettenkaefer', Ecosystem='vermin', Family='beetles' },
        ['Koura'] = { Name='Koura', Ecosystem='aquans', Family='crabs' },
        ['Kuftal Delver'] = { Name='Kuftal Delver', Ecosystem='amorphs', Family='worms' },
        ['Kuftal Digger'] = { Name='Kuftal Digger', Ecosystem='amorphs', Family='worms' },
        ['Ladon'] = { Name='Ladon', Ecosystem='dragons', Family='wyverns' },
        ['Machairodus'] = { Name='Machairodus', Ecosystem='beasts', Family='tigers' },
        ['Mimic'] = { Name='Mimic', Ecosystem='arcana', Family='mimics' },
        ['Moki'] = { Name='Moki', Ecosystem='aquans', Family='pugils' },
        ['Ovinnik'] = { Name='Ovinnik', Ecosystem='beasts', Family='tigers' },
        ['Pekapeka'] = { Name='Pekapeka', Ecosystem='aquans', Family='sea monks' },
        ['Pelican'] = { Name='Pelican', Ecosystem='birds', Family='cockatrices' },
        ['Phantom Worm'] = { Name='Phantom Worm', Ecosystem='amorphs', Family='worms' },
        ['Recluse Spider'] = { Name='Recluse Spider', Ecosystem='vermin', Family='spiders' },
        ['Robber Crab'] = { Name='Robber Crab', Ecosystem='aquans', Family='crabs' },
        ['Sabotender Mariachi'] = { Name='Sabotender Mariachi', Ecosystem='plantoids', Family='sabotenders' },
        ['Sabotender Sediendo'] = { Name='Sabotender Sediendo', Ecosystem='plantoids', Family='sabotenders' },
        ['Sand Lizard'] = { Name='Sand Lizard', Ecosystem='lizards', Family='lizards' },
        ['Scavenger Crab'] = { Name='Scavenger Crab', Ecosystem='aquans', Family='crabs' },
        ['Specter Worm'] = { Name='Specter Worm', Ecosystem='amorphs', Family='worms' },
        ['Stygian Pugil'] = { Name='Stygian Pugil', Ecosystem='aquans', Family='pugils' },
        ['Tangaroa'] = { Name='Tangaroa', Ecosystem='aquans', Family='uragnites' },
        ['Yowie'] = { Name='Yowie', Ecosystem='lizards', Family='raptors' },
    },
};
