--Zone: Sea Serpent Grotto
--Zone ID: 176
return {
    Names = {
        ['Abyss Sahagin'] = { Name='Abyss Sahagin', Ecosystem='beastmen', Family='sahagins' },
        ['Bakunawa'] = { Name='Bakunawa', Ecosystem='aquans', Family='sea monks' },
        ['Big Jaw'] = { Name='Big Jaw', Ecosystem='aquans', Family='pugils' },
        ['Bigclaw'] = { Name='Bigclaw', Ecosystem='aquans', Family='crabs' },
        ['Blubber Eyes'] = { Name='Blubber Eyes', Ecosystem='amorphs', Family='hecteyes' },
        ['Bog Sahagin'] = { Name='Bog Sahagin', Ecosystem='beastmen', Family='sahagins' },
        ['Brook Sahagin'] = { Name='Brook Sahagin', Ecosystem='beastmen', Family='sahagins' },
        ['Charybdis'] = { Name='Charybdis', Ecosystem='aquans', Family='sea monks' },
        ['Coastal Sahagin'] = { Name='Coastal Sahagin', Ecosystem='beastmen', Family='sahagins' },
        ['Coral Sahagin'] = { Name='Coral Sahagin', Ecosystem='beastmen', Family='sahagins' },
        ['Delta Sahagin'] = { Name='Delta Sahagin', Ecosystem='beastmen', Family='sahagins' },
        ['Denn the Orcavoiced'] = { Name='Denn the Orcavoiced', Ecosystem='beastmen', Family='sahagins' },
        ['Devil Manta'] = { Name='Devil Manta', Ecosystem='aquans', Family='sea monks' },
        ['Dire Bat'] = { Name='Dire Bat', Ecosystem='birds', Family='bats' },
        ['Fyuu the Seabellow'] = { Name='Fyuu the Seabellow', Ecosystem='beastmen', Family='sahagins' },
        ['Ghast'] = { Name='Ghast', Ecosystem='undead', Family='skeletons' },
        ['Glyryvilu'] = { Name='Glyryvilu', Ecosystem='aquans', Family='sea monks' },
        ['Greatclaw'] = { Name='Greatclaw', Ecosystem='aquans', Family='crabs' },
        ['Grotto Pugil'] = { Name='Grotto Pugil', Ecosystem='aquans', Family='pugils' },
        ['Ironshell'] = { Name='Ironshell', Ecosystem='aquans', Family='crabs' },
        ['Kanavid'] = { Name='Kanavid', Ecosystem='aquans', Family='sea monks' },
        ['Lagoon Sahagin'] = { Name='Lagoon Sahagin', Ecosystem='beastmen', Family='sahagins' },
        ['Lake Sahagin'] = { Name='Lake Sahagin', Ecosystem='beastmen', Family='sahagins' },
        ['Marsh Sahagin'] = { Name='Marsh Sahagin', Ecosystem='beastmen', Family='sahagins' },
        ['Masan'] = { Name='Masan', Ecosystem='amorphs', Family='leeches' },
        ['Mimic'] = { Name='Mimic', Ecosystem='arcana', Family='mimics' },
        ['Mindgazer'] = { Name='Mindgazer', Ecosystem='amorphs', Family='hecteyes' },
        ['Mousse'] = { Name='Mousse', Ecosystem='amorphs', Family='slimes' },
        ['Mouu the Waverider'] = { Name='Mouu the Waverider', Ecosystem='beastmen', Family='sahagins' },
        ['Namtar'] = { Name='Namtar', Ecosystem='undead', Family='skeletons' },
        ['Nightmare Bats'] = { Name='Nightmare Bats', Ecosystem='birds', Family='bat trios' },
        ['Novv the Whitehearted'] = { Name='Novv the Whitehearted', Ecosystem='beastmen', Family='sahagins' },
        ['Ocean Sahagin'] = { Name='Ocean Sahagin', Ecosystem='beastmen', Family='sahagins' },
        ['Ooze'] = { Name='Ooze', Ecosystem='amorphs', Family='slimes' },
        ['Pahh the Gullcaller'] = { Name='Pahh the Gullcaller', Ecosystem='beastmen', Family='sahagins' },
        ['Pond Sahagin'] = { Name='Pond Sahagin', Ecosystem='beastmen', Family='sahagins' },
        ['Qull the Shellbuster'] = { Name='Qull the Shellbuster', Ecosystem='beastmen', Family='sahagins' },
        ['Razorjaw Pugil'] = { Name='Razorjaw Pugil', Ecosystem='aquans', Family='pugils' },
        ['Riparian Sahagin'] = { Name='Riparian Sahagin', Ecosystem='beastmen', Family='sahagins' },
        ['Rivulet Sahagin'] = { Name='Rivulet Sahagin', Ecosystem='beastmen', Family='sahagins' },
        ['Robber Crab'] = { Name='Robber Crab', Ecosystem='aquans', Family='crabs' },
        ['Rock Crab'] = { Name='Rock Crab', Ecosystem='aquans', Family='crabs' },
        ['Royal Leech'] = { Name='Royal Leech', Ecosystem='amorphs', Family='leeches' },
        ['Sahagin Parasite'] = { Name='Sahagin Parasite', Ecosystem='amorphs', Family='leeches' },
        ['Sahagin\'s Wyvern'] = { Name='Sahagin\'s Wyvern', Ecosystem='dragons', Family='pet wyverns' },
        ['Sea Bonze'] = { Name='Sea Bonze', Ecosystem='aquans', Family='sea monks' },
        ['Sea Hog'] = { Name='Sea Hog', Ecosystem='aquans', Family='pugils' },
        ['Seww the Squidlimbed'] = { Name='Seww the Squidlimbed', Ecosystem='beastmen', Family='sahagins' },
        ['Shore Sahagin'] = { Name='Shore Sahagin', Ecosystem='beastmen', Family='sahagins' },
        ['Spring Sahagin'] = { Name='Spring Sahagin', Ecosystem='beastmen', Family='sahagins' },
        ['Stygian Pugil'] = { Name='Stygian Pugil', Ecosystem='aquans', Family='pugils' },
        ['Swamp Sahagin'] = { Name='Swamp Sahagin', Ecosystem='beastmen', Family='sahagins' },
        ['Thunder Elemental'] = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
        ['Undead Bats'] = { Name='Undead Bats', Ecosystem='birds', Family='bat trios' },
        ['Vampire Bat'] = { Name='Vampire Bat', Ecosystem='birds', Family='bats' },
        ['Voll the Sharkfinned'] = { Name='Voll the Sharkfinned', Ecosystem='beastmen', Family='sahagins' },
        ['Water Elemental'] = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
        ['Water Leaper'] = { Name='Water Leaper', Ecosystem='aquans', Family='pugils' },
        ['Worr the Clawfisted'] = { Name='Worr the Clawfisted', Ecosystem='beastmen', Family='sahagins' },
        ['Wuur the Sandcomber'] = { Name='Wuur the Sandcomber', Ecosystem='beastmen', Family='sahagins' },
        ['Yarr the Pearleyed'] = { Name='Yarr the Pearleyed', Ecosystem='beastmen', Family='sahagins' },
        ['Zuug the Shoreleaper'] = { Name='Zuug the Shoreleaper', Ecosystem='beastmen', Family='sahagins' },
    },
};
