--Zone: The Shrine of Ru'Avitau
--Zone ID: 178
return {
    Names = {
        ['Air Elemental'] = { Name='Air Elemental', Ecosystem='elementals', Family='elementals' },
        ['Aura Butler'] = { Name='Aura Butler', Ecosystem='arcana', Family='dolls' },
        ['Aura Gear'] = { Name='Aura Gear', Ecosystem='arcana', Family='dolls' },
        ['Aura Pot'] = { Name='Aura Pot', Ecosystem='arcana', Family='magic pots' },
        ['Aura Sculpture'] = { Name='Aura Sculpture', Ecosystem='arcana', Family='golems' },
        ['Aura Statue'] = { Name='Aura Statue', Ecosystem='arcana', Family='golems' },
        ['Aura Weapon'] = { Name='Aura Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Baelfyr'] = { Name='Baelfyr', Ecosystem='elementals', Family='elementals' },
        ['Bai Hu'] = { Name='Bai Hu', Ecosystem='beasts', Family='tigers' },
        ['Byakko'] = { Name='Byakko', Ecosystem='beasts', Family='tigers' },
        ['Byrgen'] = { Name='Byrgen', Ecosystem='elementals', Family='elementals' },
        ['Dark Elemental'] = { Name='Dark Elemental', Ecosystem='elementals', Family='elementals' },
        ['Decorative Weapon'] = { Name='Decorative Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Defender'] = { Name='Defender', Ecosystem='arcana', Family='spheroids' },
        ['Earth Elemental'] = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Faust'] = { Name='Faust', Ecosystem='arcana', Family='dolls' },
        ['Fire Elemental'] = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals' },
        ['Gefyrst'] = { Name='Gefyrst', Ecosystem='elementals', Family='elementals' },
        ['Genbu'] = { Name='Genbu', Ecosystem='lizards', Family='adamantoises' },
        ['Ice Elemental'] = { Name='Ice Elemental', Ecosystem='elementals', Family='elementals' },
        ['Kirin'] = { Name='Kirin', Ecosystem='beasts', Family='manticores' },
        ['Kirin\'s Avatar'] = { Name='Kirin\'s Avatar', Ecosystem='unclassified', Family='avarars' },
        ['Mother Globe'] = { Name='Mother Globe', Ecosystem='arcana', Family='spheroids' },
        ['Olla Grande'] = { Name='Olla Grande', Ecosystem='arcana', Family='magic pots' },
        ['Olla Media'] = { Name='Olla Media', Ecosystem='arcana', Family='magic pots' },
        ['Olla Pequena'] = { Name='Olla Pequena', Ecosystem='arcana', Family='magic pots' },
        ['Qilin'] = { Name='Qilin', Ecosystem='beasts', Family='manticores' },
        ['Qing Long'] = { Name='Qing Long', Ecosystem='dragons', Family='wyverns' },
        ['Seiryu'] = { Name='Seiryu', Ecosystem='dragons', Family='wyverns' },
        ['Slave Globe'] = { Name='Slave Globe', Ecosystem='arcana', Family='spheroids' },
        ['Suzaku'] = { Name='Suzaku', Ecosystem='birds', Family='rocs' },
        ['Thunder Elemental'] = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
        ['Ullikummi'] = { Name='Ullikummi', Ecosystem='arcana', Family='golems' },
        ['Ungeweder'] = { Name='Ungeweder', Ecosystem='elementals', Family='elementals' },
        ['Water Elemental'] = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
        ['Xuan Wu'] = { Name='Xuan Wu', Ecosystem='lizards', Family='adamantoises' },
        ['Zhu Que'] = { Name='Zhu Que', Ecosystem='birds', Family='rocs' },
    },
};
