--Zone: Lower Delkfutt's Tower
--Zone ID: 184
return {
    Names = {
        ['Akvan'] = { Name='Akvan', Ecosystem='demons', Family='ahriman' },
        ['Ancient Bat'] = { Name='Ancient Bat', Ecosystem='birds', Family='bats' },
        ['Bogy'] = { Name='Bogy', Ecosystem='undead', Family='ghost' },
        ['Chaos Idol'] = { Name='Chaos Idol', Ecosystem='arcana', Family='dolls' },
        ['Disaster Idol'] = { Name='Disaster Idol', Ecosystem='arcana', Family='dolls' },
        ['Epialtes'] = { Name='Epialtes', Ecosystem='beastmen', Family='gigas' },
        ['Eurymedon'] = { Name='Eurymedon', Ecosystem='beastmen', Family='gigas' },
        ['Fomorian Spear'] = { Name='Fomorian Spear', Ecosystem='arcana', Family='evil weapons' },
        ['Giant Gatekeeper'] = { Name='Giant Gatekeeper', Ecosystem='beastmen', Family='gigas' },
        ['Giant Guard'] = { Name='Giant Guard', Ecosystem='beastmen', Family='gigas' },
        ['Giant Lobber'] = { Name='Giant Lobber', Ecosystem='beastmen', Family='gigas' },
        ['Giant Sentry'] = { Name='Giant Sentry', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Butcher'] = { Name='Gigas Butcher', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Hallwatcher'] = { Name='Gigas Hallwatcher', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Punisher'] = { Name='Gigas Punisher', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Sculptor'] = { Name='Gigas Sculptor', Ecosystem='beastmen', Family='gigas' },
        ['Gigas\'s Bat'] = { Name='Gigas\'s Bat', Ecosystem='birds', Family='bats' },
        ['Gigas\'s Bats'] = { Name='Gigas\'s Bats', Ecosystem='birds', Family='bat trios' },
        ['Goblin Gambler'] = { Name='Goblin Gambler', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Leecher'] = { Name='Goblin Leecher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Mugger'] = { Name='Goblin Mugger', Ecosystem='beastmen', Family='goblins' },
        ['Hippolytos'] = { Name='Hippolytos', Ecosystem='beastmen', Family='gigas' },
        ['Illusory Pot'] = { Name='Illusory Pot', Ecosystem='arcana', Family='magic pots' },
        ['Light Elemental'] = { Name='Light Elemental', Ecosystem='elementals', Family='elementals' },
        ['Magic Pot'] = { Name='Magic Pot', Ecosystem='arcana', Family='magic pots' },
        ['Magic Urn'] = { Name='Magic Urn', Ecosystem='arcana', Family='magic pots' },
        ['Orna'] = { Name='Orna', Ecosystem='arcana', Family='evil weapons' },
        ['Seeker Bats'] = { Name='Seeker Bats', Ecosystem='birds', Family='bat trios' },
        ['Thunder Elemental'] = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
        ['Tyrant'] = { Name='Tyrant', Ecosystem='arcana', Family='dolls' },
    },
};
