--Zone: Dynamis - San d'Oria
--Zone ID: 185
return {
    Names = {
        ['Arch Overlord Tombstone'] = { Name='Arch Overlord Tombstone', Ecosystem='unclassified', Family='replicas' },
        ['Battlechoir Gitchfotch'] = { Name='Battlechoir Gitchfotch', Ecosystem='beastmen', Family='orcs' },
        ['Bladeburner Rokgevok'] = { Name='Bladeburner Rokgevok', Ecosystem='beastmen', Family='orcs' },
        ['Bloodfist Voshgrosh'] = { Name='Bloodfist Voshgrosh', Ecosystem='beastmen', Family='orcs' },
        ['Djokvukk\'s Wyvern'] = { Name='Djokvukk\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Kratzvatz\'s Hecteyes'] = { Name='Kratzvatz\'s Hecteyes', Ecosystem='amorph', Family='hecteyes' },
        ['Overlord\'s Tombstone'] = { Name='Overlord\'s Tombstone', Ecosystem='unclassified', Family='replicas' },
        ['Reapertongue Gadgquok'] = { Name='Reapertongue Gadgquok', Ecosystem='beastmen', Family='orcs' },
        ['Serjeant Tombstone'] = { Name='Serjeant Tombstone', Ecosystem='unclassified', Family='replicas' },
        ['Soulsender Fugbrag'] = { Name='Soulsender Fugbrag', Ecosystem='beastmen', Family='orcs' },
        ['Spellspear Djokvukk'] = { Name='Spellspear Djokvukk', Ecosystem='beastmen', Family='orcs' },
        ['Steelshank Kratzvatz'] = { Name='Steelshank Kratzvatz', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Amputator'] = { Name='Vanguard Amputator', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Backstabber'] = { Name='Vanguard Backstabber', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Bugler'] = { Name='Vanguard Bugler', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Dollmaster'] = { Name='Vanguard Dollmaster', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Footsoldier'] = { Name='Vanguard Footsoldier', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Grappler'] = { Name='Vanguard Grappler', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Gutslasher'] = { Name='Vanguard Gutslasher', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Hawker'] = { Name='Vanguard Hawker', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Impaler'] = { Name='Vanguard Impaler', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Mesmerizer'] = { Name='Vanguard Mesmerizer', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Neckchopper'] = { Name='Vanguard Neckchopper', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Pillager'] = { Name='Vanguard Pillager', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Predator'] = { Name='Vanguard Predator', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Trooper'] = { Name='Vanguard Trooper', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Vexer'] = { Name='Vanguard Vexer', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard\'s Avatar'] = { Name='Vanguard\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Vanguard\'s Hecteyes'] = { Name='Vanguard\'s Hecteyes', Ecosystem='amorph', Family='hecteyes' },
        ['Vanguard\'s Wyvern'] = { Name='Vanguard\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Voidstreaker Butchnotch'] = { Name='Voidstreaker Butchnotch', Ecosystem='beastmen', Family='orcs' },
        ['Warchief Tombstone'] = { Name='Warchief Tombstone', Ecosystem='unclassified', Family='replicas' },
        ['Wyrmgnasher Bjakdek'] = { Name='Wyrmgnasher Bjakdek', Ecosystem='beastmen', Family='orcs' },
    },
};
