--Zone: Dynamis - Bastok
--Zone ID: 186
return {
    Names = {
        ['Adamantking Effigy'] = { Name='Adamantking Effigy', Ecosystem='unclassified', Family='replicas' },
        ['Adamantking Image'] = { Name='Adamantking Image', Ecosystem='unclassified', Family='replicas' },
        ['Arch Gu\'Dha Effigy'] = { Name='Arch Gu\'Dha Effigy', Ecosystem='unclassified', Family='replicas' },
        ['Bu\'Bho Truesteel'] = { Name='Bu\'Bho Truesteel', Ecosystem='beastmen', Family='quadavs' },
        ['Gi\'Pha Manameister'] = { Name='Gi\'Pha Manameister', Ecosystem='beastmen', Family='quadavs' },
        ['Gu\'Dha Effigy'] = { Name='Gu\'Dha Effigy', Ecosystem='unclassified', Family='replicas' },
        ['Gu\'Nhi Noondozer'] = { Name='Gu\'Nhi Noondozer', Ecosystem='beastmen', Family='quadavs' },
        ['Ko\'Dho Cannonball'] = { Name='Ko\'Dho Cannonball', Ecosystem='beastmen', Family='quadavs' },
        ['Ra\'Gho Darkfount'] = { Name='Ra\'Gho Darkfount', Ecosystem='beastmen', Family='quadavs' },
        ['Ra\'Gho\'s Avatar'] = { Name='Ra\'Gho\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Va\'Zhe Pummelsong'] = { Name='Va\'Zhe Pummelsong', Ecosystem='beastmen', Family='quadavs' },
        ['Vanguard Beasttender'] = { Name='Vanguard Beasttender', Ecosystem='beastmen', Family='quadavs' },
        ['Vanguard Constable'] = { Name='Vanguard Constable', Ecosystem='beastmen', Family='quadavs' },
        ['Vanguard Defender'] = { Name='Vanguard Defender', Ecosystem='beastmen', Family='quadavs' },
        ['Vanguard Drakekeeper'] = { Name='Vanguard Drakekeeper', Ecosystem='beastmen', Family='quadavs' },
        ['Vanguard Hatamoto'] = { Name='Vanguard Hatamoto', Ecosystem='beastmen', Family='quadavs' },
        ['Vanguard Kusa'] = { Name='Vanguard Kusa', Ecosystem='beastmen', Family='quadavs' },
        ['Vanguard Mason'] = { Name='Vanguard Mason', Ecosystem='beastmen', Family='quadavs' },
        ['Vanguard Militant'] = { Name='Vanguard Militant', Ecosystem='beastmen', Family='quadavs' },
        ['Vanguard Minstrel'] = { Name='Vanguard Minstrel', Ecosystem='beastmen', Family='quadavs' },
        ['Vanguard Protector'] = { Name='Vanguard Protector', Ecosystem='beastmen', Family='quadavs' },
        ['Vanguard Purloiner'] = { Name='Vanguard Purloiner', Ecosystem='beastmen', Family='quadavs' },
        ['Vanguard Thaumaturge'] = { Name='Vanguard Thaumaturge', Ecosystem='beastmen', Family='quadavs' },
        ['Vanguard Undertaker'] = { Name='Vanguard Undertaker', Ecosystem='beastmen', Family='quadavs' },
        ['Vanguard Vigilante'] = { Name='Vanguard Vigilante', Ecosystem='beastmen', Family='quadavs' },
        ['Vanguard Vindicator'] = { Name='Vanguard Vindicator', Ecosystem='beastmen', Family='quadavs' },
        ['Vanguard\'s Avatar'] = { Name='Vanguard\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Vanguard\'s Scorpion'] = { Name='Vanguard\'s Scorpion', Ecosystem='vermin', Family='scorpions' },
        ['Vanguard\'s Wyvern'] = { Name='Vanguard\'s Wyvern', Ecosystem='dragons', Family='pet wyverns' },
        ['Ze\'Vho Fallsplitter'] = { Name='Ze\'Vho Fallsplitter', Ecosystem='beastmen', Family='quadavs' },
        ['Zo\'Pha Forgesoul'] = { Name='Zo\'Pha Forgesoul', Ecosystem='beastmen', Family='quadavs' },
    },
};
