--Zone: Dynamis - Windurst
--Zone ID: 187
return {
    Names = {
        ['Arch Tzee Xicu Idol'] = { Name='Arch Tzee Xicu Idol', Ecosystem='unclassified', Family='replicas' },
        ['Avatar Icon'] = { Name='Avatar Icon', Ecosystem='unclassified', Family='replicas' },
        ['Avatar Idol'] = { Name='Avatar Idol', Ecosystem='unclassified', Family='replicas' },
        ['Fuu Tzapo the Blessed'] = { Name='Fuu Tzapo the Blessed', Ecosystem='beastmen', Family='yagudo' },
        ['Haa Pevi the Stentorian'] = { Name='Haa Pevi the Stentorian', Ecosystem='beastmen', Family='yagudo' },
        ['Loo Hepe the Eyepiercer'] = { Name='Loo Hepe the Eyepiercer', Ecosystem='beastmen', Family='yagudo' },
        ['Maa Febi the Steadfast'] = { Name='Maa Febi the Steadfast', Ecosystem='beastmen', Family='yagudo' },
        ['Muu Febi the Steadfast'] = { Name='Muu Febi the Steadfast', Ecosystem='beastmen', Family='yagudo' },
        ['Naa Yixo the Stillrage'] = { Name='Naa Yixo the Stillrage', Ecosystem='beastmen', Family='yagudo' },
        ['Tee Zaksa the Ceaseless'] = { Name='Tee Zaksa the Ceaseless', Ecosystem='beastmen', Family='yagudo' },
        ['Tzee Xicu Idol'] = { Name='Tzee Xicu Idol', Ecosystem='unclassified', Family='replicas' },
        ['Vanguard Assassin'] = { Name='Vanguard Assassin', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Chanter'] = { Name='Vanguard Chanter', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Exemplar'] = { Name='Vanguard Exemplar', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Inciter'] = { Name='Vanguard Inciter', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Liberator'] = { Name='Vanguard Liberator', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Ogresoother'] = { Name='Vanguard Ogresoother', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Oracle'] = { Name='Vanguard Oracle', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Partisan'] = { Name='Vanguard Partisan', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Persecutor'] = { Name='Vanguard Persecutor', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Prelate'] = { Name='Vanguard Prelate', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Priest'] = { Name='Vanguard Priest', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Salvager'] = { Name='Vanguard Salvager', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Sentinel'] = { Name='Vanguard Sentinel', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Skirmisher'] = { Name='Vanguard Skirmisher', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Visionary'] = { Name='Vanguard Visionary', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard\'s Avatar'] = { Name='Vanguard\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Vanguard\'s Crow'] = { Name='Vanguard\'s Crow', Ecosystem='birds', Family='birds' },
        ['Vanguard\'s Wyvern'] = { Name='Vanguard\'s Wyvern', Ecosystem='dragons', Family='pet wyverns' },
        ['Wuu Qoho the Razorclaw'] = { Name='Wuu Qoho the Razorclaw', Ecosystem='beastmen', Family='yagudo' },
        ['Xoo Kaza the Solemn'] = { Name='Xoo Kaza the Solemn', Ecosystem='beastmen', Family='yagudo' },
        ['Xuu Bhoqa the Enigma'] = { Name='Xuu Bhoqa the Enigma', Ecosystem='beastmen', Family='yagudo' },
        ['Xuu Bhoqa\'s Avatar'] = { Name='Xuu Bhoqa\'s Avatar', Ecosystem='unclassified', Family='avatars' },
    },
};
