--Zone: Dynamis - Jeuno
--Zone ID: 188
return {
    Names = {
        ['Anvilix Sootwrists'] = { Name='Anvilix Sootwrists', Ecosystem='beastmen', Family='goblins' },
        ['Arch Goblin Golem'] = { Name='Arch Goblin Golem', Ecosystem='unclassified', Family='replicas' },
        ['Bandrix Rockjaw'] = { Name='Bandrix Rockjaw', Ecosystem='beastmen', Family='goblins' },
        ['Blazox Boneybod'] = { Name='Blazox Boneybod', Ecosystem='beastmen', Family='goblins' },
        ['Bootrix Jaggedelbow'] = { Name='Bootrix Jaggedelbow', Ecosystem='beastmen', Family='goblins' },
        ['Buffrix Eargone'] = { Name='Buffrix Eargone', Ecosystem='beastmen', Family='goblins' },
        ['Cloktix Longnail'] = { Name='Cloktix Longnail', Ecosystem='beastmen', Family='goblins' },
        ['Distilix Stickytoes'] = { Name='Distilix Stickytoes', Ecosystem='beastmen', Family='goblins' },
        ['Elixmix Hooknose'] = { Name='Elixmix Hooknose', Ecosystem='beastmen', Family='goblins' },
        ['Eremix Snottynostril'] = { Name='Eremix Snottynostril', Ecosystem='beastmen', Family='goblins' },
        ['Feralox Honeylips'] = { Name='Feralox Honeylips', Ecosystem='beastmen', Family='goblins' },
        ['Feralox\'s Slime'] = { Name='Feralox\'s Slime', Ecosystem='amorphs', Family='slimes' },
        ['Gabblox Magpietongue'] = { Name='Gabblox Magpietongue', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Golem'] = { Name='Goblin Golem', Ecosystem='unclassified', Family='replicas' },
        ['Goblin Replica'] = { Name='Goblin Replica', Ecosystem='unclassified', Family='replicas' },
        ['Goblin Statue'] = { Name='Goblin Statue', Ecosystem='unclassified', Family='replicas' },
        ['Hermitrix Toothrot'] = { Name='Hermitrix Toothrot', Ecosystem='beastmen', Family='goblins' },
        ['Humnox Drumbelly'] = { Name='Humnox Drumbelly', Ecosystem='beastmen', Family='goblins' },
        ['Jabbrox Grannyguise'] = { Name='Jabbrox Grannyguise', Ecosystem='beastmen', Family='goblins' },
        ['Jabkix Pigeonpecs'] = { Name='Jabkix Pigeonpecs', Ecosystem='beastmen', Family='goblins' },
        ['Karashix Swollenskull'] = { Name='Karashix Swollenskull', Ecosystem='beastmen', Family='goblins' },
        ['Kikklix Longlegs'] = { Name='Kikklix Longlegs', Ecosystem='beastmen', Family='goblins' },
        ['Lurklox Dhalmelneck'] = { Name='Lurklox Dhalmelneck', Ecosystem='beastmen', Family='goblins' },
        ['Mobpix Mucousmouth'] = { Name='Mobpix Mucousmouth', Ecosystem='beastmen', Family='goblins' },
        ['Morgmox Moldnoggin'] = { Name='Morgmox Moldnoggin', Ecosystem='beastmen', Family='goblins' },
        ['Mortilox Wartpaws'] = { Name='Mortilox Wartpaws', Ecosystem='beastmen', Family='goblins' },
        ['Prowlox Barrelbelly'] = { Name='Prowlox Barrelbelly', Ecosystem='beastmen', Family='goblins' },
        ['Quicktrix Hexhands'] = { Name='Quicktrix Hexhands', Ecosystem='beastmen', Family='goblins' },
        ['Rutrix Hamgams'] = { Name='Rutrix Hamgams', Ecosystem='beastmen', Family='goblins' },
        ['Scourquix Scaleskin'] = { Name='Scourquix Scaleskin', Ecosystem='beastmen', Family='goblins' },
        ['Scourquix\'s Wyvern'] = { Name='Scourquix\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Scruffix Shaggychest'] = { Name='Scruffix Shaggychest', Ecosystem='beastmen', Family='goblins' },
        ['Slystix Megapeepers'] = { Name='Slystix Megapeepers', Ecosystem='beastmen', Family='goblins' },
        ['Smeltix Thickhide'] = { Name='Smeltix Thickhide', Ecosystem='beastmen', Family='goblins' },
        ['Snypestix Eaglebeak'] = { Name='Snypestix Eaglebeak', Ecosystem='beastmen', Family='goblins' },
        ['Sparkspox Sweatbrow'] = { Name='Sparkspox Sweatbrow', Ecosystem='beastmen', Family='goblins' },
        ['Ticktox Beadyeyes'] = { Name='Ticktox Beadyeyes', Ecosystem='beastmen', Family='goblins' },
        ['Trailblix Goatmug'] = { Name='Trailblix Goatmug', Ecosystem='beastmen', Family='goblins' },
        ['Tufflix Loglimbs'] = { Name='Tufflix Loglimbs', Ecosystem='beastmen', Family='goblins' },
        ['Tymexox Ninefingers'] = { Name='Tymexox Ninefingers', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Alchemist'] = { Name='Vanguard Alchemist', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Ambusher'] = { Name='Vanguard Ambusher', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Armorer'] = { Name='Vanguard Armorer', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Dragontamer'] = { Name='Vanguard Dragontamer', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Enchanter'] = { Name='Vanguard Enchanter', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Hitman'] = { Name='Vanguard Hitman', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Maestro'] = { Name='Vanguard Maestro', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Necromancer'] = { Name='Vanguard Necromancer', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Pathfinder'] = { Name='Vanguard Pathfinder', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Pitfighter'] = { Name='Vanguard Pitfighter', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Ronin'] = { Name='Vanguard Ronin', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Shaman'] = { Name='Vanguard Shaman', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Smithy'] = { Name='Vanguard Smithy', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Tinkerer'] = { Name='Vanguard Tinkerer', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Welldigger'] = { Name='Vanguard Welldigger', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard\'s Avatar'] = { Name='Vanguard\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Vanguard\'s Slime'] = { Name='Vanguard\'s Slime', Ecosystem='amorphs', Family='slimes' },
        ['Vanguard\'s Wyvern'] = { Name='Vanguard\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Wasabix Callusdigit'] = { Name='Wasabix Callusdigit', Ecosystem='beastmen', Family='goblins' },
        ['Wilywox Tenderpalm'] = { Name='Wilywox Tenderpalm', Ecosystem='beastmen', Family='goblins' },
        ['Wyrmwix Snakespecs'] = { Name='Wyrmwix Snakespecs', Ecosystem='beastmen', Family='goblins' },
    },
};
