--Zone: King Ranperre's Tomb
--Zone ID: 190
return {
    Names = {
        ['Airi'] = { Name='Airi', Ecosystem='undead', Family='ghosts'},
        ['Ankou'] = { Name='Ankou', Ecosystem='undead', Family='skeletons'},
        ['Arcus Blades'] = { Name='Arcus Blades', Ecosystem='arcana', Family='animated blades'},
        ['Barbastelle'] = { Name='Barbastelle', Ecosystem='birds', Family='bats'},
        ['Carrion Worm'] = { Name='Carrion Worm', Ecosystem='amorphs', Family='worms'},
        ['Cemetery Cherry'] = { Name='Cemetery Cherry', Ecosystem='plantoids', Family='treants'},
        ['Cherry Sapling'] = { Name='Cherry Sapling', Ecosystem='plantoids', Family='saplings'},
        ['Corrupted Soffeil'] = { Name='Corrupted Soffeil', Ecosystem='undead', Family='skeletons'},
        ['Corrupted Ulbrig'] = { Name='Corrupted Ulbrig', Ecosystem='undead', Family='skeletons'},
        ['Corrupted Yorgos'] = { Name='Corrupted Yorgos', Ecosystem='undead', Family='skeletons'},
        ['Crypt Ghost'] = { Name='Crypt Ghost', Ecosystem='undead', Family='ghosts'},
        ['Ding Bats'] = { Name='Ding Bats', Ecosystem='birds', Family='bat trios'},
        ['Enchanted Bones'] = { Name='Enchanted Bones', Ecosystem='undead', Family='skeletons'},
        ['Goblin Ambusher'] = { Name='Goblin Ambusher', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Butcher'] = { Name='Goblin Butcher', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Gambler'] = { Name='Goblin Gambler', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Gruel'] = { Name='Goblin Gruel', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Leecher'] = { Name='Goblin Leecher', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Mugger'] = { Name='Goblin Mugger', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Thug'] = { Name='Goblin Thug', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Tinkerer'] = { Name='Goblin Tinkerer', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Weaver'] = { Name='Goblin Weaver', Ecosystem='beastmen', Family='goblins'},
        ['Grave Bat'] = { Name='Grave Bat', Ecosystem='birds', Family='bats'},
        ['Gwyllgi'] = { Name='Gwyllgi', Ecosystem='undead', Family='hounds'},
        ['Hahava'] = { Name='Hahava', Ecosystem='undead', Family='naraka'},
        ['Hati'] = { Name='Hati', Ecosystem='undead', Family='hounds'},
        ['Iruci'] = { Name='Iruci', Ecosystem='undead', Family='skeletons'},
        ['Locus Armet Beetle'] = { Name='Locus Armet Beetle', Ecosystem='vermin', Family='beetles'},
        ['Locus Cutlass Scorpion'] = { Name='Locus Cutlass Scorpion', Ecosystem='vermin', Family='scorpions'},
        ['Locus Dire Bat'] = { Name='Locus Dire Bat', Ecosystem='birds', Family='bats'},
        ['Locus Hati'] = { Name='Locus Hati', Ecosystem='undead', Family='skeletons'},
        ['Locus Lemures'] = { Name='Locus Lemures', Ecosystem='undead', Family='ghosts'},
        ['Locus Spartoi Sorcerer'] = { Name='Locus Spartoi Sorcerer', Ecosystem='undead', Family='skeletons'},
        ['Locus Spartoi Warrior'] = { Name='Locus Spartoi Warrior', Ecosystem='undead', Family='skeletons'},
        ['Locus Thousand Eyes'] = { Name='Locus Thousand Eyes', Ecosystem='amorphs', Family='hecteyes'},
        ['Locus Tomb Worm'] = { Name='Locus Tomb Worm', Ecosystem='amorphs', Family='worms'},
        ['Mouse Bat'] = { Name='Mouse Bat', Ecosystem='birds', Family='bats'},
        ['Nachzehrer'] = { Name='Nachzehrer', Ecosystem='undead', Family='skeletons'},
        ['Pey'] = { Name='Pey', Ecosystem='undead', Family='skeletons'},
        ['Plague Bats'] = { Name='Plague Bats', Ecosystem='birds', Family='bat trios'},
        ['Rock Eater'] = { Name='Rock Eater', Ecosystem='amorphs', Family='worms'},
        ['Spartoi Sorcerer'] = { Name='Spartoi Sorcerer', Ecosystem='undead', Family='skeletons'},
        ['Spartoi Warrior'] = { Name='Spartoi Warrior', Ecosystem='undead', Family='skeletons'},
        ['Spook'] = { Name='Spook', Ecosystem='undead', Family='ghosts'},
        ['Stone Eater'] = { Name='Stone Eater', Ecosystem='amorphs', Family='worms'},
        ['Tomb Bat'] = { Name='Tomb Bat', Ecosystem='birds', Family='bats'},
        ['Vrtra'] = { Name='Vrtra', Ecosystem='dragons', Family='wyrms'},
        ['Wind Bats'] = { Name='Wind Bats', Ecosystem='birds', Family='bat trios'},
    },
};
