--Zone: Dangruf Wadi
--Zone ID: 191
return {
    Names = {
        ['Celaeno'] = { Name='Celaeno', Ecosystem='birds', Family='harpeia'},
        ['Chocoboleech'] = { Name='Chocoboleech', Ecosystem='amorphs', Family='leeches'},
        ['Coral Crab'] = { Name='Coral Crab', Ecosystem='aquans', Family='crabs'},
        ['Couloir Leech'] = { Name='Couloir Leech', Ecosystem='amorphs', Family='leeches'},
        ['Fire Elemental'] = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals'},
        ['Fume Lizard'] = { Name='Fume Lizard', Ecosystem='lizards', Family='lizards'},
        ['Geyser Lizard'] = { Name='Geyser Lizard', Ecosystem='lizards', Family='lizards'},
        ['Goblin Ambusher'] = { Name='Goblin Ambusher', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Bladesmith'] = { Name='Goblin Bladesmith', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Brigand'] = { Name='Goblin Brigand', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Bushwhacker'] = { Name='Goblin Bushwhacker', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Butcher'] = { Name='Goblin Butcher', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Conjurer'] = { Name='Goblin Conjurer', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Fisher'] = { Name='Goblin Fisher', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Headsman'] = { Name='Goblin Headsman', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Healer'] = { Name='Goblin Healer', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Thug'] = { Name='Goblin Thug', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Tinkerer'] = { Name='Goblin Tinkerer', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Weaver'] = { Name='Goblin Weaver', Ecosystem='beastmen', Family='goblins'},
        ['Hoarder Hare'] = { Name='Hoarder Hare', Ecosystem='beasts', Family='rabbits'},
        ['Land Crab'] = { Name='Land Crab', Ecosystem='aquans', Family='crabs'},
        ['Natty Gibbon'] = { Name='Natty Gibbon', Ecosystem='beasts', Family='opo-opos'},
        ['Prim Pika'] = { Name='Prim Pika', Ecosystem='beasts', Family='rabbits'},
        ['Rock Lizard'] = { Name='Rock Lizard', Ecosystem='lizards', Family='lizards'},
        ['Steam Lizard'] = { Name='Steam Lizard', Ecosystem='lizards', Family='lizards'},
        ['Stone Eater'] = { Name='Stone Eater', Ecosystem='amorphs', Family='worms'},
        ['Teporingo'] = { Name='Teporingo', Ecosystem='beats', Family='rabbits'},
        ['Thread Leech'] = { Name='Thread Leech', Ecosystem='amorphs', Family='leeches'},
        ['Trimmer'] = { Name='Trimmer', Ecosystem='aquans', Family='crabs'},
        ['Wadi Crab'] = { Name='Wadi Crab', Ecosystem='aquans', Family='crabs'},
        ['Wadi Hare'] = { Name='Wadi Hare', Ecosystem='beasts', Family='rabbits'},
        ['Wadi Leech'] = { Name='Wadi Leech', Ecosystem='amorphs', Family='leeches'},
        ['Witchetty Grub'] = { Name='Witchetty Grub', Ecosystem='amorphs', Family='worms'},
    },
};
