--Zone: Ordelle's Caves
--Zone ID: 193
return {
    Names = {
        ['Agar Agar'] = { Name='Agar Agar', Ecosystem='amorphs', Family='slimes'},
        ['Air Elemental'] = { Name='Air Elemental', Ecosystem='elementals', Family='elementals'},
        ['Ancient Bat'] = { Name='Ancient Bat', Ecosystem='birds', Family='bats'},
        ['Aroma Leech'] = { Name='Aroma Leech', Ecosystem='amorphs', Family='leeches'},
        ['Bilis Leech'] = { Name='Bilis Leech', Ecosystem='amorphs', Family='leeches'},
        ['Blood Bunny'] = { Name='Blood Bunny', Ecosystem='beasts', Family='rabbits'},
        ['Bombast'] = { Name='Bombast', Ecosystem='arcana', Family='bombs'},
        ['Buds Bunny'] = { Name='Buds Bunny', Ecosystem='beasts', Family='rabbits'},
        ['Clipper'] = { Name='Clipper', Ecosystem='aquans', Family='crabs'},
        ['Donggu'] = { Name='Donggu', Ecosystem='plantoids', Family='funguars'},
        ['Dung Beetle'] = { Name='Dung Beetle', Ecosystem='vermin', Family='beetles'},
        ['Fly Agaric'] = { Name='Fly Agaric', Ecosystem='vermin', Family='flies'},
        ['Gerwitz\'s Axe'] = { Name='Gerwitz\'s Axe', Ecosystem='arcana', Family='evil weapons'},
        ['Gerwitz\'s Soul'] = { Name='Gerwitz\'s Soul', Ecosystem='undead', Family='ghosts'},
        ['Gerwitz\'s Sword'] = { Name='Gerwitz\'s Sword', Ecosystem='arcana', Family='evil weapons'},
        ['Goblin Ambusher'] = { Name='Goblin Ambusher', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Butcher'] = { Name='Goblin Butcher', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Furrier'] = { Name='Goblin Furrier', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Gambler'] = { Name='Goblin Gambler', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Leecher'] = { Name='Goblin Leecher', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Mugger'] = { Name='Goblin Mugger', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Pathfinder'] = { Name='Goblin Pathfinder', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Shaman'] = { Name='Goblin Shaman', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Smithy'] = { Name='Goblin Smithy', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Tinkerer'] = { Name='Goblin Tinkerer', Ecosystem='beastmen', Family='goblins'},
        ['Goblin\'s Bats'] = { Name='Goblin\'s Bats', Ecosystem='birds', Family='bat trios'},
        ['Goliath Beetle'] = { Name='Goliath Beetle', Ecosystem='vermin', Family='beetles'},
        ['Hognosed Bat'] = { Name='Hognosed Bat', Ecosystem='birds', Family='bats'},
        ['Jelly'] = { Name='Jelly', Ecosystem='amorphs', Family='slimes'},
        ['Krabimanjaro'] = { Name='Krabimanjaro', Ecosystem='aquans', Family='crabs'},
        ['Metallic Slime'] = { Name='Metallic Slime', Ecosystem='amorphs', Family='slimes'},
        ['Morbolger'] = { Name='Morbolger', Ecosystem='plantoids', Family='morbols'},
        ['Napalm'] = { Name='Napalm', Ecosystem='arcana', Family='bombs'},
        ['Necroplasm'] = { Name='Necroplasm', Ecosystem='undead', Family='doomed'},
        ['Poison Leech'] = { Name='Poison Leech', Ecosystem='amorphs', Family='leeches'},
        ['Polevik'] = { Name='Polevik', Ecosystem='elementals', Family='elementals'},
        ['Rancid Ooze'] = { Name='Rancid Ooze', Ecosystem='amorphs', Family='slimes'},
        ['Seeker Bats'] = { Name='Seeker Bats', Ecosystem='birds', Family='bat trios'},
        ['Shrieker'] = { Name='Shrieker', Ecosystem='plantoids', Family='funguars'},
        ['Slash Pine'] = { Name='Slash Pine', Ecosystem='plantoids', Family='saplings'},
        ['Snipper'] = { Name='Snipper', Ecosystem='aquans', Family='crabs'},
        ['Stag Crab'] = { Name='Stag Crab', Ecosystem='aquans', Family='crabs'},
        ['Stalking Sapling'] = { Name='Stalking Sapling', Ecosystem='plantoids', Family='saplings'},
        ['Stink Bats'] = { Name='Stink Bats', Ecosystem='birds', Family='bat trios'},
        ['Stroper'] = { Name='Stroper', Ecosystem='plantoids', Family='Morbols'},
        ['Stroper Chyme'] = { Name='Stroper Chyme', Ecosystem='amorphs', Family='slimes'},
        ['Swagger Spruce'] = { Name='Swagger Spruce', Ecosystem='plantoids', Family='saplings'},
        ['Targe Beetle'] = { Name='Targe Beetle', Ecosystem='vermin', Family='beetles'},
        ['Thread Leech'] = { Name='Thread Leech', Ecosystem='amorphs', Family='leeches'},
        ['Vorpal Bunny'] = { Name='Vorpal Bunny', Ecosystem='beasts', Family='rabbits'},
        ['Water Elemental'] = { Name='Water Elemental', Ecosystem='elementals', Family='elementals'},
        ['Will-o\'-the-Wisp'] = { Name='Will-o\'-the-Wisp', Ecosystem='arcana', Family='bombs'},
    },
};
