--Zone: Outer Horutoto Ruins
--Zone ID: 194
return {
    Names = {
        ['Ah Puch'] = { Name='Ah Puch', Ecosystem='undead', Family='skeletons'},
        ['Balloon'] = { Name='Balloon', Ecosystem='arcana', Family='bombs'},
        ['Battue Bats'] = { Name='Battue Bats', Ecosystem='birds', Family='bat trios'},
        ['Black Slime'] = { Name='Black Slime', Ecosystem='amorphs', Family='slimes'},
        ['Blade Bat'] = { Name='Blade Bat', Ecosystem='birds', Family='bats'},
        ['Bomb King'] = { Name='Bomb King', Ecosystem='arcana', Family='bombs'},
        ['Combat'] = { Name='Combat', Ecosystem='birds', Family='bats'},
        ['Custom Cardian'] = { Name='Custom Cardian', Ecosystem='arcana', Family='cardians'},
        ['Dancing Weapon'] = { Name='Dancing Weapon', Ecosystem='arcana', Family='evil weapons'},
        ['Desmodont'] = { Name='Desmodont', Ecosystem='birds', Family='bats'},
        ['Doppelganger Dio'] = { Name='Doppelganger Dio', Ecosystem='undead', Family='fomors'},
        ['Doppelganger Gog'] = { Name='Doppelganger Gog', Ecosystem='undead', Family='fomors'},
        ['Eight of Batons'] = { Name='Eight of Batons', Ecosystem='arcana', Family='cardians'},
        ['Eight of Coins'] = { Name='Eight of Coins', Ecosystem='arcana', Family='cardians'},
        ['Eight of Cups'] = { Name='Eight of Cups', Ecosystem='arcana', Family='cardians'},
        ['Eight of Swords'] = { Name='Eight of Swords', Ecosystem='arcana', Family='cardians'},
        ['Fetor Bats'] = { Name='Fetor Bats', Ecosystem='birds', Family='bat trios'},
        ['Five of Batons'] = { Name='Five of Batons', Ecosystem='arcana', Family='cardians'},
        ['Five of Coins'] = { Name='Five of Coins', Ecosystem='arcana', Family='cardians'},
        ['Five of Cups'] = { Name='Five of Cups', Ecosystem='arcana', Family='cardians'},
        ['Five of Swords'] = { Name='Five of Swords', Ecosystem='arcana', Family='cardians'},
        ['Four of Batons'] = { Name='Four of Batons', Ecosystem='arcana', Family='cardians'},
        ['Four of Coins'] = { Name='Four of Coins', Ecosystem='arcana', Family='cardians'},
        ['Four of Cups'] = { Name='Four of Cups', Ecosystem='arcana', Family='cardians'},
        ['Four of Swords'] = { Name='Four of Swords', Ecosystem='arcana', Family='cardians'},
        ['Fuligo'] = { Name='Fuligo', Ecosystem='amorphs', Family='slimes'},
        ['Ghoul'] = { Name='Ghoul', Ecosystem='undead', Family='skeletons'},
        ['Goblin Ambusher'] = { Name='Goblin Ambusher', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Butcher'] = { Name='Goblin Butcher', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Thug'] = { Name='Goblin Thug', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Tinkerer'] = { Name='Goblin Tinkerer', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Weaver'] = { Name='Goblin Weaver', Ecosystem='beastmen', Family='goblins'},
        ['Jack of Batons'] = { Name='Jack of Batons', Ecosystem='arcana', Family='cardians'},
        ['Jack of Coins'] = { Name='Jack of Coins', Ecosystem='arcana', Family='cardians'},
        ['Jack of Cups'] = { Name='Jack of Cups', Ecosystem='arcana', Family='cardians'},
        ['Jack of Swords'] = { Name='Jack of Swords', Ecosystem='arcana', Family='cardians'},
        ['Legalox Heftyhind'] = { Name='Legalox Heftyhind', Ecosystem='beastmen', Family='goblins'},
        ['Nine of Batons'] = { Name='Nine of Batons', Ecosystem='arcana', Family='cardians'},
        ['Nine of Coins'] = { Name='Nine of Coins', Ecosystem='arcana', Family='cardians'},
        ['Nine of Cups'] = { Name='Nine of Cups', Ecosystem='arcana', Family='cardians'},
        ['Nine of Swords'] = { Name='Nine of Swords', Ecosystem='arcana', Family='cardians'},
        ['Queen of Coins'] = { Name='Queen of Coins', Ecosystem='arcana', Family='cardians'},
        ['Queen of Swords'] = { Name='Queen of Swords', Ecosystem='arcana', Family='cardians'},
        ['Rotten Jam'] = { Name='Rotten Jam', Ecosystem='amorphs', Family='slimes'},
        ['Seven of Batons'] = { Name='Seven of Batons', Ecosystem='arcana', Family='cardians'},
        ['Seven of Coins'] = { Name='Seven of Coins', Ecosystem='arcana', Family='cardians'},
        ['Seven of Cups'] = { Name='Seven of Cups', Ecosystem='arcana', Family='cardians'},
        ['Seven of Swords'] = { Name='Seven of Swords', Ecosystem='arcana', Family='cardians'},
        ['Six of Batons'] = { Name='Six of Batons', Ecosystem='arcana', Family='cardians'},
        ['Six of Coins'] = { Name='Six of Coins', Ecosystem='arcana', Family='cardians'},
        ['Six of Cups'] = { Name='Six of Cups', Ecosystem='arcana', Family='cardians'},
        ['Six of Swords'] = { Name='Six of Swords', Ecosystem='arcana', Family='cardians'},
        ['Stink Bats'] = { Name='Stink Bats', Ecosystem='birds', Family='bat trios'},
        ['Ten of Batons'] = { Name='Ten of Batons', Ecosystem='arcana', Family='cardians'},
        ['Ten of Coins'] = { Name='Ten of Coins', Ecosystem='arcana', Family='cardians'},
        ['Ten of Cups'] = { Name='Ten of Cups', Ecosystem='arcana', Family='cardians'},
        ['Ten of Swords'] = { Name='Ten of Swords', Ecosystem='arcana', Family='cardians'},
        ['Thorn Bat'] = { Name='Thorn Bat', Ecosystem='birds', Family='bats'},
        ['Three of Batons'] = { Name='Three of Batons', Ecosystem='arcana', Family='cardians'},
        ['Three of Coins'] = { Name='Three of Coins', Ecosystem='arcana', Family='cardians'},
        ['Three of Cups'] = { Name='Three of Cups', Ecosystem='arcana', Family='cardians'},
        ['Three of Swords'] = { Name='Three of Swords', Ecosystem='arcana', Family='cardians'},
        ['Thunder Elemental'] = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals'},
        ['Two of Batons'] = { Name='Two of Batons', Ecosystem='arcana', Family='cardians'},
        ['Two of Coins'] = { Name='Two of Coins', Ecosystem='arcana', Family='cardians'},
        ['Two of Cups'] = { Name='Two of Cups', Ecosystem='arcana', Family='cardians'},
        ['Two of Swords'] = { Name='Two of Swords', Ecosystem='arcana', Family='cardians'},
        ['Voidwrought'] = { Name='Voidwrought', Ecosystem='archaic machines', Family='iron giants'},
    },
};
