--Zone: The Eldieme Necropolis
--Zone ID: 195
return {
    Names = {
        ['Anemone'] = { Name='Anemone', Ecosystem='plantoids', Family='morbols'},
        ['Azer'] = { Name='Azer', Ecosystem='arcana', Family='bombs'},
        ['Blood Soul'] = { Name='Blood Soul', Ecosystem='undead', Family='ghosts'},
        ['Cwn Cyrff'] = { Name='Cwn Cyrff', Ecosystem='undead', Family='hounds'},
        ['Dark Stalker'] = { Name='Dark Stalker', Ecosystem='undead', Family='shadows'},
        ['Dog Guardian'] = { Name='Dog Guardian', Ecosystem='undead', Family='hounds'},
        ['Earth Elemental'] = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals'},
        ['Fallen Knight'] = { Name='Fallen Knight', Ecosystem='undead', Family='skeletons'},
        ['Gasha'] = { Name='Gasha', Ecosystem='undead', Family='skeletons'},
        ['Gazer'] = { Name='Gazer', Ecosystem='amorphs', Family='hecteyes'},
        ['Haunt'] = { Name='Haunt', Ecosystem='undead', Family='ghosts'},
        ['Hell Hound'] = { Name='Hell Hound', Ecosystem='undead', Family='hounds'},
        ['Hellbound Warlock'] = { Name='Hellbound Warlock', Ecosystem='undead', Family='skeletons'},
        ['Hellbound Warrior'] = { Name='Hellbound Warrior', Ecosystem='undead', Family='skeletons'},
        ['Ice Elemental'] = { Name='Ice Elemental', Ecosystem='elementals', Family='elementals'},
        ['Ka'] = { Name='Ka', Ecosystem='undead', Family='shadows'},
        ['Lich'] = { Name='Lich', Ecosystem='undead', Family='skeletons'},
        ['Lich C Magnus'] = { Name='Lich C Magnus', Ecosystem='undead', Family='skeletons'},
        ['Lost Soul'] = { Name='Lost Soul', Ecosystem='undead', Family='skeletons'},
        ['Marchosias'] = { Name='Marchosias', Ecosystem='undead', Family='hounds'},
        ['Mimic'] = { Name='Mimic', Ecosystem='amorphs', Family='mimics'},
        ['Mummy'] = { Name='Mummy', Ecosystem='undead', Family='skeletons'},
        ['Namorodo'] = { Name='Namorodo', Ecosystem='undead', Family='skeletons'},
        ['Nekros Hound'] = { Name='Nekros Hound', Ecosystem='undead', Family='hounds'},
        ['Owl Guardian'] = { Name='Owl Guardian', Ecosystem='undead', Family='skeletons'},
        ['Puroboros'] = { Name='Puroboros', Ecosystem='arcana', Family='bombs'},
        ['Revenant'] = { Name='Revenant', Ecosystem='undead', Family='ghosts'},
        ['Shade'] = { Name='Shade', Ecosystem='undead', Family='shadows'},
        ['Skull of Envy'] = { Name='Skull of Envy', Ecosystem='undead', Family='skeletons'},
        ['Skull of Gluttony'] = { Name='Skull of Gluttony', Ecosystem='undead', Family='skeletons'},
        ['Skull of Greed'] = { Name='Skull of Greed', Ecosystem='undead', Family='skeletons'},
        ['Skull of Lust'] = { Name='Skull of Lust', Ecosystem='undead', Family='skeletons'},
        ['Skull of Pride'] = { Name='Skull of Pride', Ecosystem='undead', Family='skeletons'},
        ['Skull of Sloth'] = { Name='Skull of Sloth', Ecosystem='undead', Family='skeletons'},
        ['Skull of Wrath'] = { Name='Skull of Wrath', Ecosystem='undead', Family='skeletons'},
        ['Spriggan'] = { Name='Spriggan', Ecosystem='undead', Family='shadows'},
        ['Sturm'] = { Name='Sturm', Ecosystem='undead', Family='hounds'},
        ['Taifun'] = { Name='Taifun', Ecosystem='beasts', Family='tigers'},
        ['Tomb Mage'] = { Name='Tomb Mage', Ecosystem='undead', Family='skeletons'},
        ['Tomb Warrior'] = { Name='Tomb Warrior', Ecosystem='undead', Family='skeletons'},
        ['Tomb Wolf'] = { Name='Tomb Wolf', Ecosystem='undead', Family='hounds'},
        ['Trombe'] = { Name='Trombe', Ecosystem='beasts', Family='tigers'},
        ['Utukku'] = { Name='Utukku', Ecosystem='undead', Family='ghosts'},
        ['Yum Kimil'] = { Name='Yum Kimil', Ecosystem='undead', Family='skeletons'},
    },
};
