--Zone: Gusgen Mines
--Zone ID: 196
return {
    Names = {
        ['Accursed Soldier'] = { Name='Accursed Soldier', Ecosystem='undead', Family='skeletons'},
        ['Accursed Sorcerer'] = { Name='Accursed Sorcerer', Ecosystem='undead', Family='skeletons'},
        ['Amphisbaena'] = { Name='Amphisbaena', Ecosystem='amorphs', Family='worms'},
        ['Aroma Fly'] = { Name='Aroma Fly', Ecosystem='vermin', Family='flies'},
        ['Asphyxiated Amsel'] = { Name='Asphyxiated Amsel', Ecosystem='undead', Family='ghosts'},
        ['Bandersnatch'] = { Name='Bandersnatch', Ecosystem='undead', Family='hounds'},
        ['Banshee'] = { Name='Banshee', Ecosystem='undead', Family='ghosts'},
        ['Blind Moby'] = { Name='Blind Moby', Ecosystem='aquans', Family='pugils'},
        ['Bogy'] = { Name='Bogy', Ecosystem='undead', Family='ghosts'},
        ['Burned Bergmann'] = { Name='Burned Bergmann', Ecosystem='undead', Family='ghosts'},
        ['Crushed Krause'] = { Name='Crushed Krause', Ecosystem='undead', Family='ghosts'},
        ['Earth Elemental'] = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals'},
        ['Feu Follet'] = { Name='Feu Follet', Ecosystem='arcana', Family='bombs'},
        ['Fly Agaric'] = { Name='Fly Agaric', Ecosystem='vermin', Family='flies'},
        ['Foul Meat'] = { Name='Foul Meat', Ecosystem='undead', Family='doomed'},
        ['Gallinipper'] = { Name='Gallinipper', Ecosystem='vermin', Family='flies'},
        ['Ghast'] = { Name='Ghast', Ecosystem='undead', Family='skeletons'},
        ['Ghoul'] = { Name='Ghoul', Ecosystem='undead', Family='skeletons'},
        ['Greater Pugil'] = { Name='Greater Pugil', Ecosystem='aquans', Family='pugils'},
        ['Jelly'] = { Name='Jelly', Ecosystem='amorphs', Family='slimes'},
        ['Juggler Hecatomb'] = { Name='Juggler Hecatomb', Ecosystem='arcana', Family='evil weapons'},
        ['Lorbulcrud'] = { Name='Lorbulcrud', Ecosystem='amorphs', Family='slimes'},
        ['Madfly'] = { Name='Madfly', Ecosystem='vermin', Family='flies'},
        ['Mauthe Doog'] = { Name='Mauthe Doog', Ecosystem='undead', Family='hounds'},
        ['Mush'] = { Name='Mush', Ecosystem='amorphs', Family='slimes'},
        ['Myconid'] = { Name='Myconid', Ecosystem='plantoids', Family='funguars'},
        ['Ooze'] = { Name='Ooze', Ecosystem='amorphs', Family='slimes'},
        ['Ore Eater'] = { Name='Ore Eater', Ecosystem='amorphs', Family='worms'},
        ['Pirate Pugil'] = { Name='Pirate Pugil', Ecosystem='aquans', Family='pugils'},
        ['Pudding'] = { Name='Pudding', Ecosystem='amorphs', Family='slimes'},
        ['Pulverized Pfeffer'] = { Name='Pulverized Pfeffer', Ecosystem='undead', Family='ghosts'},
        ['Rancid Ooze'] = { Name='Rancid Ooze', Ecosystem='amorphs', Family='oozes'},
        ['Rockmill'] = { Name='Rockmill', Ecosystem='amorphs', Family='worms'},
        ['Sadfly'] = { Name='Sadfly', Ecosystem='vermin', Family='flies'},
        ['Skeleton Warrior'] = { Name='Skeleton Warrior', Ecosystem='undead', Family='skeletons'},
        ['Smothered Schmidt'] = { Name='Smothered Schmidt', Ecosystem='undead', Family='ghosts'},
        ['Spunkie'] = { Name='Spunkie', Ecosystem='arcana', Family='bombs'},
        ['Thunder Elemental'] = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals'},
        ['Wandering Ghost'] = { Name='Wandering Ghost', Ecosystem='undead', Family='ghosts'},
        ['Wendigo'] = { Name='Wendigo', Ecosystem='undead', Family='skeletons'},
        ['Wight'] = { Name='Wight', Ecosystem='undead', Family='skeletons'},
        ['Wounded Wurfel'] = { Name='Wounded Wurfel', Ecosystem='undead', Family='ghosts'},
    },
};
