--Zone: Garlaige Citadel
--Zone ID: 200
return {
    Names = {
        ['Acid Grease'] = { Name='Acid Grease', Ecosystem='amorphs', Family='slimes' },
        ['Bhuta'] = { Name='Bhuta', Ecosystem='undead', Family='ghosts' },
        ['Borer Beetle'] = { Name='Borer Beetle', Ecosystem='vermin', Family='beetles' },
        ['Chamber Beetle'] = { Name='Chamber Beetle', Ecosystem='vermin', Family='beetles' },
        ['Chandelier'] = { Name='Chandelier', Ecosystem='arcana', Family='bombs' },
        ['Citadel Bats'] = { Name='Citadel Bats', Ecosystem='birds', Family='bat trios' },
        ['Clockwork Pod'] = { Name='Clockwork Pod', Ecosystem='arcana', Family='magic pots' },
        ['Demonic Weapon'] = { Name='Demonic Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Donjon Bat'] = { Name='Donjon Bat', Ecosystem='birds', Family='bats' },
        ['Droma'] = { Name='Droma', Ecosystem='arcana', Family='magic pots' },
        ['Earth Elemental'] = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Explosure'] = { Name='Explosure', Ecosystem='arcana', Family='bombs' },
        ['Fallen Evacuee'] = { Name='Fallen Evacuee', Ecosystem='undead', Family='skeletons' },
        ['Fallen Mage'] = { Name='Fallen Mage', Ecosystem='undead', Family='skeletons' },
        ['Fallen Major'] = { Name='Fallen Major', Ecosystem='undead', Family='skeletons' },
        ['Fallen Officer'] = { Name='Fallen Officer', Ecosystem='undead', Family='skeletons' },
        ['Fallen Soldier'] = { Name='Fallen Soldier', Ecosystem='undead', Family='skeletons' },
        ['Fetid Flesh'] = { Name='Fetid Flesh', Ecosystem='undead', Family='doomed' },
        ['Fortalice Bats'] = { Name='Fortalice Bats', Ecosystem='birds', Family='bat trios' },
        ['Frogamander'] = { Name='Frogamander', Ecosystem='undead', Family='doomed' },
        ['Funnel Bats'] = { Name='Funnel Bats', Ecosystem='birds', Family='bat trios' },
        ['Guardian Statue'] = { Name='Guardian Statue', Ecosystem='arcana', Family='dolls' },
        ['Hazmat'] = { Name='Hazmat', Ecosystem='arcana', Family='bombs' },
        ['Hellmine'] = { Name='Hellmine', Ecosystem='arcana', Family='bombs' },
        ['Hovering Hotpot'] = { Name='Hovering Hotpot', Ecosystem='arcana', Family='magic pots' },
        ['Kaboom'] = { Name='Kaboom', Ecosystem='arcana', Family='bombs' },
        ['Light Elemental'] = { Name='Light Elemental', Ecosystem='elementals', Family='elementals' },
        ['Magic Jug'] = { Name='Magic Jug', Ecosystem='arcana', Family='magic pots' },
        ['Mephitas'] = { Name='Mephitas', Ecosystem='vermin', Family='scorpions' },
        ['Mimic'] = { Name='Mimic', Ecosystem='arcana', Family='mimics' },
        ['Oil Spill'] = { Name='Oil Spill', Ecosystem='amorphs', Family='slimes' },
        ['Old Two-Wings'] = { Name='Old Two-Wings', Ecosystem='birds', Family='bats' },
        ['Over Weapon'] = { Name='Over Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Puroboros'] = { Name='Puroboros', Ecosystem='arcana', Family='bombs' },
        ['Revenant'] = { Name='Revenant', Ecosystem='undead', Family='ghosts' },
        ['Roly-Poly'] = { Name='Roly-Poly', Ecosystem='amorphs', Family='flans' },
        ['Serket'] = { Name='Serket', Ecosystem='vermin', Family='scorpions' },
        ['Siege Bat'] = { Name='Siege Bat', Ecosystem='birds', Family='bats' },
        ['Skewer Sam'] = { Name='Skewer Sam', Ecosystem='birds', Family='cockatrices' },
        ['Tainted Flesh'] = { Name='Tainted Flesh', Ecosystem='undead', Family='doomed' },
        ['Thunder Elemental'] = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
        ['Vault Weapon'] = { Name='Vault Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Warden Beetle'] = { Name='Warden Beetle', Ecosystem='vermin', Family='beetles' },
        ['Wingrats'] = { Name='Wingrats', Ecosystem='birds', Family='bat trios' },
        ['Wraith'] = { Name='Wraith', Ecosystem='undead', Family='ghosts' },
    },
};
