--Zone: Fei'Yin
--Zone ID: 204
return {
    Names = {
        ['Altedour I Tavnazia'] = { Name='Altedour I Tavnazia', Ecosystem='undead', Family='shadows' },
        ['Arcus Blades'] = { Name='Arcus Blades', Ecosystem='unclassified', Family='animated weapons' },
        ['Australis Shadow'] = { Name='Australis Shadow', Ecosystem='undead', Family='shadows' },
        ['Balayang'] = { Name='Balayang', Ecosystem='birds', Family='bats' },
        ['Borealis Shadow'] = { Name='Borealis Shadow', Ecosystem='undead', Family='shadows' },
        ['Camazotz'] = { Name='Camazotz', Ecosystem='birds', Family='bats' },
        ['Capricious Cassie'] = { Name='Capricious Cassie', Ecosystem='plantoids', Family='morbols' },
        ['Carousing Celine'] = { Name='Carousing Celine', Ecosystem='plantoids', Family='morbols' },
        ['Clockwork Pod'] = { Name='Clockwork Pod', Ecosystem='arcana', Family='magic pots' },
        ['Colossus'] = { Name='Colossus', Ecosystem='arcana', Family='golems' },
        ['Dabotz\'s Ghost'] = { Name='Dabotz\'s Ghost', Ecosystem='undead', Family='ghosts' },
        ['Dark Elemental'] = { Name='Dark Elemental', Ecosystem='elementals', Family='elementals' },
        ['Droma'] = { Name='Droma', Ecosystem='arcana', Family='magic pots' },
        ['Drone'] = { Name='Drone', Ecosystem='arcana', Family='dolls' },
        ['Eastern Shadow'] = { Name='Eastern Shadow', Ecosystem='undead', Family='shadows' },
        ['Goliath'] = { Name='Goliath', Ecosystem='arcana', Family='golems' },
        ['Hellish Weapon'] = { Name='Hellish Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Ice Elemental'] = { Name='Ice Elemental', Ecosystem='elementals', Family='elementals' },
        ['Jenglot'] = { Name='Jenglot', Ecosystem='arcana', Family='dolls' },
        ['Killing Weapon'] = { Name='Killing Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Mind Hoarder'] = { Name='Mind Hoarder', Ecosystem='arcana', Family='magic pots' },
        ['Miser Murphy'] = { Name='Miser Murphy', Ecosystem='undead', Family='ghosts' },
        ['Northern Shadow'] = { Name='Northern Shadow', Ecosystem='undead', Family='shadows' },
        ['Occidentalis Shadow'] = { Name='Occidentalis Shadow', Ecosystem='undead', Family='shadows' },
        ['Ore Golem'] = { Name='Ore Golem', Ecosystem='arcana', Family='golems' },
        ['Orientalis Shadow'] = { Name='Orientalis Shadow', Ecosystem='undead', Family='shadows' },
        ['Revenant'] = { Name='Revenant', Ecosystem='undead', Family='ghosts' },
        ['Sentient Carafe'] = { Name='Sentient Carafe', Ecosystem='arcana', Family='magic pots' },
        ['Shadow'] = { Name='Shadow', Ecosystem='undead', Family='shadows' },
        ['Sluagh'] = { Name='Sluagh', Ecosystem='undead', Family='ghosts' },
        ['Southern Shadow'] = { Name='Southern Shadow', Ecosystem='undead', Family='shadows' },
        ['Specter'] = { Name='Specter', Ecosystem='undead', Family='shadows' },
        ['Talos'] = { Name='Talos', Ecosystem='arcana', Family='dolls' },
        ['Undead Bats'] = { Name='Undead Bats', Ecosystem='birds', Family='bat trios' },
        ['Underworld Bats'] = { Name='Underworld Bats', Ecosystem='birds', Family='bat trios' },
        ['Utukku'] = { Name='Utukku', Ecosystem='undead', Family='ghosts' },
        ['Vampire Bat'] = { Name='Vampire Bat', Ecosystem='birds', Family='bats' },
        ['Wekufe'] = { Name='Wekufe', Ecosystem='undead', Family='ghosts' },
        ['Western Shadow'] = { Name='Western Shadow', Ecosystem='undead', Family='shadows' },
    },
};
