--Zone: Ifrit's Cauldron
--Zone ID: 205
return {
    Names = {
        ['Ash Dragon'] = { Name='Ash Dragon', Ecosystem='dragons', Family='dragons' },
        ['Ash Lizard'] = { Name='Ash Lizard', Ecosystem='lizards', Family='lizards' },
        ['Bomb Bastard'] = { Name='Bomb Bastard', Ecosystem='arcana', Family='bombs' },
        ['Bomb Prince'] = { Name='Bomb Prince', Ecosystem='arcana', Family='bombs' },
        ['Bomb Princess'] = { Name='Bomb Princess', Ecosystem='arcana', Family='bombs' },
        ['Bomb Queen'] = { Name='Bomb Queen', Ecosystem='arcana', Family='bombs' },
        ['Cailleach Bheur'] = { Name='Cailleach Bheur', Ecosystem='undead', Family='skeletons' },
        ['Coca'] = { Name='Coca', Ecosystem='dragons', Family='wyverns' },
        ['Dire Bat'] = { Name='Dire Bat', Ecosystem='birds', Family='bats' },
        ['Dodomeki'] = { Name='Dodomeki', Ecosystem='amorphs', Family='hecteyes' },
        ['Eotyrannus'] = { Name='Eotyrannus', Ecosystem='lizards', Family='raptors' },
        ['Foreseer Oramix'] = { Name='Foreseer Oramix', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Alchemist'] = { Name='Goblin Alchemist', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Bandit'] = { Name='Goblin Bandit', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Mercenary'] = { Name='Goblin Mercenary', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Shepherd'] = { Name='Goblin Shepherd', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Bats'] = { Name='Goblin\'s Bats', Ecosystem='birds', Family='bat trios' },
        ['Hraun Dragon'] = { Name='Hraun Dragon', Ecosystem='dragons', Family='dragons' },
        ['Hurricane Wyvern'] = { Name='Hurricane Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Ildebrann'] = { Name='Ildebrann', Ecosystem='dragons', Family='wyrms' },
        ['Lindwurm'] = { Name='Lindwurm', Ecosystem='lizards', Family='raptors' },
        ['Magma'] = { Name='Magma', Ecosystem='arcana', Family='bombs' },
        ['Mimic'] = { Name='Mimic', Ecosystem='arcana', Family='mimics' },
        ['Nightmare Bats'] = { Name='Nightmare Bats', Ecosystem='birds', Family='bat trios' },
        ['Old Opo-opo'] = { Name='Old Opo-opo', Ecosystem='beasts', Family='opo-opos' },
        ['Salamander'] = { Name='Salamander', Ecosystem='lizards', Family='lizards' },
        ['Sulfur Scorpion'] = { Name='Sulfur Scorpion', Ecosystem='vermin', Family='scorpions' },
        ['Tarasque'] = { Name='Tarasque', Ecosystem='lizards', Family='lizards' },
        ['Tyrannic Tunnok'] = { Name='Tyrannic Tunnok', Ecosystem='vermin', Family='scorpions' },
        ['Volcanic Bomb'] = { Name='Volcanic Bomb', Ecosystem='arcana', Family='bombs' },
        ['Volcanic Gas'] = { Name='Volcanic Gas', Ecosystem='arcana', Family='bombs' },
        ['Volcano Wasp'] = { Name='Volcano Wasp', Ecosystem='vermin', Family='bees' },
        ['Vouivre'] = { Name='Vouivre', Ecosystem='dragons', Family='wyverns' },
        -- Custom content for HorizonXI
        ['Cauldron Eruca'] = { Name='Cauldron Eruca', Ecosystem='vermin', Family='crawlers' },
    },
};
