--Zone: Qu'Bia Arena
--Zone ID: 206
return {
    Names = {
        ['Adam'] = { Name='Adam', Ecosystem='unclassified', Family='unknowns' },
        ['Air Pot'] = { Name='Air Pot', Ecosystem='arcana', Family='magic pots' },
        ['Anansi'] = { Name='Anansi', Ecosystem='vermin', Family='spiders' },
        ['Ancient Sorcerer'] = { Name='Ancient Sorcerer', Ecosystem='undead', Family='skeletons' },
        ['Ancient Warrior'] = { Name='Ancient Warrior', Ecosystem='undead', Family='skeletons' },
        ['Annihilated Anthony'] = { Name='Annihilated Anthony', Ecosystem='undead', Family='ghosts' },
        ['Archlich Taber\'quoan'] = { Name='Archlich Taber\'quoan', Ecosystem='undead', Family='skeletons' },
        ['Atori-Tutori ???'] = { Name='Atori-Tutori ???', Ecosystem='humanoids', Family='tarutaru' },
        ['Beelzebub'] = { Name='Beelzebub', Ecosystem='vermin', Family='bees' },
        ['Capelthwaite'] = { Name='Capelthwaite', Ecosystem='undead', Family='hounds' },
        ['Chahnameed'] = { Name='Chahnameed', Ecosystem='undead', Family='doomed' },
        ['Chahnameed\'s Intestines'] = { Name='Chahnameed\'s Intestines', Ecosystem='undead', Family='doomed' },
        ['Chahnameed\'s Liver'] = { Name='Chahnameed\'s Liver', Ecosystem='undead', Family='doomed' },
        ['Chahnameed\'s Stomach'] = { Name='Chahnameed\'s Stomach', Ecosystem='undead', Family='doomed' },
        ['Crabshaw'] = { Name='Crabshaw', Ecosystem='aquans', Family='crabs' },
        ['Death Clan Destroyer'] = { Name='Death Clan Destroyer', Ecosystem='beastmen', Family='orcish warmachines' },
        ['Disfaurit B D\'Aurphe'] = { Name='Disfaurit B D\'Aurphe', Ecosystem='undead', Family='fomors' },
        ['Doll Factory'] = { Name='Doll Factory', Ecosystem='arcana', Family='dolls' },
        ['Earth Golem'] = { Name='Earth Golem', Ecosystem='arcana', Family='golems' },
        ['Earth Pot'] = { Name='Earth Pot', Ecosystem='arcana', Family='magic pots' },
        ['Fire Golem'] = { Name='Fire Golem', Ecosystem='arcana', Family='golems' },
        ['Fire Pot'] = { Name='Fire Pot', Ecosystem='arcana', Family='magic pots' },
        ['Freybug'] = { Name='Freybug', Ecosystem='undead', Family='hounds' },
        ['Generic Doll'] = { Name='Generic Doll', Ecosystem='arcana', Family='dolls' },
        ['Ghul-I-Beaban'] = { Name='Ghul-I-Beaban', Ecosystem='undead', Family='skeletons' },
        ['Gladiatorial Weapon'] = { Name='Gladiatorial Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Guytrash'] = { Name='Guytrash', Ecosystem='undead', Family='hounds' },
        ['Hell Fly'] = { Name='Hell Fly', Ecosystem='vermin', Family='bees' },
        ['Ice Pot'] = { Name='Ice Pot', Ecosystem='arcana', Family='magic pots' },
        ['Jeumouque B D\'Aurphe'] = { Name='Jeumouque B D\'Aurphe', Ecosystem='undead', Family='fomors' },
        ['Laila'] = { Name='Laila', Ecosystem='humanoids', Family='humes' },
        ['Maat'] = { Name='Maat', Ecosystem='humanoids', Family='humes' },
        ['Maldaramet B D\'Aurphe'] = { Name='Maldaramet B D\'Aurphe', Ecosystem='undead', Family='fomors' },
        ['Mauled Murdock'] = { Name='Mauled Murdock', Ecosystem='undead', Family='ghosts' },
        ['Nephiyl Keepcollapser'] = { Name='Nephiyl Keepcollapser', Ecosystem='beastmen', Family='gigas' },
        ['Nephiyl Moatfiller'] = { Name='Nephiyl Moatfiller', Ecosystem='beastmen', Family='gigas' },
        ['Nephiyl Pinnacletosser'] = { Name='Nephiyl Pinnacletosser', Ecosystem='beastmen', Family='gigas' },
        ['Nephiyl Rampartbreacher'] = { Name='Nephiyl Rampartbreacher', Ecosystem='beastmen', Family='gigas' },
        ['Punctured Percy'] = { Name='Punctured Percy', Ecosystem='undead', Family='ghosts' },
        ['Rallbrog of Clan Death'] = { Name='Rallbrog of Clan Death', Ecosystem='beastmen', Family='orcs' },
        ['Rojgnoj\'s Left Hand'] = { Name='Rojgnoj\'s Left Hand', Ecosystem='beastmen', Family='orcs' },
        ['Rojgnoj\'s Right Hand'] = { Name='Rojgnoj\'s Right Hand', Ecosystem='beastmen', Family='orcs' },
        ['Rongeur D\'os'] = { Name='Rongeur D\'os', Ecosystem='undead', Family='hounds' },
        ['Seed Goblin'] = { Name='Seed Goblin', Ecosystem='beastmen', Family='goblins' },
        ['Seed Orc'] = { Name='Seed Orc', Ecosystem='beastmen', Family='orcs' },
        ['Seed Quadav'] = { Name='Seed Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Seed Yagudo'] = { Name='Seed Yagudo', Ecosystem='beastmen', Family='yugado' },
        ['Shredded Samson'] = { Name='Shredded Samson', Ecosystem='undead', Family='ghosts' },
        ['Son of Anansi'] = { Name='Son of Anansi', Ecosystem='vermin', Family='spiders' },
        ['Thunder Pot'] = { Name='Thunder Pot', Ecosystem='arcana', Family='magic pots' },
        ['Vaicoliaux B D\'Aurphe'] = { Name='Vaicoliaux B D\'Aurphe', Ecosystem='undead', Family='fomors' },
        ['Vangknok of Clan Death'] = { Name='Vangknok of Clan Death', Ecosystem='beastmen', Family='orcs' },
        ['Vassago'] = { Name='Vassago', Ecosystem='demons', Family='kindred' },
        ['Warlord Rojgnoj'] = { Name='Warlord Rojgnoj', Ecosystem='beastmen', Family='orcs' },
        ['Water Golem'] = { Name='Water Golem', Ecosystem='arcana', Family='golems' },
        ['Water Pot'] = { Name='Water Pot', Ecosystem='arcana', Family='magic pots' },
        ['Wind Golem'] = { Name='Wind Golem', Ecosystem='arcana', Family='golems' },
        ['Worgbut of Clan Death'] = { Name='Worgbut of Clan Death', Ecosystem='beastmen', Family='orcs' },
        ['Yukvok of Clan Death'] = { Name='Yukvok of Clan Death', Ecosystem='beastmen', Family='orcs' },
    },
};
