--Zone: Quicksand Caves
--Zone ID: 208
return {
    Names = {
        ['Ancient Vessel'] = { Name='Ancient Vessel', Ecosystem='arcana', Family='magic pots' },
        ['Antican Aedilis'] = { Name='Antican Aedilis', Ecosystem='beastmen', Family='antica' },
        ['Antican Antesignanus'] = { Name='Antican Antesignanus', Ecosystem='beastmen', Family='antica' },
        ['Antican Consul'] = { Name='Antican Consul', Ecosystem='beastmen', Family='antica' },
        ['Antican Hastatus'] = { Name='Antican Hastatus', Ecosystem='beastmen', Family='antica' },
        ['Antican Legatus'] = { Name='Antican Legatus', Ecosystem='beastmen', Family='antica' },
        ['Antican Magister'] = { Name='Antican Magister', Ecosystem='beastmen', Family='antica' },
        ['Antican Praefectus'] = { Name='Antican Praefectus', Ecosystem='beastmen', Family='antica' },
        ['Antican Praetor'] = { Name='Antican Praetor', Ecosystem='beastmen', Family='antica' },
        ['Antican Princeps'] = { Name='Antican Princeps', Ecosystem='beastmen', Family='antica' },
        ['Antican Proconsul'] = { Name='Antican Proconsul', Ecosystem='beastmen', Family='antica' },
        ['Antican Quaestor'] = { Name='Antican Quaestor', Ecosystem='beastmen', Family='antica' },
        ['Antican Signifer'] = { Name='Antican Signifer', Ecosystem='beastmen', Family='antica' },
        ['Antican Triarius'] = { Name='Antican Triarius', Ecosystem='beastmen', Family='antica' },
        ['Antican Tribunus'] = { Name='Antican Tribunus', Ecosystem='beastmen', Family='antica' },
        ['Centurio IV-VII'] = { Name='Centurio IV-VII', Ecosystem='beastmen', Family='antica' },
        ['Centurio X-I'] = { Name='Centurio X-I', Ecosystem='beastmen', Family='antica' },
        ['Centurio XX-I'] = { Name='Centurio XX-I', Ecosystem='beastmen', Family='antica' },
        ['Diamond Daig'] = { Name='Diamond Daig', Ecosystem='vermin', Family='beetles' },
        ['Girtab'] = { Name='Girtab', Ecosystem='vermin', Family='scorpions' },
        ['Girtablulu'] = { Name='Girtablulu', Ecosystem='vermin', Family='scorpions' },
        ['Hastatus XI-XII'] = { Name='Hastatus XI-XII', Ecosystem='beastmen', Family='antica' },
        ['Helm Beetle'] = { Name='Helm Beetle', Ecosystem='vermin', Family='beetles' },
        ['Honor'] = { Name='Honor', Ecosystem='aquans', Family='sea monks' },
        ['Malleator Maurok'] = { Name='Malleator Maurok', Ecosystem='vermin', Family='scorpions' },
        ['Mimic'] = { Name='Mimic', Ecosystem='arcana', Family='mimics' },
        ['Nussknacker'] = { Name='Nussknacker', Ecosystem='lizards', Family='lizards' },
        ['Peon Pounder'] = { Name='Peon Pounder', Ecosystem='vermin', Family='scorpions' },
        ['Princeps IV-XLV'] = { Name='Princeps IV-XLV', Ecosystem='beastmen', Family='antica' },
        ['Proconsul XII'] = { Name='Proconsul XII', Ecosystem='beastmen', Family='antica' },
        ['Sabotender Bailaor'] = { Name='Sabotender Bailaor', Ecosystem='plantoids', Family='sabotenders' },
        ['Sabotender Bailarin'] = { Name='Sabotender Bailarin', Ecosystem='plantoids', Family='sabotenders' },
        ['Sabotender Bailarina'] = { Name='Sabotender Bailarina', Ecosystem='plantoids', Family='sabotenders' },
        ['Sagittarius X-XIII'] = { Name='Sagittarius X-XIII', Ecosystem='beastmen', Family='antica' },
        ['Sand Digger'] = { Name='Sand Digger', Ecosystem='amorphs', Family='worms' },
        ['Sand Eater'] = { Name='Sand Eater', Ecosystem='amorphs', Family='worms' },
        ['Sand Lizard'] = { Name='Sand Lizard', Ecosystem='lizards', Family='lizards' },
        ['Sand Spider'] = { Name='Sand Spider', Ecosystem='vermin', Family='spiders' },
        ['Sand Tarantula'] = { Name='Sand Tarantula', Ecosystem='vermin', Family='spiders' },
        ['Spelunking Sabotender'] = { Name='Spelunking Sabotender', Ecosystem='plantoids', Family='sabotenders' },
        ['Triarius IV-XIV'] = { Name='Triarius IV-XIV', Ecosystem='beastmen', Family='antica' },
        ['Triarius X-XV'] = { Name='Triarius X-XV', Ecosystem='beastmen', Family='antica' },
        ['Tribunus VII-I'] = { Name='Tribunus VII-I', Ecosystem='beastmen', Family='antica' },
        ['Valor'] = { Name='Valor', Ecosystem='aquans', Family='sea monks' },
    },
};
