--Zone: Gustav Tunnel
--Zone ID: 212
return {
    Names = {
        ['Amikiri'] = { Name='Amikiri', Ecosystem='vermin', Family='scorpions'},
        ['Antares'] = { Name='Antares', Ecosystem='vermin', Family='scorpions'},
        ['Baobhan Sith'] = { Name='Baobhan Sith', Ecosystem='undead', Family='ghosts'},
        ['Baronial Bat'] = { Name='Baronial Bat', Ecosystem='birds', Family='bats'},
        ['Bompupu'] = { Name='Bompupu', Ecosystem='humanoids', Family='tarutaru'},
        ['Boulder Eater'] = { Name='Boulder Eater', Ecosystem='amorphs', Family='worms'},
        ['Bune'] = { Name='Bune', Ecosystem='dragons', Family='wyverns'},
        ['Demonic Pugil'] = { Name='Demonic Pugil', Ecosystem='aquans', Family='pugils'},
        ['Doom Guard'] = { Name='Doom Guard', Ecosystem='undead', Family='skeletons'},
        ['Doom Mage'] = { Name='Doom Mage', Ecosystem='undead', Family='skeletons'},
        ['Doom Soldier'] = { Name='Doom Soldier', Ecosystem='undead', Family='skeletons'},
        ['Doom Warlock'] = { Name='Doom Warlock', Ecosystem='undead', Family='skeletons'},
        ['Earth Elemental'] = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals'},
        ['Erlik'] = { Name='Erlik', Ecosystem='undead', Family='ghosts'},
        ['Fire Elemental'] = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals'},
        ['Gigaplasm'] = { Name='Gigaplasm', Ecosystem='amorphs', Family='slimes'},
        ['Goblin Alchemist'] = { Name='Goblin Alchemist', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Mercenary'] = { Name='Goblin Mercenary', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Mine'] = { Name='Goblin Mine', Ecosystem='unclassified', Family='mines'},
        ['Goblin Poacher'] = { Name='Goblin Poacher', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Reaper'] = { Name='Goblin Reaper', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Robber'] = { Name='Goblin Robber', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Shepherd'] = { Name='Goblin Shepherd', Ecosystem='beastmen', Family='goblins'},
        ['Goblin\'s Leech'] = { Name='Goblin\'s Leech', Ecosystem='amorphs', Family='leeches'},
        ['Goblinsavior Heronox'] = { Name='Goblinsavior Heronox', Ecosystem='beastmen', Family='goblins'},
        ['Gorattz'] = { Name='Gorattz', Ecosystem='humanoids', Family='galka'},
        ['Greater Gaylas'] = { Name='Greater Gaylas', Ecosystem='birds', Family='bat trios'},
        ['Hawker'] = { Name='Hawker', Ecosystem='vermin', Family='flies'},
        ['Hell Bat'] = { Name='Hell Bat', Ecosystem='birds', Family='bats'},
        ['Labyrinth Leech'] = { Name='Labyrinth Leech', Ecosystem='amorphs', Family='leeches'},
        ['Labyrinth Lizard'] = { Name='Labyrinth Lizard', Ecosystem='lizards', Family='lizards'},
        ['Macroplasm'] = { Name='Macroplasm', Ecosystem='amorphs', Family='slimes'},
        ['Makara'] = { Name='Makara', Ecosystem='aquans', Family='pugils'},
        ['Microplasm'] = { Name='Microplasm', Ecosystem='amorphs', Family='slimes'},
        ['Nanoplasm'] = { Name='Nanoplasm', Ecosystem='amorphs', Family='slimes'},
        ['Pygmytoise'] = { Name='Pygmytoise', Ecosystem='lizards', Family='adamantoises'},
        ['Renfred'] = { Name='Renfred', Ecosystem='humanoids', Family='humes'},
        ['Robber Crab'] = { Name='Robber Crab', Ecosystem='aquans', Family='crabs'},
        ['Taxim'] = { Name='Taxim', Ecosystem='undead', Family='skeletons'},
        ['Typhoon Wyvern'] = { Name='Typhoon Wyvern',Ecosystem='dragons', Family='wyverns'},
        ['Ungur'] = { Name='Ungur', Ecosystem='dragons', Family='wyverns'},
        ['Wyvernhunter Bambrox'] = { Name='Wyvernhunter Bambrox', Ecosystem='beastmen', Family='goblins'},
        ['Wyvernpoacher Drachlox'] = { Name='Wyvernpoacher Drachlox', Ecosystem='beastmen', Family='goblins'},
    },
};
