--Zone: Labyrinth of Onzozo
--Zone ID: 213
return {
    Names = {
        ['Air Elemental'] = { Name='Air Elemental', Ecosystem='elementals', Family='elementals'},
        ['Babaulas'] = { Name='Babaulas', Ecosystem='undead', Family='skeletons'},
        ['Boribaba'] = { Name='Boribaba', Ecosystem='undead', Family='skeletons'},
        ['Cockatrice'] = { Name='Cockatrice', Ecosystem='birds', Family='cockatrices'},
        ['Flying Manta'] = { Name='Flying Manta', Ecosystem='aquans', Family='sea monks'},
        ['Goblin Alchemist'] = { Name='Goblin Alchemist', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Bandit'] = { Name='Goblin Bandit', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Bouncer'] = { Name='Goblin Bouncer', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Enchanter'] = { Name='Goblin Enchanter', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Hunter'] = { Name='Goblin Hunter', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Mercenary'] = { Name='Goblin Mercenary', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Miner'] = { Name='Goblin Miner', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Poacher'] = { Name='Goblin Poacher', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Reaper'] = { Name='Goblin Reaper', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Robber'] = { Name='Goblin Robber', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Shepherd'] = { Name='Goblin Shepherd', Ecosystem='beastmen', Family='goblins'},
        ['Goblin Trader'] = { Name='Goblin Trader', Ecosystem='beastmen', Family='goblins'},
        ['Goblin\'s Leech'] = { Name='Goblin\'s Leech', Ecosystem='amorphs', Family='leeches'},
        ['Hellion'] = { Name='Hellion', Ecosystem='undead', Family='doomed'},
        ['Labyrinth Leech'] = { Name='Labyrinth Leech', Ecosystem='amorphs', Family='leeches'},
        ['Labyrinth Manticore'] = { Name='Labyrinth Manticore', Ecosystem='beasts', Family='manticores'},
        ['Lord of Onzozo'] = { Name='Lord of Onzozo', Ecosystem='aquans', Family='sea monks'},
        ['Megapod Megalops'] = { Name='Megapod Megalops', Ecosystem='aquans', Family='crabs'},
        ['Mushussu'] = { Name='Mushussu', Ecosystem='vermin', Family='scorpions'},
        ['Mysticmaker Profblix'] = { Name='Mysticmaker Profblix', Ecosystem='beastmen', Family='goblins'},
        ['Narasimha'] = { Name='Narasimha', Ecosystem='beasts', Family='manticores'},
        ['Ose'] = { Name='Ose', Ecosystem='beasts', Family='coeurls'},
        ['Peg Powler'] = { Name='Peg Powler', Ecosystem='aquans', Family='sea monks'},
        ['Soulstealer Skullnix'] = { Name='Soulstealer Skullnix', Ecosystem='beastmen', Family='goblins'},
        ['Tainted Flesh'] = { Name='Tainted Flesh', Ecosystem='undead', Family='doomed'},
        ['Torama'] = { Name='Torama', Ecosystem='beasts', Family='coeurls'},
        ['Ubume'] = { Name='Ubume', Ecosystem='birds', Family='rocs'},
        ['Voso'] = { Name='Voso', Ecosystem='beasts', Family='coeurls'},
        ['Water Elemental'] = { Name='Water Elemental', Ecosystem='elementals', Family='elementals'},
        ['Wyvern'] = { Name='Wyvern', Ecosystem='dragons', Family='wyverns'},
    },
};
