--Zone: Lufaise Meadows
--Zone ID: 24
return {
    Names = {
        ['Abhac'] = { Name='Abhac', Ecosystem='aquans', Family='pugils'},
        ['Abraxas'] = { Name='Abraxas', Ecosystem='birds', Family='rocs'},
        ['Abununnu'] = { Name='Abununnu', Ecosystem='demons', Family='demons'},
        ['Acrophies'] = { Name='Acrophies', Ecosystem='amorphs', Family='leeches'},
        ['Air Elemental'] = { Name='Air Elemental', Ecosystem='elementals', Family='elementals'},
        ['Amaltheia'] = { Name='Amaltheia', Ecosystem='beasts', Family='sheep'},
        ['Apsaras'] = { Name='Apsaras', Ecosystem='aquans', Family='pugils'},
        ['Asrai'] = { Name='Asrai', Ecosystem='plantoids', Family='flytraps'},
        ['Atomic Cluster'] = { Name='Atomic Cluster', Ecosystem='arcana', Family='clusters'},
        ['Baumesel'] = { Name='Baumesel', Ecosystem='plantoids', Family='flytraps'},
        ['Blackbone Frazdiz'] = { Name='Blackbone Frazdiz', Ecosystem='beastmen', Family='orcs'},
        ['Bugard'] = { Name='Bugard', Ecosystem='lizards', Family='bugards'},
        ['Cetic Parasite'] = { Name='Cetic Parasite', Ecosystem='amorphs', Family='leeches'},
        ['Clipper'] = { Name='Clipper', Ecosystem='aquans', Family='crabs'},
        ['Cluster'] = { Name='Cluster', Ecosystem='arcana', Family='clusters'},
        ['Colorful Leshy'] = { Name='Colorful Leshy', Ecosystem='plantoids', Family='treants'},
        ['Crimson Knight Crab'] = { Name='Crimson Knight Crab', Ecosystem='aquans', Family='crabs'},
        ['Dark Elemental'] = { Name='Dark Elemental', Ecosystem='elementals', Family='elementals'},
        ['Death Jacket'] = { Name='Death Jacket', Ecosystem='vermin', Family='bees'},
        ['Defoliate Leshy'] = { Name='Defoliate Leshy', Ecosystem='plantoids', Family='treants'},
        ['Ferrocrab'] = { Name='Ferrocrab', Ecosystem='aquans', Family='crabs'},
        ['Flockbock'] = { Name='Flockbock', Ecosystem='beasts', Family='rams'},
        ['Fomor Bard'] = { Name='Fomor Bard', Ecosystem='undead', Family='fomors'},
        ['Fomor Beastmaster'] = { Name='Fomor Beastmaster', Ecosystem='undead', Family='fomors'},
        ['Fomor Black Mage'] = { Name='Fomor Black Mage', Ecosystem='undead', Family='fomors'},
        ['Fomor Dark Knight'] = { Name='Fomor Dark Knight', Ecosystem='undead', Family='fomors'},
        ['Fomor Dragoon'] = { Name='Fomor Dragoon', Ecosystem='undead', Family='fomors'},
        ['Fomor Monk'] = { Name='Fomor Monk', Ecosystem='undead', Family='fomors'},
        ['Fomor Ninja'] = { Name='Fomor Ninja', Ecosystem='undead', Family='fomors'},
        ['Fomor Paladin'] = { Name='Fomor Paladin', Ecosystem='undead', Family='fomors'},
        ['Fomor Ranger'] = { Name='Fomor Ranger', Ecosystem='undead', Family='fomors'},
        ['Fomor Red Mage'] = { Name='Fomor Red Mage', Ecosystem='undead', Family='fomors'},
        ['Fomor Samurai'] = { Name='Fomor Samurai', Ecosystem='undead', Family='fomors'},
        ['Fomor Summoner'] = { Name='Fomor Summoner', Ecosystem='undead', Family='fomors'},
        ['Fomor Thief'] = { Name='Fomor Thief', Ecosystem='undead', Family='fomors'},
        ['Fomor Warrior'] = { Name='Fomor Warrior', Ecosystem='undead', Family='fomors'},
        ['Fomor\'s Bat'] = { Name='Fomor\'s Bat', Ecosystem='birds', Family='bats'},
        ['Fomor\'s Elemental'] = { Name='Fomor\'s Elemental', Ecosystem='elementals', Family='elementals'},
        ['Fomor\'s Wyvern'] = { Name='Fomor\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Gigantobugard'] = { Name='Gigantobugard', Ecosystem='beastmen', Family='gigas'},
        ['Gigas Braver'] = { Name='Gigas Braver', Ecosystem='beastmen', Family='gigas'},
        ['Gigas Catapulter'] = { Name='Gigas Catapulter', Ecosystem='beastmen', Family='gigas'},
        ['Gigas Fighter'] = { Name='Gigas Fighter', Ecosystem='beastmen', Family='gigas'},
        ['Gigas Martialist'] = { Name='Gigas Martialist', Ecosystem='beastmen', Family='gigas'},
        ['Gigas Slinger'] = { Name='Gigas Slinger', Ecosystem='beastmen', Family='gigas'},
        ['Gigas Warwolf'] = { Name='Gigas Warwolf', Ecosystem='beastmen', Family='gigas'},
        ['Gigas Wrestler'] = { Name='Gigas Wrestler', Ecosystem='beastmen', Family='gigas'},
        ['Gigas\'s Sheep'] = { Name='Gigas\'s Sheep', Ecosystem='beasts', Family='sheep'},
        ['Gloam Servitor'] = { Name='Gloam Servitor', Ecosystem='demons', Family='demons'},
        ['Greater Pugil'] = { Name='Greater Pugil', Ecosystem='aquans', Family='pugils'},
        ['Grindylow'] = { Name='Grindylow', Ecosystem='aquans', Family='crabs'},
        ['Immanibugard'] = { Name='Immanibugard', Ecosystem='lizards', Family='bugards'},
        ['Kurrea'] = { Name='Kurrea', Ecosystem='lizards', Family='bugards'},
        ['Leshachikha'] = { Name='Leshachikha', Ecosystem='plantoids', Family='saplings'},
        ['Leshy'] = { Name='Leshy', Ecosystem='plantoids', Family='treants'},
        ['Megalobugard'] = { Name='Megalobugard', Ecosystem='lizards', Family='bugards'},
        ['Miner Bee'] = { Name='Miner Bee', Ecosystem='vermin', Family='bees'},
        ['Nakki'] = { Name='Nakki', Ecosystem='undead', Family='doomed'},
        ['Orcish Beastrider'] = { Name='Orcish Beastrider', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Bowshooter'] = { Name='Orcish Bowshooter', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Brawler'] = { Name='Orcish Brawler', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Footsoldier'] = { Name='Orcish Footsoldier', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Gladiator'] = { Name='Orcish Gladiator', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Impaler'] = { Name='Orcish Impaler', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Nightraider'] = { Name='Orcish Nightraider', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Stonelauncher'] = { Name='Orcish Stonelauncher', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Trooper'] = { Name='Orcish Trooper', Ecosystem='beastmen', Family='orcs'},
        ['Padfoot'] = { Name='Padfoot', Ecosystem='beasts', Family='sheep'},
        ['Petrocrab'] = { Name='Petrocrab', Ecosystem='aquans', Family='crabs'},
        ['Rainbringer Yjatvot'] = { Name='Rainbringer Yjatvot', Ecosystem='beastmen', Family='orcs'},
        ['Sengann'] = { Name='Sengann', Ecosystem='undead', Family='fomors'},
        ['Splinterspine Grukjuk'] = { Name='Splinterspine Grukjuk', Ecosystem='beastmen', Family='orcs'},
        ['Tavnazian Ram'] = { Name='Tavnazian Ram', Ecosystem='beasts', Family='rams'},
        ['Tavnazian Sheep'] = { Name='Tavnazian Sheep', Ecosystem='beasts', Family='sheep'},
        ['Thunder Elemental'] = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals'},
        ['Vampire Bat'] = { Name='Vampire Bat', Ecosystem='birds', Family='bats'},
        ['Vermillion Fishfly'] = { Name='Vermillion Fishfly', Ecosystem='vermin', Family='flies'},
        ['Vu-Murt'] = { Name='Vu-Murt', Ecosystem='aquans', Family='sea monks'},
        ['Wingrats'] = { Name='Wingrats', Ecosystem='birds', Family='bat trios'},
        ['Yal-un Eke'] = { Name='Yal-un Eke', Ecosystem='arcana', Family='clusters'},
    },
};
