--Zone: Misareaux Coast
--Zone ID: 25
return {
    Names = {
        ['Air Elemental'] = { Name='Air Elemental', Ecosystem='elementals', Family='elementals'},
        ['Alsha'] = { Name='Alsha', Ecosystem='humanoids', Family='elvaan'},
        ['Atomic Cluster'] = { Name='Atomic Cluster', Ecosystem='arcana', Family='clusters'},
        ['Bigclaw'] = { Name='Bigclaw', Ecosystem='aquans', Family='crabs'},
        ['Bloodswiller Fly'] = { Name='Bloodswiller Fly', Ecosystem='vermin', Family='flies'},
        ['Bloody Coffin'] = { Name='Bloody Coffin', Ecosystem='aquans', Family='crabs'},
        ['Boggelmann'] = { Name='Boggelmann', Ecosystem='lizards', Family='bugards'},
        ['Bugard'] = { Name='Bugard', Ecosystem='lizards', Family='bugards'},
        ['Clipper'] = { Name='Clipper', Ecosystem='aquans', Family='crabs'},
        ['Crimson Knight Crab'] = { Name='Crimson Knight Crab', Ecosystem='aquans', Family='crabs'},
        ['Dark Elemental'] = { Name='Dark Elemental', Ecosystem='elementals', Family='elementals'},
        ['Death Jacket'] = { Name='Death Jacket', Ecosystem='vermin', Family='bees'},
        ['Diatryma'] = { Name='Diatryma', Ecosystem='birds', Family='rocs'},
        ['Fomor Bard'] = { Name='Fomor Bard', Ecosystem='undead', Family='fomors'},
        ['Fomor Black Mage'] = { Name='Fomor Black Mage', Ecosystem='undead', Family='fomors'},
        ['Fomor Dark Knight'] = { Name='Fomor Dark Knight', Ecosystem='undead', Family='fomors'},
        ['Fomor Dragoon'] = { Name='Fomor Dragoon', Ecosystem='undead', Family='fomors'},
        ['Fomor Monk'] = { Name='Fomor Monk', Ecosystem='undead', Family='fomors'},
        ['Fomor Ninja'] = { Name='Fomor Ninja', Ecosystem='undead', Family='fomors'},
        ['Fomor Paladin'] = { Name='Fomor Paladin', Ecosystem='undead', Family='fomors'},
        ['Fomor Ranger'] = { Name='Fomor Ranger', Ecosystem='undead', Family='fomors'},
        ['Fomor Red Mage'] = { Name='Fomor Red Mage', Ecosystem='undead', Family='fomors'},
        ['Fomor Samurai'] = { Name='Fomor Samurai', Ecosystem='undead', Family='fomors'},
        ['Fomor Summoner'] = { Name='Fomor Summoner', Ecosystem='undead', Family='fomors'},
        ['Fomor Thief'] = { Name='Fomor Thief', Ecosystem='undead', Family='fomors'},
        ['Fomor Warrior'] = { Name='Fomor Warrior', Ecosystem='undead', Family='fomors'},
        ['Fomor\'s Elemental'] = { Name='Fomor\'s Elemental', Ecosystem='elementals', Family='elementals'},
        ['Fomor\'s Wyvern'] = { Name='Fomor\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Gigantobugard'] = { Name='Gigantobugard', Ecosystem='lizards', Family='bugards'},
        ['Gigas Braver'] = { Name='Gigas Braver', Ecosystem='beastmen', Family='gigas'},
        ['Gigas Catapulter'] = { Name='Gigas Catapulter', Ecosystem='beastmen', Family='gigas'},
        ['Gigas Martialist'] = { Name='Gigas Martialist', Ecosystem='beastmen', Family='gigas'},
        ['Gigas Warwolf'] = { Name='Gigas Warwolf', Ecosystem='beastmen', Family='gigas'},
        ['Gigas\'s Sheep'] = { Name='Gigas\'s Sheep', Ecosystem='beasts', Family='sheep'},
        ['Goaftrap'] = { Name='Goaftrap', Ecosystem='plantoids', Family='flytraps'},
        ['Gration'] = { Name='Gration', Ecosystem='beastmen', Family='gigas'},
        ['Greater Pugil'] = { Name='Greater Pugil', Ecosystem='aquans', Family='pugils'},
        ['Grindylow'] = { Name='Grindylow', Ecosystem='aquans', Family='crabs'},
        ['Makara'] = { Name='Makara', Ecosystem='aquans', Family='pugils'},
        ['Mantrap'] = { Name='Mantrap', Ecosystem='plantoids', Family='flytraps'},
        ['Miner Bee'] = { Name='Miner Bee', Ecosystem='vermin', Family='bees'},
        ['Odqan'] = { Name='Odqan', Ecosystem='arcana', Family='clusters'},
        ['Okyupete'] = { Name='Okyupete', Ecosystem='birds', Family='rocs'},
        ['Orcish Bowshooter'] = { Name='Orcish Bowshooter', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Footsoldier'] = { Name='Orcish Footsoldier', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Gladiator'] = { Name='Orcish Gladiator', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Stonelauncher'] = { Name='Orcish Stonelauncher', Ecosystem='beastmen', Family='orcs'},
        ['Orcish Trooper'] = { Name='Orcish Trooper', Ecosystem='beastmen', Family='orcs'},
        ['Overgrown Rose'] = { Name='Overgrown Rose', Ecosystem='plantoids', Family='morbols'},
        ['Seaboard Vulture'] = { Name='Seaboard Vulture', Ecosystem='birds', Family='birds'},
        ['Tavnazian Sheep'] = { Name='Tavnazian Sheep', Ecosystem='beasts', Family='sheep'},
        ['Thunder Elemental'] = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals'},
        ['Tiyanak'] = { Name='Tiyanak', Ecosystem='birds', Family='bats'},
        ['Tsui-Goab'] = { Name='Tsui-Goab', Ecosystem='vermin', Family='mantids'},
        ['Upyri'] = { Name='Upyri', Ecosystem='birds', Family='bats'},
        ['Vampire Bat'] = { Name='Vampire Bat', Ecosystem='birds', Family='bats'},
        ['Volatile Cluster'] = { Name='Volatile Cluster', Ecosystem='arcana', Family='clusters'},
        ['Warder Aglaia'] = { Name='Warder Aglaia', Ecosystem='arcana', Family='spheroids'},
        ['Warder Euphrosyne'] = { Name='Warder Euphrosyne', Ecosystem='arcana', Family='spheroids'},
        ['Warder Thalia'] = { Name='Warder Thalia', Ecosystem='arcana', Family='spheroids'},
        ['Wingrats'] = { Name='Wingrats', Ecosystem='birds', Family='bat trios'},
        ['Ziphius'] = { Name='Ziphius', Ecosystem='aquans', Family='pugils'},
        -- Custom content for HorizonXI
        ['Mammet-9999'] = { Name='Mammet-9999', Ecosystem='arcana', Family='mammets' },
    },
};
