--Zone: Phomiuna Aqueducts
--Zone ID: 27
return {
    Names = {
        ['Addled Tumor'] = { Name='Addled Tumor', Ecosystem='undead', Family='doomed'},
        ['Air Elemental'] = { Name='Air Elemental', Ecosystem='elementals', Family='elementals'},
        ['Aqueduct Spider'] = { Name='Aqueduct Spider', Ecosystem='vermin', Family='spiders'},
        ['Bavarois'] = { Name='Bavarois', Ecosystem='amorphs', Family='slimes'},
        ['Big Jaw'] = { Name='Big Jaw', Ecosystem='aquans', Family='crabs'},
        ['Canal Bats'] = { Name='Canal Bats', Ecosystem='birds', Family='bat trios'},
        ['Dark Elemental'] = { Name='Dark Elemental', Ecosystem='elementals', Family='elementals'},
        ['Diremite'] = { Name='Diremite', Ecosystem='vermin', Family='diremites'},
        ['Duendes\' Amoroso'] = { Name='Duendes\' Amoroso', Ecosystem='undead', Family='fomors'},
        ['Eba'] = { Name='Eba', Ecosystem='undead', Family='fomors'},
        ['Fomor Bard'] = { Name='Fomor Bard', Ecosystem='undead', Family='fomors'},
        ['Fomor Beastmaster'] = { Name='Fomor Beastmaster', Ecosystem='undead', Family='fomors'},
        ['Fomor Black Mage'] = { Name='Fomor Black Mage', Ecosystem='undead', Family='fomors'},
        ['Fomor Dark Knight'] = { Name='Fomor Dark Knight', Ecosystem='undead', Family='fomors'},
        ['Fomor Dragoon'] = { Name='Fomor Dragoon', Ecosystem='undead', Family='fomors'},
        ['Fomor Monk'] = { Name='Fomor Monk', Ecosystem='undead', Family='fomors'},
        ['Fomor Ninja'] = { Name='Fomor Ninja', Ecosystem='undead', Family='fomors'},
        ['Fomor Paladin'] = { Name='Fomor Paladin', Ecosystem='undead', Family='fomors'},
        ['Fomor Ranger'] = { Name='Fomor Ranger', Ecosystem='undead', Family='fomors'},
        ['Fomor Red Mage'] = { Name='Fomor Red Mage', Ecosystem='undead', Family='fomors'},
        ['Fomor Samurai'] = { Name='Fomor Samurai', Ecosystem='undead', Family='fomors'},
        ['Fomor Summoner'] = { Name='Fomor Summoner', Ecosystem='undead', Family='fomors'},
        ['Fomor Thief'] = { Name='Fomor Thief', Ecosystem='undead', Family='fomors'},
        ['Fomor Warrior'] = { Name='Fomor Warrior', Ecosystem='undead', Family='fomors'},
        ['Fomor\'s Bat'] = { Name='Fomor\'s Bat', Ecosystem='birds', Family='bats'},
        ['Fomor\'s Elemental'] = { Name='Fomor\'s Elemental', Ecosystem='elementals', Family='elementals'},
        ['Fomor\'s Wyvern'] = { Name='Fomor\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Foul Meat'] = { Name='Foul Meat', Ecosystem='undead', Family='doomed'},
        ['Freshwater Trepang'] = { Name='Freshwater Trepang', Ecosystem='amorphs', Family='slimes'},
        ['Gloop'] = { Name='Gloop', Ecosystem='amorphs', Family='slimes'},
        ['Hell Bat'] = { Name='Hell Bat', Ecosystem='birds', Family='bats'},
        ['Mahisha'] = { Name='Mahisha', Ecosystem='demons', Family='tauri'},
        ['Makara'] = { Name='Makara', Ecosystem='aquans', Family='pugils'},
        ['Minotaur'] = { Name='Minotaur', Ecosystem='demons', Family='tauri'},
        ['Ogreish Risotto'] = { Name='Ogreish Risotto', Ecosystem='amorphs', Family='slimes'},
        ['Oil Spill'] = { Name='Oil Spill', Ecosystem='amorphs', Family='slimes'},
        ['Sponge'] = { Name='Sponge', Ecosystem='amorphs', Family='slimes'},
        ['Stegotaur'] = { Name='Stegotaur', Ecosystem='demons', Family='tauri'},
        ['Taurus'] = { Name='Taurus', Ecosystem='demons', Family='tauri'},
        ['Thunder Elemental'] = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals'},
        ['Tres Duendes'] = { Name='Tres Duendes', Ecosystem='birds', Family='bat trios'},
        ['Vampire Bat'] = { Name='Vampire Bat', Ecosystem='birds', Family='bats'},
        ['Water Pumpkin'] = { Name='Water Pumpkin', Ecosystem='amorphs', Family='slimes'},
    },
};
