--Zone: Sacrarium
--Zone ID: 28
return {
    Names = {
        ['Air Elemental'] = { Name='Air Elemental', Ecosystem='elementals', Family='elementals'},
        ['Aqueduct Spider'] = { Name='Aqueduct Spider', Ecosystem='vermin', Family='spiders'},
        ['Azren Kuba'] = { Name='Azren Kuba', Ecosystem='undead', Family='skeletons'},
        ['Azren Kuguza'] = { Name='Azren Kuguza', Ecosystem='undead', Family='skeletons'},
        ['Balor'] = { Name='Balor', Ecosystem='undead', Family='fomors'},
        ['Blubber Eyes'] = { Name='Blubber Eyes', Ecosystem='amorphs', Family='hecteyes'},
        ['Caithleann'] = { Name='Caithleann', Ecosystem='undead', Family='fomors'},
        ['Dark Elemental'] = { Name='Dark Elemental', Ecosystem='elementals', Family='elementals'},
        ['Elel'] = { Name='Elel', Ecosystem='undead', Family='corses'},
        ['Fomor Bard'] = { Name='Fomor Bard', Ecosystem='undead', Family='fomors'},
        ['Fomor Beastmaster'] = { Name='Fomor Beastmaster', Ecosystem='undead', Family='fomors'},
        ['Fomor Black Mage'] = { Name='Fomor Black Mage', Ecosystem='undead', Family='fomors'},
        ['Fomor Dark Knight'] = { Name='Fomor Dark Knight', Ecosystem='undead', Family='fomors'},
        ['Fomor Dragoon'] = { Name='Fomor Dragoon', Ecosystem='undead', Family='fomors'},
        ['Fomor Monk'] = { Name='Fomor Monk', Ecosystem='undead', Family='fomors'},
        ['Fomor Ninja'] = { Name='Fomor Ninja', Ecosystem='undead', Family='fomors'},
        ['Fomor Paladin'] = { Name='Fomor Paladin', Ecosystem='undead', Family='fomors'},
        ['Fomor Ranger'] = { Name='Fomor Ranger', Ecosystem='undead', Family='fomors'},
        ['Fomor Red Mage'] = { Name='Fomor Red Mage', Ecosystem='undead', Family='fomors'},
        ['Fomor Samurai'] = { Name='Fomor Samurai', Ecosystem='undead', Family='fomors'},
        ['Fomor Summoner'] = { Name='Fomor Summoner', Ecosystem='undead', Family='fomors'},
        ['Fomor Thief'] = { Name='Fomor Thief', Ecosystem='undead', Family='fomors'},
        ['Fomor Warrior'] = { Name='Fomor Warrior', Ecosystem='undead', Family='fomors'},
        ['Fomor\'s Avatar'] = { Name='Fomor\'s Avatar', Ecosystem='unclassified', Family='avatars'},
        ['Fomor\'s Bats'] = { Name='Fomor\'s Bats', Ecosystem='birds', Family='bat trios'},
        ['Fomor\'s Elemental'] = { Name='Fomor\'s Elemental', Ecosystem='elementals', Family='elementals'},
        ['Fomor\'s Wyvern'] = { Name='Fomor\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Gazer'] = { Name='Gazer', Ecosystem='amorphs', Family='hecteyes'},
        ['Greater Gaylas'] = { Name='Greater Gaylas', Ecosystem='birds', Family='bat trios'},
        ['Indich'] = { Name='Indich', Ecosystem='undead', Family='fomors'},
        ['Keremet'] = { Name='Keremet', Ecosystem='undead', Family='corses'},
        ['Lich'] = { Name='Lich', Ecosystem='undead', Family='skeletons'},
        ['Lobais'] = { Name='Lobais', Ecosystem='undead', Family='fomors'},
        ['Luaith'] = { Name='Luaith', Ecosystem='undead', Family='fomors'},
        ['Mariselle\'s Pupil'] = { Name='Mariselle\'s Pupil', Ecosystem='undead', Family='ghosts'},
        ['Mummy'] = { Name='Mummy', Ecosystem='undead', Family='skeletons'},
        ['Old Professor Mariselle'] = { Name='Old Professor Mariselle', Ecosystem='undead', Family='ghosts'},
        ['Stegotaur'] = { Name='Stegotaur', Ecosystem='demons', Family='tauri'},
        ['Teratotaur'] = { Name='Teratotaur', Ecosystem='demons', Family='tauri'},
        ['Thunder Elemental'] = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals'},
        ['Utukku'] = { Name='Utukku', Ecosystem='undead', Family='ghosts'},
    },
};
