--Zone: Carpenters' Landing
--Zone ID: 2
return {
    Names = {
        ['Battrap'] = { Name='Battrap', 
        ['Beady Beetle'] = { Name='Beady Beetle', 
        ['Birdtrap'] = { Name='Birdtrap', 
        ['Bulldog Bats'] = { Name='Bulldog Bats', 
        ['Bullheaded Grosvez'] = { Name='Bullheaded Grosvez', 
        ['Clipper'] = { Name='Clipper', 
        ['Cryptonberry Assassin'] = { Name='Cryptonberry Assassin', 
        ['Cryptonberry Executor'] = { Name='Cryptonberry Executor', 
        ['Digger Wasp'] = { Name='Digger Wasp', 
        ['Diving Beetle'] = { Name='Diving Beetle', 
        ['Fishtrap'] = { Name='Fishtrap', 
        ['Flytrap'] = { Name='Flytrap', 
        ['Forest Tiger'] = { Name='Forest Tiger', 
        ['Fosse Pugil'] = { Name='Fosse Pugil', 
        ['Ghoul'] = { Name='Ghoul', 
        ['Glide Bomb'] = { Name='Glide Bomb', 
        ['Greater Pugil'] = { Name='Greater Pugil', 
        ['Hercules Beetle'] = { Name='Hercules Beetle', 
        ['Land Pugil'] = { Name='Land Pugil', 
        ['Marsh Funguar'] = { Name='Marsh Funguar', 
        ['Mycophile'] = { Name='Mycophile', 
        ['Orcfeltrap'] = { Name='Orcfeltrap', 
        ['Orcish Cursemaker'] = { Name='Orcish Cursemaker', 
        ['Orcish Fighter'] = { Name='Orcish Fighter', 
        ['Orcish Grunt'] = { Name='Orcish Grunt', 
        ['Orcish Neckchopper'] = { Name='Orcish Neckchopper', 
        ['Orcish Serjeant'] = { Name='Orcish Serjeant', 
        ['Orcish Stonechucker'] = { Name='Orcish Stonechucker', 
        ['Orctrap'] = { Name='Orctrap', 
        ['Overgrown Ivy'] = { Name='Overgrown Ivy', 
        ['Para'] = { Name='Para', 
        ['Poison Funguar'] = { Name='Poison Funguar', 
        ['Sabertooth Tiger'] = { Name='Sabertooth Tiger', 
        ['Shrieker'] = { Name='Shrieker', 
        ['Snipper'] = { Name='Snipper', 
        ['Specter Bat'] = { Name='Specter Bat', 
        ['Spider Wasp'] = { Name='Spider Wasp', 
        ['Spinous Pugil'] = { Name='Spinous Pugil', 
        ['Spunkie'] = { Name='Spunkie', 
        ['Stag Beetle'] = { Name='Stag Beetle', 
        ['Tempest Tigon'] = { Name='Tempest Tigon', 
        ['Thunder Elemental'] = { Name='Thunder Elemental', 
        ['Tonberry\'s Avatar'] = { Name='Tonberry\'s Avatar', 
        ['Tonberry\'s Elemental'] = { Name='Tonberry\'s Elemental', 
        ['Triangle Crab'] = { Name='Triangle Crab', 
        ['Water Elemental'] = { Name='Water Elemental', 
        ['Wendigo'] = { Name='Wendigo', 
        ['Wight'] = { Name='Wight', 
        ['Will-o\'-the-Wisp'] = { Name='Will-o\'-the-Wisp', 
    },
};
