--Zone: Carpenters' Landing
--Zone ID: 2
return {
    Names = {
        ['Battrap']                 = { Name='Battrap', Ecosystem='plantoids', Family='flytraps' },
        ['Beady Beetle']            = { Name='Beady Beetle', Ecosystem='vermin', Family='beetles' },
        ['Birdtrap']                = { Name='Birdtrap', Ecosystem='plantoids', Family='flytraps' },
        ['Bulldog Bats']            = { Name='Bulldog Bats', Ecosystem='birds', Family='bat trios' },
        ['Bullheaded Grosvez']      = { Name='Bullheaded Grosvez', Ecosystem='beastmen', Family='orcs' },
        ['Clipper']                 = { Name='Clipper', Ecosystem='aquans', Family='crabs' },
        ['Cryptonberry Assassin']   = { Name='Cryptonberry Assassin', Ecosystem='beastmen', Family='tonberries' },
        ['Cryptonberry Executor']   = { Name='Cryptonberry Executor', Ecosystem='beastmen', Family='tonberries' },
        ['Digger Wasp']             = { Name='Digger Wasp', Ecosystem='vermin', Family='bees' },
        ['Diving Beetle']           = { Name='Diving Beetle', Ecosystem='vermin', Family='beetles' },
        ['Fishtrap']                = { Name='Fishtrap', Ecosystem='plantoids', Family='flytraps' },
        ['Flytrap']                 = { Name='Flytrap', Ecosystem='plantoids', Family='flytraps' },
        ['Forest Tiger']            = { Name='Forest Tiger', Ecosystem='beasts', Family='tigers' },
        ['Fosse Pugil']             = { Name='Fosse Pugil', Ecosystem='aquans', Family='pugils' },
        ['Ghoul']                   = { Name='Ghoul', Ecosystem='undead', Family='skeletons' },
        ['Glide Bomb']              = { Name='Glide Bomb', Ecosystem='arcana', Family='bombs' },
        ['Greater Pugil']           = { Name='Greater Pugil', Ecosystem='aquans', Family='pugils' },
        ['Hercules Beetle']         = { Name='Hercules Beetle', Ecosystem='vermin', Family='beetles' },
        ['Land Pugil']              = { Name='Land Pugil', Ecosystem='aquans', Family='pugils' },
        ['Marsh Funguar']           = { Name='Marsh Funguar', Ecosystem='plantoids', Family='funguars' },
        ['Mycophile']               = { Name='Mycophile', Ecosystem='plantoids', Family='funguars' },
        ['Orcfeltrap']              = { Name='Orcfeltrap', Ecosystem='plantoids', Family='flytraps' },
        ['Orcish Cursemaker']       = { Name='Orcish Cursemaker', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Fighter']          = { Name='Orcish Fighter', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Grunt']            = { Name='Orcish Grunt', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Neckchopper']      = { Name='Orcish Neckchopper', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Serjeant']         = { Name='Orcish Serjeant', Ecosystem='beastmen', Family='orcs' },
        ['Orcish Stonechucker']     = { Name='Orcish Stonechucker', Ecosystem='beastmen', Family='orcs' },
        ['Orctrap']                 = { Name='Orctrap', Ecosystem='plantoids', Family='flytraps' },
        ['Overgrown Ivy']           = { Name='Overgrown Ivy', Ecosystem='plantoids', Family='morbols' },
        ['Para']                    = { Name='Para', Ecosystem='plantoids', Family='funguars' },
        ['Poison Funguar']          = { Name='Poison Funguar', Ecosystem='plantoids', Family='funguars' },
        ['Sabertooth Tiger']        = { Name='Sabertooth Tiger', Ecosystem='beasts', Family='tigers' },
        ['Shrieker']                = { Name='Shrieker', Ecosystem='plantoids', Family='funguars' },
        ['Snipper']                 = { Name='Snipper', Ecosystem='aquans', Family='crabs' },
        ['Specter Bat']             = { Name='Specter Bat', Ecosystem='birds', Family='bats' },
        ['Spider Wasp']             = { Name='Spider Wasp', Ecosystem='vermin', Family='bees' },
        ['Spinous Pugil']           = { Name='Spinous Pugil', Ecosystem='aquans', Family='pugils' },
        ['Spunkie']                 = { Name='Spunkie', Ecosystem='arcana', Family='bombs' },
        ['Stag Beetle']             = { Name='Stag Beetle', Ecosystem='vermin', Family='beetles' },
        ['Tempest Tigon']           = { Name='Tempest Tigon', Ecosystem='beasts', Family='tigers' },
        ['Thunder Elemental']       = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
        ['Tonberry\'s Avatar']      = { Name='Tonberry\'s Avatar', Ecosystem='unclassified', Family='monsters' },
        ['Tonberry\'s Elemental']   = { Name='Tonberry\'s Elemental', Ecosystem='elementals', Family='elementals' },
        ['Triangle Crab']           = { Name='Triangle Crab', Ecosystem='aquans', Family='crabs' },
        ['Water Elemental']         = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
        ['Wendigo']                 = { Name='Wendigo', Ecosystem='undead', Family='skeletons' },
        ['Wight']                   = { Name='Wight', Ecosystem='undead', Family='skeletons' },
        ['Will-o\'-the-Wisp']       = { Name='Will-o\'-the-Wisp', Ecosystem='arcana', Family='bombs' },
    },
};
