--Zone: Temenos
--Zone ID: 37
return {
    Names = {
        ['Abyssdweller Jhabdebb'] = { Name='Abyssdweller Jhabdebb', Ecosystem='beastmen', Family='orcs' },
        ['Aern\'s Avatar'] = { Name='Aern\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Aern\'s Elemental'] = { Name='Aern\'s Elemental', Ecosystem='elementals', Family='elementals' },
        ['Aern\'s Euvhi'] = { Name='Aern\'s Euvhi', Ecosystem='luminians', Family='euvhi' },
        ['Aern\'s Wynav'] = { Name='Aern\'s Wynav', Ecosystem='dragons', Family='wyverns' },
        ['Air Elemental'] = { Name='Air Elemental', Ecosystem='elementals', Family='elementals' },
        ['Airi'] = { Name='Airi', Ecosystem='undead', Family='ghosts' },
        ['Arch-Ultima'] = { Name='Arch-Ultima', Ecosystem='unclassified', Family='biotechnological weapons' },
        ['Armoury Crate'] = { Name='Armoury Crate', Ecosystem='arcana', Family='mimics' },
        ['Beli'] = { Name='Beli', Ecosystem='beastmen', Family='gigas' },
        ['Cryptonberry Abductor'] = { Name='Cryptonberry Abductor', Ecosystem='beastmen', Family='tonberries' },
        ['Cryptonberry Charmer'] = { Name='Cryptonberry Charmer', Ecosystem='beastmen', Family='tonberries' },
        ['Cryptonberry Designator'] = { Name='Cryptonberry Designator', Ecosystem='beastmen', Family='tonberries' },
        ['Cryptonberry Skulker'] = { Name='Cryptonberry Skulker', Ecosystem='beastmen', Family='tonberries' },
        ['Dark Elemental'] = { Name='Dark Elemental', Ecosystem='elementals', Family='elementals' },
        ['Earth Elemental'] = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Enhanced Ahriman'] = { Name='Enhanced Ahriman', Ecosystem='demons', Family='ahrimans' },
        ['Enhanced Akbaba'] = { Name='Enhanced Akbaba', Ecosystem='birds', Family='birds' },
        ['Enhanced Beetle'] = { Name='Enhanced Beetle', Ecosystem='vermin', Family='beetles' },
        ['Enhanced Dragon'] = { Name='Enhanced Dragon', Ecosystem='dragons', Family='dragons' },
        ['Enhanced Jelly'] = { Name='Enhanced Jelly', Ecosystem='amorphs', Family='slimes' },
        ['Enhanced Kettenkaefer'] = { Name='Enhanced Kettenkaefer', Ecosystem='vermin', Family='beetles' },
        ['Enhanced Koenigstiger'] = { Name='Enhanced Koenigstiger', Ecosystem='beasts', Family='tigers' },
        ['Enhanced Lizard'] = { Name='Enhanced Lizard', Ecosystem='lizards', Family='lizards' },
        ['Enhanced Makara'] = { Name='Enhanced Makara', Ecosystem='aquans', Family='pugils' },
        ['Enhanced Mandragora'] = { Name='Enhanced Mandragora', Ecosystem='plantoids', Family='mandragoras' },
        ['Enhanced Pugil'] = { Name='Enhanced Pugil', Ecosystem='aquans', Family='pugils' },
        ['Enhanced Pygmaioi'] = { Name='Enhanced Pygmaioi', Ecosystem='plantoids', Family='mandragoras' },
        ['Enhanced Salamander'] = { Name='Enhanced Salamander', Ecosystem='lizards', Family='raptors' },
        ['Enhanced Slime'] = { Name='Enhanced Slime', Ecosystem='amorphs', Family='slimes' },
        ['Enhanced Tiger'] = { Name='Enhanced Tiger', Ecosystem='beasts', Family='tigers' },
        ['Enhanced Vulture'] = { Name='Enhanced Vulture', Ecosystem='birds', Family='birds' },
        ['Fire Elemental'] = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals' },
        ['Fossil Quadav'] = { Name='Fossil Quadav', Ecosystem='beastmen', Family='quadavs' },
        ['Goblin Fencer'] = { Name='Goblin Fencer', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Slaughterman'] = { Name='Goblin Slaughterman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Theurgist'] = { Name='Goblin Theurgist', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Warlord'] = { Name='Goblin Warlord', Ecosystem='beastmen', Family='goblins' },
        ['Grognard Footsoldier'] = { Name='Grognard Footsoldier', Ecosystem='beastmen', Family='orcs' },
        ['Grognard Grappler'] = { Name='Grognard Grappler', Ecosystem='beastmen', Family='orcs' },
        ['Grognard Impaler'] = { Name='Grognard Impaler', Ecosystem='beastmen', Family='orcs' },
        ['Grognard Mesmerizer'] = { Name='Grognard Mesmerizer', Ecosystem='beastmen', Family='orcs' },
        ['Grognard Neckchopper'] = { Name='Grognard Neckchopper', Ecosystem='beastmen', Family='orcs' },
        ['Grognard Predator'] = { Name='Grognard Predator', Ecosystem='beastmen', Family='orcs' },
        ['Ice Elemental'] = { Name='Ice Elemental', Ecosystem='elementals', Family='elementals' },
        ['Iruci'] = { Name='Iruci', Ecosystem='undead', Family='skeletons' },
        ['Ji\'Gho Ageless'] = { Name='Ji\'Gho Ageless', Ecosystem='beastmen', Family='quadav' },
        ['Kari'] = { Name='Kari', Ecosystem='beastmen', Family='gigas' },
        ['Kindred Black Mage'] = { Name='Kindred Black Mage', Ecosystem='demons', Family='demons' },
        ['Kindred Dark Knight'] = { Name='Kindred Dark Knight', Ecosystem='demons', Family='demons' },
        ['Kindred Summoner'] = { Name='Kindred Summoner', Ecosystem='demons', Family='demons' },
        ['Kindred Warrior'] = { Name='Kindred Warrior', Ecosystem='demons', Family='demons' },
        ['Kindred\'s Avatar'] = { Name='Kindred\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Kindred\'s Elemental'] = { Name='Kindred\'s Elemental', Ecosystem='elementals', Family='elementals' },
        ['Kingslayer Doggvdegg'] = { Name='Kingslayer Doggvdegg', Ecosystem='beastmen', Family='orcs' },
        ['Koo Buzu the Theomanic'] = { Name='Koo Buzu the Theomanic', Ecosystem='beastmen', Family='yagudo' },
        ['Light Elemental'] = { Name='Light Elemental', Ecosystem='elementals', Family='elementals' },
        ['Lightsteel Quadav'] = { Name='Lightsteel Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Moblin Dustman'] = { Name='Moblin Dustman', Ecosystem='beastmen', Family='moblins' },
        ['Mystic Avatar'] = { Name='Mystic Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Orc\'s Wyvern'] = { Name='Orc\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Orichalcum Quadav'] = { Name='Orichalcum Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Pee Qoho the Python'] = { Name='Pee Qoho the Python', Ecosystem='beastmen', Family='yagudo' },
        ['Praetorian Guard CCCXI'] = { Name='Praetorian Guard CCCXI', Ecosystem='beastmen', Family='antica' },
        ['Praetorian Guard CCXX'] = { Name='Praetorian Guard CCXX', Ecosystem='beastmen', Family='antica' },
        ['Praetorian Guard CXLVIII'] = { Name='Praetorian Guard CXLVIII', Ecosystem='beastmen', Family='antica' },
        ['Praetorian Guard LXXIII'] = { Name='Praetorian Guard LXXIII', Ecosystem='beastmen', Family='antica' },
        ['Proto-Ultima'] = { Name='Proto-Ultima', Ecosystem='unclassified', Family='biotechnological weapons' },
        ['Pyrrha'] = { Name='Pyrrha', Ecosystem='luminians', Family='ghrahs' },
        ['Skadi'] = { Name='Skadi', Ecosystem='beastmen', Family='gigas' },
        ['Star Ruby Quadav'] = { Name='Star Ruby Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Star Sapphire Quadav'] = { Name='Star Sapphire Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Telchines Bard'] = { Name='Telchines Bard', Ecosystem='beastmen', Family='sahagin' },
        ['Telchines Dragoon'] = { Name='Telchines Dragoon', Ecosystem='beastmen', Family='sahagin' },
        ['Telchines Monk'] = { Name='Telchines Monk', Ecosystem='beastmen', Family='sahagin' },
        ['Telchines White Mage'] = { Name='Telchines White Mage', Ecosystem='beastmen', Family='sahagin' },
        ['Telchines\'s Wyvern'] = { Name='Telchines\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Temenos Aern'] = { Name='Temenos Aern', Ecosystem='luminians', Family='aerns' },
        ['Temenos Cleaner'] = { Name='Temenos Cleaner', Ecosystem='arcana', Family='magic pots' },
        ['Temenos Euvhi'] = { Name='Temenos Euvhi', Ecosystem='luminians', Family='euvhi' },
        ['Temenos Ghrah'] = { Name='Temenos Ghrah', Ecosystem='luminians', Family='ghrahs' },
        ['Temenos Weapon'] = { Name='Temenos Weapon', Ecosystem='arcana', Family='evil weapons' },
        ['Thalesek'] = { Name='Thalesek', Ecosystem='luminians', Family='euvhi' },
        ['Thrym'] = { Name='Thrym', Ecosystem='beastmen', Family='gigas' },
        ['Thunder Elemental'] = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
        ['Tonberry\'s Avatar'] = { Name='Tonberry\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Tonberry\'s Elemental'] = { Name='Tonberry\'s Elemental', Ecosystem='elementals', Family='elementals' },
        ['Water Elemental'] = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
        ['Whitegold Quadav'] = { Name='Whitegold Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Wootz Quadav'] = { Name='Wootz Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Yagudo Archpriest'] = { Name='Yagudo Archpriest', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Disciplinant'] = { Name='Yagudo Disciplinant', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Eradicator'] = { Name='Yagudo Eradicator', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Kapellmeister'] = { Name='Yagudo Kapellmeister', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Knight Templar'] = { Name='Yagudo Knight Templar', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Prelatess'] = { Name='Yagudo Prelatess', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo\'s Avatar'] = { Name='Yagudo\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Yagudo\'s Elemental'] = { Name='Yagudo\'s Elemental', Ecosystem='elementals', Family='elementals' },
    },
};
