--Zone: Apollyon
--Zone ID: 38
return {
    Names = {
        ['Adamantshell'] = { Name='Adamantshell', Ecosystem='aquans', Family='crabs' },
        ['Aeshma'] = { Name='Aeshma', Ecosystem='demons', Family='ahriman' },
        ['Ahriman\'s Avatar'] = { Name='Ahriman\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Air Elemental'] = { Name='Air Elemental', Ecosystem='elementals', Family='elementals' },
        ['Apollyon Ahriman'] = { Name='Apollyon Ahriman', Ecosystem='demons', Family='ahriman' },
        ['Apollyon Cleaner'] = { Name='Apollyon Cleaner', Ecosystem='arcana', Family='magic pots' },
        ['Apollyon Demon'] = { Name='Apollyon Demon', Ecosystem='demons', Family='demons' },
        ['Apollyon Sapling'] = { Name='Apollyon Sapling', Ecosystem='plantoids', Family='saplings' },
        ['Apollyon Scavenger'] = { Name='Apollyon Scavenger', Ecosystem='lizards', Family='bugards' },
        ['Apollyon Sweeper'] = { Name='Apollyon Sweeper', Ecosystem='arcana', Family='dolls' },
        ['Apollyon Taurus'] = { Name='Apollyon Taurus', Ecosystem='demons', Family='tauri' },
        ['Arboricole Beetle'] = { Name='Arboricole Beetle', Ecosystem='vermin', Family='beetles' },
        ['Arboricole Crawler'] = { Name='Arboricole Crawler', Ecosystem='vermin', Family='crawlers' },
        ['Arboricole Hornet'] = { Name='Arboricole Hornet', Ecosystem='vermin', Family='bees' },
        ['Arboricole Opo-opo'] = { Name='Arboricole Opo-opo', Ecosystem='beasts', Family='opo-opos' },
        ['Arboricole Raven'] = { Name='Arboricole Raven', Ecosystem='birds', Family='birds' },
        ['Arboricole Spider'] = { Name='Arboricole Spider', Ecosystem='vermin', Family='spiders' },
        ['Arch-Omega'] = { Name='Arch-Omega', Ecosystem='unclassified', Family='biological weapons' },
        ['Armoury Crate'] = { Name='Armoury Crate', Ecosystem='arcana', Family='mimics' },
        ['Bardha'] = { Name='Bardha', Ecosystem='undead', Family='ghosts' },
        ['Barometz'] = { Name='Barometz', Ecosystem='plantoids', Family='saplings' },
        ['Bata'] = { Name='Bata', Ecosystem='demons', Family='tauri' },
        ['Bialozar'] = { Name='Bialozar', Ecosystem='birds', Family='rocs' },
        ['Borametz'] = { Name='Borametz', Ecosystem='plantoids', Family='saplings' },
        ['Carnagechief Jackbodokk'] = { Name='Carnagechief Jackbodokk', Ecosystem='beastmen', Family='orcs' },
        ['Cornu'] = { Name='Cornu', Ecosystem='birds', Family='birds' },
        ['Criosphinx'] = { Name='Criosphinx', Ecosystem='beasts', Family='manticores' },
        ['Cronos'] = { Name='Cronos', Ecosystem='beastmen', Family='gigas' },
        ['Cynoprosopi'] = { Name='Cynoprosopi', Ecosystem='dragons', Family='wyrms' },
        ['Dark Elemental'] = { Name='Dark Elemental', Ecosystem='elementals', Family='elementals' },
        ['Dee Wapa the Desolator'] = { Name='Dee Wapa the Desolator', Ecosystem='beastmen', Family='yagudo' },
        ['Earth Elemental'] = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Evil Armory'] = { Name='Evil Armory', Ecosystem='arcana', Family='evil weapons' },
        ['Fir Bholg'] = { Name='Fir Bholg', Ecosystem='undead', Family='fomors' },
        ['Fire Elemental'] = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals' },
        ['Flying Spear'] = { Name='Flying Spear', Ecosystem='arcana', Family='evil weapons' },
        ['Fossil Quadav'] = { Name='Fossil Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Ghost Clot'] = { Name='Ghost Clot', Ecosystem='amorphs', Family='slimes' },
        ['Goobbue Harvester'] = { Name='Goobbue Harvester', Ecosystem='plantoids', Family='goobbues' },
        ['Gorynich'] = { Name='Gorynich', Ecosystem='dragons', Family='wyverns' },
        ['Grave Digger'] = { Name='Grave Digger', Ecosystem='undead', Family='corses' },
        ['Grognard Footsoldier'] = { Name='Grognard Footsoldier', Ecosystem='beastmen', Family='orcs' },
        ['Grognard Grappler'] = { Name='Grognard Grappler', Ecosystem='beastmen', Family='orcs' },
        ['Grognard Impaler'] = { Name='Grognard Impaler', Ecosystem='beastmen', Family='orcs' },
        ['Grognard Mesmerizer'] = { Name='Grognard Mesmerizer', Ecosystem='beastmen', Family='orcs' },
        ['Grognard Neckchopper'] = { Name='Grognard Neckchopper', Ecosystem='beastmen', Family='orcs' },
        ['Grognard Predator'] = { Name='Grognard Predator', Ecosystem='beastmen', Family='orcs' },
        ['Gunpod'] = { Name='Gunpod', Ecosystem='arcana', Family='spheroids' },
        ['Hieracosphinx'] = { Name='Hieracosphinx', Ecosystem='beasts', Family='manticores' },
        ['Hyperion'] = { Name='Hyperion', Ecosystem='beastmen', Family='gigas' },
        ['Ice Elemental'] = { Name='Ice Elemental', Ecosystem='elementals', Family='elementals' },
        ['Inhumer'] = { Name='Inhumer', Ecosystem='undead', Family='skeletons' },
        ['Jidra'] = { Name='Jidra', Ecosystem='plantoids', Family='treants' },
        ['Kaiser Behemoth'] = { Name='Kaiser Behemoth', Ecosystem='beasts', Family='behemoths' },
        ['Kerkopes'] = { Name='Kerkopes', Ecosystem='beasts', Family='opo-opos' },
        ['Kronprinz Behemoth'] = { Name='Kronprinz Behemoth', Ecosystem='beasts', Family='behemoths' },
        ['Light Elemental'] = { Name='Light Elemental', Ecosystem='elementals', Family='elementals' },
        ['Lightsteel Quadav'] = { Name='Lightsteel Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Metalloid Amoeba'] = { Name='Metalloid Amoeba', Ecosystem='amorphs', Family='slimes' },
        ['Millenary Mossback'] = { Name='Millenary Mossback', Ecosystem='lizards', Family='adamantoises' },
        ['Mountain Buffalo'] = { Name='Mountain Buffalo', Ecosystem='beasts', Family='buffaloes' },
        ['Na\'Qba Chirurgeon'] = { Name='Na\'Qba Chirurgeon', Ecosystem='beastmen', Family='quadav' },
        ['Nergal'] = { Name='Nergal', Ecosystem='amorphs', Family='leeches' },
        ['Okeanos'] = { Name='Okeanos', Ecosystem='beastmen', Family='gigas' },
        ['Orc\'s Wyvern'] = { Name='Orc\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Pluto'] = { Name='Pluto', Ecosystem='undead', Family='doomed' },
        ['Proto-Omega'] = { Name='Proto-Omega', Ecosystem='unclassified', Family='biological weapons' },
        ['Sirin'] = { Name='Sirin', Ecosystem='birds', Family='birds' },
        ['Star Ruby Quadav'] = { Name='Star Ruby Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Star Sapphire Quadav'] = { Name='Star Sapphire Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Thiazi'] = { Name='Thiazi', Ecosystem='birds', Family='rocs' },
        ['Thunder Elemental'] = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals' },
        ['Tieholtsodi'] = { Name='Tieholtsodi', Ecosystem='aquans', Family='sea monks' },
        ['Troglodyte Dhalmel'] = { Name='Troglodyte Dhalmel', Ecosystem='beasts', Family='dhalmels' },
        ['Water Elemental'] = { Name='Water Elemental', Ecosystem='elementals', Family='elementals' },
        ['Whitegold Quadav'] = { Name='Whitegold Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Wootz Quadav'] = { Name='Wootz Quadav', Ecosystem='beastmen', Family='quadav' },
        ['Yagudo Archpriest'] = { Name='Yagudo Archpriest', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Disciplinant'] = { Name='Yagudo Disciplinant', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Eradicator'] = { Name='Yagudo Eradicator', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Kapellmeister'] = { Name='Yagudo Kapellmeister', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Knight Templar'] = { Name='Yagudo Knight Templar', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo Prelatess'] = { Name='Yagudo Prelatess', Ecosystem='beastmen', Family='yagudo' },
        ['Yagudo\'s Avatar'] = { Name='Yagudo\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Yagudo\'s Elemental'] = { Name='Yagudo\'s Elemental', Ecosystem='elementals', Family='elementals' },
        ['Zlatorog'] = { Name='Zlatorog', Ecosystem='beasts', Family='rams' },
    },
};
