--Zone: Dynamis - Valkurm
--Zone ID: 39
return {
    Names = {
        ['Adamantking Effigy'] = { Name='Adamantking Effigy', Ecosystem='unclassified', Family='replicas' },
        ['Adamantking Image'] = { Name='Adamantking Image', Ecosystem='unclassified', Family='replicas' },
        ['Arch Christelle'] = { Name='Arch Christelle', Ecosystem='plantoids', Family='morbols' },
        ['Avatar Idol'] = { Name='Avatar Idol', Ecosystem='unclassified', Family='replicas' },
        ['Cirrate Christelle'] = { Name='Cirrate Christelle', Ecosystem='plantoids', Family='morbols' },
        ['Fairy Ring'] = { Name='Fairy Ring', Ecosystem='plantoids', Family='funguars' },
        ['Goblin Replica'] = { Name='Goblin Replica', Ecosystem='unclassified', Family='replicas' },
        ['Goblin Statue'] = { Name='Goblin Statue', Ecosystem='unclassified', Family='replicas' },
        ['Lost Fairy Ring'] = { Name='Lost Fairy Ring', Ecosystem='plantoids', Family='funguars' },
        ['Lost Nant\'ina'] = { Name='Lost Nant\'ina', Ecosystem='plantoids', Family='goobues' },
        ['Lost Stcemqestcint'] = { Name='Lost Stcemqestcint', Ecosystem='plantoids', Family='treants' },
        ['Manifest Icon'] = { Name='Manifest Icon', Ecosystem='unclassified', Family='replicas' },
        ['Nant\'ina'] = { Name='Nant\'ina', Ecosystem='plantoids', Family='goobues' },
        ['Nightmare Fly'] = { Name='Nightmare Fly', Ecosystem='vermin', Family='flies' },
        ['Nightmare Flytrap'] = { Name='Nightmare Flytrap', Ecosystem='plantoids', Family='flytraps' },
        ['Nightmare Funguar'] = { Name='Nightmare Funguar', Ecosystem='plantoids', Family='funguars' },
        ['Nightmare Goobbue'] = { Name='Nightmare Goobbue', Ecosystem='plantoids', Family='goobues' },
        ['Nightmare Hippogryph'] = { Name='Nightmare Hippogryph', Ecosystem='birds', Family='hippogryphs' },
        ['Nightmare Manticore'] = { Name='Nightmare Manticore', Ecosystem='beasts', Family='manticores' },
        ['Nightmare Sabotender'] = { Name='Nightmare Sabotender', Ecosystem='plantoids', Family='sabotenders' },
        ['Nightmare Sheep'] = { Name='Nightmare Sheep', Ecosystem='beasts', Family='sheep' },
        ['Nightmare Treant'] = { Name='Nightmare Treant', Ecosystem='plantoids', Family='treants' },
        ['Serjeant Tombstone'] = { Name='Serjeant Tombstone', Ecosystem='unclassified', Family='replicas' },
        ['Stcemqestcint'] = { Name='Stcemqestcint', Ecosystem='plantoids', Family='treants' },
        ['Vanguard Alchemist'] = { Name='Vanguard Alchemist', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Ambusher'] = { Name='Vanguard Ambusher', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Amputator'] = { Name='Vanguard Amputator', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Armorer'] = { Name='Vanguard Armorer', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Assassin'] = { Name='Vanguard Assassin', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Backstabber'] = { Name='Vanguard Backstabber', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Beasttender'] = { Name='Vanguard Beasttender', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Bugler'] = { Name='Vanguard Bugler', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Chanter'] = { Name='Vanguard Chanter', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Constable'] = { Name='Vanguard Constable', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Defender'] = { Name='Vanguard Defender', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Dollmaster'] = { Name='Vanguard Dollmaster', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Dragontamer'] = { Name='Vanguard Dragontamer', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Drakekeeper'] = { Name='Vanguard Drakekeeper', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Enchanter'] = { Name='Vanguard Enchanter', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Exemplar'] = { Name='Vanguard Exemplar', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Footsoldier'] = { Name='Vanguard Footsoldier', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Grappler'] = { Name='Vanguard Grappler', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Gutslasher'] = { Name='Vanguard Gutslasher', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Hatamoto'] = { Name='Vanguard Hatamoto', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Hawker'] = { Name='Vanguard Hawker', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Hitman'] = { Name='Vanguard Hitman', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Impaler'] = { Name='Vanguard Impaler', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Inciter'] = { Name='Vanguard Inciter', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Kusa'] = { Name='Vanguard Kusa', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Liberator'] = { Name='Vanguard Liberator', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Maestro'] = { Name='Vanguard Maestro', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Mason'] = { Name='Vanguard Mason', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Mesmerizer'] = { Name='Vanguard Mesmerizer', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Militant'] = { Name='Vanguard Militant', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Minstrel'] = { Name='Vanguard Minstrel', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Neckchopper'] = { Name='Vanguard Neckchopper', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Necromancer'] = { Name='Vanguard Necromancer', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Ogresoother'] = { Name='Vanguard Ogresoother', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Oracle'] = { Name='Vanguard Oracle', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Partisan'] = { Name='Vanguard Partisan', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Pathfinder'] = { Name='Vanguard Pathfinder', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Persecutor'] = { Name='Vanguard Persecutor', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Pillager'] = { Name='Vanguard Pillager', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Pitfighter'] = { Name='Vanguard Pitfighter', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Predator'] = { Name='Vanguard Predator', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Prelate'] = { Name='Vanguard Prelate', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Priest'] = { Name='Vanguard Priest', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Protector'] = { Name='Vanguard Protector', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Purloiner'] = { Name='Vanguard Purloiner', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Ronin'] = { Name='Vanguard Ronin', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Salvager'] = { Name='Vanguard Salvager', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Sentinel'] = { Name='Vanguard Sentinel', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Shaman'] = { Name='Vanguard Shaman', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Skirmisher'] = { Name='Vanguard Skirmisher', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Smithy'] = { Name='Vanguard Smithy', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Thaumaturge'] = { Name='Vanguard Thaumaturge', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Tinkerer'] = { Name='Vanguard Tinkerer', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Trooper'] = { Name='Vanguard Trooper', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Undertaker'] = { Name='Vanguard Undertaker', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Vexer'] = { Name='Vanguard Vexer', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Vigilante'] = { Name='Vanguard Vigilante', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Vindicator'] = { Name='Vanguard Vindicator', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Visionary'] = { Name='Vanguard Visionary', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Welldigger'] = { Name='Vanguard Welldigger', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard\'s Avatar'] = { Name='Vanguard\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Vanguard\'s Crow'] = { Name='Vanguard\'s Crow', Ecosystem='birds', Family='birds' },
        ['Vanguard\'s Hecteyes'] = { Name='Vanguard\'s Hecteyes', Ecosystem='amorphs', Family='hecteyes' },
        ['Vanguard\'s Scorpion'] = { Name='Vanguard\'s Scorpion', Ecosystem='vermin', Family='scorpions' },
        ['Vanguard\'s Slime'] = { Name='Vanguard\'s Slime', Ecosystem='amorphs', Family='slimes' },
        ['Vanguard\'s Wyvern'] = { Name='Vanguard\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Warchief Tombstone'] = { Name='Warchief Tombstone', Ecosystem='unclassified', Family='replicas' },
    },
};
