--Zone: Bibiki Bay
--Zone ID: 4
return {
    Names = {
        ['Alraune']                 = { Name='Alraune', Ecosystem='beastmen', Family='goblins' },
        ['Apsaras']                 = { Name='Apsaras', Ecosystem='plantoids', Family='mandragoras' },
        ['Bismarck']                = { Name='Bismarck', Ecosystem='aquans', Family='pterakos' },
        ['Catoblepas']              = { Name='Catoblepas', Ecosystem='beast', Family='dhalmels' },
        ['Coastal Opo-opo']         = { Name='Coastal Opo-opo', Ecosystem='beast', Family='opo-opos' },
        ['Coralline Uragnite']      = { Name='Coralline Uragnite', Ecosystem='aquans', Family='uragnites' },
        ['Dalham']                  = { Name='Dalham', Ecosystem='aquans', Family='sea monks' },
        ['Eft']                     = { Name='Eft', Ecosystem='lizards', Family='efts' },
        ['Ghost Crab']              = { Name='Ghost Crab', Ecosystem='aquans', Family='crabs' },
        ['Goblin Pathfinder']       = { Name='Goblin Pathfinder', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Shaman']           = { Name='Goblin Shaman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Rarab']         = { Name='Goblin\'s Rarab', Ecosystem='vermin', Family='rabbits' },
        ['Greater Pugil']           = { Name='Greater Pugil', Ecosystem='aquans', Family='pugils' },
        ['Grindylow']               = { Name='Grindylow', Ecosystem='aquans', Family='crabs' },
        ['Hobgoblin Animalier']     = { Name='Hobgoblin Animalier', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Fascinator']    = { Name='Hobgoblin Fascinator', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Martialist']    = { Name='Hobgoblin Martialist', Ecosystem='beastmen', Family='goblins' },
        ['Hobgoblin Venerer']       = { Name='Hobgoblin Venerer', Ecosystem='beastmen', Family='goblins' },
        ['Ignis Fatuus']            = { Name='Ignis Fatuus', Ecosystem='arcana', Family='bombs' },
        ['Intuila']                 = { Name='Intuila', Ecosystem='lizards', Family='efts' },
        ['Intulo']                  = { Name='Intulo', Ecosystem='lizards', Family='efts' },
        ['Island Rarab']            = { Name='Island Rarab', Ecosystem='vermin', Family='rabbits' },
        ['Jagil']                   = { Name='Jagil', Ecosystem='aquans', Family='pugils' },
        ['Kraken']                  = { Name='Kraken', Ecosystem='aquans', Family='sea monks' },
        ['Lancet Jagil']            = { Name='Lancet Jagil', Ecosystem='aquans', Family='sea monks' },
        ['Locus Bight Rarab']       = { Name='Locus Bight Rarab', Ecosystem='vermin', Family='rabbits' },
        ['Locus Camelopard']        = { Name='Locus Camelopard', Ecosystem='beast', Family='dhalmels' },
        ['Locus Ghost Crab']        = { Name='Locus Ghost Crab', Ecosystem='aquans', Family='crabs' },
        ['Locus Hypnos Eft']        = { Name='Locus Hypnos Eft', Ecosystem='lizards', Family='efts' },
        ['Marine Dhalmel']          = { Name='Marine Dhalmel', Ecosystem='beast', Family='dhalmels' },
        ['Peerifool']               = { Name='Peerifool', Ecosystem='plantoids', Family='mandragoras' },
        ['Primordial Pugil']        = { Name='Primordial Pugil', Ecosystem='aquans', Family='pugils' },
        ['Raven']                   = { Name='Raven', Ecosystem='birds', Family='birds' },
        ['Rohemolipaud']            = { Name='Rohemolipaud', Ecosystem='humanoids', Family='humans' },
        ['Serra']                   = { Name='Serra', Ecosystem='aquans', Family='pugils' },
        ['Shankha']                 = { Name='Shankha', Ecosystem='aquans', Family='uragnites' },
        ['Shen']                    = { Name='Shen', Ecosystem='aquans', Family='uragnites' },
        ['Shen\'s Filtrate']        = { Name='Shen\'s Filtrate', Ecosystem='elementals', Family='elementals' },
        ['Splacknuck']              = { Name='Splacknuck', Ecosystem='lizards', Family='efts' },
        ['Tartarus Eft']            = { Name='Tartarus Eft', Ecosystem='lizards', Family='efts' },
        ['Teine Sith']              = { Name='Teine Sith', Ecosystem='arcana', Family='bombs' },
        ['Toucan']                  = { Name='Toucan', Ecosystem='birds', Family='birds' },
        ['Tragopan']                = { Name='Tragopan', Ecosystem='birds', Family='birds' },
        ['Tropical Rarab']          = { Name='Tropical Rarab', Ecosystem='vermin', Family='rabbits' },
        ['Viscous Clot']            = { Name='Viscous Clot', Ecosystem='amorphs', Family='slimes' },
    },
};
