--Zone: Dynamis - Buburimu
--Zone ID: 40
return {
    Names = {
        ['Adamantking Effigy'] = { Name='Adamantking Effigy', Ecosystem='unclassified', Family='replicas' },
        ['Adamantking Image'] = { Name='Adamantking Image', Ecosystem='unclassified', Family='replicas' },
        ['Aitvaras'] = { Name='Aitvaras', Ecosystem='dragons', Family='dragons' },
        ['Alklha'] = { Name='Alklha', Ecosystem='dragons', Family='dragons' },
        ['Apocalyptic Beast'] = { Name='Apocalyptic Beast', Ecosystem='dragons', Family='dragons' },
        ['Arch Apocalyptic Beast'] = { Name='Arch Apocalyptic Beast', Ecosystem='dragons', Family='dragons' },
        ['Avatar Idol'] = { Name='Avatar Idol', Ecosystem='unclassified', Family='replicas' },
        ['Baa Dava the Bibliophage'] = { Name='Baa Dava the Bibliophage', Ecosystem='beastmen', Family='yagudo' },
        ['Baa\'s Avatar'] = { Name='Baa\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Barong'] = { Name='Barong', Ecosystem='dragons', Family='dragons' },
        ['Bxafraff\'s Wyvern'] = { Name='Bxafraff\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Doo Peku the Fleetfoot'] = { Name='Doo Peku the Fleetfoot', Ecosystem='beastmen', Family='yagudo' },
        ['Elvaansticker Bxafraff'] = { Name='Elvaansticker Bxafraff', Ecosystem='beastmen', Family='orcs' },
        ['Flamecaller Zoeqdoq'] = { Name='Flamecaller Zoeqdoq', Ecosystem='beastmen', Family='orcs' },
        ['Gi\'Bhe Fleshfeaster'] = { Name='Gi\'Bhe Fleshfeaster', Ecosystem='beastmen', Family='quadav' },
        ['Goblin Replica'] = { Name='Goblin Replica', Ecosystem='unclassified', Family='replicas' },
        ['Goblin Statue'] = { Name='Goblin Statue', Ecosystem='unclassified', Family='replicas' },
        ['Gosspix Blabberlips'] = { Name='Gosspix Blabberlips', Ecosystem='beastmen', Family='goblins' },
        ['Hamfist Gukhbuk'] = { Name='Hamfist Gukhbuk', Ecosystem='beastmen', Family='orcs' },
        ['Koo Rahi the Levinblade'] = { Name='Koo Rahi the Levinblade', Ecosystem='beastmen', Family='yagudo' },
        ['Lost Aitvaras'] = { Name='Lost Aitvaras', Ecosystem='dragons', Family='dragons' },
        ['Lost Alklha'] = { Name='Lost Alklha', Ecosystem='dragons', Family='dragons' },
        ['Lost Barong'] = { Name='Lost Barong', Ecosystem='dragons', Family='dragons' },
        ['Lost Stihi'] = { Name='Lost Stihi', Ecosystem='dragons', Family='dragons' },
        ['Lyncean Juwgneg'] = { Name='Lyncean Juwgneg', Ecosystem='beastmen', Family='orcs' },
        ['Manifest Icon'] = { Name='Manifest Icon', Ecosystem='unclassified', Family='replicas' },
        ['Nightmare Bunny'] = { Name='Nightmare Bunny', Ecosystem='beasts', Family='rabbits' },
        ['Nightmare Crab'] = { Name='Nightmare Crab', Ecosystem='aquans', Family='crabs' },
        ['Nightmare Crawler'] = { Name='Nightmare Crawler', Ecosystem='vermin', Family='crawlers' },
        ['Nightmare Dhalmel'] = { Name='Nightmare Dhalmel', Ecosystem='beasts', Family='dhalmels' },
        ['Nightmare Eft'] = { Name='Nightmare Eft', Ecosystem='lizards', Family='efts' },
        ['Nightmare Mandragora'] = { Name='Nightmare Mandragora', Ecosystem='plantoids', Family='mandragoras' },
        ['Nightmare Raven'] = { Name='Nightmare Raven', Ecosystem='birds', Family='birds' },
        ['Nightmare Scorpion'] = { Name='Nightmare Scorpion', Ecosystem='vermin', Family='scorions' },
        ['Nightmare Uragnite'] = { Name='Nightmare Uragnite', Ecosystem='aquans', Family='uragnites' },
        ['Qu\'Pho Bloodspiller'] = { Name='Qu\'Pho Bloodspiller', Ecosystem='beastmen', Family='quadav' },
        ['Ree Nata the Melomanic'] = { Name='Ree Nata the Melomanic', Ecosystem='beastmen', Family='yagudo' },
        ['Serjeant Tombstone'] = { Name='Serjeant Tombstone', Ecosystem='unclassified', Family='replicas' },
        ['Shamblix Rottenheart'] = { Name='Shamblix Rottenheart', Ecosystem='beastmen', Family='goblins' },
        ['Stihi'] = { Name='Stihi', Ecosystem='dragons', Family='dragons' },
        ['Te\'Zha Ironclad'] = { Name='Te\'Zha Ironclad', Ecosystem='beastmen', Family='quadav' },
        ['Va\'Rhu Bodysnatcher'] = { Name='Va\'Rhu Bodysnatcher', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Alchemist'] = { Name='Vanguard Alchemist', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Ambusher'] = { Name='Vanguard Ambusher', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Amputator'] = { Name='Vanguard Amputator', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Armorer'] = { Name='Vanguard Armorer', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Assassin'] = { Name='Vanguard Assassin', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Backstabber'] = { Name='Vanguard Backstabber', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Beasttender'] = { Name='Vanguard Beasttender', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Bugler'] = { Name='Vanguard Bugler', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Chanter'] = { Name='Vanguard Chanter', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Constable'] = { Name='Vanguard Constable', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Defender'] = { Name='Vanguard Defender', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Dollmaster'] = { Name='Vanguard Dollmaster', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Dragontamer'] = { Name='Vanguard Dragontamer', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Drakekeeper'] = { Name='Vanguard Drakekeeper', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Enchanter'] = { Name='Vanguard Enchanter', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Exemplar'] = { Name='Vanguard Exemplar', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Footsoldier'] = { Name='Vanguard Footsoldier', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Grappler'] = { Name='Vanguard Grappler', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Gutslasher'] = { Name='Vanguard Gutslasher', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Hatamoto'] = { Name='Vanguard Hatamoto', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Hawker'] = { Name='Vanguard Hawker', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Hitman'] = { Name='Vanguard Hitman', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Impaler'] = { Name='Vanguard Impaler', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Inciter'] = { Name='Vanguard Inciter', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Kusa'] = { Name='Vanguard Kusa', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Liberator'] = { Name='Vanguard Liberator', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Maestro'] = { Name='Vanguard Maestro', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Mason'] = { Name='Vanguard Mason', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Mesmerizer'] = { Name='Vanguard Mesmerizer', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Militant'] = { Name='Vanguard Militant', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Minstrel'] = { Name='Vanguard Minstrel', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Neckchopper'] = { Name='Vanguard Neckchopper', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Necromancer'] = { Name='Vanguard Necromancer', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Ogresoother'] = { Name='Vanguard Ogresoother', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Oracle'] = { Name='Vanguard Oracle', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Partisan'] = { Name='Vanguard Partisan', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Pathfinder'] = { Name='Vanguard Pathfinder', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Persecutor'] = { Name='Vanguard Persecutor', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Pillager'] = { Name='Vanguard Pillager', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Pitfighter'] = { Name='Vanguard Pitfighter', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Predator'] = { Name='Vanguard Predator', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Prelate'] = { Name='Vanguard Prelate', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Priest'] = { Name='Vanguard Priest', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Protector'] = { Name='Vanguard Protector', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Purloiner'] = { Name='Vanguard Purloiner', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Ronin'] = { Name='Vanguard Ronin', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Salvager'] = { Name='Vanguard Salvager', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Sentinel'] = { Name='Vanguard Sentinel', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Shaman'] = { Name='Vanguard Shaman', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Skirmisher'] = { Name='Vanguard Skirmisher', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Smithy'] = { Name='Vanguard Smithy', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Thaumaturge'] = { Name='Vanguard Thaumaturge', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Tinkerer'] = { Name='Vanguard Tinkerer', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard Trooper'] = { Name='Vanguard Trooper', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Undertaker'] = { Name='Vanguard Undertaker', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Vexer'] = { Name='Vanguard Vexer', Ecosystem='beastmen', Family='orcs' },
        ['Vanguard Vigilante'] = { Name='Vanguard Vigilante', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Vindicator'] = { Name='Vanguard Vindicator', Ecosystem='beastmen', Family='quadav' },
        ['Vanguard Visionary'] = { Name='Vanguard Visionary', Ecosystem='beastmen', Family='yagudo' },
        ['Vanguard Welldigger'] = { Name='Vanguard Welldigger', Ecosystem='beastmen', Family='goblins' },
        ['Vanguard\'s Avatar'] = { Name='Vanguard\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Vanguard\'s Crow'] = { Name='Vanguard\'s Crow', Ecosystem='birds', Family='birds' },
        ['Vanguard\'s Hecteyes'] = { Name='Vanguard\'s Hecteyes', Ecosystem='amorphs', Family='hecteyes' },
        ['Vanguard\'s Scorpion'] = { Name='Vanguard\'s Scorpion', Ecosystem='vermin', Family='scorions' },
        ['Vanguard\'s Slime'] = { Name='Vanguard\'s Slime', Ecosystem='amorphs', Family='slimes' },
        ['Vanguard\'s Wyvern'] = { Name='Vanguard\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Warchief Tombstone'] = { Name='Warchief Tombstone', Ecosystem='unclassified', Family='replicas' },
        ['Woodnix Shrillwhistle'] = { Name='Woodnix Shrillwhistle', Ecosystem='beastmen', Family='goblins' },
        ['Woodnix\'s Slime'] = { Name='Woodnix\'s Slime', Ecosystem='amorphs', Family='slimes' },
    },
};
