--Zone: Dynamis - Qufim
--Zone ID: 41
return {
    Names = {
        ['Adamantking Effigy'] = { Name='Adamantking Effigy', Ecosystem='unclassified', Family='replicas'},
        ['Adamantking Image'] = { Name='Adamantking Image', Ecosystem='unclassified', Family='replicas'},
        ['Antaeus'] = { Name='Antaeus', Ecosystem='beastmen', Family='gigas'},
        ['Arch Antaeus'] = { Name='Arch Antaeus', Ecosystem='beastmen', Family='gigas'},
        ['Avatar Idol'] = { Name='Avatar Idol', Ecosystem='unclassified', Family='replicas'},
        ['Goblin Replica'] = { Name='Goblin Replica', Ecosystem='unclassified', Family='replicas'},
        ['Goblin Statue'] = { Name='Goblin Statue', Ecosystem='unclassified', Family='replicas'},
        ['Lost Scolopendra'] = { Name='Lost Scolopendra', Ecosystem='aquans', Family='sea monks'},
        ['Lost Stringes'] = { Name='Lost Stringes', Ecosystem='birds', Family='bats'},
        ['Lost Suttung'] = { Name='Lost Suttung', Ecosystem='arcana', Family='golems'},
        ['Manifest Icon'] = { Name='Manifest Icon', Ecosystem='unclassified', Family='replicas'},
        ['Nightmare Diremite'] = { Name='Nightmare Diremite', Ecosystem='vermin', Family='diremites'},
        ['Nightmare Gaylas'] = { Name='Nightmare Gaylas', Ecosystem='birds', Family='bat trios'},
        ['Nightmare Kraken'] = { Name='Nightmare Kraken', Ecosystem='aquans', Family='sea monks'},
        ['Nightmare Raptor'] = { Name='Nightmare Raptor', Ecosystem='lizards', Family='raptors'},
        ['Nightmare Roc'] = { Name='Nightmare Roc', Ecosystem='birds', Family='rocs'},
        ['Nightmare Snoll'] = { Name='Nightmare Snoll', Ecosystem='arcana', Family='snolls'},
        ['Nightmare Stirge'] = { Name='Nightmare Stirge', Ecosystem='birds', Family='bats'},
        ['Nightmare Tiger'] = { Name='Nightmare Tiger', Ecosystem='beasts', Family='tigers'},
        ['Nightmare Weapon'] = { Name='Nightmare Weapon', Ecosystem='arcana', Family='evil weapons'},
        ['Scolopendra'] = { Name='Scolopendra', Ecosystem='aquans', Family='sea monks'},
        ['Serjeant Tombstone'] = { Name='Serjeant Tombstone', Ecosystem='unclassified', Family='replicas'},
        ['Stringes'] = { Name='Stringes', Ecosystem='birds', Family='bats'},
        ['Suttung'] = { Name='Suttung', Ecosystem='arcana', Family='golems'},
        ['Vanguard Alchemist'] = { Name='Vanguard Alchemist', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Ambusher'] = { Name='Vanguard Ambusher', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Amputator'] = { Name='Vanguard Amputator', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Armorer'] = { Name='Vanguard Armorer', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Assassin'] = { Name='Vanguard Assassin', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Backstabber'] = { Name='Vanguard Backstabber', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Beasttender'] = { Name='Vanguard Beasttender', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Bugler'] = { Name='Vanguard Bugler', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Chanter'] = { Name='Vanguard Chanter', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Constable'] = { Name='Vanguard Constable', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Defender'] = { Name='Vanguard Defender', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Dollmaster'] = { Name='Vanguard Dollmaster', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Dragontamer'] = { Name='Vanguard Dragontamer', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Drakekeeper'] = { Name='Vanguard Drakekeeper', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Enchanter'] = { Name='Vanguard Enchanter', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Exemplar'] = { Name='Vanguard Exemplar', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Footsoldier'] = { Name='Vanguard Footsoldier', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Grappler'] = { Name='Vanguard Grappler', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Gutslasher'] = { Name='Vanguard Gutslasher', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Hatamoto'] = { Name='Vanguard Hatamoto', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Hawker'] = { Name='Vanguard Hawker', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Hitman'] = { Name='Vanguard Hitman', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Impaler'] = { Name='Vanguard Impaler', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Inciter'] = { Name='Vanguard Inciter', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Kusa'] = { Name='Vanguard Kusa', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Liberator'] = { Name='Vanguard Liberator', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Maestro'] = { Name='Vanguard Maestro', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Mason'] = { Name='Vanguard Mason', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Mesmerizer'] = { Name='Vanguard Mesmerizer', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Militant'] = { Name='Vanguard Militant', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Minstrel'] = { Name='Vanguard Minstrel', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Neckchopper'] = { Name='Vanguard Neckchopper', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Necromancer'] = { Name='Vanguard Necromancer', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Ogresoother'] = { Name='Vanguard Ogresoother', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Oracle'] = { Name='Vanguard Oracle', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Partisan'] = { Name='Vanguard Partisan', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Pathfinder'] = { Name='Vanguard Pathfinder', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Persecutor'] = { Name='Vanguard Persecutor', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Pillager'] = { Name='Vanguard Pillager', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Pitfighter'] = { Name='Vanguard Pitfighter', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Predator'] = { Name='Vanguard Predator', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Prelate'] = { Name='Vanguard Prelate', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Priest'] = { Name='Vanguard Priest', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Protector'] = { Name='Vanguard Protector', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Purloiner'] = { Name='Vanguard Purloiner', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Ronin'] = { Name='Vanguard Ronin', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Salvager'] = { Name='Vanguard Salvager', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Sentinel'] = { Name='Vanguard Sentinel', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Shaman'] = { Name='Vanguard Shaman', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Skirmisher'] = { Name='Vanguard Skirmisher', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Smithy'] = { Name='Vanguard Smithy', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Thaumaturge'] = { Name='Vanguard Thaumaturge', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Tinkerer'] = { Name='Vanguard Tinkerer', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard Trooper'] = { Name='Vanguard Trooper', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Undertaker'] = { Name='Vanguard Undertaker', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Vexer'] = { Name='Vanguard Vexer', Ecosystem='beastmen', Family='orcs'},
        ['Vanguard Vigilante'] = { Name='Vanguard Vigilante', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Vindicator'] = { Name='Vanguard Vindicator', Ecosystem='beastmen', Family='quadav'},
        ['Vanguard Visionary'] = { Name='Vanguard Visionary', Ecosystem='beastmen', Family='yagudo'},
        ['Vanguard Welldigger'] = { Name='Vanguard Welldigger', Ecosystem='beastmen', Family='goblins'},
        ['Vanguard\'s Avatar'] = { Name='Vanguard\'s Avatar', Ecosystem='unclassified', Family='avatars'},
        ['Vanguard\'s Crow'] = { Name='Vanguard\'s Crow', Ecosystem='birds', Family='birds'},
        ['Vanguard\'s Hecteyes'] = { Name='Vanguard\'s Hecteyes', Ecosystem='amorphs', Family='hecteyes'},
        ['Vanguard\'s Scorpion'] = { Name='Vanguard\'s Scorpion', Ecosystem='vermin', Family='scorpions'},
        ['Vanguard\'s Slime'] = { Name='Vanguard\'s Slime', Ecosystem='amorphs', Family='slimes'},
        ['Vanguard\'s Wyvern'] = { Name='Vanguard\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Warchief Tombstone'] = { Name='Warchief Tombstone', Ecosystem='unclassified', Family='replicas'},
    },
};
