--Zone: Dynamis - Tavnazia
--Zone ID: 42
return {
    Names = {
        ['Adamantking Effigy'] = { Name='Adamantking Effigy', Ecosystem='unclassified', Family='replicas' },
        ['Diabolos Club'] = { Name='Diabolos Club', Ecosystem='unclassified', Family='avatars' },
        ['Diabolos Diamond'] = { Name='Diabolos Diamond', Ecosystem='unclassified', Family='avatars' },
        ['Diabolos Heart'] = { Name='Diabolos Heart', Ecosystem='unclassified', Family='avatars' },
        ['Diabolos Letum'] = { Name='Diabolos Letum', Ecosystem='unclassified', Family='avatars' },
        ['Diabolos Nox'] = { Name='Diabolos Nox', Ecosystem='unclassified', Family='avatars' },
        ['Diabolos Somnus'] = { Name='Diabolos Somnus', Ecosystem='unclassified', Family='avatars' },
        ['Diabolos Spade'] = { Name='Diabolos Spade', Ecosystem='unclassified', Family='avatars' },
        ['Diabolos Umbra'] = { Name='Diabolos Umbra', Ecosystem='unclassified', Family='avatars' },
        ['Diabolos\'s Shard'] = { Name='Diabolos\'s Shard', Ecosystem='unclassified', Family='avatars' },
        ['Effigy Prototype'] = { Name='Effigy Prototype', Ecosystem='unclassified', Family='replicas' },
        ['Goblin Replica'] = { Name='Goblin Replica', Ecosystem='unclassified', Family='replicas' },
        ['Hydra Bard'] = { Name='Hydra Bard', Ecosystem='undead', Family='fomors' },
        ['Hydra Beastmaster'] = { Name='Hydra Beastmaster', Ecosystem='undead', Family='fomors' },
        ['Hydra Black Mage'] = { Name='Hydra Black Mage', Ecosystem='undead', Family='fomors' },
        ['Hydra Dark Knight'] = { Name='Hydra Dark Knight', Ecosystem='undead', Family='fomors' },
        ['Hydra Dragoon'] = { Name='Hydra Dragoon', Ecosystem='undead', Family='fomors' },
        ['Hydra Monk'] = { Name='Hydra Monk', Ecosystem='undead', Family='fomors' },
        ['Hydra Ninja'] = { Name='Hydra Ninja', Ecosystem='undead', Family='fomors' },
        ['Hydra Paladin'] = { Name='Hydra Paladin', Ecosystem='undead', Family='fomors' },
        ['Hydra Ranger'] = { Name='Hydra Ranger', Ecosystem='undead', Family='fomors' },
        ['Hydra Red Mage'] = { Name='Hydra Red Mage', Ecosystem='undead', Family='fomors' },
        ['Hydra Samurai'] = { Name='Hydra Samurai', Ecosystem='undead', Family='fomors' },
        ['Hydra Summoner'] = { Name='Hydra Summoner', Ecosystem='undead', Family='fomors' },
        ['Hydra Thief'] = { Name='Hydra Thief', Ecosystem='undead', Family='fomors' },
        ['Hydra Warrior'] = { Name='Hydra Warrior', Ecosystem='undead', Family='fomors' },
        ['Hydra White Mage'] = { Name='Hydra White Mage', Ecosystem='undead', Family='fomors' },
        ['Hydra\'s Avatar'] = { Name='Hydra\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Hydra\'s Hound'] = { Name='Hydra\'s Hound', Ecosystem='undead', Family='hounds' },
        ['Hydra\'s Wyvern'] = { Name='Hydra\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Icon Prototype'] = { Name='Icon Prototype', Ecosystem='unclassified', Family='replicas' },
        ['Kindred Bard'] = { Name='Kindred Bard', Ecosystem='demons', Family='demons' },
        ['Kindred Beastmaster'] = { Name='Kindred Beastmaster', Ecosystem='demons', Family='demons' },
        ['Kindred Black Mage'] = { Name='Kindred Black Mage', Ecosystem='demons', Family='demons' },
        ['Kindred Dark Knight'] = { Name='Kindred Dark Knight', Ecosystem='demons', Family='demons' },
        ['Kindred Dragoon'] = { Name='Kindred Dragoon', Ecosystem='demons', Family='demons' },
        ['Kindred Monk'] = { Name='Kindred Monk', Ecosystem='demons', Family='demons' },
        ['Kindred Ninja'] = { Name='Kindred Ninja', Ecosystem='demons', Family='demons' },
        ['Kindred Paladin'] = { Name='Kindred Paladin', Ecosystem='demons', Family='demons' },
        ['Kindred Ranger'] = { Name='Kindred Ranger', Ecosystem='demons', Family='demons' },
        ['Kindred Red Mage'] = { Name='Kindred Red Mage', Ecosystem='demons', Family='demons' },
        ['Kindred Samurai'] = { Name='Kindred Samurai', Ecosystem='demons', Family='demons' },
        ['Kindred Summoner'] = { Name='Kindred Summoner', Ecosystem='demons', Family='demons' },
        ['Kindred Thief'] = { Name='Kindred Thief', Ecosystem='demons', Family='demons' },
        ['Kindred Warrior'] = { Name='Kindred Warrior', Ecosystem='demons', Family='demons' },
        ['Kindred White Mage'] = { Name='Kindred White Mage', Ecosystem='demons', Family='demons' },
        ['Kindred\'s Avatar'] = { Name='Kindred\'s Avatar', Ecosystem='unclassified', Family='avatars' },
        ['Kindred\'s Vouivre'] = { Name='Kindred\'s Vouivre', Ecosystem='dragons', Family='wyverns' },
        ['Kindred\'s Wyvern'] = { Name='Kindred\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Manifest Icon'] = { Name='Manifest Icon', Ecosystem='unclassified', Family='replicas' },
        ['Nightmare Bugard'] = { Name='Nightmare Bugard', Ecosystem='lizards', Family='bugards' },
        ['Nightmare Cluster'] = { Name='Nightmare Cluster', Ecosystem='arcana', Family='clusters' },
        ['Nightmare Hornet'] = { Name='Nightmare Hornet', Ecosystem='vermin', Family='bees' },
        ['Nightmare Leech'] = { Name='Nightmare Leech', Ecosystem='amorphs', Family='leeches' },
        ['Nightmare Makara'] = { Name='Nightmare Makara', Ecosystem='aquans', Family='pugils' },
        ['Nightmare Taurus'] = { Name='Nightmare Taurus', Ecosystem='demons', Family='tauri' },
        ['Nightmare Worm'] = { Name='Nightmare Worm', Ecosystem='amorphs', Family='worms' },
        ['Prototype Eye'] = { Name='Prototype Eye', Ecosystem='demons', Family='ahriman' },
        ['Serjeant Tombstone'] = { Name='Serjeant Tombstone', Ecosystem='unclassified', Family='replicas' },
        ['Statue Prototype'] = { Name='Statue Prototype', Ecosystem='unclassified', Family='replicas' },
        ['Tombstone Prototype'] = { Name='Tombstone Prototype', Ecosystem='unclassified', Family='replicas' },
        ['Vanguard Eye'] = { Name='Vanguard Eye', Ecosystem='demons', Family='ahriman' },
    },
};
