--Zone: Al Zahbi
--Zone ID: 48
return {
    Names = {
        ['Acrolith'] = { Name='Acrolith', Ecosystem='arcana', Family='acroliths'},
        ['Aerial Torpedo'] = { Name='Aerial Torpedo', Ecosystem='arcana', Family='bombs'},
        ['Assault Bhoot'] = { Name='Assault Bhoot', Ecosystem='undead', Family='ghosts'},
        ['Assault Draugar'] = { Name='Assault Draugar', Ecosystem='undead', Family='skeletons'},
        ['Attack Ziz'] = { Name='Attack Ziz', Ecosystem='birds', Family='cockatrices'},
        ['Bastion Gate'] = { Name='Bastion Gate', Ecosystem='structures', Family='structures'},
        ['Battering Bugard'] = { Name='Battering Bugard', Ecosystem='lizards', Family='bugards'},
        ['Bhoot Intruder'] = { Name='Bhoot Intruder', Ecosystem='undead', Family='ghosts'},
        ['Bhoot Invader'] = { Name='Bhoot Invader', Ecosystem='undead', Family='ghosts'},
        ['Bombshells'] = { Name='Bombshells', Ecosystem='arcana', Family='clusters'},
        ['Brontobugard'] = { Name='Brontobugard', Ecosystem='lizards', Family='bugards'},
        ['Bull Bugard'] = { Name='Bull Bugard', Ecosystem='lizards', Family='bugards'},
        ['Carmine Sentinel'] = { Name='Carmine Sentinel', Ecosystem='unclassified', Family='automatons'},
        ['City Gate'] = { Name='City Gate', Ecosystem='structures', Family='structures'},
        ['Cobalt Sentinel'] = { Name='Cobalt Sentinel', Ecosystem='unclassified', Family='automatons'},
        ['Dartorgor the Austere'] = { Name='Dartorgor the Austere', Ecosystem='beastmen', Family='trolls'},
        ['Decimator Mabel Ja'] = { Name='Decimator Mabel Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Dive-Puk'] = { Name='Dive-Puk', Ecosystem='dragons', Family='puks'},
        ['Draugar\'s Wyvern'] = { Name='Draugar\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Eidolic Qufeel Ja'] = { Name='Eidolic Qufeel Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Expunger'] = { Name='Expunger', Ecosystem='undead', Family='doomed'},
        ['Fighting Flan'] = { Name='Fighting Flan', Ecosystem='arcana', Family='flans'},
        ['Flame Eruca'] = { Name='Flame Eruca', Ecosystem='vermin', Family='crawlers'},
        ['Fleetfingered Mobel Ja'] = { Name='Fleetfingered Mobel Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['General Gadalar'] = { Name='General Gadalar', Ecosystem='humanoids', Family='Humes'},
        ['General Mihli'] = { Name='General Mihli', Ecosystem='humanoids', Family='mithra'},
        ['General Najelith'] = { Name='General Najelith', Ecosystem='humanoids', Family='humes'},
        ['General Rughadjeen'] = { Name='General Rughadjeen', Ecosystem='humanoids', Family='elvaan'},
        ['General Zazarg'] = { Name='General Zazarg', Ecosystem='humanoids', Family='galka'},
        ['Gere'] = { Name='Gere', Ecosystem='beasts', Family='cerberuses'},
        ['Gespenst'] = { Name='Gespenst', Ecosystem='undead', Family='ghosts'},
        ['Girzorhor the Imprudent'] = { Name='Girzorhor the Imprudent', Ecosystem='beastmen', Family='trolls'},
        ['Goblin Lansquenet'] = { Name='Goblin Lansquenet', Ecosystem='beastmen', Family='goblins'},
        ['Gulool Ja Ja'] = { Name='Gulool Ja Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Gurfurlur the Menacing'] = { Name='Gurfurlur the Menacing', Ecosystem='beastmen', Family='trolls'},
        ['Hazel Sentinel'] = { Name='Hazel Sentinel', Ecosystem='unclassified', Family='automatons'},
        ['Illuyankas'] = { Name='Illuyankas', Ecosystem='dragons', Family='hydras'},
        ['Immortal Guard'] = { Name='Immortal Guard', Ecosystem='humanoids', Family='humes'},
        ['Imperial Trooper'] = { Name='Imperial Trooper', Ecosystem='humanoids', Family='humes'},
        ['Incendiary Bombs'] = { Name='Incendiary Bombs', Ecosystem='arcana', Family='clusters'},
        ['Killing Claw'] = { Name='Killing Claw', Ecosystem='vermin', Family='scorpions'},
        ['Lamia Commandress'] = { Name='Lamia Commandress', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Freebooter'] = { Name='Lamia Freebooter', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Immolator'] = { Name='Lamia Immolator', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Jaeger'] = { Name='Lamia Jaeger', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.15'] = { Name='Lamia No.15', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.2'] = { Name='Lamia No.2', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.21'] = { Name='Lamia No.21', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.3'] = { Name='Lamia No.3', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.34'] = { Name='Lamia No.34', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.4'] = { Name='Lamia No.4', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.9'] = { Name='Lamia No.9', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Rover'] = { Name='Lamia Rover', Ecosystem='beastmen', Family='lamia'},
        ['Lamia\'s Avatar'] = { Name='Lamia\'s Avatar', Ecosystem='unclassified', Family='avatars'},
        ['Lamia\'s Elemental'] = { Name='Lamia\'s Elemental', Ecosystem='elementals', Family='elementals'},
        ['Mamool Ja Cataphract'] = { Name='Mamool Ja Cataphract', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Entrancer'] = { Name='Mamool Ja Entrancer', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Fetial'] = { Name='Mamool Ja Fetial', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Handler'] = { Name='Mamool Ja Handler', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Hospitaler'] = { Name='Mamool Ja Hospitaler', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Hussar'] = { Name='Mamool Ja Hussar', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Ravager'] = { Name='Mamool Ja Ravager', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Sapper'] = { Name='Mamool Ja Sapper', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Spotter'] = { Name='Mamool Ja Spotter', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja\'s Lizard'] = { Name='Mamool Ja\'s Lizard', Ecosystem='lizards', Family='lizards'},
        ['Mamool Ja\'s Wyvern'] = { Name='Mamool Ja\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Medusa'] = { Name='Medusa', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Cantatrice'] = { Name='Merrow Cantatrice', Ecosystem='beastmen', Family='lamia'},
        ['Merrow No.11'] = { Name='Merrow No.11', Ecosystem='beastmen', Family='lamia'},
        ['Merrow No.12'] = { Name='Merrow No.12', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Seafarer'] = { Name='Merrow Seafarer', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Shiranuhi'] = { Name='Merrow Shiranuhi', Ecosystem='beastmen', Family='lamia'},
        ['Nemean Lion'] = { Name='Nemean Lion', Ecosystem='arcana', Family='khimairas'},
        ['Panurgic Ryubool Ja'] = { Name='Panurgic Ryubool Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Phantasmal Puk'] = { Name='Phantasmal Puk', Ecosystem='dragons', Family='puks'},
        ['Pining Abazohn'] = { Name='Pining Abazohn', Ecosystem='undead', Family='qutrubs'},
        ['Poroggo Charmer'] = { Name='Poroggo Charmer', Ecosystem='beastmen', Family='poroggo'},
        ['Qiqirn Freelance'] = { Name='Qiqirn Freelance', Ecosystem='beastmen', Family='qiqirn'},
        ['Qiqirn Mine'] = { Name='Qiqirn Mine', Ecosystem='beastmen', Family='qiqirn'},
        ['Qutrub Extortionist'] = { Name='Qutrub Extortionist', Ecosystem='undead', Family='qutrubs'},
        ['Qutrub Forayer'] = { Name='Qutrub Forayer', Ecosystem='undead', Family='qutrubs'},
        ['Qutrub Wastrel'] = { Name='Qutrub Wastrel', Ecosystem='undead', Family='qutrubs'},
        ['Raid Raptor'] = { Name='Raid Raptor', Ecosystem='lizards', Family='raptors'},
        ['Sagelord Molaal Ja'] = { Name='Sagelord Molaal Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Scalding Fafool Ja'] = { Name='Scalding Fafool Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Scout Puk'] = { Name='Scout Puk', Ecosystem='dragons', Family='puks'},
        ['Searing Vogaal Ja'] = { Name='Searing Vogaal Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Siege Scorpion'] = { Name='Siege Scorpion', Ecosystem='vermin', Family='scorpions'},
        ['Slaughterous Scorpion'] = { Name='Slaughterous Scorpion', Ecosystem='vermin', Family='scorpions'},
        ['Strifelord Bakool Ja'] = { Name='Strifelord Bakool Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Surmerdar the Unbridled'] = { Name='Surmerdar the Unbridled', Ecosystem='beastmen', Family='trolls'},
        ['Thunderbolt Piraal Ja'] = { Name='Thunderbolt Piraal Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Thunderclap Sareel Ja'] = { Name='Thunderclap Sareel Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Troll Cannoneer'] = { Name='Troll Cannoneer', Ecosystem='beastmen', Family='trolls'},
        ['Troll Destroyer'] = { Name='Troll Destroyer', Ecosystem='beastmen', Family='trolls'},
        ['Troll Forager'] = { Name='Troll Forager', Ecosystem='beastmen', Family='trolls'},
        ['Troll Hoplite'] = { Name='Troll Hoplite', Ecosystem='beastmen', Family='trolls'},
        ['Troll Paviser'] = { Name='Troll Paviser', Ecosystem='beastmen', Family='trolls'},
        ['Troll Pezhetairoi'] = { Name='Troll Pezhetairoi', Ecosystem='beastmen', Family='trolls'},
        ['Troll Speculator'] = { Name='Troll Speculator', Ecosystem='beastmen', Family='trolls'},
        ['Troll Stormer'] = { Name='Troll Stormer', Ecosystem='beastmen', Family='trolls'},
        ['Troll Velites'] = { Name='Troll Velites', Ecosystem='beastmen', Family='trolls'},
        ['Troll\'s Automaton'] = { Name='Troll\'s Automaton', Ecosystem='unclassified', Family='automatons'},
        ['Volunteer'] = { Name='Volunteer', Ecosystem='humanoids', Family='elvaan'},
        ['Vorjirzur the Valiant'] = { Name='Vorjirzur the Valiant', Ecosystem='beastmen', Family='trolls'},
        ['Vorporlor the Barbaric'] = { Name='Vorporlor the Barbaric', Ecosystem='beastmen', Family='trolls'},
        ['Vyurvarjur the Nimble'] = { Name='Vyurvarjur the Nimble', Ecosystem='beastmen', Family='trolls'},
        ['War Wamoura'] = { Name='War Wamoura', Ecosystem='vermin', Family='wamouras'},
        ['War Wamouracampa'] = { Name='War Wamouracampa', Ecosystem='vermin', Family='wamouracampa'},
        ['War Wyvern'] = { Name='War Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['White Sentinel'] = { Name='White Sentinel', Ecosystem='unclassified', Family='automatons'},
        ['Wordorbor the Artificer'] = { Name='Wordorbor the Artificer', Ecosystem='beastmen', Family='trolls'},
        ['Xarhorkur the Claviger'] = { Name='Xarhorkur the Claviger', Ecosystem='beastmen', Family='trolls'},
        ['Zurmurwur the Ruthless'] = { Name='Zurmurwur the Ruthless', Ecosystem='beastmen', Family='trolls'},
    },
};
