--Zone: Wajaom Woodlands
--Zone ID: 51
return {
    Names = {
        ['Aht Urhgan Attercop'] = { Name='Aht Urhgan Attercop', Ecosystem='vermin', Family='spiders'},
        ['Air Elemental'] = { Name='Air Elemental', Ecosystem='elementals', Family='elementals'},
        ['Ameretat'] = { Name='Ameretat', Ecosystem='plantoids', Family='morbols'},
        ['Attack Ziz'] = { Name='Attack Ziz', Ecosystem='birds', Family='cockatrices'},
        ['Azoth Apsaras'] = { Name='Azoth Apsaras', Ecosystem='aquans', Family='pugils'},
        ['Battering Bugard'] = { Name='Battering Bugard', Ecosystem='lizards', Family='bugards'},
        ['Berried Chigoe'] = { Name='Berried Chigoe', Ecosystem='vermin', Family='chigoes'},
        ['Carmine Eruca'] = { Name='Carmine Eruca', Ecosystem='vermin', Family='crawlers'},
        ['Carmine Sentinel'] = { Name='Carmine Sentinel', Ecosystem='unclassified', Family='automatons'},
        ['Chelicerata'] = { Name='Chelicerata', Ecosystem='vermin', Family='chigoes'},
        ['Chigoe'] = { Name='Chigoe', Ecosystem='vermin', Family='chigoes'},
        ['Chigoe\'s Nit'] = { Name='Chigoe\'s Nit', Ecosystem='vermin', Family='chigoes'},
        ['Cobalt Sentinel'] = { Name='Cobalt Sentinel', Ecosystem='unclassified', Family='automatons'},
        ['Colorful Treant'] = { Name='Colorful Treant', Ecosystem='plantoids', Family='treants'},
        ['Dark Bugler'] = { Name='Dark Bugler', Ecosystem='demons', Family='imps'},
        ['Dark Esquire'] = { Name='Dark Esquire', Ecosystem='demons', Family='demons'},
        ['Dark Rider'] = { Name='Dark Rider', Ecosystem='unclassified', Family='avatars'},
        ['Dartorgor the Austere'] = { Name='Dartorgor the Austere', Ecosystem='beastmen', Family='trolls'},
        ['Decimator Mabel Ja'] = { Name='Decimator Mabel Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Defoliate Treant'] = { Name='Defoliate Treant', Ecosystem='plantoids', Family='treants'},
        ['Eidolic Qufeel Ja'] = { Name='Eidolic Qufeel Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Fighting Flan'] = { Name='Fighting Flan', Ecosystem='amorphs', Family='flans'},
        ['Flame Eruca'] = { Name='Flame Eruca', Ecosystem='vermin', Family='crawlers'},
        ['Fomor Bard'] = { Name='Fomor Bard', Ecosystem='undead', Family='fomors'},
        ['Fomor Beastmaster'] = { Name='Fomor Beastmaster', Ecosystem='undead', Family='fomors'},
        ['Fomor Paladin'] = { Name='Fomor Paladin', Ecosystem='undead', Family='fomors'},
        ['Fomor Thief'] = { Name='Fomor Thief', Ecosystem='undead', Family='fomors'},
        ['Fomor\'s Bats'] = { Name='Fomor\'s Bats', Ecosystem='birds', Family='bat trios'},
        ['Gharial'] = { Name='Gharial', Ecosystem='lizards', Family='wivres'},
        ['Girzorhor the Imprudent'] = { Name='Girzorhor the Imprudent', Ecosystem='beastmen', Family='trolls'},
        ['Gotoh Zha the Redolent'] = { Name='Gotoh Zha the Redolent', Ecosystem='beastmen', Family='mamool ja'},
        ['Grand Marid'] = { Name='Grand Marid', Ecosystem='beasts', Family='marids'},
        ['Great Ameretat'] = { Name='Great Ameretat', Ecosystem='plantoids', Family='marbols'},
        ['Gulool Ja Ja'] = { Name='Gulool Ja Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Gurfurlur the Menacing'] = { Name='Gurfurlur the Menacing', Ecosystem='beastmen', Family='trolls'},
        ['Haunt'] = { Name='Haunt', Ecosystem='undead', Family='ghosts'},
        ['Hazel Sentinel'] = { Name='Hazel Sentinel', Ecosystem='unclassified', Family='automatons'},
        ['Hydra'] = { Name='Hydra', Ecosystem='dragons', Family='hydras'},
        ['Incendiary Bombs'] = { Name='Incendiary Bombs', Ecosystem='arcana', Family='clusters'},
        ['Iriz Ima'] = { Name='Iriz Ima', Ecosystem='beasts', Family='marids'},
        ['Jaded Jody'] = { Name='Jaded Jody', Ecosystem='plantoids', Family='morbols'},
        ['Kissing Leech'] = { Name='Kissing Leech', Ecosystem='amorphs', Family='leeches'},
        ['Kubool Ja\'s Mhuufya'] = { Name='Kubool Ja\'s Mhuufya', Ecosystem='birds', Family='colibris'},
        ['Lesser Colibri'] = { Name='Lesser Colibri', Ecosystem='birds', Family='colibris'},
        ['Mamool Ja Bounder'] = { Name='Mamool Ja Bounder', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Cataphract'] = { Name='Mamool Ja Cataphract', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Entrancer'] = { Name='Mamool Ja Entrancer', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Fetial'] = { Name='Mamool Ja Fetial', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Handler'] = { Name='Mamool Ja Handler', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Hospitaler'] = { Name='Mamool Ja Hospitaler', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Hussar'] = { Name='Mamool Ja Hussar', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Mimicker'] = { Name='Mamool Ja Mimicker', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Sapper'] = { Name='Mamool Ja Sapper', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Savant'] = { Name='Mamool Ja Savant', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Sophist'] = { Name='Mamool Ja Sophist', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Spotter'] = { Name='Mamool Ja Spotter', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Zenist'] = { Name='Mamool Ja Zenist', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja\'s Lizard'] = { Name='Mamool Ja\'s Lizard', Ecosystem='lizards', Family='lizards'},
        ['Mamool Ja\'s Wyvern'] = { Name='Mamool Ja\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Marid'] = { Name='Marid', Ecosystem='beasts', Family='marids'},
        ['Mercurial Makara'] = { Name='Mercurial Makara', Ecosystem='aquans', Family='pugils'},
        ['Panurgic Ryubool Ja'] = { Name='Panurgic Ryubool Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Percipient Zoraal Ja'] = { Name='Percipient Zoraal Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Poroggo Charmer'] = { Name='Poroggo Charmer', Ecosystem='beastmen', Family='poroggo'},
        ['Puk'] = { Name='Puk', Ecosystem='dragons', Family='puks'},
        ['Raid Raptor'] = { Name='Raid Raptor', Ecosystem='lizards', Family='raptors'},
        ['Red Kisser'] = { Name='Red Kisser', Ecosystem='amorphs', Family='leeches'},
        ['Red Osculator'] = { Name='Red Osculator', Ecosystem='amorphs', Family='leeches'},
        ['Red Smoocher'] = { Name='Red Smoocher', Ecosystem='amorphs', Family='leeches'},
        ['Sagelord Molaal Ja'] = { Name='Sagelord Molaal Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Scalding Fafool Ja'] = { Name='Scalding Fafool Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Scout Puk'] = { Name='Scout Puk', Ecosystem='dragons', Family='puks'},
        ['Searing Vogaal Ja'] = { Name='Searing Vogaal Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Siege Scorpion'] = { Name='Siege Scorpion', Ecosystem='vermin', Family='scorpions'},
        ['Soldier Pephredo'] = { Name='Soldier Pephredo', Ecosystem='vermin', Family='bees'},
        ['Strifelord Bakool Ja'] = { Name='Strifelord Bakool Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Surmerdar the Unbridled'] = { Name='Surmerdar the Unbridled', Ecosystem='beastmen', Family='trolls'},
        ['Thu\'ban'] = { Name='Thu\'ban', Ecosystem='dragons', Family='hydras'},
        ['Thunderbolt Piraal Ja'] = { Name='Thunderbolt Piraal Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Thunderclap Sareel Ja'] = { Name='Thunderclap Sareel Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Tinnin'] = { Name='Tinnin', Ecosystem='dragons', Family='hydras'},
        ['Treant Sapling'] = { Name='Treant Sapling', Ecosystem='plantoids', Family='saplings'},
        ['Troll Cannoneer'] = { Name='Troll Cannoneer', Ecosystem='beastmen', Family='trolls'},
        ['Troll Destroyer'] = { Name='Troll Destroyer', Ecosystem='beastmen', Family='trolls'},
        ['Troll Hoplite'] = { Name='Troll Hoplite', Ecosystem='beastmen', Family='trolls'},
        ['Troll Paviser'] = { Name='Troll Paviser', Ecosystem='beastmen', Family='trolls'},
        ['Troll Pezhetairoi'] = { Name='Troll Pezhetairoi', Ecosystem='beastmen', Family='trolls'},
        ['Troll Speculator'] = { Name='Troll Speculator', Ecosystem='beastmen', Family='trolls'},
        ['Troll Stormer'] = { Name='Troll Stormer', Ecosystem='beastmen', Family='trolls'},
        ['Troll Velites'] = { Name='Troll Velites', Ecosystem='beastmen', Family='trolls'},
        ['Troll\'s Automaton'] = { Name='Troll\'s Automaton', Ecosystem='unclassified', Family='automatons'},
        ['Vigilant Kubool Ja'] = { Name='Vigilant Kubool Ja', Ecosystem='beastmen', Family='mamool ja'},
        ['Vorjirzur the Valiant'] = { Name='Vorjirzur the Valiant', Ecosystem='beastmen', Family='trolls'},
        ['Vorporlor the Barbaric'] = { Name='Vorporlor the Barbaric', Ecosystem='beastmen', Family='trolls'},
        ['Vulpangue'] = { Name='Vulpangue', Ecosystem='dragons', Family='puks'},
        ['Wajaom Tiger'] = { Name='Wajaom Tiger', Ecosystem='beasts', Family='tigers'},
        ['War Wamoura'] = { Name='War Wamoura', Ecosystem='vermin', Family='wamouras'},
        ['War Wamouracampa'] = { Name='War Wamouracampa', Ecosystem='vermin', Family='wamuracampa'},
        ['War Wyvern'] = { Name='War Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['White Sentinel'] = { Name='White Sentinel', Ecosystem='unclassified', Family='automatons'},
        ['Woodland Runner'] = { Name='Woodland Runner', Ecosystem='lizards', Family='raptors'},
        ['Woodtroll Dark Knight'] = { Name='Woodtroll Dark Knight', Ecosystem='beastmen', Family='trolls'},
        ['Woodtroll Monk'] = { Name='Woodtroll Monk', Ecosystem='beastmen', Family='trolls'},
        ['Woodtroll Ranger'] = { Name='Woodtroll Ranger', Ecosystem='beastmen', Family='trolls'},
        ['Woodtroll Warrior'] = { Name='Woodtroll Warrior', Ecosystem='beastmen', Family='trolls'},
        ['Wordorbor the Artificer'] = { Name='Wordorbor the Artificer', Ecosystem='beastmen', Family='trolls'},
        ['Worker Pephredo'] = { Name='Worker Pephredo', Ecosystem='vermin', Family='bees'},
        ['Xarhorkur the Claviger'] = { Name='Xarhorkur the Claviger', Ecosystem='beastmen', Family='trolls'},
        ['Zoraal Ja\'s Pkuucha'] = { Name='Zoraal Ja\'s Pkuucha', Ecosystem='birds', Family='colibris'},
        ['Zurmurwur the Ruthless'] = { Name='Zurmurwur the Ruthless', Ecosystem='beastmen', Family='trolls'},
    },
};
