--Zone: Bhaflau Thickets
--Zone ID: 52
return {
    Names = {
        ['Acrolith'] = { Name='Acrolith', Ecosystem='arcana', Family='acroliths'},
        ['Aht Urhgan Attercop'] = { Name='Aht Urhgan Attercop', Ecosystem='vermin', Family='spiders'},
        ['Air Elemental'] = { Name='Air Elemental', Ecosystem='elementals', Family='elementals'},
        ['Ameretat'] = { Name='Ameretat', Ecosystem='plantoids', Family='morbols'},
        ['Assault Bhoot'] = { Name='Assault Bhoot', Ecosystem='undead', Family='ghosts'},
        ['Assault Draugar'] = { Name='Assault Draugar', Ecosystem='undead', Family='skeletons'},
        ['Azoth Apsaras'] = { Name='Azoth Apsaras', Ecosystem='aquans', Family='pugils'},
        ['Berried Chigoe'] = { Name='Berried Chigoe', Ecosystem='vermin', Family='chigoes'},
        ['Chigoe'] = { Name='Chigoe', Ecosystem='vermin', Family='chigoes'},
        ['Chigoe\'s Nit'] = { Name='Chigoe\'s Nit', Ecosystem='vermin', Family='chigoes'},
        ['Colibri'] = { Name='Colibri', Ecosystem='birds', Family='colibris'},
        ['Colorful Treant'] = { Name='Colorful Treant', Ecosystem='plantoids', Family='treants'},
        ['Dark Bugler'] = { Name='Dark Bugler', Ecosystem='demons', Family='imps'},
        ['Dark Esquire'] = { Name='Dark Esquire', Ecosystem='demons', Family='imps'},
        ['Dark Rider'] = { Name='Dark Rider', Ecosystem='demons', Family='imps'},
        ['Date Eruca'] = { Name='Date Eruca', Ecosystem='vermin', Family='crawlers'},
        ['Dea'] = { Name='Dea', Ecosystem='lizards', Family='wivres'},
        ['Draugar\'s Wyvern'] = { Name='Draugar\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Emergent Elm'] = { Name='Emergent Elm', Ecosystem='plantoids', Family='triants'},
        ['Expunger'] = { Name='Expunger', Ecosystem='undead', Family='doomed'},
        ['Fomor Bard'] = { Name='Fomor Bard', Ecosystem='undead', Family='fomors'},
        ['Fomor Beastmaster'] = { Name='Fomor Beastmaster', Ecosystem='undead', Family='fomors'},
        ['Fomor Paladin'] = { Name='Fomor Paladin', Ecosystem='undead', Family='fomors'},
        ['Fomor Thief'] = { Name='Fomor Thief', Ecosystem='undead', Family='fomors'},
        ['Fomor\'s Bats'] = { Name='Fomor\'s Bats', Ecosystem='birds', Family='bat trios'},
        ['Gespenst'] = { Name='Gespenst', Ecosystem='undead', Family='ghosts'},
        ['Grand Marid'] = { Name='Grand Marid', Ecosystem='beasts', Family='marids'},
        ['Harvestman'] = { Name='Harvestman', Ecosystem='vermin', Family='spiders'},
        ['Haunt'] = { Name='Haunt', Ecosystem='undead', Family='ghosts'},
        ['Incubus Bats'] = { Name='Incubus Bats', Ecosystem='undead', Family='bat trios'},
        ['Kissing Leech'] = { Name='Kissing Leech', Ecosystem='amorphs', Family='leeches'},
        ['Lamia Commandress'] = { Name='Lamia Commandress', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Immolator'] = { Name='Lamia Immolator', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Jaeger'] = { Name='Lamia Jaeger', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.15'] = { Name='Lamia No.15', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.2'] = { Name='Lamia No.2', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.21'] = { Name='Lamia No.21', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.3'] = { Name='Lamia No.3', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.34'] = { Name='Lamia No.34', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.9'] = { Name='Lamia No.9', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Rover'] = { Name='Lamia Rover', Ecosystem='beastmen', Family='lamia'},
        ['Lamia\'s Avatar'] = { Name='Lamia\'s Avatar', Ecosystem='unclassified', Family='avatars'},
        ['Lamia\'s Elemental'] = { Name='Lamia\'s Elemental', Ecosystem='elementals', Family='elementals'},
        ['Lesser Colibri'] = { Name='Lesser Colibri', Ecosystem='birds', Family='colibris'},
        ['Lividroot Amooshah'] = { Name='Lividroot Amooshah', Ecosystem='plantoids', Family='morbols'},
        ['Locus Colibri'] = { Name='Locus Colibri', Ecosystem='birds', Family='colibris'},
        ['Locus Wivre'] = { Name='Locus Wivre', Ecosystem='lizards', Family='wivres'},
        ['Mahishasura'] = { Name='Mahishasura', Ecosystem='beasts', Family='marids'},
        ['Mamool Ja Blusterer'] = { Name='Mamool Ja Blusterer', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Infiltrator'] = { Name='Mamool Ja Infiltrator', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Lurker'] = { Name='Mamool Ja Lurker', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Mimer'] = { Name='Mamool Ja Mimer', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Philosopher'] = { Name='Mamool Ja Philosopher', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Pikeman'] = { Name='Mamool Ja Pikeman', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja Stabler'] = { Name='Mamool Ja Stabler', Ecosystem='beastmen', Family='mamool ja'},
        ['Mamool Ja\'s Raptor'] = { Name='Mamool Ja\'s Raptor', Ecosystem='lizards', Family='raptors'},
        ['Mamool Ja\'s Wyvern'] = { Name='Mamool Ja\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Marid'] = { Name='Marid', Ecosystem='beasts', Family='marids'},
        ['Medusa'] = { Name='Medusa', Ecosystem='beastmen', Family='lamia'},
        ['Mercurial Makara'] = { Name='Mercurial Makara', Ecosystem='aquans', Family='pugils'},
        ['Merrow Cantatrice'] = { Name='Merrow Cantatrice', Ecosystem='beastmen', Family='lamia'},
        ['Merrow No.11'] = { Name='Merrow No.11', Ecosystem='beastmen', Family='lamia'},
        ['Merrow No.12'] = { Name='Merrow No.12', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Seafarer'] = { Name='Merrow Seafarer', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Shiranuhi'] = { Name='Merrow Shiranuhi', Ecosystem='beastmen', Family='lamia'},
        ['Nis Puk'] = { Name='Nis Puk', Ecosystem='dragons', Family='puks'},
        ['Olden Treant'] = { Name='Olden Treant', Ecosystem='plantoids', Family='triants'},
        ['Plague Chigoe'] = { Name='Plague Chigoe', Ecosystem='vermin', Family='chigoes'},
        ['Qutrub Extortionist'] = { Name='Qutrub Extortionist', Ecosystem='undead', Family='qutrubs'},
        ['Qutrub Wastrel'] = { Name='Qutrub Wastrel', Ecosystem='undead', Family='qutrubs'},
        ['Red Kisser'] = { Name='Red Kisser', Ecosystem='amorphs', Family='leeches'},
        ['Red Osculator'] = { Name='Red Osculator', Ecosystem='amorphs', Family='leeches'},
        ['Red Smoocher'] = { Name='Red Smoocher', Ecosystem='amorphs', Family='leeches'},
        ['Sea Puk'] = { Name='Sea Puk', Ecosystem='dragons', Family='puks'},
        ['Skoffin'] = { Name='Skoffin', Ecosystem='dragons', Family='wyverns'},
        ['Treant Sapling'] = { Name='Treant Sapling', Ecosystem='plantoids', Family='saplings'},
        ['Troll Sabreur'] = { Name='Troll Sabreur', Ecosystem='beastmen', Family='trolls'},
        ['Troll Shieldbearer'] = { Name='Troll Shieldbearer', Ecosystem='beastmen', Family='trolls'},
        ['Troll Surveillant'] = { Name='Troll Surveillant', Ecosystem='beastmen', Family='trolls'},
        ['Troll\'s Automaton'] = { Name='Troll\'s Automaton', Ecosystem='unclassified', Family='automatons'},
        ['Wajaom Tiger'] = { Name='Wajaom Tiger', Ecosystem='beasts', Family='tigers'},
    },
};
