--Zone: Ilrusi Atoll
--Zone ID: 55
return {
    Names = {
        ['Carrion Crab'] = { Name='Carrion Crab', Ecosystem='aquans', Family='crabs'},
        ['Carrion Leech'] = { Name='Carrion Leech', Ecosystem='amorphs', Family='leeches'},
        ['Carrion Slime'] = { Name='Carrion Slime', Ecosystem='amorphs', Family='slimes'},
        ['Carrion Toad'] = { Name='Carrion Toad', Ecosystem='undead', Family='doomed'},
        ['Clipper'] = { Name='Clipper', Ecosystem='aquans', Family='crabs'},
        ['Cursed Chest'] = { Name='Cursed Chest', Ecosystem='arcana', Family='mimics'},
        ['D5J2-MERROW'] = { Name='D5J2-MERROW', Ecosystem='beastmen', Family='lamia'},
        ['D5R3-MERROW'] = { Name='D5R3-MERROW', Ecosystem='beastmen', Family='lamia'},
        ['D5S1-MERROW'] = { Name='D5S1-MERROW', Ecosystem='beastmen', Family='lamia'},
        ['Draugar'] = { Name='Draugar', Ecosystem='undead', Family='skeletons'},
        ['Fallen Imperial Trooper'] = { Name='Fallen Imperial Trooper', Ecosystem='undead', Family='fomors'},
        ['Fallen Imperial Wizard'] = { Name='Fallen Imperial Wizard', Ecosystem='undead', Family='fomors'},
        ['Fallen Volunteer'] = { Name='Fallen Volunteer', Ecosystem='undead', Family='fomors'},
        ['Giant Pugil'] = { Name='Giant Pugil', Ecosystem='aquans', Family='pugils'},
        ['Imp'] = { Name='Imp', Ecosystem='demons', Family='imps'},
        ['K22B6-LAMIA'] = { Name='K22B6-LAMIA', Ecosystem='beastmen', Family='lamia'},
        ['K22H3-LAMIA'] = { Name='K22H3-LAMIA', Ecosystem='beastmen', Family='lamia'},
        ['K22P2-LAMIA'] = { Name='K22P2-LAMIA', Ecosystem='beastmen', Family='lamia'},
        ['Kelp Crab'] = { Name='Kelp Crab', Ecosystem='aquans', Family='crabs'},
        ['Kelp Kulshedra'] = { Name='Kelp Kulshedra', Ecosystem='aquans', Family='sea monks'},
        ['Kelp Pugil'] = { Name='Kelp Pugil', Ecosystem='aquans', Family='pugils'},
        ['Khimaira 14X'] = { Name='Khimaira 14X', Ecosystem='arcana', Family='khimairas'},
        ['Kraken'] = { Name='Kraken', Ecosystem='aquans', Family='sea monks'},
        ['Lamia No.13'] = { Name='Lamia No.13', Ecosystem='beastmen', Family='lamia'},
        ['Martial Maestro Megomak'] = { Name='Martial Maestro Megomak', Ecosystem='beastmen', Family='moblins'},
        ['Orobon'] = { Name='Orobon', Ecosystem='aquans', Family='orobons'},
        ['Percipient Fish'] = { Name='Percipient Fish', Ecosystem='aquans', Family='pugils'},
        ['Puffer Pugil'] = { Name='Puffer Pugil', Ecosystem='aquans', Family='pugils'},
        ['Qiqirn Pecheur'] = { Name='Qiqirn Pecheur', Ecosystem='beastmen', Family='qiqirns'},
        ['Snipper'] = { Name='Snipper', Ecosystem='aquans', Family='crabs'},
        ['Undead Crab'] = { Name='Undead Crab', Ecosystem='aquans', Family='crabs'},
        ['Undead Leech'] = { Name='Undead Leech', Ecosystem='amorphs', Family='leeches'},
        ['Undead Slime'] = { Name='Undead Slime', Ecosystem='amorphs', Family='slimes'},
        ['Undead Toad'] = { Name='Undead Toad', Ecosystem='aquans', Family='toads'},
    },
};
