--Zone: Periqia
--Zone ID: 56
return {
    Names = {
        ['Arrapago Crab'] = { Name='Arrapago Crab', Ecosystem='aquans', Family='crabs'},
        ['Augmented Chigoe'] = { Name='Augmented Chigoe', Ecosystem='vermin', Family='chigoes'},
        ['Batteilant Bhoot'] = { Name='Batteilant Bhoot', Ecosystem='undead', Family='ghosts'},
        ['Black Baron'] = { Name='Black Baron', Ecosystem='demons', Family='imps'},
        ['Bloody Daggers'] = { Name='Bloody Daggers', Ecosystem='unclassified', Family='animated weapons'},
        ['Chigoe Breeder'] = { Name='Chigoe Breeder', Ecosystem='beastmen', Family='lamia'},
        ['Cursed Axe'] = { Name='Cursed Axe', Ecosystem='unclassified', Family='animated weapons'},
        ['Cursed Chigoe'] = { Name='Cursed Chigoe', Ecosystem='vermin', Family='chigoes'},
        ['Darkling Draugar'] = { Name='Darkling Draugar', Ecosystem='undead', Family='skeletons'},
        ['Debaucher'] = { Name='Debaucher', Ecosystem='undead', Family='doomed'},
        ['Demonic Rod'] = { Name='Demonic Rod', Ecosystem='unclassified', Family='animated weapons'},
        ['Draconic Draugar'] = { Name='Draconic Draugar', Ecosystem='undead', Family='skeletons'},
        ['Draugar\'s Wyvern'] = { Name='Draugar\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Excaliace'] = { Name='Excaliace', Ecosystem='humanoids', Family='elvaan'},
        ['Experimental Undead'] = { Name='Experimental Undead', Ecosystem='undead', Family='fomors'},
        ['K23H1-LAMIA'] = { Name='K23H1-LAMIA', Ecosystem='beastmen', Family='lamia'},
        ['Karazahm'] = { Name='Karazahm', Ecosystem='humanoids', Family='elvaan'},
        ['King Goldemar'] = { Name='King Goldemar', Ecosystem='demons', Family='dvergers'},
        ['Lamia No.14'] = { Name='Lamia No.14', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.17'] = { Name='Lamia No.17', Ecosystem='beastmen', Family='lamia'},
        ['Living Staves'] = { Name='Living Staves', Ecosystem='unclassified', Family='animated weapons'},
        ['Magic Shields'] = { Name='Magic Shields', Ecosystem='unclassified', Family='animated weapons'},
        ['Merrow No.16'] = { Name='Merrow No.16', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Shadowdancer'] = { Name='Merrow Shadowdancer', Ecosystem='beastmen', Family='lamia'},
        ['Periqia Pugil'] = { Name='Periqia Pugil', Ecosystem='aquans', Family='pugils'},
        ['Putrid Immortal Guard'] = { Name='Putrid Immortal Guard', Ecosystem='undead', Family='doomed'},
        ['Qiqirn Miner'] = { Name='Qiqirn Miner', Ecosystem='beastmen', Family='qiqirns'},
        ['Qutrub'] = { Name='Qutrub', Ecosystem='undead', Family='qutrubs'},
        ['Umarid'] = { Name='Umarid', Ecosystem='humanoids', Family='humes'},
        ['Wight'] = { Name='Wight', Ecosystem='undead', Family='skeletons'},
    },
};
