--Zone: Uleguerand Range
--Zone ID: 5
return {
    Names = {
        ['Agloolik'] = { Name='Agloolik', 
        ['Akselloak'] = { Name='Akselloak', 
        ['Black Coney'] = { Name='Black Coney', 
        ['Bonnacon'] = { Name='Bonnacon', 
        ['Brontotaur'] = { Name='Brontotaur', 
        ['Buffalo'] = { Name='Buffalo', 
        ['Camahueto'] = { Name='Camahueto', 
        ['Cwn Annwn'] = { Name='Cwn Annwn', 
        ['Demon\'s Elemental'] = { Name='Demon\'s Elemental', 
        ['Doom Mage'] = { Name='Doom Mage', 
        ['Doom Soldier'] = { Name='Doom Soldier', 
        ['Dread Demon'] = { Name='Dread Demon', 
        ['Esbat'] = { Name='Esbat', 
        ['Fachan'] = { Name='Fachan', 
        ['Father Frost'] = { Name='Father Frost', 
        ['Frost Flambeau'] = { Name='Frost Flambeau', 
        ['Geush Urvan'] = { Name='Geush Urvan', 
        ['Giant Buffalo'] = { Name='Giant Buffalo', 
        ['Glacier Eater'] = { Name='Glacier Eater', 
        ['Gore Demon'] = { Name='Gore Demon', 
        ['Ice Elemental'] = { Name='Ice Elemental', 
        ['Isarukitsck'] = { Name='Isarukitsck', 
        ['Jormungand'] = { Name='Jormungand', 
        ['Judicator Demon'] = { Name='Judicator Demon', 
        ['Kindred Black Mage'] = { Name='Kindred Black Mage', 
        ['Kindred Dark Knight'] = { Name='Kindred Dark Knight', 
        ['Kindred Summoner'] = { Name='Kindred Summoner', 
        ['Kindred Warrior'] = { Name='Kindred Warrior', 
        ['King Buffalo'] = { Name='King Buffalo', 
        ['Little Wingman'] = { Name='Little Wingman', 
        ['Magnotaur'] = { Name='Magnotaur', 
        ['Mindgazer'] = { Name='Mindgazer', 
        ['Molech'] = { Name='Molech', 
        ['Morozko'] = { Name='Morozko', 
        ['Mountain Worm'] = { Name='Mountain Worm', 
        ['Nightmare Bats'] = { Name='Nightmare Bats', 
        ['Nival Raptor'] = { Name='Nival Raptor', 
        ['Phasma'] = { Name='Phasma', 
        ['Polar Hare'] = { Name='Polar Hare', 
        ['Scowlenkos'] = { Name='Scowlenkos', 
        ['Skvader'] = { Name='Skvader', 
        ['Smolenkos'] = { Name='Smolenkos', 
        ['Snoll'] = { Name='Snoll', 
        ['Snow Maiden'] = { Name='Snow Maiden', 
        ['Srei Ap'] = { Name='Srei Ap', 
        ['Stygian Demon'] = { Name='Stygian Demon', 
        ['Succubus Bats'] = { Name='Succubus Bats', 
        ['Tyrannotaur'] = { Name='Tyrannotaur', 
        ['Uleguerand Tiger'] = { Name='Uleguerand Tiger', 
        ['Variable Hare'] = { Name='Variable Hare', 
        ['White Coney'] = { Name='White Coney', 
    },
};
