--Zone: Uleguerand Range
--Zone ID: 5
return {
    Names = {
        ['Agloolik']                = { Name='Agloolik', Ecosystem='arcana', Family='snolls' },
        ['Akselloak']               = { Name='Akselloak', Ecosystem='arcana', Family='snolls' },
        ['Black Coney']             = { Name='Black Coney', Ecosystem='beasts', Family='rabbits' },
        ['Bonnacon']                = { Name='Bonnacon', Ecosystem='beasts', Family='buffaloes' },
        ['Brontotaur']              = { Name='Brontotaur', Ecosystem='demons', Family='tauri' },
        ['Buffalo']                 = { Name='Buffalo', Ecosystem='beasts', Family='buffaloes' },
        ['Camahueto']               = { Name='Camahueto', Ecosystem='beasts', Family='buffaloes' },
        ['Cwn Annwn']               = { Name='Cwn Annwn', Ecosystem='undead', Family='hounds' },
        ['Demon\'s Elemental']      = { Name='Demon\'s Elemental',Ecosystem='elementals', Family='elementals' },
        ['Doom Mage']               = { Name='Doom Mage', Ecosystem='undead', Family='skeletons' },
        ['Doom Soldier']            = { Name='Doom Soldier', Ecosystem='undead', Family='skeletons' },
        ['Dread Demon']             = { Name='Dread Demon', Ecosystem='demons', Family='demons' },
        ['Esbat']                   = { Name='Esbat', Ecosystem='birds', Family='bats' },
        ['Fachan']                  = { Name='Fachan', Ecosystem='demons', Family='ahriman' },
        ['Father Frost']            = { Name='Father Frost', Ecosystem='arcana', Family='snolls' },
        ['Frost Flambeau']          = { Name='Frost Flambeau', Ecosystem='arcana', Family='snolls' },
        ['Geush Urvan']             = { Name='Geush Urvan', Ecosystem='beasts', Family='buffaloes' },
        ['Giant Buffalo']           = { Name='Giant Buffalo', Ecosystem='beasts', Family='buffaloes' },
        ['Glacier Eater']           = { Name='Glacier Eater', Ecosystem='amorphs', Family='worms' },
        ['Gore Demon']              = { Name='Gore Demon', Ecosystem='demons', Family='demons' },
        ['Ice Elemental']           = { Name='Ice Elemental', Ecosystem='elementals', Family='elementals' },
        ['Isarukitsck']             = { Name='Isarukitsck', Ecosystem='birds', Family='apkallu' },
        ['Jormungand']              = { Name='Jormungand', Ecosystem='dragons', Family='wyrms' },
        ['Judicator Demon']         = { Name='Judicator Demon', Ecosystem='demons', Family='demons' },
        ['Kindred Black Mage']      = { Name='Kindred Black Mage', Ecosystem='demons', Family='demons' },
        ['Kindred Dark Knight']     = { Name='Kindred Dark Knight', Ecosystem='demons', Family='demons' },
        ['Kindred Summoner']        = { Name='Kindred Summoner', Ecosystem='demons', Family='demons' },
        ['Kindred Warrior']         = { Name='Kindred Warrior', Ecosystem='demons', Family='demons' },
        ['King Buffalo']            = { Name='King Buffalo', Ecosystem='beasts', Family='buffaloes' },
        ['Little Wingman']          = { Name='Little Wingman', Ecosystem='birds', Family='apkallu' },
        ['Magnotaur']               = { Name='Magnotaur', Ecosystem='demons', Family='tauri' },
        ['Mindgazer']               = { Name='Mindgazer', Ecosystem='amorphs', Family='hecteyes' },
        ['Molech']                  = { Name='Molech', Ecosystem='demons', Family='tauri' },
        ['Morozko']                 = { Name='Morozko', Ecosystem='arcana', Family='snolls' },
        ['Mountain Worm']           = { Name='Mountain Worm', Ecosystem='amorphs', Family='worms' },
        ['Nightmare Bats']          = { Name='Nightmare Bats', Ecosystem='birds', Family='bat trios' },
        ['Nival Raptor']            = { Name='Nival Raptor', Ecosystem='lizards', Family='raptors' },
        ['Phasma']                  = { Name='Phasma', Ecosystem='undead', Family='ghosts' },
        ['Polar Hare']              = { Name='Polar Hare', Ecosystem='beasts', Family='rabbits' },
        ['Scowlenkos']              = { Name='Scowlenkos', Ecosystem='demons', Family='ahriman' },
        ['Skvader']                 = { Name='Skvader', Ecosystem='beasts', Family='rabbits' },
        ['Smolenkos']               = { Name='Smolenkos', Ecosystem='demons', Family='ahriman' },
        ['Snoll']                   = { Name='Snoll', Ecosystem='arcana', Family='snolls' },
        ['Snow Maiden']             = { Name='Snow Maiden', Ecosystem='arcana', Family='snolls' },
        ['Srei Ap']                 = { Name='Srei Ap', Ecosystem='undead', Family='ghosts' },
        ['Stygian Demon']           = { Name='Stygian Demon', Ecosystem='demons', Family='demons' },
        ['Succubus Bats']           = { Name='Succubus Bats', Ecosystem='birds', Family='bat trios' },
        ['Tyrannotaur']             = { Name='Tyrannotaur', Ecosystem='demons', Family='tauri' },
        ['Uleguerand Tiger']        = { Name='Uleguerand Tiger', Ecosystem='beasts', Family='tigers' },
        ['Variable Hare']           = { Name='Variable Hare', Ecosystem='beasts', Family='rabbits' },
        ['White Coney']             = { Name='White Coney', Ecosystem='beasts', Family='rabbits' },
        -- Custom content for HorizonXI
        ['Gigas Brawler']           = { Name='Gigas Brawler', Ecosystem='beastmen', Family='gigas' },
        ['Gigas Crusher']           = { Name='Gigas Crusher', Ecosystem='beastmen', Family='gigas' },
    },
};
