--Zone: Mount Zhayolm
--Zone ID: 61
return {
    Names = {
        ['Anantaboga'] = { Name='Anantaboga', Ecosystem='dragons', Family='dragons' },
        ['Ancient Bombs'] = { Name='Ancient Bombs', Ecosystem='arcana', Family='clusters' },
        ['Assassin Fly'] = { Name='Assassin Fly', Ecosystem='vermin', Family='flies' },
        ['Brass Borer'] = { Name='Brass Borer', Ecosystem='vermin', Family='wamouracampa' },
        ['Cerberus'] = { Name='Cerberus', Ecosystem='beasts', Family='cerberuses' },
        ['Chary Apkallu'] = { Name='Chary Apkallu', Ecosystem='birds', Family='apkullu' },
        ['Claret'] = { Name='Claret', Ecosystem='amorphs', Family='slimes' },
        ['Dahak'] = { Name='Dahak', Ecosystem='dragons', Family='dragons' },
        ['Dark Bugler'] = { Name='Dark Bugler', Ecosystem='demons', Family='imps' },
        ['Dark Esquire'] = { Name='Dark Esquire', Ecosystem='demons', Family='imps' },
        ['Dark Rider'] = { Name='Dark Rider', Ecosystem='demons', Family='imps' },
        ['Earth Elemental'] = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Ebony Pudding'] = { Name='Ebony Pudding', Ecosystem='amorphs', Family='flans' },
        ['Elder\'s Imp'] = { Name='Elder\'s Imp', Ecosystem='demons', Family='imps' },
        ['Energetic Eruca'] = { Name='Energetic Eruca', Ecosystem='vermin', Family='crawlers' },
        ['Fahrafahr the Bloodied'] = { Name='Fahrafahr the Bloodied', Ecosystem='beastmen', Family='trolls' },
        ['Fire Elemental'] = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals' },
        ['Garfurlar the Rabid'] = { Name='Garfurlar the Rabid', Ecosystem='beastmen', Family='trolls' },
        ['Garharlor the Unruly'] = { Name='Garharlor the Unruly', Ecosystem='beastmen', Family='trolls' },
        ['Garhorlur the Brutal'] = { Name='Garhorlur the Brutal', Ecosystem='beastmen', Family='trolls' },
        ['Giant Orobon'] = { Name='Giant Orobon', Ecosystem='aquans', Family='orobons' },
        ['Grand Grenade'] = { Name='Grand Grenade', Ecosystem='arcana', Family='bombs' },
        ['Hilltroll Dark Knight'] = { Name='Hilltroll Dark Knight', Ecosystem='beastmen', Family='trolls' },
        ['Hilltroll Monk'] = { Name='Hilltroll Monk', Ecosystem='beastmen', Family='trolls' },
        ['Hilltroll Paladin'] = { Name='Hilltroll Paladin', Ecosystem='beastmen', Family='trolls' },
        ['Hilltroll Puppetmaster'] = { Name='Hilltroll Puppetmaster', Ecosystem='beastmen', Family='trolls' },
        ['Hilltroll Ranger'] = { Name='Hilltroll Ranger', Ecosystem='beastmen', Family='trolls' },
        ['Hilltroll Red Mage'] = { Name='Hilltroll Red Mage', Ecosystem='beastmen', Family='trolls' },
        ['Hilltroll Warrior'] = { Name='Hilltroll Warrior', Ecosystem='beastmen', Family='trolls' },
        ['Ignamoth'] = { Name='Ignamoth', Ecosystem='vermin', Family='wamouras' },
        ['Khromasoul Bhurborlor'] = { Name='Khromasoul Bhurborlor', Ecosystem='beastmen', Family='trolls' },
        ['King Apkallu'] = { Name='King Apkallu', Ecosystem='birds', Family='apkullu' },
        ['Magmatic Eruca'] = { Name='Magmatic Eruca', Ecosystem='vermin', Family='crawlers' },
        ['Mountain Clot'] = { Name='Mountain Clot', Ecosystem='amorphs', Family='slimes' },
        ['Orichalcumshell'] = { Name='Orichalcumshell', Ecosystem='aquans', Family='crabs' },
        ['Phasma'] = { Name='Phasma', Ecosystem='undead', Family='ghosts' },
        ['Sarama'] = { Name='Sarama', Ecosystem='beasts', Family='cerberuses' },
        ['Sarameya'] = { Name='Sarameya', Ecosystem='beasts', Family='cerberuses' },
        ['Scoriaceous Eruca'] = { Name='Scoriaceous Eruca', Ecosystem='vermin', Family='crawlers' },
        ['Sicklemoon Crab'] = { Name='Sicklemoon Crab', Ecosystem='aquans', Family='crabs' },
        ['Sicklemoon Jagil'] = { Name='Sicklemoon Jagil', Ecosystem='aquans', Family='pugils' },
        ['Sulphuric Jagil'] = { Name='Sulphuric Jagil', Ecosystem='aquans', Family='pugils' },
        ['Sweeping Cluster'] = { Name='Sweeping Cluster', Ecosystem='arcana', Family='clusters' },
        ['Troll Artilleryman'] = { Name='Troll Artilleryman', Ecosystem='beastmen', Family='trolls' },
        ['Troll Cuirasser'] = { Name='Troll Cuirasser', Ecosystem='beastmen', Family='trolls' },
        ['Troll Grenadier'] = { Name='Troll Grenadier', Ecosystem='beastmen', Family='trolls' },
        ['Troll Hammersmith'] = { Name='Troll Hammersmith', Ecosystem='beastmen', Family='trolls' },
        ['Troll Speculator'] = { Name='Troll Speculator', Ecosystem='beastmen', Family='trolls' },
        ['Troll\'s Automaton'] = { Name='Troll\'s Automaton', Ecosystem='unclassified', Family='automatons' },
        ['Vanasarvik'] = { Name='Vanasarvik', Ecosystem='demons', Family='imps' },
        ['Volcanic Leech'] = { Name='Volcanic Leech', Ecosystem='amorphs', Family='leeches' },
        ['Vozold Clot'] = { Name='Vozold Clot', Ecosystem='amorphs', Family='slimes' },
        ['Vozold Jagil'] = { Name='Vozold Jagil', Ecosystem='aquans', Family='pugils' },
        ['Wamoura'] = { Name='Wamoura', Ecosystem='vermin', Family='wamouras' },
        ['Wamoura Prince'] = { Name='Wamoura Prince', Ecosystem='vermin', Family='wamouras' },
        ['Wootzshell'] = { Name='Wootzshell', Ecosystem='aquans', Family='crabs' },
        ['Zazalda Clot'] = { Name='Zazalda Clot', Ecosystem='amorphs', Family='slimes' },
        ['Zazalda Jagil'] = { Name='Zazalda Jagil', Ecosystem='aquans', Family='pugils' },
        ['Zhayolm Apkallu'] = { Name='Zhayolm Apkallu', Ecosystem='birds', Family='birds' },
    },
};
