--Zone: Halvung
--Zone ID: 62
return {
    Names = {
        ['Achamoth'] = { Name='Achamoth', Ecosystem='vermin', Family='wamouras' },
        ['Achamoth Nympha'] = { Name='Achamoth Nympha', Ecosystem='vermin', Family='wamouras' },
        ['Achamothcampa'] = { Name='Achamothcampa', Ecosystem='vermin', Family='wamouracampas' },
        ['Antares'] = { Name='Antares', Ecosystem='vermin', Family='scorpions' },
        ['Archaic Mirror'] = { Name='Archaic Mirror', Ecosystem='structures', Family='structures' },
        ['Big Bomb'] = { Name='Big Bomb', Ecosystem='arcana', Family='bombs' },
        ['Black Pudding'] = { Name='Black Pudding', Ecosystem='amorphs', Family='flans' },
        ['Chiliarch Gordarvor'] = { Name='Chiliarch Gordarvor', Ecosystem='beastmen', Family='trolls' },
        ['Copper Borer'] = { Name='Copper Borer', Ecosystem='vermin', Family='wamouracampas' },
        ['Dahak'] = { Name='Dahak', Ecosystem='dragons', Family='dragons' },
        ['Dextrose'] = { Name='Dextrose', Ecosystem='amorphs', Family='flans' },
        ['Dorgerwor the Astute'] = { Name='Dorgerwor the Astute', Ecosystem='beastmen', Family='trolls' },
        ['Earth Elemental'] = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Ebony Pudding'] = { Name='Ebony Pudding', Ecosystem='amorphs', Family='flans' },
        ['Farlarder the Shrewd'] = { Name='Farlarder the Shrewd', Ecosystem='beastmen', Family='trolls' },
        ['Fire Elemental'] = { Name='Fire Elemental', Ecosystem='elementals', Family='elementals' },
        ['Flammeri'] = { Name='Flammeri', Ecosystem='amorphs', Family='flans' },
        ['Friar\'s Lantern'] = { Name='Friar\'s Lantern', Ecosystem='arcana', Family='bombs' },
        ['Gurfurlur the Menacing'] = { Name='Gurfurlur the Menacing', Ecosystem='beastmen', Family='trolls' },
        ['Hetairoi Vuryargur'] = { Name='Hetairoi Vuryargur', Ecosystem='beastmen', Family='trolls' },
        ['Hetairoi Zarwarkur'] = { Name='Hetairoi Zarwarkur', Ecosystem='beastmen', Family='trolls' },
        ['Hilltroll Elite Guard'] = { Name='Hilltroll Elite Guard', Ecosystem='beastmen', Family='trolls' },
        ['Hilltroll Mirror Guard'] = { Name='Hilltroll Mirror Guard', Ecosystem='beastmen', Family='trolls' },
        ['Kirlirger the Abhorrent'] = { Name='Kirlirger the Abhorrent', Ecosystem='beastmen', Family='trolls' },
        ['Magmatic Eruca'] = { Name='Magmatic Eruca', Ecosystem='vermin', Family='crawlers' },
        ['Moblin Billionaire'] = { Name='Moblin Billionaire', Ecosystem='beastmen', Family='moblins' },
        ['Moblin Millionaire'] = { Name='Moblin Millionaire', Ecosystem='beastmen', Family='moblins' },
        ['Mythril Mouth Monamaq'] = { Name='Mythril Mouth Monamaq', Ecosystem='beastmen', Family='moblins' },
        ['Purgatory Bat'] = { Name='Purgatory Bat', Ecosystem='birds', Family='bats' },
        ['Qiqirn Diamantaire'] = { Name='Qiqirn Diamantaire', Ecosystem='beastmen', Family='qiqirns' },
        ['Qiqirn Mercenary'] = { Name='Qiqirn Mercenary', Ecosystem='beastmen', Family='qiqirns' },
        ['Qiqirn Mine'] = { Name='Qiqirn Mine', Ecosystem='unclassified', Family='mines' },
        ['Reacton'] = { Name='Reacton', Ecosystem='arcana', Family='bombs' },
        ['Troll Artilleryman'] = { Name='Troll Artilleryman', Ecosystem='beastmen', Family='trolls' },
        ['Troll Cameist'] = { Name='Troll Cameist', Ecosystem='beastmen', Family='trolls' },
        ['Troll Combatant'] = { Name='Troll Combatant', Ecosystem='beastmen', Family='trolls' },
        ['Troll Cuirasser'] = { Name='Troll Cuirasser', Ecosystem='beastmen', Family='trolls' },
        ['Troll Engraver'] = { Name='Troll Engraver', Ecosystem='beastmen', Family='trolls' },
        ['Troll Gemologist'] = { Name='Troll Gemologist', Ecosystem='beastmen', Family='trolls' },
        ['Troll Grenadier'] = { Name='Troll Grenadier', Ecosystem='beastmen', Family='trolls' },
        ['Troll Ironworker'] = { Name='Troll Ironworker', Ecosystem='beastmen', Family='trolls' },
        ['Troll Lapidarist'] = { Name='Troll Lapidarist', Ecosystem='beastmen', Family='trolls' },
        ['Troll Machinist'] = { Name='Troll Machinist', Ecosystem='beastmen', Family='trolls' },
        ['Troll Mythril Guard'] = { Name='Troll Mythril Guard', Ecosystem='beastmen', Family='trolls' },
        ['Troll Scrimer'] = { Name='Troll Scrimer', Ecosystem='beastmen', Family='trolls' },
        ['Troll Smelter'] = { Name='Troll Smelter', Ecosystem='beastmen', Family='trolls' },
        ['Troll Stoneworker'] = { Name='Troll Stoneworker', Ecosystem='beastmen', Family='trolls' },
        ['Troll Targeteer'] = { Name='Troll Targeteer', Ecosystem='beastmen', Family='trolls' },
        ['Troll\'s Automaton'] = { Name='Troll\'s Automaton', Ecosystem='unclassified', Family='automatons' },
        ['Volcanic Bats'] = { Name='Volcanic Bats', Ecosystem='birds', Family='bat trios' },
        ['Wamoura'] = { Name='Wamoura', Ecosystem='vermin', Family='wamouras' },
        ['Wamouracampa'] = { Name='Wamouracampa', Ecosystem='vermin', Family='wamouracampas' },
        ['Wheel Wamoura'] = { Name='Wheel Wamoura', Ecosystem='vermin', Family='wamouracampas' },
        ['Woodtroll Elite Guard'] = { Name='Woodtroll Elite Guard', Ecosystem='beastmen', Family='trolls' },
        ['Woodtroll Mirror Guard'] = { Name='Woodtroll Mirror Guard', Ecosystem='beastmen', Family='trolls' },
    },
};
