--Zone: Mamook
--Zone ID: 65
return {
    Names = {
        ['Air Elemental'] = { Name='Air Elemental', Ecosystem='elementals', Family='elementals' },
        ['Archaic Mirror'] = { Name='Archaic Mirror', Ecosystem='structures', Family='structures' },
        ['Battle Bugard'] = { Name='Battle Bugard', Ecosystem='lizards', Family='bugards' },
        ['Brei'] = { Name='Brei', Ecosystem='amorphs', Family='slimes' },
        ['Carpophagous Puk'] = { Name='Carpophagous Puk', Ecosystem='dragons', Family='puks' },
        ['Carriage Lizard'] = { Name='Carriage Lizard', Ecosystem='lizards', Family='lizards' },
        ['Chamrosh'] = { Name='Chamrosh', Ecosystem='birds', Family='colibris' },
        ['Colibri'] = { Name='Colibri', Ecosystem='birds', Family='colibris' },
        ['Darting Kachaal Ja'] = { Name='Darting Kachaal Ja', Ecosystem='beastmen', Family='mamool ja' },
        ['Devout Radol Ja'] = { Name='Devout Radol Ja', Ecosystem='beastmen', Family='mamool ja' },
        ['Dragonscaled Bugaal Ja'] = { Name='Dragonscaled Bugaal Ja', Ecosystem='beastmen', Family='mamool ja' },
        ['Firedance Magmaal Ja'] = { Name='Firedance Magmaal Ja', Ecosystem='beastmen', Family='mamool ja' },
        ['Forbidding Koheel Ja'] = { Name='Forbidding Koheel Ja', Ecosystem='beastmen', Family='mamool ja' },
        ['Gulool Ja Ja'] = { Name='Gulool Ja Ja', Ecosystem='beastmen', Family='mamool ja' },
        ['Hundredfaced Hapool Ja'] = { Name='Hundredfaced Hapool Ja', Ecosystem='beastmen', Family='mamool ja' },
        ['Hunting Raptor'] = { Name='Hunting Raptor', Ecosystem='lizards', Family='raptors' },
        ['Iriri Samariri'] = { Name='Iriri Samariri', Ecosystem='beastmen', Family='poroggos' },
        ['Mamook Crab'] = { Name='Mamook Crab', Ecosystem='aquans', Family='crabs' },
        ['Mamook Mush'] = { Name='Mamook Mush', Ecosystem='amorphs', Family='slimes' },
        ['Mamool Ja'] = { Name='Mamool Ja', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Bloodsucker'] = { Name='Mamool Ja Bloodsucker', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Blusterer'] = { Name='Mamool Ja Blusterer', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Bounder'] = { Name='Mamool Ja Bounder', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Chamberlain'] = { Name='Mamool Ja Chamberlain', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Conservator'] = { Name='Mamool Ja Conservator', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Diver'] = { Name='Mamool Ja Diver', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Frogman'] = { Name='Mamool Ja Frogman', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Infiltrator'] = { Name='Mamool Ja Infiltrator', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Lurker'] = { Name='Mamool Ja Lurker', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Mimer'] = { Name='Mamool Ja Mimer', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Mimicker'] = { Name='Mamool Ja Mimicker', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Palatine'] = { Name='Mamool Ja Palatine', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Philosopher'] = { Name='Mamool Ja Philosopher', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Pikeman'] = { Name='Mamool Ja Pikeman', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Savant'] = { Name='Mamool Ja Savant', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Sophist'] = { Name='Mamool Ja Sophist', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Spearman'] = { Name='Mamool Ja Spearman', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Stabler'] = { Name='Mamool Ja Stabler', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Strapper'] = { Name='Mamool Ja Strapper', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Treasurer'] = { Name='Mamool Ja Treasurer', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Zenist'] = { Name='Mamool Ja Zenist', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja\'s Lizard'] = { Name='Mamool Ja\'s Lizard', Ecosystem='lizards', Family='lizards' },
        ['Mamool Ja\'s Raptor'] = { Name='Mamool Ja\'s Raptor', Ecosystem='lizards', Family='raptors' },
        ['Mamool Ja\'s Wyvern'] = { Name='Mamool Ja\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Mikilulu'] = { Name='Mikilulu', Ecosystem='aquans', Family='toads' },
        ['Mikiluru'] = { Name='Mikiluru', Ecosystem='aquans', Family='toads' },
        ['Mikirulu'] = { Name='Mikirulu', Ecosystem='aquans', Family='toads' },
        ['Mikiruru'] = { Name='Mikiruru', Ecosystem='aquans', Family='toads' },
        ['Nikilulu'] = { Name='Nikilulu', Ecosystem='aquans', Family='toads' },
        ['Nipper'] = { Name='Nipper', Ecosystem='aquans', Family='crabs' },
        ['Poroggo'] = { Name='Poroggo', Ecosystem='beastmen', Family='poroggos' },
        ['Poroggo Casanova'] = { Name='Poroggo Casanova', Ecosystem='beastmen', Family='poroggos' },
        ['Predatory Colibri'] = { Name='Predatory Colibri', Ecosystem='birds', Family='colibris' },
        ['Puk'] = { Name='Puk', Ecosystem='dragons', Family='puks' },
        ['Qiqirn Goldsmith'] = { Name='Qiqirn Goldsmith', Ecosystem='beastmen', Family='qiqirns' },
        ['Qiqirn Mine'] = { Name='Qiqirn Mine', Ecosystem='unclassified', Family='mines' },
        ['Qiqirn Poulterer'] = { Name='Qiqirn Poulterer', Ecosystem='beastmen', Family='qiqirns' },
        ['Sagelord Molaal Ja'] = { Name='Sagelord Molaal Ja', Ecosystem='beastmen', Family='mamool ja' },
        ['Sea Puk'] = { Name='Sea Puk', Ecosystem='dragons', Family='puks' },
        ['Shadelurking Zolool Ja'] = { Name='Shadelurking Zolool Ja', Ecosystem='beastmen', Family='mamool ja' },
        ['Spinner'] = { Name='Spinner', Ecosystem='vermin', Family='spiders' },
        ['Suhur Mas'] = { Name='Suhur Mas', Ecosystem='aquans', Family='pugils' },
        ['Tyrannobugard'] = { Name='Tyrannobugard', Ecosystem='lizards', Family='bugards' },
        ['Venomfang'] = { Name='Venomfang', Ecosystem='lizards', Family='raptors' },
        ['Wartkin'] = { Name='Wartkin', Ecosystem='aquans', Family='toads' },
        ['Watch Wyvern'] = { Name='Watch Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Yalungur'] = { Name='Yalungur', Ecosystem='birds', Family='colobris' },
        ['Ziz'] = { Name='Ziz', Ecosystem='birds', Family='cockatrices' },
        ['Zizzy Zillah'] = { Name='Zizzy Zillah', Ecosystem='birds', Family='cockatrices' },
    },
};
