--Zone: Mamool Ja Training Grounds
--Zone ID: 66
return {
    Names = {
        ['Bluethunder Kaqool Ja'] = { Name='Bluethunder Kaqool Ja', Ecosystem='beastmen', Family='mamool ja' },
        ['Bugard'] = { Name='Bugard', Ecosystem='lizards', Family='bugards' },
        ['Chigoe'] = { Name='Chigoe', Ecosystem='vermin', Family='chigoes' },
        ['Dilapidated Gate'] = { Name='Dilapidated Gate', Ecosystem='structures', Family='structures' },
        ['Festive Firedrake'] = { Name='Festive Firedrake', Ecosystem='dragons', Family='wyverns' },
        ['Huge Spider'] = { Name='Huge Spider', Ecosystem='vermin', Family='spiders' },
        ['Leech'] = { Name='Leech', Ecosystem='amorphs', Family='leeches' },
        ['Mamool Ja Breeder'] = { Name='Mamool Ja Breeder', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Executioner'] = { Name='Mamool Ja Executioner', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Farrier'] = { Name='Mamool Ja Farrier', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Mahout'] = { Name='Mamool Ja Mahout', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Recruit'] = { Name='Mamool Ja Recruit', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Trainee'] = { Name='Mamool Ja Trainee', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Trainer'] = { Name='Mamool Ja Trainer', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Warder'] = { Name='Mamool Ja Warder', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja\'s Lizard'] = { Name='Mamool Ja\'s Lizard', Ecosystem='lizards', Family='lizards' },
        ['Marid'] = { Name='Marid', Ecosystem='beasts', Family='marids' },
        ['Molted Bugard'] = { Name='Molted Bugard', Ecosystem='lizards', Family='bugards' },
        ['Molted Lindwurm'] = { Name='Molted Lindwurm', Ecosystem='lizards', Family='raptors' },
        ['Molted Mamool Ja'] = { Name='Molted Mamool Ja', Ecosystem='beastmen', Family='mamool ja' },
        ['Molted Puk'] = { Name='Molted Puk', Ecosystem='dragons', Family='puks' },
        ['Molted Ziz'] = { Name='Molted Ziz', Ecosystem='birds', Family='cockatrices' },
        ['Orochi'] = { Name='Orochi', Ecosystem='dragons', Family='hydras' },
        ['Pit Bugard'] = { Name='Pit Bugard', Ecosystem='lizards', Family='bugards' },
        ['Pit Lindwurm'] = { Name='Pit Lindwurm', Ecosystem='lizards', Family='raptors' },
        ['Pit Puk'] = { Name='Pit Puk', Ecosystem='dragons', Family='puks' },
        ['Pit Spider'] = { Name='Pit Spider', Ecosystem='vermin', Family='spiders' },
        ['Poroggo'] = { Name='Poroggo', Ecosystem='beastmen', Family='poroggos' },
        ['Puk'] = { Name='Puk', Ecosystem='dragons', Family='puks' },
        ['Puk Executioner'] = { Name='Puk Executioner', Ecosystem='dragons', Family='puks' },
        ['Qiqirn Huckster'] = { Name='Qiqirn Huckster', Ecosystem='beastmen', Family='qiqirns' },
        ['Sagelord Molaal Ja'] = { Name='Sagelord Molaal Ja', Ecosystem='beastmen', Family='mamool ja' },
        ['Slavering Lizard'] = { Name='Slavering Lizard', Ecosystem='lizards', Family='lizards' },
    },
};
