--Zone: Aydeewa Subterrane
--Zone ID: 68
return {
    Names = {
        ['Air Elemental'] = { Name='Air Elemental', Ecosystem='elementals', Family='elementals' },
        ['Anautogenous Slug'] = { Name='Anautogenous Slug', Ecosystem='amorphs', Family='leeches' },
        ['Aydeewa Crab'] = { Name='Aydeewa Crab', Ecosystem='aquans', Family='crabs' },
        ['Aydeewa Diremite'] = { Name='Aydeewa Diremite', Ecosystem='vermin', Family='diremites' },
        ['Bluestreak Gyugyuroon'] = { Name='Bluestreak Gyugyuroon', Ecosystem='beastment', Family='qiqirns' },
        ['Cave Mold'] = { Name='Cave Mold', Ecosystem='amorphs', Family='slimes' },
        ['Cave Pugil'] = { Name='Cave Pugil', Ecosystem='aquans', Family='pugils' },
        ['Cave Tiger'] = { Name='Cave Tiger', Ecosystem='beasts', Family='tigers' },
        ['Chigre'] = { Name='Chigre', Ecosystem='vermin', Family='chigoes' },
        ['Crystal Eater'] = { Name='Crystal Eater', Ecosystem='plantoids', Family='funguars' },
        ['Defoliator'] = { Name='Defoliator', Ecosystem='vermin', Family='crawlers' },
        ['Deforester'] = { Name='Deforester', Ecosystem='vermin', Family='crawlers' },
        ['Fossorial Flea'] = { Name='Fossorial Flea', Ecosystem='vermin', Family='chigoes' },
        ['Great Ameretat'] = { Name='Great Ameretat', Ecosystem='plantoids', Family='morbols' },
        ['Lizardtrap'] = { Name='Lizardtrap', Ecosystem='plantoids', Family='flytraps' },
        ['Mold Eater'] = { Name='Mold Eater', Ecosystem='amorphs', Family='worms' },
        ['Morta'] = { Name='Morta', Ecosystem='plantoids', Family='belladonnas' },
        ['Mycohopper'] = { Name='Mycohopper', Ecosystem='plantoids', Family='funguars' },
        ['Mycoskulker'] = { Name='Mycoskulker', Ecosystem='plantoids', Family='funguars' },
        ['Nosferatu'] = { Name='Nosferatu', Ecosystem='undead', Family='vampyrs' },
        ['Nosferatu Bats'] = { Name='Nosferatu Bats', Ecosystem='birds', Family='bat trios' },
        ['Nosferatu Murk'] = { Name='Nosferatu Murk', Ecosystem='undead', Family='fomors' },
        ['Nosferatu Wolf'] = { Name='Nosferatu Wolf', Ecosystem='undead', Family='hounds' },
        ['Pandemonium Lamp'] = { Name='Pandemonium Lamp', Ecosystem='undead', Family='corpselights' },
        ['Pandemonium Warden'] = { Name='Pandemonium Warden', Ecosystem='demons', Family='dvergers' },
        ['Phlebotomic Slug'] = { Name='Phlebotomic Slug', Ecosystem='amorphs', Family='leeches' },
        ['Puktrap'] = { Name='Puktrap', Ecosystem='plantoids', Family='flytraps' },
        ['Qiqirn Archaeologist'] = { Name='Qiqirn Archaeologist', Ecosystem='beastment', Family='qiqirns' },
        ['Qiqirn Enterpriser'] = { Name='Qiqirn Enterpriser', Ecosystem='beastment', Family='qiqirns' },
        ['Qiqirn Lieuter'] = { Name='Qiqirn Lieuter', Ecosystem='beastment', Family='qiqirns' },
        ['Qiqirn Mine'] = { Name='Qiqirn Mine', Ecosystem='unclassified', Family='mines' },
        ['Qiqirn Mosstrooper'] = { Name='Qiqirn Mosstrooper', Ecosystem='beastment', Family='qiqirns' },
        ['Ravishing Rafflesia'] = { Name='Ravishing Rafflesia', Ecosystem='plantoids', Family='rafflesias' },
        ['Slime Eater'] = { Name='Slime Eater', Ecosystem='amorphs', Family='worms' },
        ['Slime Mold'] = { Name='Slime Mold', Ecosystem='amorphs', Family='slimes' },
        ['Treant Sapling'] = { Name='Treant Sapling', Ecosystem='plantoids', Family='saplings' },
    },
};
