--Zone: Leujaoam Sanctum
--Zone ID: 69
return {
    Names = {
        ['Afrhaad'] = { Name='Afrhaad', Ecosystem='humanoids', Family='humes' },
        ['Bashdeel'] = { Name='Bashdeel', Ecosystem='humanoids', Family='humes' },
        ['Clavauert B Chanoix'] = { Name='Clavauert B Chanoix', Ecosystem='humanoids', Family='elvaan' },
        ['Coney'] = { Name='Coney', Ecosystem='vermin', Family='rabbits' },
        ['Count Dracula'] = { Name='Count Dracula', Ecosystem='undead', Family='vampyrs' },
        ['Cursed Doppelganger'] = { Name='Cursed Doppelganger', Ecosystem='humanoids', Family='mythra' },
        ['Danzo'] = { Name='Danzo', Ecosystem='humanoids', Family='humes' },
        ['Dhiadjhar'] = { Name='Dhiadjhar', Ecosystem='humanoids', Family='humes' },
        ['Frozen Bones'] = { Name='Frozen Bones', Ecosystem='undead', Family='skeletons' },
        ['Ganmuul'] = { Name='Ganmuul', Ecosystem='humanoids', Family='humes' },
        ['Gasharyad'] = { Name='Gasharyad', Ecosystem='humanoids', Family='humes' },
        ['Gelid Bhoot'] = { Name='Gelid Bhoot', Ecosystem='undead', Family='ghosts' },
        ['Ghahnis'] = { Name='Ghahnis', Ecosystem='humanoids', Family='elvaan' },
        ['Ghayaraan'] = { Name='Ghayaraan', Ecosystem='humanoids', Family='humes' },
        ['Habraheem'] = { Name='Habraheem', Ecosystem='humanoids', Family='humes' },
        ['Hkadouf'] = { Name='Hkadouf', Ecosystem='humanoids', Family='humes' },
        ['Imp'] = { Name='Imp', Ecosystem='demons', Family='imps' },
        ['Jalyaat'] = { Name='Jalyaat', Ecosystem='humanoids', Family='humes' },
        ['Krinahal'] = { Name='Krinahal', Ecosystem='humanoids', Family='humes' },
        ['Kudagitsune'] = { Name='Kudagitsune', Ecosystem='undead', Family='ghosts' },
        ['Kusa'] = { Name='Kusa', Ecosystem='humanoids', Family='humes' },
        ['Lamia Bowyer'] = { Name='Lamia Bowyer', Ecosystem='beastmen', Family='lamiae' },
        ['Lamia Prosector'] = { Name='Lamia Prosector', Ecosystem='beastmen', Family='lamiae' },
        ['Lamia Sharper'] = { Name='Lamia Sharper', Ecosystem='beastmen', Family='lamiae' },
        ['Leujaoam Worm'] = { Name='Leujaoam Worm', Ecosystem='amorphs', Family='worms' },
        ['Mareyamad'] = { Name='Mareyamad', Ecosystem='humanoids', Family='humes' },
        ['Mineral Eater'] = { Name='Mineral Eater', Ecosystem='amorphs', Family='worms' },
        ['Nareema'] = { Name='Nareema', Ecosystem='humanoids', Family='humes' },
        ['Oko'] = { Name='Oko', Ecosystem='humanoids', Family='humes' },
        ['Qiqirn Miner'] = { Name='Qiqirn Miner', Ecosystem='beastmen', Family='qiqirns' },
        ['Qudeen'] = { Name='Qudeen', Ecosystem='humanoids', Family='humes' },
        ['Rahdjab'] = { Name='Rahdjab', Ecosystem='humanoids', Family='elvaan' },
        ['Raubahn'] = { Name='Raubahn', Ecosystem='humanoids', Family='humes' },
        ['Rhushouf'] = { Name='Rhushouf', Ecosystem='humanoids', Family='elvaan' },
        ['Saizo'] = { Name='Saizo', Ecosystem='humanoids', Family='humes' },
        ['Salimuhl'] = { Name='Salimuhl', Ecosystem='humanoids', Family='humes' },
        ['Salyhaar'] = { Name='Salyhaar', Ecosystem='humanoids', Family='humes' },
        ['Shailham'] = { Name='Shailham', Ecosystem='humanoids', Family='humes' },
        ['Sharayaan'] = { Name='Sharayaan', Ecosystem='humanoids', Family='humes' },
        ['Shayaam'] = { Name='Shayaam', Ecosystem='humanoids', Family='humes' },
        ['Tahbmar'] = { Name='Tahbmar', Ecosystem='humanoids', Family='humes' },
        ['Ubdeen'] = { Name='Ubdeen', Ecosystem='humanoids', Family='humes' },
        ['Udhaaman'] = { Name='Udhaaman', Ecosystem='humanoids', Family='humes' },
        ['Varajahl'] = { Name='Varajahl', Ecosystem='humanoids', Family='humes' },
        ['Wharadi'] = { Name='Wharadi', Ecosystem='humanoids', Family='humes' },
        ['Yhalbin'] = { Name='Yhalbin', Ecosystem='humanoids', Family='humes' },
        ['Zhadjaraf'] = { Name='Zhadjaraf', Ecosystem='humanoids', Family='humes' },
    },
};
