--Zone: Zhayolm Remnants
--Zone ID: 73
return {
    Names = {
        ['Acrolith'] = { Name='Acrolith', Ecosystem='arcana', Family='acroliths' },
        ['Archaic Chariot'] = { Name='Archaic Chariot', Ecosystem='archaia', Family='chariots' },
        ['Archaic Gear'] = { Name='Archaic Gear', Ecosystem='archaia', Family='gears' },
        ['Archaic Gears'] = { Name='Archaic Gears', Ecosystem='archaia', Family='gears' },
        ['Archaic Rampart'] = { Name='Archaic Rampart', Ecosystem='archaia', Family='ramparts' },
        ['Battleclad Chariot'] = { Name='Battleclad Chariot', Ecosystem='archaia', Family='chariots' },
        ['Bull Bugard'] = { Name='Bull Bugard', Ecosystem='lizards', Family='bugards' },
        ['Crawler'] = { Name='Crawler', Ecosystem='vermin', Family='crawlers' },
        ['Diremite'] = { Name='Diremite', Ecosystem='vermin', Family='diremites' },
        ['Draco Lizard'] = { Name='Draco Lizard', Ecosystem='lizards', Family='lizards' },
        ['First Rampart'] = { Name='First Rampart', Ecosystem='archaia', Family='ramparts' },
        ['Fourth Rampart'] = { Name='Fourth Rampart', Ecosystem='archaia', Family='ramparts' },
        ['Greater Manticore'] = { Name='Greater Manticore', Ecosystem='beasts', Family='manticores' },
        ['Hydra'] = { Name='Hydra', Ecosystem='dragons', Family='hydras' },
        ['Jakko'] = { Name='Jakko', Ecosystem='demons', Family='imps' },
        ['Mamool Ja Bounder'] = { Name='Mamool Ja Bounder', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Mimicker'] = { Name='Mamool Ja Mimicker', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Savant'] = { Name='Mamool Ja Savant', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Sophist'] = { Name='Mamool Ja Sophist', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Spearman'] = { Name='Mamool Ja Spearman', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Strapper'] = { Name='Mamool Ja Strapper', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja Zenist'] = { Name='Mamool Ja Zenist', Ecosystem='beastmen', Family='mamool ja' },
        ['Mamool Ja\'s Lizard'] = { Name='Mamool Ja\'s Lizard', Ecosystem='lizards', Family='lizards' },
        ['Mamool Ja\'s Wyvern'] = { Name='Mamool Ja\'s Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Mindgazer'] = { Name='Mindgazer', Ecosystem='amorphs', Family='hecteyes' },
        ['Poroggo Gent'] = { Name='Poroggo Gent', Ecosystem='beastmen', Family='poroggos' },
        ['Poroggo Madame'] = { Name='Poroggo Madame', Ecosystem='beastmen', Family='poroggos' },
        ['Pugil'] = { Name='Pugil', Ecosystem='aquans', Family='pugils' },
        ['Puk'] = { Name='Puk', Ecosystem='dragons', Family='puks' },
        ['Rogue Marid'] = { Name='Rogue Marid', Ecosystem='beasts', Family='marids' },
        ['Second Rampart'] = { Name='Second Rampart',Ecosystem='archaia', Family='ramparts' },
        ['Slime Mold'] = { Name='Slime Mold', Ecosystem='amorphs', Family='slimes' },
        ['Third Rampart'] = { Name='Third Rampart', Ecosystem='archaia', Family='ramparts' },
        ['Toad'] = { Name='Toad', Ecosystem='aquans', Family='toads' },
        ['Torama'] = { Name='Torama', Ecosystem='beasts', Family='coeurls' },
        ['Vagrant Lindwurm'] = { Name='Vagrant Lindwurm', Ecosystem='lizards', Family='raptors' },
        ['Wajaom Tiger'] = { Name='Wajaom Tiger', Ecosystem='beasts', Family='tigers' },
        ['Wyvern'] = { Name='Wyvern', Ecosystem='dragons', Family='wyverns' },
        ['Ziz'] = { Name='Ziz', Ecosystem='birds', Family='cockatrices' },
    },
};
