--Zone: Arrapago Remnants
--Zone ID: 74
return {
    Names = {
        ['Archaic Chariot'] = { Name='Archaic Chariot', Ecosystem='archaia', Family='chariots'},
        ['Archaic Gear'] = { Name='Archaic Gear', Ecosystem='archaia', Family='gears'},
        ['Archaic Gears'] = { Name='Archaic Gears', Ecosystem='archaia', Family='gears'},
        ['Archaic Rampart'] = { Name='Archaic Rampart', Ecosystem='archaia', Family='ramparts'},
        ['Armored Chariot'] = { Name='Armored Chariot', Ecosystem='archaia', Family='chariots'},
        ['Demonic Pugil'] = { Name='Demonic Pugil', Ecosystem='aquans', Family='pugils'},
        ['Demonic Rose'] = { Name='Demonic Rose', Ecosystem='plantoids', Family='morbols'},
        ['Deviate Bhoot'] = { Name='Deviate Bhoot', Ecosystem='undead', Family='ghosts'},
        ['Devil Manta'] = { Name='Devil Manta', Ecosystem='aquans', Family='sea monks'},
        ['Draugar\'s Wyvern'] = { Name='Draugar\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Gespenst'] = { Name='Gespenst', Ecosystem='undead', Family='ghosts'},
        ['Goobbue Wanderer'] = { Name='Goobbue Wanderer', Ecosystem='plantoids', Family='goobues'},
        ['Korrigan'] = { Name='Korrigan', Ecosystem='plantoids', Family='mandragoras'},
        ['Lamia Dancer'] = { Name='Lamia Dancer', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Dartist'] = { Name='Lamia Dartist', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Fatedealer'] = { Name='Lamia Fatedealer', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Graverobber'] = { Name='Lamia Graverobber', Ecosystem='beastmen', Family='lamia'},
        ['Lamia\'s Elemental'] = { Name='Lamia\'s Elemental', Ecosystem='elementals', Family='elementals'},
        ['Merrow Chantress'] = { Name='Merrow Chantress', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Icedancer'] = { Name='Merrow Icedancer', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Kabukidancer'] = { Name='Merrow Kabukidancer', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Shadowdancer'] = { Name='Merrow Shadowdancer', Ecosystem='beastmen', Family='lamia'},
        ['Migrant Russula'] = { Name='Migrant Russula', Ecosystem='plantoids', Family='funguars'},
        ['Mourioche'] = { Name='Mourioche', Ecosystem='plantoids', Family='mandragoras'},
        ['Nipper'] = { Name='Nipper', Ecosystem='aquans', Family='crabs'},
        ['Orobon'] = { Name='Orobon', Ecosystem='aquans', Family='orobons'},
        ['Princess Pudding'] = { Name='Princess Pudding', Ecosystem='amorphs', Family='flans'},
        ['Psycheflayer'] = { Name='Psycheflayer', Ecosystem='demons', Family='soulflayers'},
        ['Qiqirn Astrologer'] = { Name='Qiqirn Astrologer', Ecosystem='beastment', Family='qiqirns'},
        ['Qiqirn Mine'] = { Name='Qiqirn Mine', Ecosystem='unclassified', Family='mines'},
        ['Qiqirn Treasure Hunter'] = { Name='Qiqirn Treasure Hunter', Ecosystem='aquans', Family='qiqirns'},
        ['Qutrub'] = { Name='Qutrub', Ecosystem='undead', Family='qutrubs'},
        ['Reserve Draugar'] = { Name='Reserve Draugar', Ecosystem='undead', Family='qutrubs'},
        ['Sabotender Maestro'] = { Name='Sabotender Maestro', Ecosystem='plantoids', Family='sabotenders'},
        ['Seasonal Treant'] = { Name='Seasonal Treant', Ecosystem='plantoids', Family='treants'},
        ['Staggering Sapling'] = { Name='Staggering Sapling', Ecosystem='plantoids', Family='saplings'},
        ['Vile Wahzil'] = { Name='Vile Wahzil', Ecosystem='demons', Family='soulflayers'},
    },
};
