--Zone: Bhaflau Remnants
--Zone ID: 75
return {
    Names = {
        ['Acrolith'] = { Name='Acrolith', Ecosystem='arcana', Family='acroliths'},
        ['Archaic Chariot'] = { Name='Archaic Chariot', Ecosystem='archaia', Family='chariots'},
        ['Archaic Gear'] = { Name='Archaic Gear', Ecosystem='archaia', Family='gears'},
        ['Archaic Gears'] = { Name='Archaic Gears', Ecosystem='archaia', Family='gears'},
        ['Archaic Rampart'] = { Name='Archaic Rampart', Ecosystem='archaia', Family='ramparts'},
        ['Bifrons'] = { Name='Bifrons', Ecosystem='arcana', Family='bombs'},
        ['Black Pudding'] = { Name='Black Pudding', Ecosystem='amorphs', Family='flans'},
        ['Carmine Eruca'] = { Name='Carmine Eruca', Ecosystem='vermin', Family='crawlers'},
        ['Cerberus'] = { Name='Cerberus', Ecosystem='beasts', Family='cerberuses'},
        ['Chigoe'] = { Name='Chigoe', Ecosystem='vermin', Family='chigoes'},
        ['Colibri'] = { Name='Colibri', Ecosystem='birds', Family='colibris'},
        ['Dahak'] = { Name='Dahak', Ecosystem='dragons', Family='dragons'},
        ['Demented Jalaawa'] = { Name='Demented Jalaawa', Ecosystem='demons', Family='soulflayers'},
        ['Dormant Rampart'] = { Name='Dormant Rampart', Ecosystem='archaia', Family='ramparts'},
        ['Empathic Flan'] = { Name='Empathic Flan', Ecosystem='amorphs', Family='flans'},
        ['Flux Flan'] = { Name='Flux Flan', Ecosystem='amorphs', Family='flans'},
        ['Gate Widow'] = { Name='Gate Widow', Ecosystem='vermin', Family='spiders'},
        ['Hunting Wasp'] = { Name='Hunting Wasp', Ecosystem='birds', Family='bees'},
        ['Long-Bowed Chariot'] = { Name='Long-Bowed Chariot', Ecosystem='archaia', Family='chariots'},
        ['Mad Bomber'] = { Name='Mad Bomber', Ecosystem='arcana', Family='bombs'},
        ['Peryton'] = { Name='Peryton', Ecosystem='birds', Family='rocs'},
        ['Reactionary Rampart'] = { Name='Reactionary Rampart', Ecosystem='archaia', Family='ramparts'},
        ['Skirmish Pephredo'] = { Name='Skirmish Pephredo', Ecosystem='vermin', Family='bees'},
        ['Sulfur Scorpion'] = { Name='Sulfur Scorpion', Ecosystem='vermin', Family='scorpions'},
        ['Tragopan'] = { Name='Tragopan', Ecosystem='birds', Family='birds'},
        ['Troll Cameist'] = { Name='Troll Cameist', Ecosystem='beastmen', Family='trolls'},
        ['Troll Engraver'] = { Name='Troll Engraver', Ecosystem='beastmen', Family='trolls'},
        ['Troll Gemologist'] = { Name='Troll Gemologist', Ecosystem='beastmen', Family='trolls'},
        ['Troll Ironworker'] = { Name='Troll Ironworker', Ecosystem='beastmen', Family='trolls'},
        ['Troll Lapidarist'] = { Name='Troll Lapidarist', Ecosystem='beastmen', Family='trolls'},
        ['Troll Smelter'] = { Name='Troll Smelter', Ecosystem='beastmen', Family='trolls'},
        ['Troll Stoneworker'] = { Name='Troll Stoneworker', Ecosystem='beastmen', Family='trolls'},
        ['Troll\'s Automaton'] = { Name='Troll\'s Automaton', Ecosystem='unclassified', Family='automatons'},
        ['Wamouracampa'] = { Name='Wamouracampa', Ecosystem='vermin', Family='wamouracampas'},
        ['Wandering Wamoura'] = { Name='Wandering Wamoura', Ecosystem='vermin', Family='wamouras'},
        ['Zebra Zachary'] = { Name='Zebra Zachary', Ecosystem='birds', Family='cockatrices'},
    },
};
