--Zone: Silver Sea Remnants
--Zone ID: 76
return {
    Names = {
        ['Acrolith'] = { Name='Acrolith', Ecosystem='arcana', Family='acroliths'},
        ['Apkallu'] = { Name='Apkallu', Ecosystem='birds', Family='apkallus'},
        ['Archaic Chariot'] = { Name='Archaic Chariot', Ecosystem='archaia', Family='chariots'},
        ['Archaic Gear'] = { Name='Archaic Gear', Ecosystem='archaia', Family='gears'},
        ['Archaic Gears'] = { Name='Archaic Gears', Ecosystem='archaia', Family='gears'},
        ['Archaic Rampart'] = { Name='Archaic Rampart', Ecosystem='archaia', Family='ramparts'},
        ['Ashu Talif Crew'] = { Name='Ashu Talif Crew', Ecosystem='undead', Family='fomors'},
        ['Citadel Chelonian'] = { Name='Citadel Chelonian', Ecosystem='lizards', Family='adamantoises'},
        ['Deadpan Devilet'] = { Name='Deadpan Devilet', Ecosystem='demons', Family='imps'},
        ['Deinonychus'] = { Name='Deinonychus', Ecosystem='lizards', Family='raptors'},
        ['Dekka'] = { Name='Dekka', Ecosystem='demons', Family='imps'},
        ['Devilet'] = { Name='Devilet', Ecosystem='demons', Family='imps'},
        ['Don Poroggo'] = { Name='Don Poroggo', Ecosystem='beastmen', Family='porggos'},
        ['Doom Mage'] = { Name='Doom Mage', Ecosystem='undead', Family='skeletons'},
        ['Gakke'] = { Name='Gakke', Ecosystem='demons', Family='imps'},
        ['Garm'] = { Name='Garm', Ecosystem='undead', Family='hounds'},
        ['Guard Skeleton'] = { Name='Guard Skeleton', Ecosystem='undead', Family='skeletons'},
        ['Gyroscopic Gear'] = { Name='Gyroscopic Gear', Ecosystem='archaia', Family='gears'},
        ['Gyroscopic Gears'] = { Name='Gyroscopic Gears', Ecosystem='archaia', Family='gears'},
        ['Hammerblow Majanun'] = { Name='Hammerblow Majanun', Ecosystem='undead', Family='fomors'},
        ['Haunt'] = { Name='Haunt', Ecosystem='undead', Family='ghosts'},
        ['Heraldic Imp'] = { Name='Heraldic Imp', Ecosystem='demons', Family='imps'},
        ['Imp'] = { Name='Imp', Ecosystem='demons', Family='imps'},
        ['Long-Armed Chariot'] = { Name='Long-Armed Chariot', Ecosystem='archaia', Family='chariots'},
        ['Night Eft'] = { Name='Night Eft', Ecosystem='lizards', Family='efts'},
        ['Orobon'] = { Name='Orobon', Ecosystem='aquans', Family='orobons'},
        ['Powderkeg Yanadahn'] = { Name='Powderkeg Yanadahn', Ecosystem='undead', Family='fomors'},
        ['Psycheflayer'] = { Name='Psycheflayer', Ecosystem='demons', Family='soulflayers'},
        ['Sand Lizard'] = { Name='Sand Lizard', Ecosystem='lizards', Family='lizards'},
    },
};
