--Zone: Nyzul Isle
--Zone ID: 77
return {
    Names = {
        ['Adamantoise'] = { Name='Adamantoise', Ecosystem='lizards', Family='adamantoises'},
        ['Aiatar'] = { Name='Aiatar', Ecosystem='dragons', Family='wyverns'},
        ['Alexander'] = { Name='Alexander', Ecosystem='unclassified', Family='avatars'},
        ['Amanita'] = { Name='Amanita', Ecosystem='plantoids', Family='funguars'},
        ['Amemet'] = { Name='Amemet', Ecosystem='lizards', Family='lizards'},
        ['Ameretat'] = { Name='Ameretat', Ecosystem='plantoids', Family='morbols'},
        ['Amikiri'] = { Name='Amikiri', Ecosystem='vermin', Family='scorpions'},
        ['Amnaf'] = { Name='Amnaf', Ecosystem='humanoids', Family='humes'},
        ['Ancient Goobbue'] = { Name='Ancient Goobbue', Ecosystem='plantoids', Family='goobues'},
        ['Anise Custard'] = { Name='Anise Custard', Ecosystem='amorphs', Family='flans'},
        ['Aquarius'] = { Name='Aquarius', Ecosystem='aquans', Family='crabs'},
        ['Arachne'] = { Name='Arachne', Ecosystem='vermin', Family='spider'},
        ['Archaic Gear'] = { Name='Archaic Gear', Ecosystem='arachaia', Family='gears'},
        ['Archaic Gears'] = { Name='Archaic Gears', Ecosystem='arachaia', Family='gears'},
        ['Archaic Rampart'] = { Name='Archaic Rampart', Ecosystem='arachaia', Family='ramparts'},
        ['Argus'] = { Name='Argus', Ecosystem='amorphs', Family='hecteyes'},
        ['Ash Dragon'] = { Name='Ash Dragon', Ecosystem='dragons', Family='dragons'},
        ['Asphyxiated Amsel'] = { Name='Asphyxiated Amsel', Ecosystem='undead', Family='ghosts'},
        ['Balrahn'] = { Name='Balrahn', Ecosystem='undead', Family='fomors'},
        ['Barbastelle'] = { Name='Barbastelle', Ecosystem='birds', Family='bats'},
        ['Bat Eye'] = { Name='Bat Eye', Ecosystem='demons', Family='ahriman'},
        ['Battledressed Chariot'] = { Name='Battledressed Chariot', Ecosystem='arachaia', Family='chariots'},
        ['Behemoth'] = { Name='Behemoth', Ecosystem='beasts', Family='behemoths'},
        ['Bhoot'] = { Name='Bhoot', Ecosystem='undead', Family='ghosts'},
        ['Black Pudding'] = { Name='Black Pudding', Ecosystem='amorphs', Family='flans'},
        ['Bloodpool Vorax'] = { Name='Bloodpool Vorax', Ecosystem='amorphs', Family='leeches'},
        ['Bloodsucker'] = { Name='Bloodsucker', Ecosystem='amorphs', Family='leeches'},
        ['Bloodtear Baldurf'] = { Name='Bloodtear Baldurf', Ecosystem='beasts', Family='sheep'},
        ['Bomb King'] = { Name='Bomb King', Ecosystem='arcana', Family='bombs'},
        ['Bonnacon'] = { Name='Bonnacon', Ecosystem='beasts', Family='buffaloes'},
        ['Boroka'] = { Name='Boroka', Ecosystem='birds', Family='hyppogryphs'},
        ['Bouncing Ball'] = { Name='Bouncing Ball', Ecosystem='amorphs', Family='leeches'},
        ['Buburimboo'] = { Name='Buburimboo', Ecosystem='aquans', Family='pugils'},
        ['Bull Bugard'] = { Name='Bull Bugard', Ecosystem='beasts', Family='bugards'},
        ['Bune'] = { Name='Bune', Ecosystem='dragons', Family='wyverns'},
        ['Burned Bergmann'] = { Name='Burned Bergmann', Ecosystem='undead', Family='ghosts'},
        ['Byakko'] = { Name='Byakko', Ecosystem='beasts', Family='tigers'},
        ['Cactuar Cantautor'] = { Name='Cactuar Cantautor', Ecosystem='plantoids', Family='sabotenders'},
        ['Capricious Cassie'] = { Name='Capricious Cassie', Ecosystem='plantoids', Family='marbols'},
        ['Caraway Custard'] = { Name='Caraway Custard', Ecosystem='amorphs', Family='flans'},
        ['Cargo Crab Colin'] = { Name='Cargo Crab Colin', Ecosystem='aquans', Family='crabs'},
        ['Carmine Eruca'] = { Name='Carmine Eruca', Ecosystem='vermin', Family='crawlers'},
        ['Carnero'] = { Name='Carnero', Ecosystem='beasts', Family='sheep'},
        ['Cerberus'] = { Name='Cerberus', Ecosystem='beasts', Family='cerberuses'},
        ['Charybdis'] = { Name='Charybdis', Ecosystem='aquans', Family='sea monks'},
        ['Chocoboleech'] = { Name='Chocoboleech', Ecosystem='amorphs', Family='leeches'},
        ['Cinnamon Custard'] = { Name='Cinnamon Custard', Ecosystem='amorphs', Family='flans'},
        ['Crushed Krause'] = { Name='Crushed Krause', Ecosystem='undead', Family='ghosts'},
        ['Cumin Custard'] = { Name='Cumin Custard', Ecosystem='amorphs', Family='flans'},
        ['Cwn Cyrff'] = { Name='Cwn Cyrff', Ecosystem='undead', Family='hounds'},
        ['Daggerclaw Dracos'] = { Name='Daggerclaw Dracos', Ecosystem='lizards', Family='raptors'},
        ['Dahak'] = { Name='Dahak', Ecosystem='dragons', Family='dragons'},
        ['Death Cap'] = { Name='Death Cap', Ecosystem='plantoids', Family='funguars'},
        ['Death from Above'] = { Name='Death from Above', Ecosystem='vermin', Family='bees'},
        ['Deinonychus'] = { Name='Deinonychus', Ecosystem='lizards', Family='raptors'},
        ['Demonic Tiphia'] = { Name='Demonic Tiphia', Ecosystem='vermin', Family='bees'},
        ['Desmodont'] = { Name='Desmodont', Ecosystem='birds', Family='bats'},
        ['Diamond Daig'] = { Name='Diamond Daig', Ecosystem='vermin', Family='beetles'},
        ['Doppelganger Dio'] = { Name='Doppelganger Dio', Ecosystem='undead', Family='shadows'},
        ['Doppelganger Gog'] = { Name='Doppelganger Gog', Ecosystem='undead', Family='shadows'},
        ['Dosetsu Tree'] = { Name='Dosetsu Tree', Ecosystem='plantoids', Family='treants'},
        ['Draugar'] = { Name='Draugar', Ecosystem='undead', Family='skeletons'},
        ['Drexerion the Condemned'] = { Name='Drexerion the Condemned', Ecosystem='undead', Family='shadows'},
        ['Drooling Daisy'] = { Name='Drooling Daisy', Ecosystem='plantoids', Family='morbols'},
        ['Duke Decapod'] = { Name='Duke Decapod', Ecosystem='aquans', Family='crabs'},
        ['Dune Widow'] = { Name='Dune Widow', Ecosystem='vermin', Family='spiders'},
        ['Eastern Shadow'] = { Name='Eastern Shadow', Ecosystem='undead', Family='shadows'},
        ['Ebony Pudding'] = { Name='Ebony Pudding', Ecosystem='amorphs', Family='flans'},
        ['Edacious Opo-opo'] = { Name='Edacious Opo-opo', Ecosystem='beasts', Family='opo-opos'},
        ['Elel'] = { Name='Elel', Ecosystem='undead', Family='corses'},
        ['Ellyllon'] = { Name='Ellyllon', Ecosystem='plantoids', Family='funguars'},
        ['Emergent Elm'] = { Name='Emergent Elm', Ecosystem='plantoids', Family='treants'},
        ['Energetic Eruca'] = { Name='Energetic Eruca', Ecosystem='vermin', Family='crawlers'},
        ['Eriri Samariri'] = { Name='Eriri Samariri', Ecosystem='beastmen', Family='poroggos'},
        ['Fafnir'] = { Name='Fafnir', Ecosystem='dragons', Family='wyrms'},
        ['Falcatus Aranei'] = { Name='Falcatus Aranei',Ecosystem='vermin', Family='spiders'},
        ['Fraelissa'] = { Name='Fraelissa', Ecosystem='plantoids', Family='treants'},
        ['Friar Rush'] = { Name='Friar Rush', Ecosystem='arcana', Family='bombs'},
        ['Friar\'s Lantern'] = { Name='Friar\'s Lantern', Ecosystem='arcana', Family='bombs'},
        ['Frostmane'] = { Name='Frostmane', Ecosystem='beasts', Family='manticores'},
        ['Fungus Beetle'] = { Name='Fungus Beetle', Ecosystem='vermin', Family='beetles'},
        ['Gargantua'] = { Name='Gargantua', Ecosystem='arcana', Family='golems'},
        ['Garm'] = { Name='Garm', Ecosystem='undead', Family='hounds'},
        ['Gem Heister Roorooroon'] = { Name='Gem Heister Roorooroon', Ecosystem='beastmen', Family='qiqirns'},
        ['Genbu'] = { Name='Genbu', Ecosystem='lizards', Family='adamantoises'},
        ['Ghillie Dhu'] = { Name='Ghillie Dhu', Ecosystem='plantoids', Family='saplings'},
        ['Ginger Custard'] = { Name='Ginger Custard', Ecosystem='amorphs', Family='flans'},
        ['Golden Bat'] = { Name='Golden Bat', Ecosystem='birds', Family='bats'},
        ['Greatclaw'] = { Name='Greatclaw', Ecosystem='aquans', Family='crabs'},
        ['Gyre-Carlin'] = { Name='Gyre-Carlin', Ecosystem='vermin', Family='diremites'},
        ['Habetrot'] = { Name='Habetrot', Ecosystem='vermin', Family='crawlers'},
        ['Habrok'] = { Name='Habrok', Ecosystem='birds', Family='birds'},
        ['Helldiver'] = { Name='Helldiver', Ecosystem='birds', Family='birds'},
        ['Hellion'] = { Name='Hellion', Ecosystem='undead', Family='doomed'},
        ['Heraldic Imp'] = { Name='Heraldic Imp', Ecosystem='demons', Family='imps'},
        ['Herbage Hunter'] = { Name='Herbage Hunter', Ecosystem='vermin', Family='crawlers'},
        ['Hercules Beetle'] = { Name='Hercules Beetle', Ecosystem='vermin', Family='beetles'},
        ['Hippomaritimus'] = { Name='Hippomaritimus', Ecosystem='aquans', Family='pugils'},
        ['Hovering Hotpot'] = { Name='Hovering Hotpot', Ecosystem='arcana', Family='magic pots'},
        ['Hydra'] = { Name='Hydra', Ecosystem='dragons', Family='hydras'},
        ['Imp'] = { Name='Imp', Ecosystem='demons', Family='imps'},
        ['Imperial Gear'] = { Name='Imperial Gear', Ecosystem='arachaia', Family='gears'},
        ['Imperial Gears'] = { Name='Imperial Gears', Ecosystem='arachaia', Family='gears'},
        ['Intulo'] = { Name='Intulo', Ecosystem='lizards', Family='efts'},
        ['Jaded Jody'] = { Name='Jaded Jody', Ecosystem='plantoids', Family='morbols'},
        ['Jaggedy-Eared Jack'] = { Name='Jaggedy-Eared Jack', Ecosystem='beasts', Family='rabbits'},
        ['Jolly Green'] = { Name='Jolly Green', Ecosystem='plantoids', Family='goobues'},
        ['Juggler Hecatomb'] = { Name='Juggler Hecatomb', Ecosystem='arcana', Family='evil weapons'},
        ['Keeper of Halidom'] = { Name='Keeper of Halidom', Ecosystem='plantoids', Family='goobues'},
        ['Khimaira'] = { Name='Khimaira', Ecosystem='arcana', Family='khimairas'},
        ['Killing Weapon'] = { Name='Killing Weapon', Ecosystem='arcana', Family='evil weapons'},
        ['King Arthro'] = { Name='King Arthro', Ecosystem='aquans', Family='crabs'},
        ['Kirata'] = { Name='Kirata', Ecosystem='beasts', Family='tigers'},
        ['Koropokkur'] = { Name='Koropokkur', Ecosystem='plantoids', Family='mandragoras'},
        ['Kreutzet'] = { Name='Kreutzet', Ecosystem='birds', Family='rocs'},
        ['Kulshedra'] = { Name='Kulshedra', Ecosystem='aquans', Family='sea monks'},
        ['Leaping Lizzy'] = { Name='Leaping Lizzy', Ecosystem='lizards', Family='lizards'},
        ['Leech King'] = { Name='Leech King', Ecosystem='amorphs', Family='leeches'},
        ['Leshy'] = { Name='Leshy', Ecosystem='plantoids', Family='treants'},
        ['Lesser Colibri'] = { Name='Lesser Colibri', Ecosystem='birds', Family='colibris'},
        ['Lindwurm'] = { Name='Lindwurm', Ecosystem='lizards', Family='raptors'},
        ['Lizardtrap'] = { Name='Lizardtrap', Ecosystem='plantoids', Family='flytraps'},
        ['Long-Gunned Chariot'] = { Name='Long-Gunned Chariot', Ecosystem='arachaia', Family='chariots'},
        ['Long-Horned Chariot'] = { Name='Long-Horned Chariot', Ecosystem='arachaia', Family='chariots'},
        ['Lord of Onzozo'] = { Name='Lord of Onzozo', Ecosystem='aquans', Family='sea monks'},
        ['Lumber Jack'] = { Name='Lumber Jack', Ecosystem='vermin', Family='beetles'},
        ['Magic Flagon'] = { Name='Magic Flagon', Ecosystem='arcana', Family='magic pots'},
        ['Mahishasura'] = { Name='Mahishasura', Ecosystem='beasts', Family='marids'},
        ['Maighdean Uaine'] = { Name='Maighdean Uaine', Ecosystem='plantoids', Family='saplings'},
        ['Maltha'] = { Name='Maltha', Ecosystem='amorphs', Family='slimes'},
        ['Manticore'] = { Name='Manticore', Ecosystem='beasts', Family='manticores'},
        ['Marid'] = { Name='Marid', Ecosystem='beasts', Family='marids'},
        ['Marsh Murre'] = { Name='Marsh Murre', Ecosystem='birds', Family='birds'},
        ['Megalobugard'] = { Name='Megalobugard', Ecosystem='lizards', Family='bugards'},
        ['Mint Custard'] = { Name='Mint Custard', Ecosystem='amorphs', Family='flans'},
        ['Mischievous Micholas'] = { Name='Mischievous Micholas', Ecosystem='beasts', Family='opo-opos'},
        ['Mokka'] = { Name='Mokka', Ecosystem='demons', Family='imps'},
        ['Mokke'] = { Name='Mokke', Ecosystem='demons', Family='imps'},
        ['Mokku'] = { Name='Mokku', Ecosystem='demons', Family='imps'},
        ['Mousse'] = { Name='Mousse', Ecosystem='amorphs', Family='slimes'},
        ['Mucoid Mass'] = { Name='Mucoid Mass', Ecosystem='amorphs', Family='slimes'},
        ['Mycophile'] = { Name='Mycophile', Ecosystem='plantoids', Family='funguars'},
        ['Naja Salaheem'] = { Name='Naja Salaheem', Ecosystem='humanoids', Family='mithra'},
        ['Narasimha'] = { Name='Narasimha', Ecosystem='beasts', Family='manticores'},
        ['Nightmare Vase'] = { Name='Nightmare Vase', Ecosystem='arcana', Family='magic pots'},
        ['Nis Puk'] = { Name='Nis Puk', Ecosystem='dragons', Family='puks'},
        ['Noble Mold'] = { Name='Noble Mold', Ecosystem='plantoids', Family='funguars'},
        ['Nocuous Weapon'] = { Name='Nocuous Weapon', Ecosystem='arcana', Family='evil weapons'},
        ['Northern Shadow'] = { Name='Northern Shadow', Ecosystem='undead', Family='shadows'},
        ['Numbing Norman'] = { Name='Numbing Norman', Ecosystem='vermin', Family='bees'},
        ['Nunyenunc'] = { Name='Nunyenunc', Ecosystem='birds', Family='birds'},
        ['Nussknacker'] = { Name='Nussknacker', Ecosystem='lizards', Family='lizards'},
        ['Nutmeg Custard'] = { Name='Nutmeg Custard', Ecosystem='amorphs', Family='flans'},
        ['Odqan'] = { Name='Odqan', Ecosystem='arcana', Family='clusters'},
        ['Ogama'] = { Name='Ogama', Ecosystem='undead', Family='doomed'},
        ['Old Two-Wings'] = { Name='Old Two-Wings', Ecosystem='birds', Family='bats'},
        ['Ominous Weapon'] = { Name='Ominous Weapon', Ecosystem='arcana', Family='evil weapons'},
        ['Oni Carcass'] = { Name='Oni Carcass', Ecosystem='undead', Family='doomed'},
        ['Orctrap'] = { Name='Orctrap', Ecosystem='plantoids', Family='flytraps'},
        ['Oriri Samariri'] = { Name='Oriri Samariri', Ecosystem='beastmen', Family='poroggos'},
        ['Ose'] = { Name='Ose', Ecosystem='beasts', Family='coeurls'},
        ['Panzer Percival'] = { Name='Panzer Percival', Ecosystem='vermin', Family='beetles'},
        ['Patripatan'] = { Name='Patripatan', Ecosystem='beasts', Family='coeurls'},
        ['Peallaidh'] = { Name='Peallaidh', Ecosystem='beasts', Family='sheep'},
        ['Peg Powler'] = { Name='Peg Powler', Ecosystem='aquans', Family='sea monks'},
        ['Pelican'] = { Name='Pelican', Ecosystem='birds', Family='cockatrices'},
        ['Peryton'] = { Name='Peryton', Ecosystem='birds', Family='rocs'},
        ['Phanduron the Condemned'] = { Name='Phanduron the Condemned', Ecosystem='undead', Family='shadows'},
        ['Poroggo Gent'] = { Name='Poroggo Gent', Ecosystem='beastmen', Family='poroggos'},
        ['Psycheflayer'] = { Name='Psycheflayer', Ecosystem='demons', Family='soulflayers'},
        ['Puk'] = { Name='Puk', Ecosystem='dragons', Family='puks'},
        ['Puktrap'] = { Name='Puktrap', Ecosystem='plantoids', Family='flytraps'},
        ['Pulverized Pfeffer'] = { Name='Pulverized Pfeffer', Ecosystem='undead', Family='ghosts'},
        ['Qiqirn Archaeologist'] = { Name='Qiqirn Archaeologist', Ecosystem='beastmen', Family='qiqirns'},
        ['Qiqirn Mine'] = { Name='Qiqirn Mine', Ecosystem='unclassified', Family='mines'},
        ['Qiqirn Treasure Hunter'] = { Name='Qiqirn Treasure Hunter', Ecosystem='beastmen', Family='qiqirns'},
        ['Quick Draw Sasaroon'] = { Name='Quick Draw Sasaroon', Ecosystem='beastmen', Family='qiqirns'},
        ['Racing Chariot'] = { Name='Racing Chariot', Ecosystem='arachaia', Family='chariots'},
        ['Rambukk'] = { Name='Rambukk', Ecosystem='beasts', Family='rams'},
        ['Raubahn'] = { Name='Raubahn', Ecosystem='humanoids', Family='humes'},
        ['Razfahd'] = { Name='Razfahd', Ecosystem='humanoids', Family='humes'},
        ['Roc'] = { Name='Roc', Ecosystem='birds', Family='rocs'},
        ['Sabotender Bailarin'] = { Name='Sabotender Bailarin', Ecosystem='plantoids', Family='sabotenders'},
        ['Sabotender Mariachi'] = { Name='Sabotender Mariachi', Ecosystem='plantoids', Family='sabotenders'},
        ['Sand Lizard'] = { Name='Sand Lizard', Ecosystem='lizards', Family='lizards'},
        ['Seiryu'] = { Name='Seiryu', Ecosystem='dragons', Family='wyverns'},
        ['Sekhmet'] = { Name='Sekhmet', Ecosystem='beasts', Family='coeurls'},
        ['Serket'] = { Name='Serket', Ecosystem='vermin', Family='scorpions'},
        ['Serpopard Ishtar'] = { Name='Serpopard Ishtar', Ecosystem='beasts', Family='dhalmels'},
        ['Serra'] = { Name='Serra', Ecosystem='aquans', Family='pugils'},
        ['Sewer Syrup'] = { Name='Sewer Syrup', Ecosystem='amorphs', Family='slimes'},
        ['Shadow Eye'] = { Name='Shadow Eye', Ecosystem='demons', Family='ahriman'},
        ['Sharp-Eared Ropipi'] = { Name='Sharp-Eared Ropipi', Ecosystem='beasts', Family='rabbits'},
        ['Shielded Chariot'] = { Name='Shielded Chariot', Ecosystem='arachaia', Family='chariots'},
        ['Shii'] = { Name='Shii', Ecosystem='undead', Family='hounds'},
        ['Simurgh'] = { Name='Simurgh', Ecosystem='birds', Family='rocs'},
        ['Skewer Sam'] = { Name='Skewer Sam', Ecosystem='birds', Family='cockatrices'},
        ['Skull of Envy'] = { Name='Skull of Envy', Ecosystem='undead', Family='skeletons'},
        ['Skull of Gluttony'] = { Name='Skull of Gluttony', Ecosystem='undead', Family='skeletons'},
        ['Skull of Greed'] = { Name='Skull of Greed', Ecosystem='undead', Family='skeletons'},
        ['Skull of Lust'] = { Name='Skull of Lust', Ecosystem='undead', Family='skeletons'},
        ['Skull of Pride'] = { Name='Skull of Pride', Ecosystem='undead', Family='skeletons'},
        ['Skull of Sloth'] = { Name='Skull of Sloth', Ecosystem='undead', Family='skeletons'},
        ['Skull of Wrath'] = { Name='Skull of Wrath', Ecosystem='undead', Family='skeletons'},
        ['Slumbering Samwell'] = { Name='Slumbering Samwell', Ecosystem='beasts', Family='sheep'},
        ['Smothered Schmidt'] = { Name='Smothered Schmidt', Ecosystem='undead', Family='ghosts'},
        ['Southern Shadow'] = { Name='Southern Shadow', Ecosystem='undead', Family='shadows'},
        ['Spinner'] = { Name='Spinner', Ecosystem='vermin', Family='spiders'},
        ['Spiny Spipi'] = { Name='Spiny Spipi', Ecosystem='vermin', Family='crawlers'},
        ['Stealth Bomber Gagaroon'] = { Name='Stealth Bomber Gagaroon', Ecosystem='beastmen', Family='qiqirns'},
        ['Steelfleece Baldarich'] = { Name='Steelfleece Baldarich', Ecosystem='beasts', Family='sheep'},
        ['Stinging Sophie'] = { Name='Stinging Sophie', Ecosystem='vermin', Family='bees'},
        ['Stray Mary'] = { Name='Stray Mary', Ecosystem='beasts', Family='sheep'},
        ['Stygian Pugil'] = { Name='Stygian Pugil', Ecosystem='aquans', Family='pugils'},
        ['Suzaku'] = { Name='Suzaku', Ecosystem='birds', Family='rocs'},
        ['Swamfisk'] = { Name='Swamfisk', Ecosystem='aquans', Family='pugils'},
        ['Sweeping Cluster'] = { Name='Sweeping Cluster', Ecosystem='arcana', Family='clusters'},
        ['Tainted Flesh'] = { Name='Tainted Flesh', Ecosystem='undead', Family='doomed'},
        ['Taisaijin'] = { Name='Taisaijin', Ecosystem='amorphs', Family='hecteyes'},
        ['Tarasque'] = { Name='Tarasque', Ecosystem='lizards', Family='lizards'},
        ['Teporingo'] = { Name='Teporingo', Ecosystem='beasts', Family='rabbits'},
        ['Thousand Eyes'] = { Name='Thousand Eyes', Ecosystem='amorphs', Family='hecteyes'},
        ['Tococo'] = { Name='Tococo', Ecosystem='birds', Family='birds'},
        ['Tom Tit Tat'] = { Name='Tom Tit Tat', Ecosystem='plantoids', Family='mandragoras'},
        ['Tottering Toby'] = { Name='Tottering Toby', Ecosystem='plantoids', Family='saplings'},
        ['Trickster Kinetix'] = { Name='Trickster Kinetix', Ecosystem='arcana', Family='evil weapons'},
        ['Tumbling Truffle'] = { Name='Tumbling Truffle', Ecosystem='plantoids', Family='funguars'},
        ['Tyrannic Tunnok'] = { Name='Tyrannic Tunnok', Ecosystem='vermin', Family='scorpions'},
        ['Ungur'] = { Name='Ungur', Ecosystem='dragons', Family='wyverns'},
        ['Unut'] = { Name='Unut', Ecosystem='beasts', Family='rabbits'},
        ['Uriri Samariri'] = { Name='Uriri Samariri', Ecosystem='beastmen', Family='poroggos'},
        ['Valkurm Emperor'] = { Name='Valkurm Emperor', Ecosystem='vermin', Family='flies'},
        ['Vanilla Custard'] = { Name='Vanilla Custard', Ecosystem='amorphs', Family='flans'},
        ['Vile Ineef'] = { Name='Vile Ineef', Ecosystem='demons', Family='soulflayers'},
        ['Vile Wahdaha'] = { Name='Vile Wahdaha', Ecosystem='demons', Family='soulflayers'},
        ['Vile Yabeewa'] = { Name='Vile Yabeewa', Ecosystem='demons', Family='soulflayers'},
        ['Voluptuous Vivian'] = { Name='Voluptuous Vivian', Ecosystem='plantoids', Family='morbols'},
        ['Vouivre'] = { Name='Vouivre', Ecosystem='dragons', Family='wyverns'},
        ['Wajaom Tiger'] = { Name='Wajaom Tiger', Ecosystem='beasts', Family='tigers'},
        ['Wake Warder Wanda'] = { Name='Wake Warder Wanda', Ecosystem='aquans', Family='crabs'},
        ['Wamoura'] = { Name='Wamoura', Ecosystem='vermin', Family='wamouras'},
        ['Wamouracampa'] = { Name='Wamouracampa', Ecosystem='vermin', Family='wamouracampas'},
        ['Waraxe Beak'] = { Name='Waraxe Beak', Ecosystem='birds', Family='cockatrices'},
        ['Western Shadow'] = { Name='Western Shadow', Ecosystem='undead', Family='shadows'},
        ['Wild Karakul'] = { Name='Wild Karakul', Ecosystem='beasts', Family='sheep'},
        ['Wivre'] = { Name='Wivre', Ecosystem='lizards', Family='wivres'},
        ['Woodland Sage'] = { Name='Woodland Sage', Ecosystem='plantoids', Family='treants'},
        ['Wounded Wurfel'] = { Name='Wounded Wurfel', Ecosystem='undead', Family='ghosts'},
        ['Wraith Bat'] = { Name='Wraith Bat', Ecosystem='birds', Family='bats'},
        ['Wyvern'] = { Name='Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Yara Ma Yha Who'] = { Name='Yara Ma Yha Who', Ecosystem='plantoids', Family='saplings'},
        ['Yowie'] = { Name='Yowie', Ecosystem='lizards', Family='raptors'},
        ['Zahak'] = { Name='Zahak', Ecosystem='dragons', Family='hydras'},
        ['Ziz'] = { Name='Ziz', Ecosystem='birds', Family='cockatrices'},
        ['Zizzy Zillah'] = { Name='Zizzy Zillah', Ecosystem='birds', Family='cockatrices'},
    },
};
