--Zone: Caedarva Mire
--Zone ID: 79
return {
    Names = {
        ['Aynu-kaysey'] = { Name='Aynu-kaysey', Ecosystem='undead', Family='qutrubs'},
        ['Brekekekex'] = { Name='Brekekekex', Ecosystem='beastmen', Family='poroggos'},
        ['Caedarva Leech'] = { Name='Caedarva Leech', Ecosystem='amorphs', Family='leeches'},
        ['Caedarva Marshscum'] = { Name='Caedarva Marshscum', Ecosystem='amorphs', Family='slimes'},
        ['Caedarva Pondscum'] = { Name='Caedarva Pondscum', Ecosystem='amorphs', Family='slimes'},
        ['Caedarva Toad'] = { Name='Caedarva Toad', Ecosystem='aquans', Family='toads'},
        ['Chigoe'] = { Name='Chigoe', Ecosystem='vermin', Family='chigoes'},
        ['Chorus Toad'] = { Name='Chorus Toad', Ecosystem='aquans', Family='toads'},
        ['Dark Bugler'] = { Name='Dark Bugler', Ecosystem='demons', Family='imps'},
        ['Dark Elemental'] = { Name='Dark Elemental', Ecosystem='elementals', Family='elementals'},
        ['Dark Esquire'] = { Name='Dark Esquire', Ecosystem='demons', Family='demons'},
        ['Dark Rider'] = { Name='Dark Rider', Ecosystem='unclassified', Family='avatars'},
        ['Draugar Servant'] = { Name='Draugar Servant', Ecosystem='undead', Family='skeletons'},
        ['Draugar\'s Wyvern'] = { Name='Draugar\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Elder Treant'] = { Name='Elder Treant', Ecosystem='plantoids', Family='treants'},
        ['Ephramadian Shade'] = { Name='Ephramadian Shade', Ecosystem='undead', Family='fomors'},
        ['Experimental Lamia'] = { Name='Experimental Lamia', Ecosystem='beastmen', Family='lamia'},
        ['Guard Bhoot'] = { Name='Guard Bhoot', Ecosystem='undead', Family='ghosts'},
        ['Guard Skeleton'] = { Name='Guard Skeleton', Ecosystem='undead', Family='skeletons'},
        ['Heraldic Imp'] = { Name='Heraldic Imp', Ecosystem='demons', Family='imps'},
        ['Jazaraat'] = { Name='Jazaraat', Ecosystem='undead', Family='fomors'},
        ['Jnun'] = { Name='Jnun', Ecosystem='undead', Family='doomed'},
        ['Khimaira'] = { Name='Khimaira', Ecosystem='arcana', Family='khimairas'},
        ['Lamia Chaukidar'] = { Name='Lamia Chaukidar', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Deathdancer'] = { Name='Lamia Deathdancer', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Fatedealer'] = { Name='Lamia Fatedealer', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Idolater'] = { Name='Lamia Idolater', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Necromancer'] = { Name='Lamia Necromancer', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.27'] = { Name='Lamia No.27', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Toxophilite'] = { Name='Lamia Toxophilite', Ecosystem='beastmen', Family='lamia'},
        ['Llamhigyn Y Dwr'] = { Name='Llamhigyn Y Dwr', Ecosystem='beastmen', Family='lamia'},
        ['Mahjlaef the Paintorn'] = { Name='Mahjlaef the Paintorn', Ecosystem='demons', Family='soulflayers'},
        ['Marsh Murre'] = { Name='Marsh Murre', Ecosystem='birds', Family='birds'},
        ['Mature Treant'] = { Name='Mature Treant', Ecosystem='plantoids', Family='treants'},
        ['Merrow Shadowdancer'] = { Name='Merrow Shadowdancer', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Typhoondancer'] = { Name='Merrow Typhoondancer', Ecosystem='beastmen', Family='lamia'},
        ['Moshdahn'] = { Name='Moshdahn', Ecosystem='undead', Family='qutrubs'},
        ['Mosshorn'] = { Name='Mosshorn', Ecosystem='beasts', Family='rams'},
        ['Oil Slick'] = { Name='Oil Slick', Ecosystem='amorphs', Family='slimes'},
        ['Orderly Imp'] = { Name='Orderly Imp', Ecosystem='demons', Family='imps'},
        ['Peallaidh'] = { Name='Peallaidh', Ecosystem='beasts', Family='sheep'},
        ['Puktrap'] = { Name='Puktrap', Ecosystem='plantoids', Family='flytraps'},
        ['Qiqirn Mine'] = { Name='Qiqirn Mine', Ecosystem='beastmen', Family='qiqirns'},
        ['Qiqirn Mireguide'] = { Name='Qiqirn Mireguide', Ecosystem='beastmen', Family='qiqirns'},
        ['Qiqirn Rock Hound'] = { Name='Qiqirn Rock Hound', Ecosystem='beastmen', Family='qiqirns'},
        ['Ravin Raven'] = { Name='Ravin Raven', Ecosystem='birds', Family='birds'},
        ['Reserve Draugar'] = { Name='Reserve Draugar', Ecosystem='undead', Family='skeletons'},
        ['Shedu'] = { Name='Shedu', Ecosystem='arcana', Family='khimairas'},
        ['Slough Skua'] = { Name='Slough Skua', Ecosystem='birds', Family='birds'},
        ['Soulflayer'] = { Name='Soulflayer', Ecosystem='demons', Family='soulflayers'},
        ['Spongilla Fly'] = { Name='Spongilla Fly', Ecosystem='vermin', Family='flies'},
        ['Suhur Mas'] = { Name='Suhur Mas', Ecosystem='aquans', Family='pugils'},
        ['Thunder Elemental'] = { Name='Thunder Elemental', Ecosystem='elementals', Family='elementals'},
        ['Treant Sapling'] = { Name='Treant Sapling', Ecosystem='plantoids', Family='saplings'},
        ['Tyger'] = { Name='Tyger', Ecosystem='arcana', Family='khimairas'},
        ['Vauxia Fly'] = { Name='Vauxia Fly', Ecosystem='vermin', Family='flies'},
        ['Verdelet'] = { Name='Verdelet', Ecosystem='demons', Family='imps'},
        ['Water Elemental'] = { Name='Water Elemental', Ecosystem='elementals', Family='elementals'},
        ['Wild Karakul'] = { Name='Wild Karakul', Ecosystem='beasts', Family='sheep'},
        ['Zikko'] = { Name='Zikko', Ecosystem='demons', Family='imps'},
    },
};
