--Zone: Attohwa Chasm
--Zone ID: 7
return {
    Names = {
        ['Air Elemental'] = { Name='Air Elemental', 
        ['Alastor Antlion'] = { Name='Alastor Antlion', 
        ['Ambusher Antlion'] = { Name='Ambusher Antlion', 
        ['Arch Corse'] = { Name='Arch Corse', 
        ['Attohwa Coeurl'] = { Name='Attohwa Coeurl', 
        ['Bane Lizard'] = { Name='Bane Lizard', 
        ['Bifrons'] = { Name='Bifrons', 
        ['Bloody Skull'] = { Name='Bloody Skull', 
        ['Burrow Antlion'] = { Name='Burrow Antlion', 
        ['Cave Antlion'] = { Name='Cave Antlion', 
        ['Chasm Lizard'] = { Name='Chasm Lizard', 
        ['Citipati'] = { Name='Citipati', 
        ['Corse'] = { Name='Corse', 
        ['Cutlass Scorpion'] = { Name='Cutlass Scorpion', 
        ['Doom Scorpion'] = { Name='Doom Scorpion', 
        ['Earth Elemental'] = { Name='Earth Elemental', 
        ['Executioner Antlion'] = { Name='Executioner Antlion', 
        ['Feeler Antlion'] = { Name='Feeler Antlion', 
        ['Fjalar'] = { Name='Fjalar', 
        ['Flesh Eater'] = { Name='Flesh Eater', 
        ['Gallinipper'] = { Name='Gallinipper', 
        ['Goblin Furrier'] = { Name='Goblin Furrier', 
        ['Goblin Pathfinder'] = { Name='Goblin Pathfinder', 
        ['Goblin Poacher'] = { Name='Goblin Poacher', 
        ['Goblin Reaper'] = { Name='Goblin Reaper', 
        ['Goblin Robber'] = { Name='Goblin Robber', 
        ['Goblin Shaman'] = { Name='Goblin Shaman', 
        ['Goblin Smithy'] = { Name='Goblin Smithy', 
        ['Goblin Trader'] = { Name='Goblin Trader', 
        ['Goblin\'s Gallinipper'] = { Name='Goblin\'s Gallinipper', 
        ['Goblin\'s Ogrefly'] = { Name='Goblin\'s Ogrefly', 
        ['Hecteyes'] = { Name='Hecteyes', 
        ['Hunter Antlion'] = { Name='Hunter Antlion', 
        ['Lich'] = { Name='Lich', 
        ['Lioumere'] = { Name='Lioumere', 
        ['Master Coeurl'] = { Name='Master Coeurl', 
        ['Monarch Ogrefly'] = { Name='Monarch Ogrefly', 
        ['Mummy'] = { Name='Mummy', 
        ['Muut'] = { Name='Muut', 
        ['Muut\'s Hound Warrior'] = { Name='Muut\'s Hound Warrior', 
        ['Muut\'s Sacrifice'] = { Name='Muut\'s Sacrifice', 
        ['Ogrefly'] = { Name='Ogrefly', 
        ['Pit Antlion'] = { Name='Pit Antlion', 
        ['Sand Lizard'] = { Name='Sand Lizard', 
        ['Sargas'] = { Name='Sargas', 
        ['Sekhmet'] = { Name='Sekhmet', 
        ['Tiamat'] = { Name='Tiamat', 
        ['Tomb Mage'] = { Name='Tomb Mage', 
        ['Tomb Warrior'] = { Name='Tomb Warrior', 
        ['Tracer Antlion'] = { Name='Tracer Antlion', 
        ['Tracker Antlion'] = { Name='Tracker Antlion', 
        ['Trench Antlion'] = { Name='Trench Antlion', 
        ['Tulwar Scorpion'] = { Name='Tulwar Scorpion', 
        ['Will-o\'-the-Wykes'] = { Name='Will-o\'-the-Wykes', 
        ['Xolotl'] = { Name='Xolotl', 
        ['Xolotl\'s Hound Warrior'] = { Name='Xolotl\'s Hound Warrior', 
        ['Xolotl\'s Sacrifice'] = { Name='Xolotl\'s Sacrifice', 
    },
};
