--Zone: Attohwa Chasm
--Zone ID: 7
return {
    Names = {
        ['Air Elemental']               = { Name='Air Elemental', Ecosystem='elementals', Family='elementals' },
        ['Alastor Antlion']             = { Name='Alastor Antlion', Ecosystem='vermin', Family='antlions' },
        ['Ambusher Antlion']            = { Name='Ambusher Antlion', Ecosystem='vermin', Family='antlions' },
        ['Arch Corse']                  = { Name='Arch Corse', Ecosystem='undead', Family='corses' },
        ['Attohwa Coeurl']              = { Name='Attohwa Coeurl', Ecosystem='beasts', Family='coeurls' },
        ['Bane Lizard']                 = { Name='Bane Lizard', Ecosystem='lizards', Family='lizards' },
        ['Bifrons']                     = { Name='Bifrons', Ecosystem='arcana', Family='bombs' },
        ['Bloody Skull']                = { Name='Bloody Skull', Ecosystem='undead', Family='corpslights' },
        ['Burrow Antlion']              = { Name='Burrow Antlion', Ecosystem='vermin', Family='antlions' },
        ['Cave Antlion']                = { Name='Cave Antlion', Ecosystem='vermin', Family='antlions' },
        ['Chasm Lizard']                = { Name='Chasm Lizard', Ecosystem='lizards', Family='lizards' },
        ['Citipati']                    = { Name='Citipati', Ecosystem='undead', Family='corses' },
        ['Corse']                       = { Name='Corse', Ecosystem='undead', Family='corses' },
        ['Cutlass Scorpion']            = { Name='Cutlass Scorpion', Ecosystem='vermin', Family='scorpions' },
        ['Doom Scorpion']               = { Name='Doom Scorpion', Ecosystem='vermin', Family='scorpions' },
        ['Earth Elemental']             = { Name='Earth Elemental', Ecosystem='elementals', Family='elementals' },
        ['Executioner Antlion']         = { Name='Executioner Antlion', Ecosystem='vermin', Family='antlions' },
        ['Feeler Antlion']              = { Name='Feeler Antlion', Ecosystem='vermin', Family='antlions' },
        ['Fjalar']                      = { Name='Fjalar', Ecosystem='demons', Family='dvergrs' },
        ['Flesh Eater']                 = { Name='Flesh Eater', Ecosystem='amorphs', Family='worms' },
        ['Gallinipper']                 = { Name='Gallinipper', Ecosystem='vermin', Family='flies' },
        ['Goblin Furrier']              = { Name='Goblin Furrier', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Pathfinder']           = { Name='Goblin Pathfinder', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Poacher']              = { Name='Goblin Poacher', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Reaper']               = { Name='Goblin Reaper', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Robber']               = { Name='Goblin Robber', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Shaman']               = { Name='Goblin Shaman', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Smithy']               = { Name='Goblin Smithy', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Trader']               = { Name='Goblin Trader', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Gallinipper']       = { Name='Goblin\'s Gallinipper', Ecosystem='vermin', Family='flies' },
        ['Goblin\'s Ogrefly']           = { Name='Goblin\'s Ogrefly', Ecosystem='vermin', Family='flies' },
        ['Hecteyes']                    = { Name='Hecteyes', Ecosystem='amorphs', Family='hecteyes' },
        ['Hunter Antlion']              = { Name='Hunter Antlion', Ecosystem='vermin', Family='antlions' },
        ['Lich']                        = { Name='Lich', Ecosystem='undead', Family='skeletons' },
        ['Lioumere']                    = { Name='Lioumere', Ecosystem='vermin', Family='antlions' },
        ['Master Coeurl']               = { Name='Master Coeurl', Ecosystem='beasts', Family='coeurls' },
        ['Monarch Ogrefly']             = { Name='Monarch Ogrefly', Ecosystem='vermin', Family='flies' },
        ['Mummy']                       = { Name='Mummy', Ecosystem='undead', Family='skeletons' },
        ['Muut']                        = { Name='Muut', Ecosystem='undead', Family='corses' },
        ['Muut\'s Hound Warrior']       = { Name='Muut\'s Hound Warrior', Ecosystem='undead', Family='skeletons' },
        ['Muut\'s Sacrifice']           = { Name='Muut\'s Sacrifice', Ecosystem='undead', Family='skeletons' },
        ['Ogrefly']                     = { Name='Ogrefly', Ecosystem='vermin', Family='flies' },
        ['Pit Antlion']                 = { Name='Pit Antlion', Ecosystem='vermin', Family='antlions' },
        ['Sand Lizard']                 = { Name='Sand Lizard', Ecosystem='lizards', Family='lizards' },
        ['Sargas']                      = { Name='Sargas', Ecosystem='vermin', Family='scorpions' },
        ['Sekhmet']                     = { Name='Sekhmet', Ecosystem='beasts', Family='coeurls' },
        ['Tiamat']                      = { Name='Tiamat', Ecosystem='dragons', Family='wyrms' },
        ['Tomb Mage']                   = { Name='Tomb Mage', Ecosystem='undead', Family='skeletons' },
        ['Tomb Warrior']                = { Name='Tomb Warrior', Ecosystem='undead', Family='skeletons' },
        ['Tracer Antlion']              = { Name='Tracer Antlion', Ecosystem='vermin', Family='antlions' },
        ['Tracker Antlion']             = { Name='Tracker Antlion', Ecosystem='vermin', Family='antlions' },
        ['Trench Antlion']              = { Name='Trench Antlion', Ecosystem='vermin', Family='antlions' },
        ['Tulwar Scorpion']             = { Name='Tulwar Scorpion', Ecosystem='vermin', Family='scorpions' },
        ['Will-o\'-the-Wykes']          = { Name='Will-o\'-the-Wykes', Ecosystem='arcana', Family='bombs' },
        ['Xolotl']                      = { Name='Xolotl', Ecosystem='undead', Family='corses' },
        ['Xolotl\'s Hound Warrior']     = { Name='Xolotl\'s Hound Warrior', Ecosystem='undead', Family='skeletons' },
        ['Xolotl\'s Sacrifice']         = { Name='Xolotl\'s Sacrifice', Ecosystem='undead', Family='skeletons' },
    },
};
