--Zone: Pso'Xja
--Zone ID: 9
return {
    Names = {
        ['Archaic Chest']           = { Name='Archaic Chest', Ecosystem='arcana', Family='mimics' },
        ['Avalanche']               = { Name='Avalanche', Ecosystem='arcana', Family='snolls' },
        ['Blubber Eyes']            = { Name='Blubber Eyes', Ecosystem='amorphs', Family='hecteyes' },
        ['Camazotz']                = { Name='Camazotz', Ecosystem='birds', Family='bats' },
        ['Cryptonberry Cutter']     = { Name='Cryptonberry Cutter', Ecosystem='beastmen', Family='tonberries' },
        ['Cryptonberry Harrier']    = { Name='Cryptonberry Harrier', Ecosystem='beastmen', Family='tonberries' },
        ['Cryptonberry Plaguer']    = { Name='Cryptonberry Plaguer', Ecosystem='beastmen', Family='tonberries' },
        ['Cryptonberry Stalker']    = { Name='Cryptonberry Stalker', Ecosystem='beastmen', Family='tonberries' },
        ['Dark Elemental']          = { Name='Dark Elemental', Ecosystem='elementals', Family='elementals' },
        ['Demonic Millstone']       = { Name='Demonic Millstone', Ecosystem='arcana', Family='magic pots' },
        ['Dire Bat']                = { Name='Dire Bat', Ecosystem='birds', Family='bats' },
        ['Diremite']                = { Name='Diremite', Ecosystem='vermin', Family='diremites' },
        ['Diremite Assaulter']      = { Name='Diremite Assaulter', Ecosystem='vermin', Family='diremites' },
        ['Diremite Dominator']      = { Name='Diremite Dominator', Ecosystem='vermin', Family='diremites' },
        ['Diremite Stalker']        = { Name='Diremite Stalker', Ecosystem='vermin', Family='diremites' },
        ['Frost Lizard']            = { Name='Frost Lizard', Ecosystem='lizards', Family='lizards' },
        ['Gargoyle']                = { Name='Gargoyle', Ecosystem='arcana', Family='dolls' },
        ['Gargoyle-Iota']           = { Name='Gargoyle-Iota', Ecosystem='arcana', Family='dolls' },
        ['Gargoyle-Kappa']          = { Name='Gargoyle-Kappa', Ecosystem='arcana', Family='dolls' },
        ['Gargoyle-Lambda']         = { Name='Gargoyle-Lambda', Ecosystem='arcana', Family='dolls' },
        ['Gargoyle-Mu']             = { Name='Gargoyle-Mu', Ecosystem='arcana', Family='dolls' },
        ['Gazer']                   = { Name='Gazer', Ecosystem='amorphs', Family='hecteyes' },
        ['Goblin Alchemist']        = { Name='Goblin Alchemist', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Bandit']           = { Name='Goblin Bandit', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Bouncer']          = { Name='Goblin Bouncer', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Enchanter']        = { Name='Goblin Enchanter', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Hunter']           = { Name='Goblin Hunter', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Jeweler']          = { Name='Goblin Jeweler', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Mercenary']        = { Name='Goblin Mercenary', Ecosystem='beastmen', Family='goblins' },
        ['Goblin Veterinarian']     = { Name='Goblin Veterinarian', Ecosystem='beastmen', Family='goblins' },
        ['Goblin\'s Bat']           = { Name='Goblin\'s Bat', Ecosystem='birds', Family='bats' },
        ['Golden-Tongued Culberry'] = { Name='Golden-Tongued Culberry', Ecosystem='beastmen', Family='tonberries' },
        ['Gyre-Carlin']             = { Name='Gyre-Carlin', Ecosystem='vermin', Family='diremites' },
        ['Ice Elemental']           = { Name='Ice Elemental', Ecosystem='elementals', Family='elementals' },
        ['Labyrinth Lizard']        = { Name='Labyrinth Lizard', Ecosystem='lizards', Family='lizards' },
        ['Magic Millstone']         = { Name='Magic Millstone', Ecosystem='arcana', Family='magic pots' },
        ['Maledict Millstone']      = { Name='Maledict Millstone', Ecosystem='arcana', Family='magic pots' },
        ['Maze Lizard']             = { Name='Maze Lizard', Ecosystem='lizards', Family='lizards' },
        ['Million Eyes']            = { Name='Million Eyes', Ecosystem='amorphs', Family='hecteyes' },
        ['Morozko']                 = { Name='Morozko', Ecosystem='arcana', Family='snolls' },
        ['Nunyunuwi']               = { Name='Nunyunuwi', Ecosystem='arcana', Family='golems' },
        ['Purgatory Bat']           = { Name='Purgatory Bat', Ecosystem='birds', Family='bats' },
        ['Snoll']                   = { Name='Snoll', Ecosystem='arcana', Family='snolls' },
        ['Snow Lizard']             = { Name='Snow Lizard', Ecosystem='lizards', Family='lizards' },
        ['Snowball']                = { Name='Snowball', Ecosystem='arcana', Family='snolls' },
        ['Thousand Eyes']           = { Name='Thousand Eyes', Ecosystem='amorphs', Family='hecteyes' },
        ['Tonberry\'s Elemental']   = { Name='Tonberry\'s Elemental', Ecosystem='elementals', Family='elementals' },
        ['Treasure Chest']          = { Name='Treasure Chest', Ecosystem='arcana', Family='mimics' },
        ['Vampire Bat']             = { Name='Vampire Bat', Ecosystem='birds', Family='bats' },
    },
};
