--Zone: Pso'Xja
--Zone ID: 9
return {
    Names = {
        ['Archaic Chest'] = { Name='Archaic Chest', 
        ['Avalanche'] = { Name='Avalanche', 
        ['Blubber Eyes'] = { Name='Blubber Eyes', 
        ['Camazotz'] = { Name='Camazotz', 
        ['Cryptonberry Cutter'] = { Name='Cryptonberry Cutter', 
        ['Cryptonberry Harrier'] = { Name='Cryptonberry Harrier', 
        ['Cryptonberry Plaguer'] = { Name='Cryptonberry Plaguer', 
        ['Cryptonberry Stalker'] = { Name='Cryptonberry Stalker', 
        ['Dark Elemental'] = { Name='Dark Elemental', 
        ['Demonic Millstone'] = { Name='Demonic Millstone', 
        ['Dire Bat'] = { Name='Dire Bat', 
        ['Diremite'] = { Name='Diremite', 
        ['Diremite Assaulter'] = { Name='Diremite Assaulter', 
        ['Diremite Dominator'] = { Name='Diremite Dominator', 
        ['Diremite Stalker'] = { Name='Diremite Stalker', 
        ['Frost Lizard'] = { Name='Frost Lizard', 
        ['Gargoyle'] = { Name='Gargoyle', 
        ['Gargoyle-Iota'] = { Name='Gargoyle-Iota', 
        ['Gargoyle-Kappa'] = { Name='Gargoyle-Kappa', 
        ['Gargoyle-Lambda'] = { Name='Gargoyle-Lambda', 
        ['Gargoyle-Mu'] = { Name='Gargoyle-Mu', 
        ['Gazer'] = { Name='Gazer', 
        ['Goblin Alchemist'] = { Name='Goblin Alchemist', 
        ['Goblin Bandit'] = { Name='Goblin Bandit', 
        ['Goblin Bouncer'] = { Name='Goblin Bouncer', 
        ['Goblin Enchanter'] = { Name='Goblin Enchanter', 
        ['Goblin Hunter'] = { Name='Goblin Hunter', 
        ['Goblin Jeweler'] = { Name='Goblin Jeweler', 
        ['Goblin Mercenary'] = { Name='Goblin Mercenary', 
        ['Goblin Veterinarian'] = { Name='Goblin Veterinarian', 
        ['Goblin\'s Bat'] = { Name='Goblin\'s Bat', 
        ['Golden-Tongued Culberry'] = { Name='Golden-Tongued Culberry', 
        ['Gyre-Carlin'] = { Name='Gyre-Carlin', 
        ['Ice Elemental'] = { Name='Ice Elemental', 
        ['Labyrinth Lizard'] = { Name='Labyrinth Lizard', 
        ['Magic Millstone'] = { Name='Magic Millstone', 
        ['Maledict Millstone'] = { Name='Maledict Millstone', 
        ['Maze Lizard'] = { Name='Maze Lizard', 
        ['Million Eyes'] = { Name='Million Eyes', 
        ['Morozko'] = { Name='Morozko', 
        ['Nunyunuwi'] = { Name='Nunyunuwi', 
        ['Purgatory Bat'] = { Name='Purgatory Bat', 
        ['Snoll'] = { Name='Snoll', 
        ['Snow Lizard'] = { Name='Snow Lizard', 
        ['Snowball'] = { Name='Snowball', 
        ['Thousand Eyes'] = { Name='Thousand Eyes', 
        ['Tonberry\'s Elemental'] = { Name='Tonberry\'s Elemental', 
        ['Treasure Chest'] = { Name='Treasure Chest', 
        ['Vampire Bat'] = { Name='Vampire Bat', 
    },
};
