gVars.Monster_geneology = {
    ['amorphs'] = {
        { ['Family'] = 'botuli',
          ['Monsters'] = { 'botulus rex' }.
        },
        { ['Family'] = 'flans',
          ['Monsters'] = { 'anise custard','black pudding','caraway custard','cinnamon custard',
            'cumin custard','dextrose','ebony pudding','empathic flan','fighting flan','flammeri',
            'flux flan','ginger custard','immortal flan','mint custard','nutmeg custard',
            'princess pudding','two-faced flan','vanilla custard' },
        },
        { ['Family'] = 'hecteyes',
          ['Monsters'] = { 'argus','blubber eyes','gazer','hecteyes','million eyes','mindgazer',
            'muddyeyes','rancideyes','shoggoth','taisaijin','thousand eyes','vanguard hecteyes' },
        },
        { ['Family'] = 'leeches',
          ['Monsters'] = { 'acrophies','anautogenous slug','angler leech','arrapago leech','big leech',
            'bloodpool vorax','bloodsucker','bouncing ball','caedarva leech','carrion leech',
            'cetic parasite','chocoboleech','forest leech','horrid fluke','huge leech','kissing leech',
            'lamprey lord','leech','leech king','nergal','nightmare leech','nirgali','phlebotomic slug',
            'poison leech','red kisser','red osculator','red smoocher','swamp leech','thread leech',
            'undead leech','volcanic leech' },
        },
        { ['Family'] = 'slimes',
          ['Monsters'] = { 'amoebic nodule','bavarois','blobdingnag','brei','caedarva marshscum',
            'caedarva pondscum','carrion slime','cave mold','chimera clot','claret','clot','coastal slime',
            'downslime','enhanced jelly','enhanced slime','freshwater trepang','ghost clot','globster',
            'gloop','globster','maltha','mamook mush','metalloid amoeba','mountain clot','mousse','mucoid mass',
            'muddy slime','ogreish risotto','oil slick','ooze','oil spill','orichalcumshell','protozoan',
            'pudding master','septic boil','sewer syrup','slime mold','sponge','talacca clot','undead slime',
            'vanguard slime','viscous clot','water pumpkin','winter slime','woodnix\'s slime','zazalda clot' },
        },
        { ['Family'] = 'worms',
          ['Monsters'] =  { 'bedrock barry','boreal worm','carrion worm','eikon worm','flesh eater',
            'glacial eater','ground guzzler','hugemaw harold','leujaoam worm','mineral eater',
            'mold eater','mountain worm','nightmare worm','rock eater','sallow seymour','sand worm',
            'slime eater','stone eater','tunnel worm','ziryu' },
        },
    },
    ['aquans'] = {
        { ['Family'] = 'crabs',
          ['Monsters'] = { 'adamantshell','aquarius','arrapago crab','aydeewa crab','bigclaw','blind crab',
            'bloody coffin','blue bascinet','bubbly bernie','cargo crab colin','carrion crab','clipper',
            'coral crab','crimson knight crab','cutter','cyan deep crab','despotic decapod',
            'duke decapod','dweomershell','emperor arthro','ferrocrab','ghost crab','giant pugil',
            'glacial crab','greatclaw','grindylow','gugru crab','heike crab','ice crab','ironshell','kelp crab',
            'king arthro','knight crab','krabkatoa','land crab','limicoline crab','locust ghost crab',
            'mamook crab','metal shears','mole crab','mud crab','mugger crab','nightmare crab',
            'nightmare kraken','nipper','palm crab','passage crab','petrocrab','river crab','robber crab',
            'rock crab','sand crab','savanna crab','sicklemoon crab','snapper','snipper','stag crab',
            'stone crab','submarinenipper','sunderclaw','tegmine','thickshell','tree crab','triangle crab',
            'undead crab','vermivorous crab','wake warder wanda','wootzshell' },
        },
        { ['Family'] = 'orobons',
          ['Monsters'] = { 'angler orobon','giant orobon','gugru orobon','northern piranu','nuhn','ornery oroban',
            'orobon','southern piranu' },
        },
        { ['Family'] = 'pterakos',
          ['Monsters'] = { 'bismarck' }
        },
        { ['Family'] = 'pugils',
          ['Monsters'] = { 'abhac','abyssal pugil','aipaloovik','apsaras','azoth apsaras','beach pugil',
            'big jaw','bigmouth billy','buburimboo','capricornus','cave pugil','cheval pugil','cyan deep pugil',
            'demonic pugil','enhanced makara','fatty pugil','ferocious pugil','fighting pugil','fosse pugil',
            'giant pugil','greater pugil','gugru jagil','hippomaritimus','island jagil','jagil','lancet jagil',
            'land pugil','kelp pugil','ketos','land pugil','makara','mercurial makara','mud pugil',
            'nightmare makara','ocean jagil','ocean kraken','percipient fish','piriqia pugil',
            'primordial pugil','puffer pugil','pug pugil','pugil','quagmire pugil','razorjaw pugil',
            'river crab','sand pugil','serra','shoal pugil','sicklemoon jagil','spinous pugil','spring pugil',
            'stygian pugil','suhur mas','sulphuric jagil','swamfisk','swamp pugil','terror pugil',
            'thalassic pugil','vepar','zazalda jagil','ziphius' },
        },
        { ['Family'] = 'sea monks',
          ['Monsters'] = { 'beach monk','blanched kraken','bathybic kulshedra','charybdis','colossal calamari',
            'devil manta','kelp kulshedra','kraken','kulshedra','lahama','lord of onzoso','lost scolopendra',
            'morgawr','nostokulshedra','peg powler','proteus','scolopendra','tieholtsodi','vu-murt',
            'yacumama' },
        },
        { ['Family'] = 'toads',
          ['Monsters'] = { 'caedarva toad','chorus toad','mikilulu','toad','undead toad','wartkin' },
        },
        { ['Family'] = 'urganites',
          ['Monsters'] = { 'bladmall','coastal urgnite','cyclopean conch','harajnite','nepionic bladmall',
            'nepionic parata','nightmare uragnite','parata','shankha','shen','uragnite','zoredonite' },
        },
    },
    ['arcana'] = {
        { ['Family'] = 'acroliths',
          ['Monsters'] = { 'acrolith','boompadu','earth mover','koghatu','mechanical menace','wulgaru' },
        },
        { ['Family'] = 'bombs',
          ['Monsters'] = { 'aerial torpedo','ancient bomb','balloon','bifrons','big bomb','bomb','bomb king',
            'enna-enna','forger','fox fire','friar rush','friar\'s lantern','glide bomb','grand grenade',
            'grenade','ignis fatuus','mad bomber','reaction','shrapnel','spunkie','teine sith','volcanic bomb',
            'vulcanian bomb','will-o\'-the-wisp','will-o\'-the-wykes' },
        },
        { ['Family'] = 'clusters',
          ['Monsters'] = { 'atomic cluster','bombshells','cluster','incendiary bombs','nightmare cluster',
            'nitro cluster','odqan','razon','sweeping cluster','unstable cluster','volatile cluster',
            'yal-un eke' },
        },
        { ['Family'] = 'evil weapons',
          ['Monsters'] = { 'barbaric weapon','boggart','cursed weapon','eldritch edge','evil armoury',
            'evil weapon','flying spear','juggler hecatomb','killing weapon','nightmare weapon',
            'nocuous weapon','omnimous weapon','prankster maverix','temenos weapon','trickster kinetix' },
        },
        { ['Family'] = 'dolls',
          ['Monsters'] = { 'apollyon sweeper','calcabrina','gargoyle','gargoyle-iota','gargoyle-kappa',
            'gargoyle-lambda','gargoyle-mu','living statue' },
        },
        { ['Family'] = 'golems',
          ['Monsters'] = { 'gargantua','largantua','lost suttang','nunyunuwi','stone golem','suttang' },
        },
        { ['Family'] = 'grimoire',
          ['Monsters'] = { 'rw nw prt m hrw' },
        },
        { ['Family'] = 'khimairas',
          ['Monsters'] = { 'khimaira','khimaira 13','khimaira 14x','nemean lion','shedu','tyger' },
        },
        { ['Family'] = 'magic pots',
          ['Monsters'] = { 'apollyon cleaner','demonic millstone','hovering hotpot','magic flagon',
            'magic millstone','maledict millstone','nightmare vase','temenos cleaner' },
        },
        { ['Family'] = 'mammets',
          ['Monsters'] = { 'mammet master','mammet-19 epsilon','mammet-800','mammet-9999' },
        },
        { ['Family'] = 'mimics',
          ['Monsters'] = { 'archaic chest','armoury crate','cursed chest','mimic','treasure chest' },
        },
        { ['Family'] = 'snolls',
          ['Monsters']  = { 'agloolik','akselloak','avalanche','father frost','frost flambeau',
            'morozko','nightmare snoll','snoll','snoll tzar','snow devil','snowball','snow maiden' },
        },
        { ['Family'] = 'spheroids',
          ['Monsters'] = { 'gunpod','warder agliaia','warder euphrosyne','warder thalia' },
        },
    },
    ['archaia'] = {
      { ['Family'] = 'chariots',
        ['Monsters'] = { 'archaic chariot','armored chariot','battleclad chariot','battledressed chariot',
          'long-bowed chariot','long-armed chariot','long-gunned chariot','long-horned chariot','racing chariot',
          'shielded chariot' },
      },
      { ['Family'] = 'gears',
        ['Monsters'] = { 'archaic gear','archaic gears','armed gears','gyroscopic gear','gyroscopic gears',
          'imperial gear','imperial gears' },
      },
      { ['Family'] = 'ramparts',
        ['Monsters'] = { 'archaic rampart','dormant rampart','first rampart','fourth rampart',
          'reactionary rampart','second rampart','third rampart' },
      },
    },
    ['archaic machines'] = {
    },
    ['beastmen'] = {
        { ['Family'] = 'antica',
          ['Monsters'] = { 'antican auxiliarius','antican centurio','antican decurio','antican faber',
            'antican funditor','antican sagittarius','antican speculator','antican veles',
            'centurio xii-i','centurio xiii-v','contantican black mage','contantican paladin',
            'contantican ranger','contantican warrior','decurio i-iii','decurio xiii-lv',
            'hastatus xiii-cxxviii','hastatus xiii-lxxv','hastatus xiii-xcvi','hastatus xiii-xxv',
            'praetorian guard cccxi','praetorian guard ccxx','praetorian guard cxlviii',
            'praetorian guard lxxiii','princeps xiii-lxxxix','sagittarius xiii-xxvi','triarius xiii-lix' },
        },
        { ['Family'] = 'bugbears',
          ['Monsters'] = { 'bugallug','bugbby','bugbear bondman','bugboy','bugbear deathsman',
            'bugbear matman','bugbear muscleman','bugbear porterman','bugbear servingman',
            'bugbear strongman','bugbear trashman','bugbear watchman' },
        },
        { ['Family'] = 'gigas',
          ['Monsters'] = { 'antaeus','arch antaeus','beli','blizzard gigas','chronos','cold gigas',
            'frost gigas','gigas beastmaster','gigas black mage','gigas braver','gigas brawler','gigas catapulter',
            'gigas clearcutter','gigas crusher','gigas fighter','gigas hillrazer','gigas martialist','gigas monk',
            'gigas overseer','gigas ranger','gigas slinger','gigas warrior','gigas warwolf','gigaswrestler',
            'graupel gigas','gration','hail gigas','humbaba','hyperion','kari','kumbaba','okeanos','rime gigas',
            'skadi','sleet gigas','snow gigas','thrym' },
        },
        { ['Family'] = 'goblins',
          ['Monsters']  = { 'alraune','chekochuk','chuglix berrypaws','dread dealing dredodak',
            'gambilox wanderling','goblin alchemist','goblin ambusher','goblin archeologist',
            'goblin bandit','goblin boss','goblin bouncer','goblin bounty hunter','goblin butcher',
            'goblin collector','goblin craftsman','goblin digger','goblin doctor','goblin doorman',
            'goblin duelist','goblin enchanter','goblin fencer','goblin fireman','goblin fisher',
            'goblin foreman','goblin freelance','goblin furrier','goblin gambler','goblin gaoler',
            'goblin guide','goblin gutterman','goblin hammerman','goblin hangman','goblin headman',
            'goblin hunter','goblin jeweler','goblin junkman','goblin lansquenet','goblin leecher',
            'goblin leadman','goblin lengthman','goblin marksman','goblin mercenary','goblin mugger',
            'goblin oilman','goblin packman','goblin pathfinder','goblin pirate','goblin poacher',
            'goblin preceptor','goblin professor','goblin reaper','goblin robber','goblin shaman',
            'goblin shepherd','goblin shovelman','goblin slaughterman','goblin smithy','goblin swindler',
            'goblin swordmaker','goblin swordsman','goblin thespian','goblin theurgist','goblin thug',
            'goblin tinkerer','goblin tollman','goblin trader','goblin veterinarian','goblin warlord',
            'goblin weaver','goblin wolfman','gosspix blabberlips','hobgoblin animalier',
            'hobgoblin beastmaster','hobgoblin black mage','hobgoblin dark knight','hobgoblin fascinator',
            'hobgoblin martialist','hobgoblin ranger','hobgoblin red mage','hobgoblin thief',
            'hobgoblin venerer','hobgoblin warrior','hobgoblin white mage','shamblix rottenheart',
            'swashstox beadblinker','sword sorcerer solisq','vanguard alchemist','vanguard ambusher',
            'vanguard armorer','vanguard dragontamer','vanguard enchanter','vanguard hitman',
            'vanguard maestro','vanguard necromancer','vanguard pathfinder','vanguard pitfighter',
            'vanguard ronin','vanguard shaman','vanguard smithy','vanguard tinkerer','vanguard welldigger',
            'vegnix greenthumb','woodnix shrillwhistle' },
        },
        { ['Family'] = 'lamiae',
          ['Monsters'] = { 'assassin\'s apprentice','chigoe breeder','d5j2-merrow','d5r3-merrow','d5s1-merrow',
            'euryale','experimental lamia','k22b6-lamia','k22h3-lamia','k22p2-lamia','k23h1-lamia',
            'lamia bellydancer','lamia bower','lamia chaukidar','lamia comandress','lamia dancer',
            'lamia dartist','lamia deathdancer','lamia exon','lamia fatedealer','lamia freebooter',
            'lamia graverobber','lamia idolater','lamia immolater','lamia jaeger','lamia necromancer',
            'lamia no.11','lamia no.13','lamia no.14','lamia no.15','lamia no.17','lamia no.18',
            'lamia no.19','lamia no.2','lamia no.21','lamia no.24','lamia no.27','lamia no.3','lamia no.34',
            'lamia No.4','lamia no.9','lamia palace guard','lamia prospector','lamia rover','lamia sharper',
            'lamia toxophilite','lamie no.7','lamie no.8','lamie bellydancer','lamie deathdancer',
            'lamie necromancer','lamie toxophilite','llamhigyn y dwr','medusa','merrow bladedancer',
            'merrow cantatrice','merrow chantress','merrow icedancer','merrow kabukidancer','merrow no.5',
            'merrow no.11','merrow no.12','merrow no.16','merrow seafarer','merrow shadowdancer',
            'merrow shiranuhi','merrow songstress','merrow typhoondancer','merrow wavedancer',
            'nix bladedancer','nix songstress','nix typhoondancer','nix wavedancer' },
        },
        { ['Family'] = 'mamool ja',
          ['Monsters'] = { 'blacktattoo vedool ja','bluethunder kaqool ja','darting kachaal ja',
            'decimator mabel ja','divout radol ja','dragonscaled bugaal ja','eidolic qufeel ja',
            'firedance magmaal ja','fleetfingered mobel ja','forbidding koheel ja','goton zha the redolent',
            'gulool ja ja','hundredfaced hapool ja','lancelord gaheel ja','molted mamool ja','mamool ja',
            'mamool ja bloodsucker','mamool ja blusterer','mamool ja bounder','mamool ja breeder',
            'mamool ja cataphract','mamool ja chamberlain','mamool ja conservator','mamool ja diver',
            'mamool ja entrancer','mamool ja executioner','mamool ja farrier','mamool ja fetial',
            'mamool ja flamerearer','mamool ja frogman','mamool ja handler','mamool ja hospitaler',
            'mamool ja hussar','mamool ja infiltrator','mamool ja isangoma','mamool ja lurker',
            'mamool ja mahout','mamool ja mimer','mamool ja mimicker','mamool ja palatine',
            'mamool ja philosopher','mamool ja pikeman','mamool ja polemicist','mamool ja profligate',
            'mamool ja ravager','mamool ja recruit','mamool ja sapper','mamool ja savant','mamool ja sophist',
            'mamool ja spearman','mamool ja spotter','mamool ja stabler','mamool ja strapper',
            'mamool ja trainer','mamool ja treasurer','mamool ja unseen','mamool ja warder',
            'mamool ja zenist','panurgic ryubool ja','percipient zoraal ja','sagelord molaal ja',
            'sagelord zolool ja','scalding fafool ja','searing vogaal ja','shadowhand kajeel ja',
            'strifelord bakool ja','thunderbolt piraal ja','thunderclap sareel ja',
            'vigilant kubool ja','whitetattoo rahool ja' },
        },
        { ['Family'] = 'moblins',
          ['Monsters'] = { 'book browser bokabraq','chemical cook chemachiq','grimoire guru grimogek',
            'martial maestro megomak','moblin aidman','moblin ashman','moblin billionaire','moblin chapman',
            'moblin clergyman','moblin coalman','moblin draftsman','moblin dustman','moblin engineman',
            'moblin fantocciniman','moblin gasman','moblin groundman','moblin gurneyman','moblin millionaire',
            'mythril mouth monamaq','moblin pickman','moblin pikeman','moblin ragman','moblin repairman',
            'moblin roadman','moblin rodman','moblin scapelman','moblin tankman','moblin wisewoman',
            'moblin witchman','moblin workman','moblin yardman','movamuq','spell spitter spilospok',
            'swipostik','trikotrak','twilotak' },
        },
        { ['Family'] = 'orcs',
          ['Monsters'] = { 'abyssdweller jhabdebb','blackbone frazdiz','bullheaded grosvez',
            'carnagechief jackbodokk','elvaansticker bxafraff','flamecaller zoeqdoq','grognard footsoldier',
            'grognard grappler','grognard impaler','grognard mesmerizer','grognard neckchopper',
            'grognard predator','hamfist gukhbuk','halforc black mage','halforc dark knight','halforc dragoon',
            'halforc monk','halforc paladin','halforc ranger','halforc warrior','kingslayer doggvdegg',
            'lyncean juwgneg','marauder dvogzog','meteormauler zhagtegg','orcish beastrider',
            'orcish bowshooter','orcish brawler','orcish chasseur','occish colonel','orcish cursemaker',
            'orcish fighter','orcish fodder','orchish footsoldier','orcish gladiator','orcish grappler',
            'orcish grunt','orcish impaler','orcish mesmerizer','orgcish neckchopper','orcish nightraider',
            'orcish serjeant','orcish stonechucker','orcish stonelauncher','orcish trooper',
            'rainbringer yjatvot','splinterspine grukjuk','supplespine mujwuj','vanguard amputator',
            'vanguard backstabber','vanguard bugler','vanguard dollmaster','vanguard footsoldier',
            'vanguard grappler','vanguard gutslasher','vanguard hawker','vanguard impaler',
            'vanguard mesmerizer','vanguard neckchopper','vanguard pillager','vanguard predator',
            'vanguard trooper','vanguard vexer' },
        },
        { ['Family'] = 'poroggos',
          ['Monsters'] = { 'brekekekex','don poroggo','eriri samariri','iriri samariri','oriri samariri',
            'uriri samariri','poroggo','poroggo casanova','poroggo charmer','poroggo gent',
            'poroggo madame' },
        },
        {
          ['Family'] = 'qiqirn',
          ['Monsters'] = { 'bluestreak gyugyuroon','cheese hoarder gigiroon','cookieduster lipiroon',
            'gem heister roorooroom','qiqirn archaeologist','qiqirn astrologer','qiqirn ceramist',
            'qiqirn diamantaire','qiqirn eggler','qiqirn enterpriser','qiqirn freelance','qiqirn goldsmith',
            'qiqirn huckster','qiqirn lieuter','qiqirn mercenary','qiqirn mine','qiqirn mireguide',
            'qiqirn miner','qiqirn mosstrooper','qiqirn pecheur','qiqirn poulterer','qiqirn rock hound',
            'qiqirn trailer','qiqirn treasure hunter','qiqirn bolcanist','quick draw sasarroon',
            'stealth bomber gagaroon' },
        },
        { ['Family'] = 'quadavs',
          ['Monsters'] = { 'amber quadav','amethyst quadav','bo\'who warmonger','brass quadav',
            'bronze quadav','cobalt quadav','copper quadav','fossil quadav','garnet quadav',
            'gi\'bhe fleshfeaster','greater quadav','ji\'gho ageless','heliodor quadav','leadd quadav',
            'lightsteel quadav','metaquadav black mage','metaquadav dark knight','metaquadav paladin',
            'metaquadav red mage','metaquadav thief','metaquadav warrior','metaquadav white mage',
            'na\'qba chirurgeon','ni\'zho bladebender','old quadav','onyx quadav','orichalcum quadav',
            'qu\'pho bloodspiller','sapphire quadav','silver quadav','star ruby quadav',
            'star sapphire quadav','te\'zha ironclad','va\'rhu bodysnatcher','vanguard beasttender',
            'vanguard constable','vanguard defender','vanguard drakekeeper','vanguard hatamoto',
            'vanguard kusa','vanguard mason','vanguard militant','vanguard minstrel','vanguard protector',
            'vanguard purloiner','vanguard thaumaturge','vanguard undertaker','vanguard vigilante',
            'vanguard vindicator','veteran quadav','whitegold quadav','wootz quadav','young quadav',
            'zircon quadav' },
        },
        { ['Family'] = 'sahagin',
          ['Monsters'] = { 'houu the shoalwader','telchines bard','telchines dragoon','telchines monk',
            'telchines white mage' },
        },
        { ['Family'] = 'tonberries',
          ['Monsters'] = { 'cryptonberry abductor','cryptonberry assassin','cryptonberry charmer',
            'cryptonberry cutter','cryptonberry designator','cryptonberry executor','cryptonberry harrier',
            'cryptonberry plaguer','cryptonberry skulker','cryptonberry stalker','golden-tongued culberry',
            'murk-veined baneberry' },
        },
        { ['Family'] = 'trolls',
          ['Monsters'] = { 'broken troll soldier','chiliarch gordarvor','dartorgor the austere',
            'dorgerwor the astute','fahrafahr the bloodied','farlarder the shrewd','garfurlar the rabid',
            'garharlor the unruly','garhorlur the brutal','girzorhor the imprudent','gurfurlur the menacing',
            'hetairoi vuryargur','hetairoi zarwarkur','hilltroll dark knight','hilltroll elite guard',
            'hilltroll mirror guard','hilltroll monk','hilltroll paladin','hilltroll ranger',
            'hilltroll red mage','hilltroll warrior','jorporbor the hellraker','khromasoul bhurborlor',
            'kirlirger the abhorrent','old troll','surmerdar the unbridled','troll artilleryman','troll cameist',
            'troll cannoneer','troll combantant','troll cuirasser','troll destroyer','troll engraver',
            'troll forager','troll gemologist','troll grenadier','troll hammersmith','troll hoplite',
            'troll ironworker','troll lapidarist','troll machinist','troll mythril guard','troll paviser',
            'troll pezhetairoi','troll sabreur','troll scrimer','troll shieldbearer','troll smelter',
            'troll speculator','troll stoneworker','troll stormer','troll surveillant','troll targeteer',
            'troll velites','vorjirzur the valiant','vorporlor the barbaric','vyurvarjur the nimble',
            'woodland dark knight','woodland monk','woodland ranger','woodland warrior',
            'wordorbor the artificer','woodtroll elite guard','woodtroll mirror guard',
            'xarhorkur the claviger','zurmurwur the ruthless' },
        },
        { ['Family'] = 'yagudo',
          ['Monsters'] = { 'baa dava the bibliophage','coo keja the unseen','dee wapa the desolator',
            'doo peku the fleetfoot','gessho','koo buzu the theomanic','koo rahi the levinblade',
            'naa zeku the unwaiting','patripatan','pee qoho the python','ree nata the melomanic',
            'theoyagudo bard','theoyagudo black mage','theoyagado monk','theoyagado ninja',
            'theoyagado samurai','theoyagado summoner','theoyagado white mage','vanguard assassin',
            'vanguard chanter','vanguard exemplar','vanguard inciter','vanguard liberator',
            'vanguard ogresoother','vanguard oracle','vanguard partisan','vanguard persecutor',
            'vanguard prelate','vanguard priest','vanguard salvager','vanguard sentinel',
            'vanguard skirmisher','vanguard visionary','yagudo acolyte','yagudo archpriest',
            'yagudo condottiere','yagudo disciplinant','yagudo eradicator','yagado follower',
            'yagado initiate','yagudo kapellmeister','yagudo knight templar','yagado mendicant',
            'yagado missionary','yagado persecutor','yagudo prelatess','yagado piper','yagado priest',
            'yagado scribe','yagado theologist','yagado votary'},
        },
    },
    ['beasts'] = {
        { ['Family'] = 'behemoths',
          ['Monsters'] = { 'behemoth','kaiser behemoth','kronprinz behemoth' },
        },
        { ['Family'] = 'buffaloes',
          ['Monsters'] = { 'apis','bonnacon','buffalo','camahueto','geush urvan','giant buffalo',
            'icefallo','king buffalo','meadow buffalo','mountain buffalo','snofallo' },
        },
        { ['Family'] = 'cerberuses',
          ['Monsters'] = { 'black shuck','cerberus','gere','sarama','sarameya' },
        },
        { ['Family'] = 'coeurls',
          ['Monsters'] = { 'attohwa coeurl','boreal coeurl','chesma','coeurl','master coeurl','ose',
            'patripatan','puma','rime lynx','sekhmet','torama' },
        },
        { ['Family'] = 'dhalmels',
          ['Monsters'] = { 'allocamelus','bull dhalmel','cape dhalmels','catoblepas','desert dhalmel',
            'locust camelopard','marine dhalmel','nandi','nightmare dhalmel','scorch dhalmel',
            'serpopard ishtar','serpopard ninlil','troglodyte dhalmel','wild dhalmel' },
        },
        { ['Family'] = 'manticores',
          ['Monsters'] = { 'criosphinx','frostmane','glazemane','greater manticore','hieracosphinx',
            'lesser manticore','manticore','narasimha','nightmare manticore','satyral' },
        },
        { ['Family'] = 'marids',
          ['monsters'] = { 'grand marid','iriz ima','mahishasura','marid','mahishasura','rogue marid' },
        },
        { ['Family'] = 'opo-opos',
          ['Monsters'] = { 'arboricole opo-opo','coastal opo-opo','edacious opo-opo','kerkopes',
            'mischievous micholas' },
        },
        { ['Family'] = 'rabbits',
          ['Monsters'] = { 'beach bunny','bearclaw leveret','bearclaw rabbit','black coney','bog bunny',
            'canyon rarab','coney','cape coney','forest hare','goblin\'s rabbit','goblin\'s rarab',
            'gougetooth ganzaga','island rarab','jaggedy-eared jack','locus bight rarab','mighty rarab',
            'nightmare bunny','plateau hare','polar hare','sand hare','savanna rarab','sharp-eared ropipi',
            'shikaree x\'s rabbit','skyader','steppe hare','teporingo','tropical rarab','unut',
            'variable hare','void hare','white coney','wild rabbit' },
        },
        { ['Family'] = 'rams',
          ['Monsters'] = { 'battering ram','bloodtear baldurf','flockbock','ironhorn baldurno',
            'lumbering lambert','mosshorn','rambukk','rampaging ram','steelfleece baldarich','tammuz',
            'tavnasian ram','tremor ram','zlatorog' },
        },
        { ['Family'] = 'sheep',
          ['Monsters'] = { 'amaltheia','brutal sheep','carnelo','gigas\'s sheep','mad sheep',
            'nightmare sheep','ornery sheep','padfoot','peallaidh','prickly sheep','raging sheep',
            'rambukk','slumbering samwell','stray mary','tavnasian sheep','thunderhead','wild karakul',
            'wild sheep' },
        },
        { ['Family'] = 'tigers',
          ['Monsters'] = { 'badshah','boreal tiger','byakko','cave tiger','dawon','enhanced koenigstiger',
            'enhanced tiger','forest tiger','gigas\'s tiger','goblin\'s tiger','kirata','koenigstiger',
            'nightmare tiger','nue','plumbago','sabertooth tiger','skirling liger','sturmtiger','tempest tigon',
            'tundra tiger','uleguerand tiger','wajaom tiger' },
        },
    },
    ['birds'] = {
        { ['Family'] = 'apkallu',,
          ['Monsters'] = { 'almighty apkallu','apkallu','arrapago apkallu','ashakku','chary apkallu',
            'emperor apkallu','isarukitsck','king apkallu','lil\' apkallu','little wingman','zhayolm apkallu' },
        },
        { ['Family'] = 'bat trios',
          ['Monsters']  = { 'black triple stars','bulldog bats','canal bats','dark bats','ding bats',
            'fomor\'s bats','gale bats','greater gaylas','incubus bats','midnight wings','night bats',
            'nightmare bats','nightmare gaylas','nosferatu bats','plague bats','sand bats','succubus bats',
            'tres duendes','volcanic bats','wingrats' },
        },
        { ['Family'] = 'bats',
          ['Monsters'] = { 'acro bat','ba','barbastelle','black bat','camazotz','desmodont','dire bat',
            'dust bat','esbat','fledermaus','giant bat','goblin\'s bat','golden bat','hell bat','lost strings',
            'moon bat','mouse bat','naraka bat','night bats','nightmare stirge','old two-wings','poison bat',
            'purgatory bat','specter bat','star bat','stirge','strings','tiyanak','upyri','vampire bat',
            'wraith bat' },
        },
        { ['Family'] = 'birds',
          ['Monsters'] = { 'abyssdiver','akbaba','arboricole raven','carrion crow','cornu',
            'enhanced akbaba','enhanced vulture','eyegouger','habrok','helldiver','jubjub','marsh murre',
            'nightmare raven','nihniknoovi','nunyenunc','raven','ravin raven','riverne vulture','screamer',
            'seaboard vulture','sirin','slough skua','stolas','suparna','suparna fledgling',
            'toco toucan','tococo','toucan','tragopan','vanguard crow','vulture','zagh','zu' },
        },
        { ['Family'] = 'cockatrices',
          ['Monsters'] = { 'attack ziz','axe beak','chonchon','kaneakeluh','killer jonny','molted ziz',
            'pelican','sand cockatrice','sewer sam','waraxe beak','zebra zachary','ziz','zizzy zillah' },
        },
        { ['Family'] = 'colibris',
          ['Monsters'] = { 'chamrosh','colibri','kubool ja\'s mhuufya','lesser colibri','locus colibri',
            'mocking colibri','predatory colibri','yalunger','zoraal ja\'s pkuucha' },
        },
        { ['Family'] = 'hippogryphs',
          ['Monsters'] = { 'boroka','cloud hippogryph','guard hippogryph','heliodromos',
            'hippogryph','imdugud','nightmare hippogryph','strato hippogryph','watch hippogryph' },
        },
        { ['Family'] = 'rocs',
          ['Monsters'] = { 'abraxas','bialozar','diatryma','Gullinkambi','kreutzet','lesser roc',
            'nightmare roc','nimbus hippogryph','okyupete','peryton','roc','ruinous rocs','simurgh',
            'strix','suzaku','thiazi','vedrfolnir','yatagarasu' }
        },
    },
    ['demons'] = {
        { ['Family'] = 'ahrimans',
          ['Monsters'] = { 'aeshma','apollyon ahriman','enhanced ahriman','bat eye','evil eye','fachen',
            'prototype eye','pyracmon','scowlenkos','shadow eye','vanguard eye' },
        },
        { ['Family'] = 'demons',
          ['Monsters'] = { 'abununnu','apollyon demon','dark esquire','deamon aristocrat','demon knight',
            'demon pawn','deamon warlock','demon wizard','dread demon','duke focalor','gloam servitor','gore demon',
            'judicator demon','kindred bard','kindred beastmaster','kindred black mage','kindred dark knight',
            'kindred dragoon','kindred monk','kindred ninja','kindred paladin','kindred ranger',
            'kindred red mage','kindred samurai','kindred summoner','kindred thief','kindred warrior',
            'kindred white mage','stygian demon' },
        },
        { ['Family'] = 'dvergrs',
          ['Monsters'] = { 'fjalar','king goldemar','pandemonium warden' },
        },
        { ['Family'] = 'gallus'
          ['Monsters'] = { 'ig-alima' },
        },
        { ['Family'] = 'imps',
          ['Monsters'] = { 'black baron','bukki','dark bugler','dark esquire','deadpan devilet',
            'dekka','devilet','elder\'s imp','gakke','heraldic imp','imp','imp bandsman','jakko',
            'mokka','mokke','mokku','orderly imp','seneschal imp', 'vanasarvik','verdelet','zikko' },
        },
        { ['Family'] = 'soulflayers',
          ['Monsters'] = { 'demented jalaawa','mahjlaef the paintorn','nepionic soulflayer','psycheflayer',
            'soulflayer','vile ineed','vile wahdaha','vile wahzil','vile yabeewa' },
        },
        { ['Family'] = 'tauri',
          ['Monsters']  = { 'apollyon taurus','bata','brontotaur','eldertaur','magnotaur','mahisha','minotaur',
            'mindertaur','molech','nightmare taurus','stegotaur','taurus','terataur','tyrannotaur' },
        },
    },
    ['dragons'] = {
        { ['Family'] = 'dragons',
          ['Monsters'] = { 'aitvaras','alkla','anantaboga','apocalyptic beast','arch apocalyptic beast',
            'ash dragon','barong','beist','biast','dahak','enhanced dragon','kulili','lost aitvaras','lost alkla',
            'lost barong','lost stihi','shadow dragon','stihi' },
        },
        { ['Family'] = 'hydras',
          ['Monsters'] = { 'hydra','illuyankas','orochi','thu\'ban','tinnin','zahak' },
        },
        { ['Family'] = 'puks',
          ['Monsters'] = { 'carpophagous puk','dive-puk','highwind','molted puk','nis puk','phantasmal puk',
            'phantom puk','pit puk','puk','puk executioner','sarimanok','scout puk','sea puk','vulpangue' },
        },,
        { ['Family'] = 'wyrms',
          ['Monsters']  = { 'cynoprosopi','fafnir','jormungand','ouryu','tiamat','vrtra' },
        },
        { ['Family'] = 'wyverns',
          ['Monsters'] = { 'aern\'s wynav','aiatar','bune','bxafraff\'s wyvern','draugar\'s wyvern',
            'fantoccini wyvern','festive firedrake','firedrake','flamedrake','fomor\'s wyvern','gorynich',
            'ignidrake','kindred vouivre','kindred wyvern', 'mamool ja\'s wyvern','orc\'s wyvern','pyrodrake',
            'scoffin','scorched-snout wyvern','seiryu','shikaree z\'s wyvern','ungur','vanguard wyvern',
            'vouivre','war wyvern','watch wyvern','wyvern' },
        },
        { ['Family'] = 'zilant',
          ['Monsters'] = { 'yilbegan' },
        },
    },
    ['elementals'] = {
        { ['Family'] = 'elementals',
          ['Monsters'] = { 'aern\'s elemental','air elemental','aither','beorht','chaos elemental','dark elemental',
            'demon\'s elemental','deorc','demon\'s elemental','earth elemental','eorthe','fire elemental',
            'fomor\'s elemental','gullin baelfyr','gullin byrgen','gullein gefyrst','gullin ungeweder',
            'ice elemental','kindred\'s elemental','lacus','lamia\'s elemental','light elemental','nocuous inferno',
            'pruina','puretos','shen\'s filtrate','thunor','thunder elemental','tonberry\'s elemental',
            'water elemental','yagudo\'s elemental' },
        },
        { ['Family'] = 'pixies',
          ['Monsters'] = { 'belphoebe','bhishani','erd','pixie','skuld','sprite','verthandi' },
        },
    },
    ['empties'] = {
        { ['Family'] = 'cravers',
          ['Monsters'] = { 'coveter','craver','cumulator','delver','envier','repiner','solicitor' },
        },
        { ['Family'] = 'gorgers',
          ['Monsters'] = { 'gorger','ingester','ingurgitator','neogorger','neogurgitator','neoingester','neosatiaror',
            'offspring','procreator','progenerator','propagator','satiator' },
        },
        { ['Family'] = 'receptacles',
          ['Monsters'] = { 'memory receptacle' },
        },
        { ['Family'] = 'seethers',
          ['Monsters'] = { 'provoker','seether' }.
        },
        { ['Family'] = 'thinkers',
          ['Monsters'] = { 'agonizer','cerebrator','cogitator','contemplator','ponderer','thinker',
            'wreaker' },
        },
        { ['Family'] = 'wanderers',
          ['Monsters'] = { 'deviator','stray','wanderer' },
        },
        { ['Family'] = 'weepers',
          ['Monsters'] = { 'wailer','weeper' },
        },
    },
    ['humanoids'] = {
        { ['Family'] = 'elvaan',crawler
          ['Monsters'] = { 'alsha','clavauert b chanoix','excaliace','general rughadjeen','ghahnis',
            'karazahm','qultada','rahdjab','rhushouf','shamarhaan','volunteer' },
        },
        { ['Family'] = 'galka',
          ['Monsters'] = { 'general zazarg','gowam' },
        },
        { ['Family'] = 'humes',
          ['Monsters']  = { 'afrhaad','amnaf','bashdeel','danzo','dhiadjhar','fantoccini','ganmuul','gasharyad',
            'general gadalar','general najelith','ghayaraan','habraheem','hkadouf','imperial guard',
            'imperial trooper','jalyaat','jasweem','krinahal','mareema','qudeen','raubahn','razfahd',
            'rohemolipaud','tenzen','tiyaash','oko','saizo','salumuhl','salyhaar','shailham','sharayaan',
            'shayaam','tahbmar','ubdeen','udhaaman','umarid','varajahl','wabjahl','wharadi','yazquhl',
            'yhalbin','zhadjaraf' },
        },
        { ['Family'] = 'mithra',
          ['Monsters'] = { 'cursed doppelganger','general mihli','naja salaheem','shikaree x','shikaree y',
            'shikaree z' },
        },
        { ['Family'] = 'tarutaru',
          ['Monsters'] = { 'cherukiki','karabab','kukki-chebukki','makki-chebukki' },
        },
        { ['Family'] = 'zilart',
          ['Monsters'] = { 'eald\'narche','kam\'lanaut' },
        },
    },
    ['lizards'] = {
        { ['Family'] = 'adamantoises',
          ['Monsters'] = { 'adamantoise','citadel chelonian','genbu','millenary mossback' },
        },
        { ['Family'] = 'bugards',
          ['Monsters'] = { 'apollyon scavenger','battering bugard','battle bugard','beast bugard',
            'boggelmann','brontobugard','bugard','bullbugard','gigantobugard','hotupuku','immanibugard',
            'kurrea','megalobugard','molted bugard','nightmare bugard','pit bugard','tyrranobugard' },
        },
        { ['family'] = 'efts',
          ['Monsters']  = { 'eft','intuila','intulo','locust hypnos eft','night eft','nightmare eft',
            'race runner','splacknuck','tarutarus eft' },
        },
        { ['Family'] = 'lizards',
          ['Monsters'] = { 'amemet','arid lizard','bane lizard','bounding belinda','carriage lizard',
            'chasm lizard','draco lizard','dust lizard','enhanced lizard','frost lizard','grylio',
            'highlander lizard','hill lizard','labyrinth lizard','leaping lizzy','mamool ja\'s lizard',
            'maze lizard','nussknacker','mist lizard','ridge lizard','rock lizard','sand lizard',
            'slavering lizard','snow lizard','tarasque' },
        },
        { ['Family'] = 'raptors',
          ['Monsters'] = { 'daggerclaw dracos','deinonychus','dromoeosaurus','enhanced salamander',
            'hunting raptor','lindwurm','mamool ja\'s raptor','molted lindwurm','nightmare raptor',
            'nival raptor','pit lindwurm','raid raptor','raptor','tsaagan','vagrant lindwurm',
            'velociraptor','venomfang','woodland runner','yowie','zmey gorynych' },
        },
        { ['family'] = 'wivres',
          ['Monsters'] = { 'cherufe','dea','gharial','locus wivre','stachysaurus','wivre' },
        },
    },
    ['luminians'] = {
        { ['Family'] = 'aerns',
          ['Monsters'] = { 'absolute virtue','aw\'aern','eo\'aern','ix\'aern','om\'aern','qn\'aern',
              'ru\'aern','temenos aern','ul\'aern' },
        },
        { ['Family'] = 'euvhi',
          ['Monsters'] = { 'aern\'s euvhi','aw\'euvhi','eo\'euvhi','jailor of faith','temenos euvhi',
            'thalesek' },
        },
        { ['Family'] = 'ghrahs',
          ['Monsters'] = { 'aw\'ghrah','eo\'ghrah','ix\'ghrah','jailor of fortitude','kf\'ghrah','pyrrha',
            'temenos ghrah' },
        }
        { ['Family'] = 'hpemde',
          ['Monsters'] = { 'jailor of prudence','om\'hpemde','qn\'hpemde','ul\'hpemde' },
        },
        { ['Family'] = 'phuabo',
          ['Monsters'] = { 'jailor of hope','om\'phuabo','ru\'phuabo','ul\'phuabo' },
        },
        { ['Family'] = 'xzomits'
          ['Monsters'] = { 'aern\'s xzomit','jailor of justice','om\'xzomit','qn\'xzomit','ul\'xzomit' },
        },
        { ['Family'] = 'yovra',
          ['Monsters'] = { 'jailor of love','om\'yovra','ul\'yovra' },
        },
        { ['Family'] = 'zdei',
          ['Monsters'] = { 'aw\'zdei','eo\'zdei','ix\'zdei','jailor of temperance','qn\'zdei' },
        },
    },
    ['plantoids'] = {
        { ['Family'] = 'belladonnas',
          ['Monsters'] = { 'morta' },
        },
        { ['Family'] = 'flytraps',
          ['Monsters']  = { 'asrai','battrap','baumesel','bird trap','fishtrap','flytrap',
            'goaftrap','hamadryad','hawkertrap','lizardtrap','mantrap','nightmare flytrap','orcfeltrap',
            'orctrap','puktrap','shieldtrap' },
        },
        { ['Family'] = 'funguars',
          ['Monsters'] = { 'amanita','ballistisporer','crystal eatter','death cap','ellyllon','fairy ring',
            'forest funguar','grass funguar','jugnar funguar','marsh funguar','lost fairy ring',
            'migrant russula','mycohopper','mycophile','mycoskulker','nightmare funguar','noble mold',
            'para','poison funguar','shrieker','tumbling truffle' },
        },
        { ['Family'] = 'goobbues',
          ['Monsters'] = { 'ancient goobbue','goobue','goobue farmer','goobbue harvester','goobbue wanderer',
            'jolly green','joyous green','keeper of halidome','lost nant\'ina','nant\'ina','nightmare goobbue',
            'urayuli' },
        },
        { ['Family'] = 'mandragoras',
          ['Monsters']  = { 'backoo','bakru','enhanced pygmaioi','apsaras','koropokkur','korrogan','mandragora',
            'mourioche','nightmare mandragoras','peerifool','pygmaioi','sylvestre','tiny mandragora',
            'tom tit tat' },
        },
        { ['Family'] = 'morbols',
          ['Monsters'] = { 'ameretat','arch christelle','capricious cassie','cirrate christelle',
            'demonic rose','drooling daisy','grand amererat','great amererat','jaded jody',
            'lividroot amooshah', 'lumantishee','malboro','ochu','overgrown ivy','overgrown rose',
            'toxic tamlyn','voluptous vivian' },
        },
        { ['Family'] = 'rafflesias',
          ['Monsters'] = { 'ravishing rafflesia' },
        }
        { ['Family'] = 'sabotenders',
          ['Monsters'] = { 'cactrot rapido','cactuar cantautor','ghillie dhu','nightmare sabotender',
            'sabotender','sabotender bailarin','sabotender corrido','sabotender maestro','sabotender mariachi',
            'yara ma tha who' },
        },
        { ['Family'] = 'saplings',
          ['Monsters'] = { 'apollyon sapling','barometz','borametz','duessa','ghillie dhu',
            'leshachikha','maighdean uaine','sappy sycamore','sobbing sapling','staggering sapling',
            'stalking sapling','strolling sapling','tottering toby','treant sapling','walking sapling',
            'wandering sapling','yara ma yha who' },
        },
        { ['Family'] = 'treants',
          ['Monsters'] = { 'ahtu','cernunnos','colorful leshy','colorful treant','defoliate leshy',
            'defoliate treant','dosetsu tree','elder treant','emergent elm','fradubio','fraelissa',
            'jidra','leshy','lost stcemqestcint','marsh treant','nightmare treant','olden treant',
            'seasonal treant','stcemqestcint','treant','walking tree','weeping willow','woodland sage' },
        },
    },
    ['structures'] = {
        { ['Family'] = 'structures',
          ['Monsters'] = { 'archaic mirror','bastion gate','brittle rock','city gate','dilapidated gate' },
        },
    },
    ['unclassified'] = {
        { ['Family'] = 'animated weapons',
          ['Monsters'] = { 'bloody daggers','cursed axe','demonic rod','living staves','magic shields' },
        },
        { ['Family'] = 'automatons',
          ['Monsters'] = { 'carmine sentinel','cobalt sentinel', 'elvaan automaton','fantoccini automaton',
            'galkan automaton','hazel sentinel','hume automaton','mithran automaton','ob',
            'tarutaru automaton','troll\'s automaton','valkeng','white sentinel' },
        },
        { ['Family'] = 'avatars',
          ['Monsters'] = { 'aern\'s avatar','ahriman\'s avatar','alexander','baa\'s avatar','bahamut',
            'dark rider','diabolos','diabolos club','diabolos diamond','diabolos heart','diabolos letum',
            'diabolos nox','diabolos somnus','diabolos spade','diabolos umbra','diabolos\'s shard',
            'effigy prototype','fantoccini avatar','fomor\'s avatar','goblin replica','kindred\'s avatar',
            'lamia\'s avatar','mystic avatar','tonberry\'s avatar','vanguard avatar','yagudo\'s avatar' },
        },
        { ['Family'] = 'biotechnological weapons',
          ['Monsters'] = { 'arch-omega','arch-ultima','omega','proto-omega','proto-ultima','ultima','ultimega' },
        },
        { ['Family'] = 'monsters',
          ['Monsters'] = { 'fantoccini monster','tonberry\'s avatar'  },
        },
        { ['Family'] = 'simulacra',
          ['Monsters'] = { 'adamanking effigy','adamanking image','avatar icon','avatar idol','effigy prototype',
            'fangmonger colossus','goblin replica','goblin statue','icon prototype','manifest icon',
            'serjeant tombstone','statue prototype','tombstone','tombstone prototype','warchief tombstone' },
        },
        { ['Family'] = 'supreme beings',
          ['Monsters'] = { 'metus','promathia' },
        },
    },
    ['undead'] = {
        { ['Family'] = 'corpselights',
          ['Monsters'] = { 'bloody skull','gwynn ap nudd','pandemonium lamp','virvatuli' },
        },
        { ['Family'] = 'corses',
          ['Monsters'] = { 'arch corse','citipati','corse','elel','grave digger','gwyn ap knudd','keremet',
            'muut','xolotl' },
        },
        { ['Family'] = 'doomed',
          ['Monsters'] = { 'addled tumor','carrion toad','debaucher','expunger','feuerunke','foul meat',
            'jnun','hellion','jnun','llamhign y dwr','nakki','ogama','oni carcass','pluto',
            'putrid immortal guard','tainted flesh' },
        },
        { ['Family'] = 'fomors',
          ['Monsters'] = { 'arcane phantasm','ashu talif captain','ashu talif crew',
            'axesarion the wanderer','balrahn','duendes\' amoroso','balor','bendigeit vran',
            'caithleann','doman','draconic draugar','eba','ephramadian shade','experimental undead',
            'fallen imperial trooper','fallen imperial wizard','fallen volunteer','fir bholg',
            'fomor bard','fomor beastmaster','fomor black mage','fomor dark knight',
            'formor dragoon','fomor monk','fomor ninja','fomor paladin','fomor ranger',
            'fomor red mage','fomor samurai','fomor summoner','fomor thief','fomor warrior',
            'giollemitte b feroun','hammerblow majanun','hydra bard','hydra beastmaster','hydra black mage',
            'hydra dark knight','hydra dragoon','hydra monk','hydra ninja','hydra paladin','hydra ranger',
            'hydra red mage','hydra samurai','hydra summoner','hydra thief','hydra warrior',
            'hydra white mage','indich','jazaraat','lobais','luaith','marchelute','nosferatu wolf',
            'powederkeg yanadahn','sengann' },
        },
        { ['Family'] = 'ghosts',
          ['Monsters'] = { 'airi','asphyxiated amsel','assault bhoot','bardha','batteilant bhoot','bhoot',
            'bhoot intruder','bhoot invader','bogy','burned bergman','crushed krause','deviate bhoot',
            'erdgeist','ereshkigal','etemmu','evil spirit','fantasma','gelid bhoot','gespenst',
            'ghost','ghoul','gjenganger','guard bhoot','haunt','kudagitsune','lugat','mariselle\'s pupil',
            'old professor mariselle','onryo','otherworldly rimester','phasma','poltergeist',
            'pulverized pfeffer','revenant','smothered schmidt','srei ap','utukku','wounded wurfel' },
        },
        { ['Family'] = 'hounds',
          ['Monsters'] = { 'barghest','black wolf','bog dog','boreal hound','cwn annwn','cwn cyrff',
            'drooling hound','garm','gore hound','haty','mad fox','mauthe doog','scavenging hound','shii',
            'tainted hound','wolf zombie' },
        },
        { ['Family'] = 'naraka',
          ['Monsters'] = { 'kalasutrax' },
        },
        { ['Family'] = 'qutrubs',
          ['Monsters'] = { 'aynu-kaysey','dimgruzub','moshdahn','pining abazohn','qutrub','qutrub extortionist',
            'qutrub forayer','qutrub wastrel','zareehkl the jubilant' },
        },
        { ['Family'] = 'shadows',
          ['Monsters'] = { 'doppelganger dio','doppelganger gog','drexerion the condemned','eastern shadow',
            'northern shadow','phanduron the condemned','southern shadow','western shadow' },
        },
        { ['Family'] = 'skeletons',
          ['Monsters'] = { 'assault draugar','azren kuba','azren kuguza','bloody bones','cadaver warrior',
            'cadaver witch','darkling draugar','doom mage','doom soldier','draugar','draugar servant',
            'enchanted bones','erebus','frozen bones','ghast','ghoul','guard skeleton','inhumer','iruci',
            'lamia\'s skeleton','lich','lost soul','magicked bones','mummy','muut\'s hound warrior',
            'muut\'s sacrifice','pey','reserve drauger','skeleton esquire','skeleton sorcerer',
            'skeleton warrior','skull of envy','skull of gluttony','skull of greed','skull of lust',
            'skull of pride','skull of sloth','skull of wrath','smierc','timeworn warrior','tomb mage',
            'tomb warrior','velionis','wendigo','wight','xolotl\'s hound warrior','xolotl\'s sacrifice',
            'zombie' },
        },
        { ['Family'] = 'vampyrs',
          ['Monsters'] = { 'count dracula','lord asag','lord ruthven','nosferatu','oupire','vidmapire' },
        },
    },
    ['vermin'] = {
        { ['Family'] = 'antlions',
          ['Monsters'] = { 'alastor antlion','ambusher antlion','armored hunter','burrow antlion','cave antlion',
            'executioner antlion','feeler antlion','hunter antlion','lioumere','orcus','pit antlion',
            'shrewd hunter','swift hunter','tracer antlion','tracker antlion','trench antlion','tuchulcha' },
        },
        { ['Family'] = 'bees',
          ['Monsters'] = { 'arboricole hornet','bumblebee','cactus bee','canyon wasp','death from above',
            'death jacket','death wasp','deathly stinger','demonic tiphia','digger wasp','giant bee',
            'goblin\'s bee','huge hornet','huge wasp','hunting wasp','killer bee','maneating hornet',
            'miner bee','nightmare hornet','numbing norman','raker bee','skirmish pephredo',
            'soldier pephredo','spider wasp','stinging sophie','water wasp','worker pephredo',
            'yellow jacket' },
        },
        { ['Family'] = 'beetles',
          ['Monsters']  = { 'arboricole beetle','beady beetle','diamond daig','diving beetle','donnergugi',
            'enhanced beetle','enhanced kettenkaefer','fungus beetle','gawky gawain','goblin\'s beetle',
            'hercules beetle','lancing lamorak','lumber jack','panzer percival','rummager beetle',
            'sand beetle','scarab beetle','stag beetle' },
        },
        { ['Family'] = 'chigoes',
          ['Monsters'] = { 'augmented chigoe','berried chigoe','chelicerata','chigoe','chigoe\'s nit',
            'chigre','cursed chigoe','fossorial flea','plague chigoe' },
        },
        { ['Family'] = 'crawlers',
          ['Monsters'] = { 'arboricole crawler','berry grub','bolster','cactus grub','canyon crawler',
            'carmine eruca','carnivorous crawler','crawler','crimson eruca','date eruca','defoliator',
            'deforester','energetic eruca','flame eruca','habetrot','herbage hunter','magmatic eruca',
            'nightmare crawler','prickly pitriv','ravenous crawler','scoriaceous eruca','shell grub',
            'silk caterpillar','spiny spipi' },
        },
        { ['Family'] = 'diremites',
          ['Monsters'] = { 'aydeewa diremite','diremite','diremite assaulter','diremite dominator',
            'diremite stalker','gyre-carlin','nightmare diremite','pasuk' },
        },
        { ['Family'] = 'flies',
          ['Monsters'] = { 'assassin fly','bloodswiller fly','carmine dobsonfly','cliff glider',
            'crane fly','damselfly','darner','farruca fly','gadfly','gallinipper','goblin\'s gallinipper',
            'goblin\'s dragonfly','goblin\'s ogrefly','hawker','lanky leglen','may fly','migrant dobsonfly',
            'migrant hawker','monarch ogrefly','nightmare fly','ogrefly','spongilla fly','valkurm emperor',
            'vauxia fly','vermillion fishfly' },
        },
        { ['Family'] = 'mantids',
          ['Monsters'] = { 'tsui-goab' },
        },
        { ['Family'] = 'scorpions',
          ['Monsters'] = { 'amikiri','antares','cutlass scorpion','doom scorpion','jyeshtha','killing claw',
            'nightmare scorpion','sargas','siege scorpion','slaughterous scorpion','sulfur scorpion',
            'tulwar scorpion','tyrannic tunnok','vanguard scorpion' },
        },
        { ['Family'] = 'spiders'
          ['Monsters'] = { 'aht urghan attercop','aquaduct spider','arachne','arboricole spider','dune widow',
            'falcatus aranei','gate widow','giant spider','goblin\'s spider','harvestman','huge spider',
            'pit spider','spinner','tsuchigumo' },
        },
        { ['Family'] = 'wamouras',
          ['Monsters'] = { 'achamoth','achamoth nympha','ignamoth','ranch wamoura','wamoura','wamoura prince',
            'wandering wamoura','war wamoura','witch wamoura' },
        },
        { ['Family'] = 'wamouracampa',
          ['Monsters'] = { 'achamothcaampa','brass borer','copper borer','ranch wamouracampa','wamouracampa',
            'war wamouracampe','wheel wamoura' },
        },
    },
};
