--Zone: Bibiki Bay
--Zone ID: 4
return {
    Names = {
        ['Alraune'] = { Name='Alraune', 
        ['Apsaras'] = { Name='Apsaras', 
        ['Bismarck'] = { Name='Bismarck', 
        ['Catoblepas'] = { Name='Catoblepas', 
        ['Coastal Opo-opo'] = { Name='Coastal Opo-opo', 
        ['Coralline Uragnite'] = { Name='Coralline Uragnite', 
        ['Dalham'] = { Name='Dalham', 
        ['Eft'] = { Name='Eft', 
        ['Ghost Crab'] = { Name='Ghost Crab', 
        ['Goblin Pathfinder'] = { Name='Goblin Pathfinder', 
        ['Goblin Shaman'] = { Name='Goblin Shaman', 
        ['Goblin\'s Rarab'] = { Name='Goblin\'s Rarab', 
        ['Greater Pugil'] = { Name='Greater Pugil', 
        ['Grindylow'] = { Name='Grindylow', 
        ['Hobgoblin Animalier'] = { Name='Hobgoblin Animalier', 
        ['Hobgoblin Fascinator'] = { Name='Hobgoblin Fascinator', 
        ['Hobgoblin Martialist'] = { Name='Hobgoblin Martialist', 
        ['Hobgoblin Venerer'] = { Name='Hobgoblin Venerer', 
        ['Ignis Fatuus'] = { Name='Ignis Fatuus', 
        ['Intuila'] = { Name='Intuila', 
        ['Intulo'] = { Name='Intulo', 
        ['Island Rarab'] = { Name='Island Rarab', 
        ['Jagil'] = { Name='Jagil', 
        ['Kraken'] = { Name='Kraken', 
        ['Lancet Jagil'] = { Name='Lancet Jagil', 
        ['Locus Bight Rarab'] = { Name='Locus Bight Rarab', 
        ['Locus Camelopard'] = { Name='Locus Camelopard', 
        ['Locus Ghost Crab'] = { Name='Locus Ghost Crab', 
        ['Locus Hypnos Eft'] = { Name='Locus Hypnos Eft', 
        ['Marine Dhalmel'] = { Name='Marine Dhalmel', 
        ['Peerifool'] = { Name='Peerifool', 
        ['Primordial Pugil'] = { Name='Primordial Pugil', 
        ['Raven'] = { Name='Raven', 
        ['Rohemolipaud'] = { Name='Rohemolipaud', 
        ['Serra'] = { Name='Serra', 
        ['Shankha'] = { Name='Shankha', 
        ['Shen'] = { Name='Shen', 
        ['Shen\'s Filtrate'] = { Name='Shen\'s Filtrate', 
        ['Splacknuck'] = { Name='Splacknuck', 
        ['Tartarus Eft'] = { Name='Tartarus Eft', 
        ['Teine Sith'] = { Name='Teine Sith', 
        ['Toucan'] = { Name='Toucan', 
        ['Tragopan'] = { Name='Tragopan', 
        ['Tropical Rarab'] = { Name='Tropical Rarab', 
        ['Viscous Clot'] = { Name='Viscous Clot', 
    },
};
