--Zone: Arrapago Reef
--Zone ID: 54
return {
    Names = {
        ['Archaic Mirror'] = { Name='Archaic Mirror', Ecosystem='structures', Family='structures'},
        ['Arrapago Apkallu'] = { Name='Arrapago Apkallu', Ecosystem='birds', Family='apkallu'},
        ['Arrapago Leech'] = { Name='Arrapago Leech', Ecosystem='amorphs', Family='leeches'},
        ['Ashakku'] = { Name='Ashakku', Ecosystem='birds', Family='apkallu'},
        ['Assassin\'s Apprentice'] = { Name='Assassin\'s Apprentice', Ecosystem='unclassified', Family='unknowns'},
        ['Bhoot'] = { Name='Bhoot', Ecosystem='undead', Family='ghosts'},
        ['Bloody Bones'] = { Name='Bloody Bones', Ecosystem='undead', Family='skeletons'},
        ['Bukki'] = { Name='Bukki', Ecosystem='demons', Family='imps'},
        ['Chimera Clot'] = { Name='Chimera Clot', Ecosystem='amorphs', Family='slimes'},
        ['Dark Elemental'] = { Name='Dark Elemental', Ecosystem='elementals', Family='elementals'},
        ['Dimgruzub'] = { Name='Dimgruzub', Ecosystem='undead', Family='qutrubs'},
        ['Draugar Servant'] = { Name='Draugar Servant', Ecosystem='undead', Family='skeletons'},
        ['Draugar\'s Wyvern'] = { Name='Draugar\'s Wyvern', Ecosystem='dragons', Family='wyverns'},
        ['Dweomershell'] = { Name='Dweomershell', Ecosystem='aquans', Family='crabs'},
        ['Emperor Apkallu'] = { Name='Emperor Apkallu', Ecosystem='birds', Family='apkallu'},
        ['Ephramadian Shade'] = { Name='Ephramadian Shade', Ecosystem='undead', Family='fomors'},
        ['Euryale'] = { Name='Euryale', Ecosystem='beastmen', Family='lamia'},
        ['Fallen Imperial Trooper'] = { Name='Fallen Imperial Trooper', Ecosystem='undead', Family='fomors'},
        ['Fallen Imperial Wizard'] = { Name='Fallen Imperial Wizard', Ecosystem='undead', Family='fomors'},
        ['Fallen Volunteer'] = { Name='Fallen Volunteer', Ecosystem='undead', Family='fomors'},
        ['Giant Orobon'] = { Name='Giant Orobon', Ecosystem='aquans', Family='orobons'},
        ['Heraldic Imp'] = { Name='Heraldic Imp', Ecosystem='demons', Family='imps'},
        ['Ice Elemental'] = { Name='Ice Elemental', Ecosystem='elementals', Family='elementals'},
        ['Jnun'] = { Name='Jnun', Ecosystem='undead', Family='doomed'},
        ['Lahama'] = { Name='Lahama', Ecosystem='aquans', Family='sea monks'},
        ['Lamia Bellydancer'] = { Name='Lamia Bellydancer', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Dancer'] = { Name='Lamia Dancer', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Dartist'] = { Name='Lamia Dartist', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Deathdancer'] = { Name='Lamia Deathdancer', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Exon'] = { Name='Lamia Exon', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Fatedealer'] = { Name='Lamia Fatedealer', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Graverobber'] = { Name='Lamia Graverobber', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Idolater'] = { Name='Lamia Idolater', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Necromancer'] = { Name='Lamia Necromancer', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.11'] = { Name='Lamia No.11', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.18'] = { Name='Lamia No.18', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.19'] = { Name='Lamia No.19', Ecosystem='beastmen', Family='lamia'},
        ['Lamia No.24'] = { Name='Lamia No.24', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Palace Guard'] = { Name='Lamia Palace Guard', Ecosystem='beastmen', Family='lamia'},
        ['Lamia Toxophilite'] = { Name='Lamia Toxophilite', Ecosystem='beastmen', Family='lamia'},
        ['Lamia\'s Avatar'] = { Name='Lamia\'s Avatar', Ecosystem='unclassified', Family='avatars'},
        ['Lamia\'s Elemental'] = { Name='Lamia\'s Elemental', Ecosystem='elementals', Family='elementals'},
        ['Lamia\'s Skeleton'] = { Name='Lamia\'s Skeleton', Ecosystem='undead', Family='skeletons'},
        ['Lamie Bellydancer'] = { Name='Lamie Bellydancer', Ecosystem='beastmen', Family='lamia'},
        ['Lamie Deathdancer'] = { Name='Lamie Deathdancer', Ecosystem='beastmen', Family='lamia'},
        ['Lamie Necromancer'] = { Name='Lamie Necromancer', Ecosystem='beastmen', Family='lamia'},
        ['Lamie No.7'] = { Name='Lamie No.7', Ecosystem='beastmen', Family='lamia'},
        ['Lamie No.8'] = { Name='Lamie No.8', Ecosystem='beastmen', Family='lamia'},
        ['Lamie No.9'] = { Name='Lamie No.9', Ecosystem='beastmen', Family='lamia'},
        ['Lamie Toxophilite'] = { Name='Lamie Toxophilite', Ecosystem='beastmen', Family='lamia'},
        ['Lil\' Apkallu'] = { Name='Lil\' Apkallu', Ecosystem='birds', Family='apkallu'},
        ['Llamhigyn Y Dwr'] = { Name='Llamhigyn Y Dwr', Ecosystem='undead', Family='doomed'},
        ['Medusa'] = { Name='Medusa', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Bladedancer'] = { Name='Merrow Bladedancer', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Chantress'] = { Name='Merrow Chantress', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Icedancer'] = { Name='Merrow Icedancer', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Kabukidancer'] = { Name='Merrow Kabukidancer', Ecosystem='beastmen', Family='lamia'},
        ['Merrow No.5'] = { Name='Merrow No.5', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Shadowdancer'] = { Name='Merrow Shadowdancer', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Songstress'] = { Name='Merrow Songstress', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Typhoondancer'] = { Name='Merrow Typhoondancer', Ecosystem='beastmen', Family='lamia'},
        ['Merrow Wavedancer'] = { Name='Merrow Wavedancer', Ecosystem='beastmen', Family='lamia'},
        ['Naraka Bat'] = { Name='Naraka Bat', Ecosystem='birds', Family='bats'},
        ['Nipper'] = { Name='Nipper', Ecosystem='aquans', Family='crabs'},
        ['Nirgali'] = { Name='Nirgali', Ecosystem='amorphs', Family='leeches'},
        ['Nix Bladedancer'] = { Name='Nix Bladedancer', Ecosystem='beastmen', Family='lamia'},
        ['Nix Songstress'] = { Name='Nix Songstress', Ecosystem='beastmen', Family='lamia'},
        ['Nix Typhoondancer'] = { Name='Nix Typhoondancer', Ecosystem='beastmen', Family='lamia'},
        ['Nix Wavedancer'] = { Name='Nix Wavedancer', Ecosystem='beastmen', Family='lamia'},
        ['Nostokulshedra'] = { Name='Nostokulshedra', Ecosystem='aquans', Family='sea monks'},
        ['Nuhn'] = { Name='Nuhn', Ecosystem='aquans', Family='orobons'},
        ['Ornery Orobon'] = { Name='Ornery Orobon',Ecosystem='aquans', Family='orobons'},
        ['Phasma'] = { Name='Phasma', Ecosystem='undead', Family='ghosts'},
        ['Purgatory Bat'] = { Name='Purgatory Bat', Ecosystem='birds', Family='bats'},
        ['Qiqirn Mine'] = { Name='Qiqirn Mine', Ecosystem='beastmen', Family='qiqrns'},
        ['Qiqirn Trailer'] = { Name='Qiqirn Trailer', Ecosystem='beastmen', Family='qiqrns'},
        ['Qiqirn Treasure Hunter'] = { Name='Qiqirn Treasure Hunter', Ecosystem='beastmen', Family='qiqrns'},
        ['Qutrub'] = { Name='Qutrub', Ecosystem='undead', Family='skeletons'},
        ['Reserve Draugar'] = { Name='Reserve Draugar', Ecosystem='undead', Family='skeletons'},
        ['Seneschal Imp'] = { Name='Seneschal Imp', Ecosystem='demons', Family='imps'},
        ['Soulflayer'] = { Name='Soulflayer', Ecosystem='demons', Family='soulflayers'},
        ['Velionis'] = { Name='Velionis', Ecosystem='undead', Family='skeletons'},
        ['Wootzshell'] = { Name='Wootzshell', Ecosystem='aquans', Family='crabs'},
        ['Zareehkl the Jubilant'] = { Name='Zareehkl the Jubilant', Ecosystem='undead', Family='qutrubs'},
    },
};
