tWeaponType = {
    ['AXE'] = { 'aern axe','aern axe ii','ark tabar','bronze axe','bronze axe +1','demonic axe','dullahan axe','gramk axe','orcish axe','brass axe','brass axe +1','legionnaire\'s axe',
                'light axe','bone axe','bone axe +1','felling axe','jolt axe','bastokan axe','republic axe','bone axe','bone axe +1','battleaxe','battleaxe +1','platoon axe','rusty axe',
                'tomahawk','tomahawk +1','tigerhunter','military pick','garde pick','plain pick','war pick','war pick +1','warrior\'s axe','mythril axe','mythril axe +1','navy axe',
                'de saintre\'s axe','emeth pick','barbaroi axe','combat caster\'s axe','razor axe','veldt axe','veldt axe +1','cmb.cst. axe +1','cmb.cst. axe +2','storm axe','tabar',
                'tabar +1','viking axe','gerwitz\'s axe','mythril axe','mythril axe +1','viperine axe','darksteel axe','darksteel axe +1','wrath tabar','arcanabane','kabrakan\'s axe',
                'sirocco axe','tungi','darksteel pick','darksteel pick +1','fransisca','darksteel tabar','dst. tabar +1','acha d\'armas','nadziak','nadziak +1','fendoir','fleetwing',
                'lohar','rainmaker','juggernaut','kriegsbeil','marid ancus','rune axe','furnace tabarzin'.'pick of trials','rsv.cpt. pick','storm tabar','tabarzin','tabarzin +1',
                'barkborer','leopard axe','martial axe','retributor','woodsville\'s axe','lyft tabar','maneater','mighty pick','temperance axe','labrys','lion tamer','zoraal ja\'s axe',
                'aymur','bonebiter','chopper','double axe','dynamis axe','erlking\'s tabar','guttler','leonine axe','ogre killer','punisher','relic axe','sirius axe','sleggiold',
                'splinter','tartaglia' },
    ['CLUB'] = { 'ash club','ash club +1','caduceus','charm wand +1','chocobo wand','citrullus mallet','club hammer','dream bell','dream bell +1','feline hagoita','floral hagoita',
                 'g. spriggan club','gobbie gavel','hagoita','heartbeater','heartbeater +1','heartstopper','heartstopper +1','jingly rod','jingly rod +1','kitty rod','korrigan mallet',
                 'kupo rod','kyuka uchiwa','kyuka uchiwa +1','lady bell','lady bell +1','leafkin bopper','leafkin Bopper +1','maestro\'s baton','maple wand','maple wand +1','melomane mallet',
                 'miracle wand','miracle wand +1','moogle rod','nmd. moogle rod','onion rod','p. sprig. club','r. sprig. club','seika uchiwa','saika uchiwa +1','shell scepter',
                 'soulflayer\'s Wand','tengu war fan','thunder hammer','trainee hammer','bronze mace','bronze mace +1','bronze hammer','bronze hammer +1','bronze rod','bronze rod +1',
                 'rabbit stick','mana wand','willow wand','willow wand +1','freesword\'s club','pilgrim\'s wand','wild cudgel','brass hammer','brass hammer +1','brass rod','brass rod +1',
                 'hermit\'s wand','federation club','moonlight wand','windurstian club','chestnut club','solid club','decurion\'s hammer','yew wand','yew wand +1','mace','mace +1',
                 'bouncer club','platoon mace','warhammer','warhammer +1','earth wand','rod','rod +1','bastokan hammer','republic hammer','pixie mace','artemis\'s mace','raise rod',
                 'bone cudgel','bone cudgel +1','heat rod','eremite\'s wand','eremite\'s wand +1','rounsey wand','ryl.sqr. mace','maul','maul +1','replica maul','chestnut wand',
                 'high mana wand','solid wand','kingdom mace','mythril rod','mythril rod +1','san d\'orian macxe','mythril mace','mythril mace +1','selene\'s wand','oak cudgel',
                 'oak cudgel +1','warp cudgel','holy maul','holy maul +1','sacred maul','spirit maul','great club','great club +1','sealed mace','blessed hammer','casting wand',
                 'dia wand','bone rod','bone rod +1','holy mace','holy mace +1','sacred mace','moonwatch wand','time hammer','rose wand','rose wand +1','shellbuster','lillith\'s rod',
                 'tct.mag. wand','healing mace','sloth wand','t.m. wand +1','t.m. wand +2','arcana breaker','msk.cmd. rod','ryl. guard\'s rod','thoth\'s wand','raise ii rod',
                 'darksteel mace','darksteel mace +1','fey wand','dominion wand','ebony wand','ebony wand +1','darksteel rod','darksteel rod +1','asklepios','daedalus hammer',
                 'kraken club','octave club','curse wand','darksteel maul','darksteel maul +1','leviathan\'s rod','mythic wand','mythic wand +1','titan\'s cudgel','holy wand',
                 'holy wand +1','living rod','platinum mace','platinum mace +1','sacred wand','flan masher','sea rob. cudgel','seawolf cudgel','skirnir\'s wand','clearpath',
                 'flanged mace','flanged mace +1','grandeur','jadagna','jadagna -1','jadagna +1','templar hammer','horrent mace','imperial wand','mighty cudgel','mistileinn',
                 'platinum rod','platinum rod +1','purgatory mace','rune rod','brass jadagna','brass jadagna +1','buzdygan','buzdygan +1','club of trials','fourth mace','kerykeion',
                 'pealing buzdygan','rsv.cpt. mace','snr.msk. rod','templar mace','yigit bulawa','antares','martial wand','morgenstern','ramuh\'s mace','scepter','scepter +1',
                 'zonure','lyft ferule','perdu wand','prudence rod','brise-os','brise-os +1','deae gratia','battering maul','culacula','dweomer maul','dynamis maul','goedendag',
                 'guillintani','ingrimm','mjollnir','rageblow','raphael\'s rod','relic maul','star rod','stenz','werebuster','yagrush' },
    ['DAGGER'] = { 'aern dagger','aern dagger ii','bronze dagger','bronze dagger +1','bronze knife','bronze knife +1','ceremonial dagger','chicken knife ii','esikuva','infiltrator',
                   'norgish dagger','onion dagger','onion knife','qutrub knife','rusty dagger','tranee knife','trainee\'s needle','wind knife','wind knife +1','beestinger',
                   'blind dagger','blind dagger +1','blind knife','blind knife +1','brass dagger','brass dagger +1','piercing dagger','aspir knife','dagger','dagger +1','hushed dagger',
                   'silence dagger','silence dagger +1','spark dagger','spark dagger +1','knife','knife +1','baselard','baselard +1','burnite shell','decurion\'s dagger','kukri',
                   'kukri +1','mercenary\'s knife','platoon dagger','poison baselard','poison dagger','poison dagger +1','python baselard','poison knife','poison knife +1','acid dagger',
                   'corrosive dagger','melt dagger','mythril dagger','mythril dagger +1','poison kukri','poison kukri +1','ranging knife','ranging knife +1','bastokan dagger',
                   'federation knife','parrying knife','republic dagger','windurstian knife','kris','kris +1','archer\'s knife','hawker\'s knife','hawker\'s knife +1','mrc.cpt. kukri',
                   'ryl.sqr. dagger','sleep dagger','thug\'s jambiya','thug\'s jambiya +1','acid knife','corrosive knife','melt knife','mythril knife','mythril knife +1','acid kukri',
                   'corrosive kukri','federation kukri','kingdom dagger','melt kukri','mythril kukri','mythril kukri +1','san. dagger','windurstian kukri','fine baselard',
                   'mythril baselard','spark baselard','spark baselard +1','chiroptera dagger','minstrel\'s dagger','acid baselard','combat caster\'s dagger','corrosive baselard',
                   'marauder\'s knife','melt baselard','paper knife','calveley\'s dagger','jongleur\'s dagger','combat caster\'s dagger +1','combat caster\'s dagger +2','burglar\'s dagger',
                   'bone knife','bone knife +1','deathbone knife','hornetneedle','galkan dagger','cordair\'s knife','mercurial kris','lust dagger','triple dagger','darksteel knife',
                   'darksteel knife +1','venom knife','venom knife +1','darksteel jambiya','darksteel jambiya +1','darksteel baselard','darksteel baselard +1','beetle knife','beetle knife +1',
                   'kidney dagger','avis','darksteel kris','darksteel kris +1','spark kris','spark kris +1','venom kris','venom kris +1','chicken knife','darksteel kukri','darksteel kukri +1',
                   'cermet knife','cermet knife +1','bano del sol','trailer\'s kukri','cermet kukri','cermet kukri +1','demon\'s knife','demon\'s knife +1','venom baselard','venom baselard +1',
                   'anubis\'s knife','garuda\'s knife','stun knife','stun knife +1','odorous knife','odorous knife +1','courser\'s pugio','harpe','hoplites harpe','kard','venom kukri',
                   'venom kukri +1','farseer','silktone','sirocco kukri','stun kukri','stun kukri +1','valiant knife','adaman kris','adaman kris +1','assassin\'s jambiya','behemoth knife +1',
                   'behemoth knife','daylight dagger','magnet knife','orichalcum dagger','palladium dagger','rune kris','taillefer\'s dagger','thief\'s knife','triton\'s dagger',
                   'bartholomew\'s knife','buccaneer\'s knife','cobra knife','dagger of trials','khanjar','matron\'s knife','misericorde','misericorde +1','Master Caster knife',
                   'stylet','zareehkl jambiya','adder jambiya','adder jambiya +1','adder jambiya +1','amir jambiya','argent dagger','blau dolch','ermine\'s tail','gully','gully +1',
                   'khimaira jambiya','martial knife','ponderous gully','titan\'s baselard','x\'s knife','creve-coeur','heart snatcher','jambiya','jambiya +1','lyft jambiya','mighty knife',
                   'perseus\'s harpe','trilling dagger','azoth','thanatos baselard','athame','batardeau','carnwenhan','dakini','dancing dagger','dweomer knife','dynamis dagger',
                   'edgeless knife','fane baselard','kartika','machismo','malefic dagger','mandau','peeler','relic dagger','renegade','swordbreaker','vajra' },
    ['H2H'] = { 'aphelion knuckles','cat baghnakhs','cat baghnakhs +1','cesti','cesti +1','fruit punches','premium mogti','tokkosho','trainee scissors','worm feelers','worm feelers +1',
                'bronze knuckles','bronze knuckles +1','brass knuckles','brass knuckles +1','freesword\'s baghnakhs','legionnaire\'s knuckles','royal archer\'s cesti','tropical punches',
                'tropical punches +1','brass baghnakhs','brass baghnakhs +1','hydro baghnakhs','hydro baghnakhs +1','burning cesti','lizard cesti','smash cesti','strike baghnakhs',
                'bastokan knuckles','federation baghnakhs','kingdom cesti','replublic knuckles','san d\'orian cesti','windurstian baghnakhs','hushed baghnakhs','silence baghnakhs',
                'silence baghnakhs +1','cxougar baghnakhs','metal knuckles','metal knuckles +1','platoon cesti','sonic knuckles','baghnakhs','baghnakhs +1','lynx baghnakhs','custodes',
                'poison cesti','poison cesti +1','boreas cesti','claws','claws +1','hydro claws','hydro claws +1','tyro katars','tyro katars +1','impact knuckles','katars','katars +1',
                'poison baghnakhs','poison baghnakhs +1','poison claws','poison claws +1','mythril knuckles','mythril knuckles +1','poison katars','poison katars +1','vampiric claws',
                'himantes','himantes +1','noble himantes','tekko Kagi','tourney patas','acid claws','corrosive claws','melt claws','mythril claws','mythril claws +1','exocets','adargas',
                'adargas +1','patas','patas +1','cross-counters','retaliators','tactician magician\'s hooks','coeurl cesti','darksteel claws','darksteel claws +1','tactician magician\'s hooks +1',
                'tactician magician\'s hooks +2','torama cesti','birdbanes','darksteel knuckles','darksteel knuckles +1','sainti','sainti +1','bone patas','bone patas +1','hydro patas',
                'hydro patas +1','venom claws','venom claws +1','poppet katars','spartan cesti','cermet claws','cermet claws +1','darksteel katars','darksteel katars +1','gnole sainti',
                'gnole sainti +1','black adargas','black adargas +1','pagures','puppet claws','jamadhars','jamadhars +1','stun claws','stun claws +1','venom katars'.'venom katars +1',
                'gold patas','gold patas +1','severus claws','severus claws +1','darksteel sainti','darksteel sainti +1','shiva\'s claws','feral fangs','stun jamadhars','stun jamadhars +1',
                'tigerfangs','narasimha\'s cesti','narasimha\'s cesti +1','vishnu\'s cesti','dragon claws','dragon claws +1','acantha shavers','avengers','useshi','behem. cesti +1',
                'behemoth cesti','hades sainti','hades sainti +1','pahluwan katars','rune baghnakhs','cobra baghnakhs','diamond knuckles','diamond knuckles +1','knuckles of trials',
                'meteor cesti','master caster\'s baghnakhs','pahluwan patas','shlng. baghnakhs','martial knuckles','mighty patas','wagh baghnakhs','destroyers','faith baghnakhs',
                'indra katars','lyft sainti','manoples','manoples +1','ponder. manoples','burning fists','caestus','cat\'s claws','dynamis knuckles','glanzfaust','kaiser knuckles',
                'koenigs knuckles','mantis','militant knuckles','oberon\'s knuckles','pugilists','relic knuckles','simian fists','spharai','wargfangs' },
    ['KATANA'] = { 'kunai','kunai +1','wakizashi','wakizashi +1','kyofu','kyofu +1','shinobi-gatana','shinobi-gatana +1','gassan','mokuto','mokuto +1','seito','suzume','ganko',
                   'hibari','hibari +1','busuto','busuto +1','fukuro','nikkariaoe','kodachi','kodachi +1','reppu','reppu +1','niokiyotsuna','ohaguro','bokuto','bokuto +1','hanafubuki',
                   'sakurafubuki','sakurafubuki +1','melt katana','yoto','yoto +1','hien','hien +1','sai','sai +1','buboso','kageboshi','tsugumi','shinogi','keppu','keppu +1','muketsu',
                   'muketsu +1','hototogisu','hocho','sairen','kabutowari','kabutowari +1','kitsutsuki','kororito','kororito +1','imanotsurugi','amanojaku','fudo','karasuageha',
                   'ryumon','hayabusa','hayabusa +1','kodachi of trials','sayosamonji','unsho','mamushito','mamushito +1','senjuinrikio','shamo','shusui','unji','hirenjaku','hirenjaku +1',
                   'izayoi','izayoi +1','musanto','oninohocho','shiranui','tojaku','kugui','narigitsune','otori','rai kunimitsu','ihintanto','kikoku','mimizuku','nagi','rogetsu',
                   'sasuke katana','yoshimitsu' },
    ['SWORD'] = { 'aern sword','aern sword ii','bronze sword','bronze sword +1','onion sword','wax sword','wax sword +1','sapara','sapara +1','xiphos','xiphos +1','spatha','spatha +1',
                  'royal archer\'s sword','bee spatha','bee spatha +1','bilbo','bilbo +1','brass xiphos','brass xiphos +1','scimitar','scimitar +1','spark bilbo','spark bilbo +1',
                  'kingdom sword','san d\'orian sword','fire sword','flame sword','iron sword','iron sword +1','longsword','longsword +1','vulcan sword','auriga xiphos','small sword',
                  'degen','degen +1','platoon spatha','kaiser sword','tuck','tuck +1','nadrs','san d\'orian sword','gladiator','gladius','mithran scimitar','broadsword','broadsword +1',
                  'centurion\'s sword','fleuret','fleuret +1','strider sword','bastokan sword','hunting sword','republic sword','war sword','holy sword','holy sword +1','mythril degen',
                  'mythril degen +1','mythril sword','mythril sword +1','sacred sword','spark degen','spark degen +1','spirit sword','tulwar','tulwar +1','divine sword','divine sword +1',
                  'hallowed sword','grudge sword','buzzard tuck','combat caster\'s scimitar','fencing degen','flame degen','flame degen +1','honor sword','junior musketeer\'s tuck',
                  'vulcan degen','shotel','shotel +1','combat caster\'s scimitar +1','combat caster\'s scimitar +2','duel rapier','junior musketeer\'s tuck +1','junior musketeer\'s tuck +2',
                  'falchion','falchion +1','ancient sword','holy degen','holy degen +1','sacred degen','flame blade','flame blade +1','knight\'s sword','knight\'s sword +1','vulcan blade',
                  'crimson blade','immortal\'s shotel','temple knight army sword','tactician magician\'s espadon','darksteel sword','darksteel sword +1','temple knight sword +1',
                  'temple knight sword +2','tactician magician\'s espadon +1','tactician magician\'s espadon +2','crescent sword','darksteel falchion','bloodsword','bloody rapier',
                  'carnage rapier','musketeer commander\'s falshion','royal guard\'s fleuret','schlaeger','schlaeger +1','wise wizard\'s anelace','wise wizard\'s bilbo','saber','saber +1',
                  'gluttony sword','hanger','hanger +1','bloody blade','carnage blade','aramis\'s rapier','cermet sword','cermet sword +1','dragvandil','bastard sword','bastard sword +1',
                  'greed scimitar','leech scimitar','mailbreaker','mailbreaker +1','swan bilbo','hornet fleuret','wasp fleuret','cutlass','cutlass +1','gold sword','gold sword +1',
                  'kazbalger','kazbalger +1','bloody sword','carnage sword','jagdplaute','jagdplaute +1','rapier','rapier +1','spark rapier','spark rapier +1','colichemarde','colichemarde +1',
                  'company fleuret','ifrit\'s blade','macuahuitl','macuahuitl +1','macuahuitl -1','phntom fleuret','save the queen','coral sword','espadon','espadon +1','merman\'s sword',
                  'schwert','schwert +1','dainslaif','platinum cuirass','platinum cuirass +1','enhancing sword','epee','epee +1','tutelary','corsair\'s scimitar','wing sword','wing sword +1',
                  'company sword','hrotti','joyeuse','nightmare sword','ridill','rune blade','storm scimitar','durandal','kaskara','kaskara +1','sapara of trials','senior gold musketeer\'s scimitar',
                  'anelace','anelace +1','dissector','martial anelace','pealing anelace','princely sword','shiva\'s shotel','sylphid epee','bayard\'s sword','guespiere','justice sword','verdun',
                  'verdun +1','sanguine sword','seiryu\'s sword','brave blade','burtgang','caliburn','curtana','dynamis sword','excalibur','glyptic sword','hofud','murgleis','organics',
                  'relic sword','vorpal sword' },
    ['GKATANA'] = { 'ark tachi'.'hardwwood katana','lotus katana','melon slicer','mumeito','mutsunokami','mutsunokami +1','shinai','wooden katana','zanmato','zanmateo +1','tachi','tachi +1',
                    'katayama','uchigatana','uchigatana +1','nodachi','nodachi +1','gunromaru','okanehira','kanesada','kotetsu','homura','homura +1','koen','ashura','ashura +1','hosodachi',
                    'hosodachi +1','tsurugitachi','kagehide','magoroku','mikazuki','mikazuki +1','odenta','koryukagemitsu','soboro sukehiro','kiku-ichimonji','jindachi','jindachi +1',
                    'dotanuki','raikiri','amakura','daihannya','gld.msk. uchigat','omokage','zanbato','zanbato +1','kanesada +1','shinkanesada','onikiri','sukesada','kazaridachi',
                    'kazaridachi +1','messhikimaru','mukademaru','namioyogi','honebami','kamewari','kosetsusamonji','kumokirimaru','murasame','hotarumaru','shirogatana','shirogatana +1',
                    'tachi of trials','hagun','kotetsu +1','michishiba','nanatsusaya','shinkotetsu','shinsoki','butachi','butachi +1','kagiroi','namikirimaru','nukemaru','onimaru',
                    'unshomaru','ushikirimaru','hacchonenbutsu','Amanomurakumo','donto','efunotachi','futsuno mitama','hayatemaru','ito','kogarasumaru','kurodachi','oboromaru',
                    'pachipachio','radennotachi','rindomaru','shirodachi','totsukanotsurugi','windslicer' },
    ['GSWORD'] = { 'brave blade ii','chaosbringer','goujian','irradiance blade','judge\'s sword','lament','ophidian sword','rusty greatsword','deathbringer','surviver','claymore',
                   'claymore +1','gust claymore','gust claymore +1','burning claymore','flame claymore','vulcan claymore','estramacon','braveheart','2-hand. sword +1','lucent sword',
                   'mrc. greatsword','plain sword','platoon sword','two-hand. sword','barbarian\'s sword','federation sword','windurstian sword','hellfire sword','inferno sword',
                   'prominence sword','demonic sword','falx','falx + 1','fine claymore','halo claymore','mythril claymore','icicle sword','ryl.swd. blade','greatsword','greatsword +1',
                   'gust sword','gust sword +1','ryl.swd. blade+1','ryl.swd. blade+2','fausser','fausser +1','cobra claymore','gerwitz\'s sword','musketeer\'s sword','msk. sword +1',
                   'msk. sword +2','glorious sword','dst. claymore','dst. claymore +1','ryl.grd. sword','darksteel falx','darksteel falx +1','ram-dao','ram-dao +1','zweihander',
                   'zweihander +1','arrondight','mercurial sword','lockheart','mythril heart','mythril heart +1','ascalon','balisarde','cruadin','flamberg','flamberg +1','gust tongue',
                   'gust tongue +1','adaman claymore','balmung','crude sword','djinnbringer','gloom claymore','ferrara','nagan','nagan +1','pealing nagan','rsv.cpt.grt. sword',
                   'sword of trials','martial sword','mighty sword','scheherazarde','subduer','bahadur','bahadur +1','balan\'s sword','gigant sword','gold algol','gold algol +1',
                   'lyft claymore','perdu claymore','naglering','skofnung','albion','algol','brand d\'arcon','break blade','dull claymore','dynamis blade','galatyn','gilded blade',
                   'nightfall','ragnarok','relic blade','salamand sword','sunblade','valhalla' },
    ['POLEARM'] = { 'aern spear','aern spear ii','escritorio','harpoon','harpoon +1','hotengeki','iapetus','mizukage naginata','pitchfork','pitchfork +1','sha wujing\'s la. +1',
                    'sha wujang\'s lance','tzee xicu\'s blade','obelisk','bronze spear','bronze spear +1','gimlet spear','brass spear','brass spear +1','spark spear','spark spear +1',
                    'rul.sqr. spear','cruel spear','fuscina','platoon lance','kingdom spear','san d\'orian spear','spear','spear +1','military spear','ryl.sqr. halberd','lizard piecer',
                    'kingdom halberd','lance','lance +1','lucent lance','san. halberd','spark lance','spark lance +1','halberd','halberd +1','broach lance','obelisk lance','obelisk lance +1',
                    'behourd lance','peregrine','orc piercer','trident','heavy halberd','mythril lance','mythril lance +1','wind spear','r.k. army lance','kamayari','kamayari +1',
                    'r.k. lance +1','r.k. lance +2','holy lance','holy lance +1','monsoon spear','sacred lance','thundercloud','battle fork','battle fork +1','spark fork','spark fork +1',
                    'calamar','partisan','partisan +1','darksteel lance','dst. lance +1','envy spear','couse','couse +1','dark mezraq','dark mezraq +1','dispel couse','gnd.kgt. lance',
                    'schwarz lance','heavy lance','bloody lance','carnage lance','golden spear','golden spear +1','cermet lance','cermet lance +1','narval','gae bolg','tonbo-giri','barchha',
                    'barchha +1','bourdonasse','colossal lance','engetsuto','engetsuto +1','mercurial lance','puk lance','rune halberd','schiltron spear','imperial neza','ox tongue',
                    'ox tongue +1','rsv.cpt.lance','spear of trials','dreizack','leviathan\'s couse','martial lance','perforator','tomoe','z\'s trident','love halberd','mighty lance',
                    'stone=splitter','wyvern spear','wyvern spear +1','achilles\'s spear','ice lance','ice lance','dynamis lance','gae assail','gungnir','hotspur lance','mezraq','mezraq +1',
                    'orichalcum lance','ponderous lance','radiant lance','relic lance','ryunohige','thalassocrat','thalassocrat +1','tournament lance','triton\'s lance','valkyrie\'s fork',
                    'wyrm tongue' },
    ['SCYTHE'] = { 'bronze zaghnal','bronze zaghnal +1','brass zaghnal','brass zaghnal +1','keen zaghnal','legionnaire\'s scythe','plantreaper','bastokan scythe','republic scythe',
                   'lucent scythe','scythe','scythe +1','cruel scythe','platoon zaghnal','zaghnal','zaghnal +1','webcutter','frostreaper','mercenary captain\'s scythe','federation scythe',
                   'windurstian scythe','harvester','mutilator','mythril scythe','mythril scythe +1','raven scythe','mythril zaghnal','mythril zaghnal +1','antlion sickle','jet sickle',
                   'mandibular sickle','falcastra','barbarian\'s scythe','bone scythe','bone scythe +1','smiting scythe','smiting scythe +1','demonslicer','ivory sickle','ivory sickle +1',
                   'vassago\'s scythe','rusty zaghnal','a l\'outrance','darksteel scythe','darksteel scythe +1','ascention','blackjack','faucheuse','vendetta','goshisho\'s scythe',
                   'havoc scythe','king maker','moliones\'s sickle','naigama','naigama +1','rune scythe','volunteer\'s scythe','fourth zaghnal','scythe of trials','senior gold musketeer\'s scythe',
                   'storm zaghnal','zareehkl scythe','garuda\'s sickle','martial scythe','mighty zaghnal','y\'s scythe','blizzard scythe','death scythe','death scythe +1','gravedigger',
                   'lyft scythe','orichalcum scythe','perdu sickle','triton\'s scythe','enforcer','suzaku\'s scythe','tredecim scythe','white joker','apocalypse','bahamut\'s zaghnal',
                   'bec de faucon','death sickle','dweomer scythe','dynamis scythe','farmhand','liberator','memento scythe','ogre sickle','relic scythe','scarecrow scythe','severance',
                   'stigma','ultimatum','vengeance' },
    ['STAVE'] = { 'aern staff','aern staff ii','ash staff','ash staff +1','caver\'s shovel','cobra staff','fed. signet staff','fourth staff','hapy staff','kgd. signet staff','lamia staff',
                  'levin','malice masher','malice masher +1','onion staff','profane staff','ram staff','ranine staff','rep. signet staff','savage. pole','sophistry','treat staff','trick staff',
                  'treat staff ii','trick staff ii','ash pole','ash pole +1','freesword\'s staff','gelong staff','lgn. staff','holly staff','holly staff +1','bastokan staff','federation staff',
                  'pestle','republic staff','windurstian staff','flexible pole','holly pole','holly pole +1','monster signa','mercenary\'s pole','misery staff','platoon staff','elm staff',
                  'elm staff +1','federation pole','windurstian pole','spiked club','spiked club +1','astaroth cane','dolphin staff','melampus staff','spiro staff','elm pole','elm pole +1',
                  'hypno staff','whale staff','whale staff +1','militart pole','oak staff','oak staff +1','passaddhi staff','passaddhi staff +1','chanter\'s staff','dragon staff','dusky staff',
                  'himmel staff','kukulcan\'s staff','oak pole','oak pole +1','ceres\' spica','qi staff','qi staff +1','footman\'s staff','pastoral staff','quarterstaff','musketeer\'s pole',
                  'walrus staff','apollo\'s staff','aquilo\'s staff','auster\'s staff','chatoyant staff','dark staff','earth staff','fire staff','ice staff','iridal staff','jupiter\'s staff',
                  'light staff','neptune\'s staff','pluto\'s staff','terra\'s staff','thunder staff','vulcan\'s staff','water staff','wind staff','msk. pole +1','msk. pole +2','sunlight pole',
                  'pride staff','dryad staff','healing staff','wis.wiz. staff','rockmasher','revenging staff','rvg. staff +1','heavy staff','mahogany pole','mahogany pole +1','mahogany staff',
                  'achalaus\'s pole','battle staff','battle staff +1','ebony pole','ebony pole +1','ramuh\'s staff','power staff','kinnara pole','catalyst','cocytus pole','kebble','astral signa',
                  'mercurial pole','mythic pole','mythic pole +1','rune staff','yigit pole','astral staff','atesh pole','grim staff','imperial pole','mst.cst. pole','pole of trials','prelatic pole',
                  'prester','carbuncle\'s pole','iron-splitter','iron-splitter +1','martial staff','might pole','somnus signa','steel-splitter','zen pole','alkalurops','hope staff','kinkobo',
                  'lyft pole','mekki shakki','perdu staff','primate staff','primate staff +1','samudra','thyrsusstab','wyvern perch','capricorn staff','bahamut\'s staff','claustrum','cracked staff',
                  'crook','danda','diabolos\'s pole','dorje','dynamis staff','eight-sd. pole +1','eight-sided pole','fay crozier','kirin\'s pole','laevateinn','mage\'s staff','majestas','nirvana',
                  'relic staff','sage\'s staff','scepter staff','shillelagh','slaine','teiwaz','thyrus' },
    ['ARCHERY'] = { 'artemis\'s bow','artemis\'s bow +1','judge\'s bow','mizukage-no-yumi','shortbow','shortbow +1','longbow','longbow +1','self bow','self bow +1','freesword\'s bow',
                    'ryl.arc. longbow','hunter\'s longbow','federation longbow','kingdom bow','san d\'orian bow','windurstian bow','power bow','power bow +1','platoon bow','wrapped bow',
                    'wrapped bow +1','assassin\'s bow','great bow','great bow +1','hamayumi','shadow bow','shadow bow +1','composite bow','composite bow +1','speed bow','battle bow',
                    'battle bow +1','hunter\'s zamburak','shikar bow','kaman','kaman +1','war bow','war bow +1','sagittarius\'bow','eurytos\' bow','lightning bow','lightning bow +1',
                    'vali\'s bow','loxley bow','rapid bow','rapid bow +1','sarnga','selene\'s bow','pharaoh\'s bow','amanokakoyumi','failnaught','gendawa','gendawa +1','imperial bow',
                    'mighty bow','rosenbogen','rosenbogen +1','arco de velocidad','bow of trials','cobra bow','imperial kaman','mst.cst. bow','shigeto bow','shigeto bow +1','expunger',
                    'ifrit\'s bow','martial bow','perdu bow','rune bow','astrild','cerberus bow','cerberus bow +1','dynamis bow','fay gendawa','futatokoroto','goshawk','gyrfalcon',
                    'kestrel','lamian kaman','lamian kaman -1','lamian kaman +1','relic bow','sparrow','wolver bow','yoichinoyumi' },
    ['MARKSMANSHIP'] = { 'decazoom mk-xi','light crossbow','light crossbow +1','silver gun','silver gun +1','troll gun','firefly','hakenbuechse','musketoon','musketoon +1','lgn. crossbow',
                         'crossbow','crossbow +1','bandit\'s gun','bandit\'s gun +1','bas. crossbow','rep. crossbow','tanegashima','tanegashima +1','almogavar bow','platoon gun','arquebus',
                         'arquebus +1','power crossbow','pirate\'s gun','pirate\'s gun +1','mars\'s hexagun','mars\'s hexagun +1','military gun','zamburak','zamburak +1','nous arbalest',
                         'serpentine gun','darksteel hexagun','dst. hexagun +1','rikonodo','killer crossbow','thug\'s zamburak','trump gun','negoroshiki','negoroshiki +1','tell\'s crossbow',
                         'tracker\'s bow','tracker\'s bow +1','deluxe carbine','arbalest','arbalest +1','musketeer gun','seadog gun','seadog gun +1','musketeer gun +1','musketeer gun +2',
                         'leo crossbow','leo crossbow +2','leion crossbow','matchlock gun','matchlock gun +1','armbrust','fourth gun','heavy crossbow','heavy crossbow +1','shark gun',
                         'blunderbuss','blunderbuss +1','velocity bow','velocity bow +1','hexagun','hexagun +1','magoichi\'s gun','othinus\' bow','flagel. crossbow','basilisk','machine crossbow',
                         'murderer','rpt. crossbow','grosveneur\'s bow','hellfire','hellfire +1','storm zamburak','great cassandra','gun of trial','imperial gun','octant','silver cassandra',
                         'ziska\'s crossbow','coffinmaker','martial gun','peacemaker','culverin','culverin +1','lyft crossbow','lyft hexagun','perdu crossbow','grand crossbow','staurobow',
                         'staurobow +1','veuglaire','annihilator','blue steel','corsair\'s gun','corsair\'s gun +1','death penalty','dragonmaw','dynamis gun','fane hexagun','ferdinand',
                         'gastraphetes','huracan','killer bow','magnatus','marksman gun','quicksilver','relic gun','thunderstick' },
    ['THROWING'] = { 'grudge','coarse boomerang','boomerang','boomerang +1','rogetsurin','flame boomerang','platoon disc','platoon edge','wingedge','wingedge +1','chakram','chakram +1',
                     'long boomerang','cmb.cst. b\'merang','jr.msk. chakram','cmb.cst. bmrng +1','cmb.cst. bmrng +2','jr.msk.chakram +1','jr.msk.chakram +2','yagudo freezer','comet tail',
                     'moonring blade','moonring blade +1','light boomerang','death chakram','rising sun','rising sun +1','lamiabane','mamoolbane','trollbane','ungar boomerang','aureole',
                     'snakeeye','pebble','bomb arm','snoll arm','cluster arm','dart','hawkeye','shurikan','grenade','juji shurikan','quake grenade','tathlum','hyo','riot grenade','manji shurikan',
                     'astragalos','fuma shurikan','antarctic wind','arctic wind','east wind','zephyr','angon','throwing tomahawk' },
    }
    ['AMMO'] = { 'stone arrow','wooden arrow','bone arrow','iron arrow','fang arrow','beetle arrow','poison arrow','silver arrow','horn arrow','sleep arrow','gold arrow','scorpion arrow',
                 'fire arrow','ice arrow','lightning arrow','bodkin arrow','platinum arrow','demon arrow','combat caster\'s arrow','patriarch proector\'s arrow','temple knight\'s arrow',
                 'kabura arrow','bronze bolt','crossbow bolt','blind bolt','acid bolt','sleep bolt','bloody bolt','venom bolt','holy bolt','mythril bolt','darksteel bolt','iron musketeer\'s bolt',
                 'bullet','spartan bullet','gold bullet','iron bullet','silver bullet','carapace bullet','cannon shell','heavy shell','battery','kilo battery','mega battery','hydro battery',
                 'kilo pump','wind fan','kilo fan','mega fan','virtue stone' },
    ['SHIELD'] = { 'lauan shield','lauan shield +1','marine shield','ageist','hatchling shield','she-slime shield','judge\'s shield','shell shield','maple shield','maple shield +1','clipeus',
                   'parana shield','aspis','aspis +1','elm shield','elm shield +1','fish scale shield','tropical shield','lantern shield','decurion\'s shield','mahogany shield','strong shield',
                   'turtle shield','turtle shield +1','bastokan targe','republic targe','kite shield','frost shield','kite shield +1','faerie shield','ashigaru targe','beater\'s aspis','flat shield',
                   'genin aspis','healer\'s shield','killer targe','magician\'s shield','mercenary\'s targe','pilferer\'s aspis','singer\'s shield','tortoise shield','trinmmer\'s aspis','varlet\'s targe',
                   'warlock\'s shield','wizard\'s shield','wrestler\'s aspis','wyvern\'s targe','targe','targe +1','oak shield','coated shield','oak shield +1','jennet shield','nymph shield',
                   'nymph shield +1','royal squire\'s shield','light buckler','balance buckler','elegant shield','strike shield','heater shield','heater shield +1','royal squire\'s shield +1',
                   'royal squire\'s shield +2','buckler','buckler +1','viking shield','hard shield','leather shield','leather shield +1','royal knight army shield','temple knight army shield',
                   'divine shield','holy shield','sentinel shield','serket shield','master shield','royal knight shield +2','temple knight shield +1','temple knight shield +2','royal knight army shield +1',
                   'royal knight army shield +2','scutum','scutum +1','musketeer commander\'s shield','royal guard\'s shield','hoplan','hoplan +1','sparton hoplan','astral shield','flame shield',
                   'wivre shield','wivre shield +1','darksteel buckler','spiked butler','patriarch protector\'s shield','darksteel shield','darksteel shield +1','round shield','round shield +1',
                   'charging shield','gilt buckler','gold buckler','tower shield','tower shield +1','diamond shield','diamond shield +1','astral aspis','asmiral\'s shield','dominus shield',
                   'general\'s shield','numinous shield','numinous shield +1','caballero shield','hickory shield','highlander\'s targe','picaroon\'s shield','storm shield','absorbing shield',
                   'legion scutum','ritter shield','ritter shield +1','tatami shield','ice shield','ice shield +1','palmerin\'s shield','januwiyah','januwiyah +1','kaiser shield','koenig shield',
                   'tariqah','tariqah +1','genbu\'s shield','muse tariqah','riot shield','aegis','acheron shield','acheron shield +1','relic shield','ancile','bulwark shield','dynamis shield',
                   'simba buckler' },
};
